objects/Account_Approvals__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Approvals</relationshipLabel>
        <relationshipName>Account_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Final Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Approval</label>
    <nameField>
        <displayFormat>AA-{0000000}</displayFormat>
        <label>Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Approvals</pluralLabel>
    <recordTypes>
        <fullName>Dealer_Score_Adjustment</fullName>
        <active>true</active>
        <description>Dealer Score Adjustment</description>
        <label>Dealer Score Adjustment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner_Lead_Routing</fullName>
        <active>true</active>
        <description>Partner Lead Routing (Opt in or Opt Out)</description>
        <label>Partner Lead Routing</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Score_Setting__c.object
<CustomObject>
    <description>Used to track the scoring metrics related to a Dealer Score.</description>
    <fields>
        <fullName>Calculation_Type__c</fullName>
        <label>Calculation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>Equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Between</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater than or equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less than or equal to</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_Value__c</fullName>
        <label>Score Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Score Setting</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Score Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUpdateDealerScores.cls
@IsTest (SeeAllData=true)
public with sharing class TestUpdateDealerScores {
    
    static testMethod void testUpdateDealerScores() 
    {       
        
        UpdateDealerScores b = new UpdateDealerScores();
        
        Test.startTest();
        
        Id batchProcessId = Database.executeBatch(b);
        
        Test.stopTest();

    }
    
    static testMethod void testUpdateDealerScoreRollups() 
    {       
    
        SFDCSpecialUtilities.isRunningTest = true;
        
        UpdateDealerOpportunityScores b = new UpdateDealerOpportunityScores();
        
        Test.startTest();
        
        Id batchProcessId = Database.executeBatch(b);
        
        Test.stopTest();


    }
    
    static testMethod void testUpdateDealerOpportunityScores() 
    {       
    
        SFDCSpecialUtilities.isRunningTest = true;
        
        UpdateDealerOpportunityScores b = new UpdateDealerOpportunityScores();
        
        Test.startTest();
        
        Id batchProcessId = Database.executeBatch(b);
        
        Test.stopTest();


    }
    static testMethod void testInsertScoreSetting()
    {
        List <Score_Setting__c> ssList = new List <Score_Setting__c>();
        
        Score_Setting__c dsNumGreatThanEqual = new Score_Setting__c();
        dsNumGreatThanEqual.Field_Name__c = 'AccountNumber';
        dsNumGreatThanEqual.Field_Value__c = '100';
        dsNumGreatThanEqual.Field_Label__c = 'Account Number';
        dsNumGreatThanEqual.Calculation_Type__c = 'Number';
        dsNumGreatThanEqual.Operator__c = 'Greater than or equal to';
        dsNumGreatThanEqual.Score_Value__c = 30;
        ssList.add(dsNumGreatThanEqual);
                
        test.startTest();
        
        insert ssList;
        
        test.stopTest();        
    }     
    
    
    static testMethod void testUpdateScoreSetting()
    {
        List <Score_Setting__c> ssList = new List <Score_Setting__c>();
        
        Score_Setting__c dsNumGreatThanEqual = new Score_Setting__c();
        dsNumGreatThanEqual.Field_Name__c = 'AccountNumber';
        dsNumGreatThanEqual.Field_Value__c = '100';
        dsNumGreatThanEqual.Field_Label__c = 'Account Number';
        dsNumGreatThanEqual.Calculation_Type__c = 'Number';
        dsNumGreatThanEqual.Operator__c = 'Greater than or equal to';
        dsNumGreatThanEqual.Score_Value__c = 30;
        ssList.add(dsNumGreatThanEqual);
                
        insert ssList;
        
        test.startTest();
        
        ssList[0].Score_Value__c = 20;
        
        update ssList;
        
        test.stopTest();        
    }        
    
    static testMethod void testInsertAccount()
    {
        List <Account> testInsertAccounts = new List <Account>();
        for(Integer i = 0; i<1; i++)
        {
            Account acct = new Account();
            acct.Name = 'Test12346956564' + string.valueOf(i);
            acct.Type = 'Elite-Partner-Residential';
            acct.RSM_Discretionary_Adj__c = 5;
            acct.AccountNumber = string.valueOf(i)+'00';
            acct.BillingCity = 'Test City';
            acct.BillingStreet = i + ' Main Street';
            acct.BillingState = 'AZ';
            acct.BillingCountry = 'United States';
            acct.BillingPostalCode = '12345';
            acct.Opp_Convert_Rate__c = 70;
            testInsertAccounts.add(acct);
        }
        
        test.startTest();
        insert testInsertAccounts;
        
        testInsertAccounts[0].BillingStreet = 'Test Street';
        
        update testInsertAccounts;
        test.stopTest();
        
    }
    
    static testMethod void testLeadFlowOptInOut()
    {
        Account acct = new Account();
        acct.Name = 'Test123456888999';
        acct.Type = 'Elite-Partner-Residential';
        acct.RSM_Discretionary_Adj__c = 5;
        acct.BillingCity = 'Test City';
        acct.BillingStreet = 'Main Street';
        acct.BillingState = 'AZ';
        acct.BillingCountry = 'United States';
        acct.BillingPostalCode = '12345';
        acct.Opp_Convert_Rate__c = 70;
        insert acct;
        
        Id lsrRecTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Partner_Lead_Routing' AND sObjectType = 'Account_Approvals__c'][0].Id;
        Id daRecTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Dealer_Score_Adjustment' AND sObjectType = 'Account_Approvals__c'][0].Id;
        
        List <Account_Approvals__c> aaList = new List <Account_Approvals__c>();
        Account_Approvals__c aa1 = new Account_Approvals__c();
        aa1.Status__c = 'Pending';
        aa1.Account__c = acct.Id;
        aa1.RecordTypeId = lsrRecTypeId;
        aaList.add(aa1);
        
        Account_Approvals__c aa2 = new Account_Approvals__c();
        aa2.Status__c = 'Pending';
        aa2.Account__c = acct.Id;
        aa2.RecordTypeId = daRecTypeId;
        aaList.add(aa2);
        
        test.startTest();
        
        insert aaList;
        
        for(Account_Approvals__c aa : aaList)
        {
            aa.Status__c = 'Approved';
        }
        
        update aaList;
        
        test.stopTest();
    }
}