objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Bill_To_Site__c.object
<CustomObject>
    <description>Bill to site from Oracle ERP</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Address3__c</fullName>
        <label>Address3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill to Site</relationshipLabel>
        <relationshipName>Bill_to_Site</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Oracle_Operating_Unit__c</fullName>
        <label>Oracle Operating Unit</label>
        <picklist>
            <picklistValues>
                <fullName>SPCN OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPDE OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPEB OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPES OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPKR OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPMLL OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPNA OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPPT OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPSA OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPSV OU</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_ID__c</fullName>
        <description>Oracle Site ID</description>
        <externalId>true</externalId>
        <label>Site ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Bill to Site</label>
    <nameField>
        <label>Bill To Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill to Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Authorized_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field allows access for a specific dealer user to place orders via the online-order process in Salesforce. The dealer account also needs to be enabled for online ordering.</description>
        <label>Authorized to Order</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This flag will indicate whether or not this item in Oracle is Active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Oracle Item Description</description>
        <label>Description</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <label>Long Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Bill_to_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Site</label>
        <referenceTo>Bill_To_Site__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oracle_Operating_Unit__c</fullName>
        <label>Oracle Operating Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_to_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Site</label>
        <referenceTo>Ship_to_Site__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Partner PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Order_Line__c.object
<CustomObject>
    <description>This custom object holds the order line information to be passed to Oracle after Online Ordering Process.</description>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <label>Item ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Item_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Oracle Item ID reference field of Item Type</description>
        <label>Oracle Item ID</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Line_Number__c</fullName>
        <label>Order Line Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Quantity * Unit Price</description>
        <label>Extended Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_per_Box__c</fullName>
        <label>Quantity per Box</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <formula>IF(  (Oracle_Item_ID__r.Item_ID__c  =  &apos;500610&apos;), Purchase_Order__r.Requested_Delivery_Date__c + 35 ,Purchase_Order__r.Requested_Delivery_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SmartPack_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SmartPack Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>The Unit price of the product per item.</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLine-{0000000000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ship_to_Site__c.object
<CustomObject>
    <description>Ship to site from Oracle ERP</description>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Address3__c</fullName>
        <label>Address3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_First_Name__c</fullName>
        <label>Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Last_Name__c</fullName>
        <label>Contact Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <description>Cash flow redesign- Sangita changed the sharing to read only. This way all partner users who can read their account can create a shipping site.</description>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipping Sites (Dealer Account)</relationshipLabel>
        <relationshipName>Ship_to_Site</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Oracle_Account_Number__c</fullName>
        <label>Oracle Account Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Operating_Unit__c</fullName>
        <description>Cash Flow- Existing oracle operating unit field maps the partner account number instead of operating unit. We need the actual operating unit (SPNA OU, SPEB OU) to query and find one ship to site to send to Oracle via OrderIntegrationService. SOA Integraion will populate this field for all primary addresses every 1 hour. OrderAppController class will read this value to populate ship to address on the PO.</description>
        <label>Oracle Operating Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shipping Site</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Ship to Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestOrderCloneController.cls
/* This test class for OrderCloneController */

@isTest 
private with sharing class TestOrderCloneController {
    
    @isTest
    public static void TestOrderCloneController1(){
        Account acct = getPartnerAccount();
        User u =getPartnerPortalUser(acct);
        acct = u.Contact.Account;
        if(acct.Oracle_Operating_Unit__c == null || acct.Oracle_Operating_Unit__c == ''){
            acct.Oracle_Operating_Unit__c = 'SPCN OU'; 
            update acct;
        }
        
        
        System.runAs(u){       
            List<Item__c> listOracleItems = createOracleItems();
            Purchase_Order__c purchaseOrder  = createPO(acct);
            List<Purchase_Order_Line__c> polineItemsList = createPOLineItems(purchaseOrder, listOracleItems);
            ApexPages.currentPage().getParameters().put('id', purchaseOrder.Id);         
            OrderCloneController cloneInstance = new OrderCloneController();    
            Id testId = cloneInstance.insertPurchaseOrder();
            cloneInstance.insertPurchaseOrderLine(purchaseOrder.Id);
            cloneInstance.ClonePurchaseOrder();
        }
    }
    
    private static Account getPartnerAccount(){
        String recType ='';
        for(RecordType r:[select id,Name from RecordType where sObjectType ='Account' and name ='Partner' LIMIT 1])
             recType = r.ID;
             
        Account acct = new Account(name='test'+String.valueOf(DateTime.now().getTime()),recordTypeID=recType);
        acct.ShippingCity = 'Jaipur';
        acct.ShippingStreet = 'Durgapura';
        acct.ShippingCountry = 'India';
        acct.ShippingState='Rajasthan';
        acct.ShippingPostalCode ='302018';
        acct.Oracle_Operating_Unit__c = 'SPCN OU';
        acct.Online_Order_Access__c = true;
        acct.Oracle_Account_Number__c = 'test-12345';
        acct.BillingCity = 'san mateo';
      acct.BillingStreet = 'Concar drive';
      acct.BillingPostalCode ='94402';
      acct.BillingCountry = 'USA'; 
        insert acct;
        setDealerShippingSite(acct);
        setDealerBillingSite(acct);
        return acct;                     
    }
    
     private static User getPartnerPortalUser(Account acct){
        User user = null;
        for(User u:[select id,Name,contactId,Contact.AccountID, Contact.Account.AccountNumber,Contact.Account.Name,Contact.Account.ShippingStreet,Contact.Account.ShippingState,Contact.Account.ShippingCity,Contact.Account.ShippingCountry,Contact.Account.Oracle_Operating_Unit__c,Contact.Account.ShippingPostalCode, Contact.Account.Oracle_Account_Number__c from User where (Profile.Name = 'Partner Executive' or Profile.Name = 'EU Partner Executive' )and isActive = true and ContactID != null LIMIT 1]){
            user =u;
        }
        if(user != null) return user;
        if(acct == null){
            acct =  getPartnerAccount();
        }
        Contact cont = new Contact(AccountID = acct.id,FirstName='testconbyPO2',LastName='testconbyPO2');
        cont.Email ='te@test.com';
        cont.Authorized_to_Order__c = true;
        insert cont;        
        String username ='testconbyPO2@world.com';
        user = new User(LastName = 'Hello222'+String.ValueOf(DateTime.Now()) ,FirstName = 'W'+ String.ValueOf(DateTime.Now()));
        user.ContactId = cont.Id;
        user.Username = username;
        user.Alias = 'yoo';
        user.CommunityNickname = username.subString(0,7);
        user.TimeZoneSidKey = 'America/Los_Angeles';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.Email = cont.Email;
        user.LocaleSidKey = 'en_US';
        List<Profile> lstProfile = [select Id from Profile where Name = 'Partner Executive'];
        if(lstProfile.Size()>0){
            user.ProfileId = lstProfile[0].Id;
            insert user;
        } 
        return user;
        
    }
    
    private static List<Item__c> createOracleItems(){
        List<Item__c> lstItems = new List<Item__c>();
        for(integer i=0;i<5;i++){
            Item__c testItem = new Item__c();
            testItem.Name = 'OracleItemId'+i;
            testItem.CurrencyIsoCode = 'USD';
            testItem.Description__c = 'test description'+i;
            testItem.Long_Description__c = 'test long description'+i;
            testItem.Item_ID__c = 'testdesignitem'+i;
            testItem.active__c = true;
            lstItems.add(testItem);           
        }  
        if(lstItems != null && lstItems.size()>0)
            insert lstItems; 
       return lstItems ;   
    }
    
     //creating purchase order line items
    private static List<Purchase_Order_Line__c> createPOLineItems(Purchase_Order__c po,List<Item__c> listOracleItems){  
        List<Purchase_Order_Line__c> poLineItemList = new List<Purchase_Order_Line__c>();
        for(integer i=0;i<5;i++){
            Purchase_Order_Line__c pLine1 = new Purchase_Order_Line__c();
            pLine1.Purchase_Order__c = po.ID;
            pLine1.Item_Description__c = 'test item smartpack'+i;
            pLine1.Item_ID__c = 'testid'+i;
            pLine1.Oracle_Item_Id__c = listOracleItems.get(i).ID;
            pLine1.Price__c = 5;
            pLine1.Quantity__c = 5;
            pLine1.Unit_Price__c = 5;           
            pLine1.Quantity_per_Box__c = 2;
            pLine1.Order_Line_Number__c = '1.0';
            pLine1.CurrencyIsoCode = 'USD';
            pLine1.SmartPack_Item__c = true;
            poLineItemList.add(pLine1);         
        }
        for(integer i=0;i<5;i++){
            Purchase_Order_Line__c pLine1 = new Purchase_Order_Line__c();
            pLine1.Purchase_Order__c = po.ID;
            pLine1.Item_Description__c = 'test item alacarte'+i;
            pLine1.Item_ID__c = 'testid'+i;
            pLine1.Oracle_Item_Id__c = listOracleItems.get(i).ID;
            pLine1.Price__c = 5;
            pLine1.Quantity__c = 5;
            pLine1.Unit_Price__c = 5;       
            pLine1.Quantity_per_Box__c = 2;
            pLine1.Order_Line_Number__c = '1.0';
            pLine1.CurrencyIsoCode = 'USD';
            pLine1.SmartPack_Item__c = false;
            poLineItemList.add(pLine1);
        }
        if(poLineItemList != null && poLineItemList.size()>0)   
            insert poLineItemList;
        return poLineItemList;          
    }   
    
     private static Purchase_Order__c createPO(Account acct){
        Purchase_Order__c po = new Purchase_Order__c();
        po.Dealer_Account__c = acct.ID;
        Ship_to_Site__c shToSite = setDealerShippingSite(acct);
        Bill_to_Site__c billToSite = setDealerBillingSite(acct);            
        po.Ship_to_Site__c = shToSite.ID;
        po.Ship_to_Site__r = shToSite;
        po.Bill_to_Site__c = billToSite.ID;
        po.Bill_to_Site__r = billToSite;          
        po.Requested_Delivery_Date__c = System.today();         
        insert po;
        createPOLineItems(po);
        return po;
    }

     private static Ship_to_Site__c setDealerShippingSite(Account acct){
        Ship_to_Site__c shipSite = new Ship_to_Site__c();
        shipSite.Dealer_Account__c = acct.ID;
        shipSite.Address1__c ='Test Address1';
        shipSite.Address2__c ='Test Address2';
        shipSite.Address3__c ='Test Address3';
        shipSite.City__c ='Jaipur';
        shipSite.State__c='Rajasthan';
        shipSite.Country__c  ='India';
        shipSite.Contact_First_Name__c='Con FirName';
        shipSite.Contact_Last_Name__c='Con LastName';
        shipSite.Zip__c='302018';
        insert shipSite;
        return shipSite;
    }
    
    private static Bill_to_Site__c setDealerBillingSite(Account acct){
        Bill_To_Site__c billToSite = new Bill_To_Site__c();
        billToSite.Dealer_Account__c = acct.ID;
        billToSite.Address1__c ='Test Address1';
        billToSite.Address2__c ='Test Address2';
        billToSite.Address3__c ='Test Address3';
        billToSite.City__c ='Jaipur';
        billToSite.State__c='Rajasthan';
        billToSite.Country__c ='India';
        /*billToSite.Contact_First_Name__c='Con FirName';
        billToSite.Contact_Last_Name__c='Con LastName';*/
        billToSite.Zip__c='302018';
        billToSite.Site_ID__c = String.valueOf(DateTime.now().getTime());
        insert billToSite;
        return billToSite;
    }
    
    private static void createPOLineItems(Purchase_Order__c po){    
        List<Purchase_Order_Line__c> lineItemsList = new List<Purchase_Order_Line__c>();
        for(integer i=0;i<5;i++){
            Purchase_Order_Line__c pLine1 = new Purchase_Order_Line__c();
            pLine1.Purchase_Order__c = po.ID;
            pLine1.Item_Description__c = 'test item'+i;
            pLine1.Item_ID__c = 'testid'+i;
            pLine1.Price__c = 5;
            pLine1.Quantity__c = 5;
            pLine1.Unit_Price__c = 5;
            pLine1.SmartPack_Item__c = false;
            pLine1.Quantity_per_Box__c = 2;
            pLine1.Order_Line_Number__c = '1.0';
            pLine1.CurrencyIsoCode = 'USD';
            lineItemsList.add(pLine1);
        }   
        insert lineItemsList;
    }
}