objects/Alliance_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <description>Residential Installation Project Mgmt
Priti Rastogi
The Roles a Partner Account can play on a residential project

New Roles are added for adding roles to community.</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Builder HERS Rater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Service Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Partner</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV HERS Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR HERS Rater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Alliance Partner</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Alliance Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Fee_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Role__c</fullName>
        <description>Its a field to define a partner role . Partner&apos;s Fee structure can be different based on his role in the deal</description>
        <label>Partner Role</label>
        <picklist>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Fee Distribution</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Fee Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees Distribution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Installation_Model__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>If Auto, Installation Model will be automatically assigned if criteria are met. If Manual, a user will need to manually assign the Installation Model</description>
        <label>Assignment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Auto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Installation Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Oracle Item Description</description>
        <label>Description</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <description>Created for Dynamic Proposal project. #131670101</description>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POLineFeeSetup__c.object
<CustomObject>
    <description>Setup object to manage PO Line Items</description>
    <fields>
        <fullName>Financial_Offering__c</fullName>
        <label>Financial Offering</label>
        <picklist>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>POLineFeeSetups</relationshipLabel>
        <relationshipName>POLineFeeSetups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MileStone__c</fullName>
        <label>MileStone</label>
        <picklist>
            <picklistValues>
                <fullName>LEASE ORIGINATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERMIT RECEIVED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LEASE INSTALLATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LEASE INTERCONNECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORIGINATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INSTALLATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTERCONNECT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Installation Model. Created for Loan Backend project.</description>
        <label>Model</label>
        <referenceTo>Installation_Model__c</referenceTo>
        <relationshipLabel>POLineFeeSetups</relationshipLabel>
        <relationshipName>POLineFeeSetups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Role__c</fullName>
        <label>Partner Role</label>
        <picklist>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Value_From__c</fullName>
        <description>Field from which the fee value will be derived. For example, service lines are read from quote.dealer-fees__c.</description>
        <label>Value From</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>POLineFeeSetup</label>
    <nameField>
        <displayFormat>POLFS-{000}</displayFormat>
        <label>POLineFeeSetup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POLineFeeSetups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <label>Sales Type</label>
        <picklist>
            <picklistValues>
                <fullName>Third Party Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Partner PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Order_Line__c.object
<CustomObject>
    <description>This custom object holds the order line information to be passed to Oracle after Online Ordering Process.</description>
    <fields>
        <fullName>Item_ID__c</fullName>
        <label>Item ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Role__c</fullName>
        <label>Partner Role</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLine-{0000000000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <defaultValue>&quot;New Quote&quot;</defaultValue>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Installation_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Installation Model. Created for Loan Backend Project</description>
        <label>Installation Model</label>
        <referenceTo>Installation_Model__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Fees_Fields_API__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It&apos;s a custom setting to save the api name on the quote</description>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <description>It&apos;s a field to save the API name of quote field where the values need to be inserted.. !!!</description>
        <label>Field API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Quote Fees Fields API</label>
</CustomObject>

objects/Residential_Project__c.object
<CustomObject>
    <fields>
        <fullName>Installation_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Residential Installation Project Mgmt
Relates an installation model to a project. Populated programmatically or manually</description>
        <label>Installation Model</label>
        <referenceTo>Installation_Model__c</referenceTo>
        <relationshipLabel>Residential Projects</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO Reference</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Residential Project</relationshipLabel>
        <relationshipName>Residential_Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This look up field is populated from the quote record at the time of project record creation.
It is a link to the quote associated with the homeowner&apos;s signed contract.</description>
        <label>Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Quote.OpportunityId</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Residential Projects</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Residential Project</label>
    <nameField>
        <label>Residential Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Projects</pluralLabel>
    <recordTypes>
        <fullName>TPS</fullName>
        <active>true</active>
        <description>Record Type for Third Party Sales</description>
        <label>TPS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PrepPOLineItems.cls
/* **************************************************************************************
* Class Name     : PrepPOLineItems 
* Version        : 1.0 
* Created Date   : 13 Aug 2015
* Function       : Class to prep PO Line Items based on Financial Offering

* Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Chaitanya Devarapalli       13 Aug 2015          Original Version
*************************************************************************************/
public class PrepPOLineItems{
    public static Integer runningPOLNumber;
    
	//Prepare PO Line Items
	public static List<Purchase_Order_Line__c> preparePOLines(Map<Id, Quote> mapQot, Purchase_Order__c po, Integer runningPOLNum) {
		List<Purchase_Order_Line__c> polList = new List<Purchase_Order_Line__c>();
		try {
			List<POLineFeeSetup__c> polFSList = new List<POLineFeeSetup__c>();
			Map<String, Id> rolePartnerIdMap = new Map<String, Id>();
			Map<String, Decimal> partnerRoleFeeMap = new Map<String, Decimal>();
			Map<String,Id> temprolePartnerIdMap = Dealerfee_cal_Utility_ModelBased.mPartnerRoleWithAccId;
			boolean bMaxFit = false;
			Boolean isTPSCashOrder = false;

			// TPS Cash order check
			if(po.Sales_Type__c == 'Cash' && String.isNotBlank(po.Dealer_Account__r.NH_SSE_Type__c) && po.Dealer_Account__r.NH_SSE_Type__c.contains('TPS')) {
				isTPSCashOrder = true;
			}

			for(String pRole : temprolePartnerIdMap.keySet()){
				if(pRole == 'Opportunity Owner'){
					rolePartnerIdMap.put('TPS', temprolePartnerIdMap.get(pRole));
					partnerRoleFeeMap.put('TPS', (Decimal)mapQot.get(po.Quote__c).get(Quote_Fees_Fields_API__c.getInstance(pRole).Field_API_Name__c));
				}
				else{
					rolePartnerIdMap.put(pRole, temprolePartnerIdMap.get(pRole));
					partnerRoleFeeMap.put(pRole, (Decimal)mapQot.get(po.Quote__c).get(Quote_Fees_Fields_API__c.getInstance(pRole).Field_API_Name__c));
				}
			}

			runningPOLNumber = runningPOLNum;
			Fee_Distribution__c tpsFD = new Fee_Distribution__c();
			Quote q = mapQot.get(po.Quote__c);

			if(q != null && q.Installation_Model__c != null) {
				polFSList = [SELECT Financial_Offering__c, MileStone__c, Partner_Role__c, Percentage__c, Item__c, Item__r.Name, Item__r.Item_ID__c, Item__r.Description__c, Value_From__c, MaxFit__c FROM POLineFeeSetup__c WHERE Model__c = :q.Installation_Model__c AND Item__c != null AND (MileStone__c != 'ORIGINATION' OR (MileStone__c='ORIGINATION' AND MaxFit__c = :bMaxFit))];

				// list for Alliance Partners on Residential Project
				List<Alliance_Partner__c> alliancePartners;
				if(isTPSCashOrder) {
					// get Alliance Partners
					for(Residential_Project__c rp : [SELECT Id FROM Residential_Project__c WHERE Quote__c IN :mapQot.keySet() ORDER BY CreatedDate DESC LIMIT 1]) {
						alliancePartners = [SELECT Partner_Account__c, Role__c FROM Alliance_Partner__c WHERE Residential_Project__c = :rp.Id AND Role__c != null];
					}
				}

				for(POLineFeeSetup__c polfs : polFSList){
					Double unitPrice;
					Integer quantity;
					Id vendorName;

					if(q.Installation_Model__r.Type__c == 'Auto'){
						if(q.Installation_Model__r.Partner__c == 'New Homes'){
							unitPrice = 0.00;
							quantity = 1;
						} else {
							if(q.get(polfs.Value_From__c) != null && polfs.Percentage__c != null) {
								unitPrice = Double.valueOf((Decimal)q.get(polfs.Value_From__c)) * polfs.Percentage__c / 100;
							} else unitPrice = 0;

							quantity = Integer.valueOf(unitPrice) != 0 ? Integer.valueOf(unitPrice) : 1;
							vendorName = q.Opportunity.Account.Partner_Account__c;
						}
					} else if(q.Installation_Model__r.Type__c == 'Manual'){
						tpsFD = Dealerfee_cal_Utility_ModelBased.fdTPS;

						if(tpsFD.MaxFit_Reduction__c > 0.00){
							bMaxFit = true;
						}

						if(polfs.Partner_Role__c == 'TPS'){
							Double tpsFee = PartnerRoleFeeMap.get(polfs.Partner_Role__c) + tpsFD.MaxFit_Reduction__c;

							if(polfs.MaxFit__c) {
								unitPrice = (tpsFee * polfs.Percentage__c / 100) - tpsFD.MaxFit_Reduction__c;
								quantity = Integer.valueOf((tpsFee * polfs.Percentage__c / 100) - tpsFD.MaxFit_Reduction__c) != 0 ? Integer.valueOf((tpsFee * polfs.Percentage__c / 100) - tpsFD.MaxFit_Reduction__c) : 1;
							} else {
								unitPrice = tpsFee * polfs.Percentage__c / 100;
								quantity = Integer.valueOf(tpsFee*polfs.Percentage__c / 100) != 0 ? Integer.valueOf(tpsFee*polfs.Percentage__c / 100) :1;
							}
						} else if(polfs.Partner_Role__c != null) {
							if(PartnerRoleFeeMap.get(polfs.Partner_Role__c) != null && polfs.Percentage__c != null) {
								unitPrice = PartnerRoleFeeMap.get(polfs.Partner_Role__c) * polfs.Percentage__c / 100;
							} else unitPrice = 0;

							quantity = Integer.valueOf(PartnerRoleFeeMap.get(polfs.Partner_Role__c) * polfs.Percentage__c / 100) != 0 ? Integer.valueOf(PartnerRoleFeeMap.get(polfs.Partner_Role__c) * polfs.Percentage__c / 100) : 1;

							vendorName = rolePartnerIdMap.get(polfs.Partner_Role__c);
						} else {
							if(q.get(polfs.Value_From__c) != null && polfs.Percentage__c != null) {
								unitPrice = Double.valueOf((Decimal)q.get(polfs.Value_From__c)) * polfs.Percentage__c / 100;
							} else unitPrice = 0;

							quantity = Integer.valueOf(unitPrice) != 0 ? Integer.valueOf(unitPrice) : 1;
							vendorName = q.Opportunity.Account.Partner_Account__c;
						}
					}
					if(isTPSCashOrder) {
						for(Alliance_Partner__c ap : alliancePartners) {
							if(ap.Role__c == polfs.Partner_Role__c) {
								vendorName = ap.Partner_Account__c;
							}
						}
					}

					polList.add(new Purchase_Order_Line__c(Order_Line_Number__c = String.valueOf(runningPOLNum ++),
														   Unit_Price__c = unitPrice,
														   Quantity__c = quantity,
														   Purchase_Order__c = po.Id,
														   Price__c = 100,
														   currencyisocode = po.currencyisocode,
														   Item_Number__c = polfs.Item__r.Name,
														   Item_ID__c = polfs.Item__r.Item_ID__c,
														   Item_Description__c = polfs.Item__r.Description__c,
														   Oracle_Item_ID__c = polfs.Item__c,
														   Oracle_Warehouse__c = q.QuoteType__c == 'Lease' ? q.Opportunity.Account.Oracle_Warehouse_Derived__c : '',
														   Vendor_Name__c = vendorName,
														   Partner_Role__c = polfs.Partner_Role__c
														  ));
					runningPOLNumber++;
				}
			}
		} catch(Exception e) {
			Exlog.Log(e);
		}
		return polList;
	}
    
    //Method to find missing roles in Opportunity Team based on the Installation Model selected
    public static String findMissingRoles(List<OpportunityTeamMember> otmList,Installation_Model__c iModel){
        String nP=null;
        Set<String> teamMemRoleSet = new Set<String>();
        for(OpportunityTeamMember otm:otmList){
            teamMemRoleSet.add(otm.TeamMemberRole);
        }
        if(iModel.Type__c=='Manual'){
            List<String> imList = iModel.Roles__c.split(';');
            if(!teamMemRoleSet.isEmpty()){
                for(String im:imList){
                    if(!teamMemRoleSet.contains(im)){
                        if(nP!=null)
                            nP = nP+','+im;
                        else
                            nP = im;
                    }
                }
            }
            return nP;
        }
        else
            return nP;
    }
    
}