objects/Alliance_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Residential Installation Project Mgmt
Priti Rastogi</description>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alliance Partners</relationshipLabel>
        <relationshipName>Alliance_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residential_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Residential Installation Project Mgmt
Priti Rastogi</description>
        <label>Residential Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Residential_Project__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Template</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Alliance Partners</relationshipLabel>
        <relationshipName>Alliance_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Residential Installation Project Mgmt
Priti Rastogi
The Roles a Partner Account can play on a residential project

New Roles are added for adding roles to community.</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Builder HERS Rater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Service Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Partner</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV HERS Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR HERS Rater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Alliance Partner</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Alliance Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NH_Community__c.object
<CustomObject>
    <label>NH Community</label>
    <nameField>
        <label>Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NH Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Project_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Project Tasks (Project Task)</relationshipLabel>
        <relationshipName>Project_Tasks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Project_Fields__c</fullName>
        <description>Residential Project Mgmt 
Priti Rastogi 
On a task template you can select the project fields that need to be populated before that task can be completed</description>
        <inlineHelpText>Required Project Fields are data fields on the project record that are required inputs for task completion. If one of these fields is associated with a project task, the system will validate that the field is populated before allowing task completion.</inlineHelpText>
        <label>Required Project Fields</label>
        <picklist>
            <picklistValues>
                <fullName>AHJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled Site Survey Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeowner Scheduled Installation Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi Level Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Service Panel Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Service Panel Manufacturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumption Monitoring Compatible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Breaker Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Breaker Rating (Amps)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battery Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smart Thermostat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeowner Utility Meter No.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeowner Utility Account No.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can solar breaker be installed in MSP?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder WO #</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder WO Date of Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder WO $ Value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actual Time (Hours)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tracking Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escrow Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Install Promised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rough Wire Promised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trim Promised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PTA Bldg Inspection Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Witness Test date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials Ship-to location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested Delivery Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solar Rebate (Expected)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Residential_Project__c</fullName>
        <description>Project Name: Residential Installation Management 
Requester: Priti Rastogi 
Project master.</description>
        <label>Residential Project</label>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Project Name: Residential Installation Management 
Requester: Priti Rastogi 
Statuses of task, based on task type. Key data point for task automation and reporting. ** Edit with Caution **</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Name: Residential Installation Management 
Requester: Priti Rastogi 
Populated programmatically. Lookup to the Task Template Parent. This field is used to keep templates in sync with their clones.</description>
        <label>Template Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Residential_Project__c.object
<CustomObject>
    <fields>
        <fullName>Battery_Storage__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
Battery storage field is manually populated as a text entry field by a system user (typically and EC)
This field allos the sales person to inform the operations team as to whether or not there is a battery storage system to install at the homeowner&apos;s site.
Future changes: this description was written on 5/10/2016 - In the near future, Battery Storage fields will populated as formula fields drawn from the quote record.</description>
        <label>Battery Storage</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Smart_Thermostat__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This pick list field is manually populated by the EC if she/he sells a homeowner a smart thermostat along with their solar system.

This will eventually become a formula field populated from the quote record once we implement functionality in the proposal tool for ECs to sell smart thermostats to homeowners.</description>
        <label>Smart Thermostat</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This pick list value is automatically populated at record creation with a default value of &quot;Active.&quot; This is a pick list field that can be manually updated by a project team member at any point during the installation project lifecycle in order to communicate project status to the whole team and to track project status data.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Residential Project</label>
    <nameField>
        <label>Residential Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ResidentialProjectNH_Test.cls
@isTest
public class ResidentialProjectNH_Test {
    
    static testMethod void communityAlliance() {

        Account installationPartner = TestFactory_StandardObjects.createPartnerAccount();
        insert installationPartner;
        
        NH_Community__c nhCommunity = TestFactory_ResidentialProjMgmt.createNHCommunity(NULL, NULL);
        insert nhCommunity;

        Alliance_Partner__c ap = TestFactory_ResidentialProjMgmt.createCommunityAlliancePartner(nhCommunity.Id, installationPartner.Id);
        ap.Role__c = 'IP';
        insert ap;

        Test.startTest();

        Residential_Project__c project = TestFactory_ResidentialProjMgmt.createNewHomeProjectWithTemplateTaskOnly(NULL, NULL, NULL, nhCommunity.Id, NULL);
        insert project; 

               

        List<Alliance_Partner__c> aps = [SELECT Role__c, Partner_Account__c FROM Alliance_Partner__c WHERE Residential_Project__c =: project.Id];
        system.assertEquals(aps.size(), 1);
        system.assertEquals(aps[0].Role__c, 'IP');
        system.assertEquals(aps[0].Partner_Account__c, installationPartner.Id);

        Account a = TestFactory_StandardObjects.getPartnerAccount();

        Alliance_Partner__c ap2 = TestFactory_ResidentialProjMgmt.createCommunityAlliancePartner(nhCommunity.Id, a.Id);
        ap2.Role__c = 'Inspection Partner';
        insert ap2;

        List<Alliance_Partner__c> aps2 = [SELECT Role__c, Partner_Account__c FROM Alliance_Partner__c WHERE Residential_Project__c =: project.Id];
        system.assertEquals(aps2.size(), 2);
        
        ap.Role__c = 'Design';
        update ap;

        List<Alliance_Partner__c> aps4 = [SELECT Role__c, Partner_Account__c FROM Alliance_Partner__c WHERE Residential_Project__c =: project.Id AND Partner_Account__c =: installationPartner.Id];
        system.assertEquals(aps4[0].Role__c, 'Design');

        Test.stopTest();

    }

    static testMethod void communityAllianceDelete(){
        Account installationPartner = TestFactory_StandardObjects.createPartnerAccount();
        insert installationPartner;
        
        NH_Community__c nhCommunity = TestFactory_ResidentialProjMgmt.createNHCommunity(NULL, NULL);
        insert nhCommunity;

        Alliance_Partner__c ap = TestFactory_ResidentialProjMgmt.createCommunityAlliancePartner(nhCommunity.Id, installationPartner.Id);
        ap.Role__c = 'IP';
        insert ap;

        Test.startTest();

        Residential_Project__c project = TestFactory_ResidentialProjMgmt.createNewHomeProjectWithTemplateTaskOnly(NULL, NULL, NULL, nhCommunity.Id, NULL);
        insert project; 

        delete ap;

        List<Alliance_Partner__c> aps = [SELECT Role__c, Partner_Account__c FROM Alliance_Partner__c WHERE Residential_Project__c =: project.Id];
        system.assertEquals(aps.size(), 0);
        Test.stopTest();

    }

    static testMethod void taskValidation() {

        Residential_Project__c template = TestFactory_ResidentialProjMgmt.createProjectTemplate();
        insert template;

        List<Project_Task__c> templateTasks = TestFactory_ResidentialProjMgmt.createTemplateTasks(template.Id, 5);

        templateTasks[0].Required_Project_Fields__c = 'Battery Storage;Smart Thermostat';
        insert templateTasks;

        
        Residential_Project__c project = TestFactory_ResidentialProjMgmt.createNewHomeProjectWithTemplate(NULL, NULL, NULL, NULL, template.Id);
        insert project;

        Test.startTest();

        Project_Task__c t = [SELECT Id, Status__c FROM Project_Task__c WHERE Template_Task__c =: templateTasks[0].Id LIMIT 1] ;
        t.Status__c = 'Completed';
        Boolean isError = FALSE;

        try{
            update t;
        }catch(Exception e){
            isError = TRUE;
        }
        
        system.assertEquals(isError, TRUE);

        project.Battery_Storage__c = 'No';
        project.Smart_Thermostat__c = 'No';
        update project;

        update t;

        Test.stopTest();
    }

}