objects/Alliance_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Project_Record_Type__c</fullName>
        <description>Returns the Residential Projects record type, used as criteria in trigger handlers</description>
        <formula>Residential_Project__r.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Residential Installation Project Mgmt
Priti Rastogi</description>
        <label>Residential Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Residential_Project__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Project Template</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Alliance Partners</relationshipLabel>
        <relationshipName>Alliance_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Residential Installation Project Mgmt
Priti Rastogi
The Roles a Partner Account can play on a residential project

New Roles are added for adding roles to community.</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Builder HERS Rater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Service Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Partner</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV HERS Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR HERS Rater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Alliance Partner</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Alliance Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Residential_Project__c.object
<CustomObject>
    <label>Residential Project</label>
    <nameField>
        <label>Residential Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Projects</pluralLabel>
    <recordTypes>
        <fullName>TPS</fullName>
        <active>true</active>
        <description>Record Type for Third Party Sales</description>
        <label>TPS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Alliance_PartnerBeforeInsertHandler.cls
/* **************************************************************************************
* Class Name     : Alliance_PartnerBeforeInserteHandler
* Version        : 1.0
* Created Date   : 13 feb 2017
* Function       : Function execute on Alliance_Partner before Insert

* Modification Log    :
* Developer             Date                   Description
* ----------------------------------------------------------------------------
* Ankit                 13 feb 2017         Original Version
*************************************************************************************/
public class Alliance_PartnerBeforeInsertHandler extends TriggerHandlerBase{
	// -------- Constants --------
	Id papId = AlliancePartnerUtility.papId;

	// -------- Variables --------
	Map<Id, List<Alliance_Partner__c>> mPartnerWithResProject;

	// -------- Constructor --------
	public Alliance_PartnerBeforeInsertHandler() {}

	//Begin processing
	public override void qualifyStartingRecords(List<sObject> newList, List<sObject> oldList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
		Diagnostics.push('Alliance_PartnerAfterDeleteHandler qualifyStartingRecords');

		List<Alliance_Partner__c> newRecords = (List<Alliance_Partner__c>)newList;
		mPartnerWithResProject = new Map<Id, List<Alliance_Partner__c>> ();

		for(Alliance_Partner__c ap : newRecords) {
			// filtering the records for TPS IP Partners
			if(ap.RecordTypeId == papId && ap.Project_Record_Type__c == 'TPS' && ap.Role__c == 'IP') {
				if(!mPartnerWithResProject.Containskey(ap.Residential_Project__c))
					mPartnerWithResProject.put(ap.Residential_Project__c, new List<Alliance_Partner__c>{ap});
				}
			}
		}

	public override void start() {
		// Calling the function to assign the IP on Alliance Partner
		if(!mPartnerWithResProject.isEmpty()) {
			AlliancePartnerUtility.finsertIPPartnerForTPS(mPartnerWithResProject);
		}
	}

	public override void finish(Boolean fromStart) {
		Diagnostics.pop();
	}
}