objects/ALR_Theaters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to manage the different theaters that should go through the ALR Process.</description>
    <label>ALR Theaters</label>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>AssignRandomPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if select Partner Randomly</inlineHelpText>
        <label>Paid Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>Case
00150174
Per Stelli Munnis request, this field should be added to Campaign</description>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Alliance</fullName>
        <active>true</active>
        <description>Alliance Campaigns</description>
        <label>Alliance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Campaign</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Partners</relationshipLabel>
        <relationshipName>Campaign_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if Partner is available for Opportunity Routing</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to partner account</description>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Partners</relationshipLabel>
        <relationshipName>Campaign_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Partner</label>
    <nameField>
        <label>Campaign Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DealerGeneral__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email_Address_For_ALR_Alerts__c</fullName>
        <description>This is the email address for communicating problems or information during the Automatic Lead Assignment process.</description>
        <inlineHelpText>This is the email address for communicating problems or information during the Automatic Lead Assignment process.</inlineHelpText>
        <label>Email Address For ALR Alerts</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enable_ALR_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked then the ALR process of Auto Conversion and Auto Dealer Assignment is active.</description>
        <inlineHelpText>If checked then the ALR process of Auto Conversion and Auto Dealer Assignment is active.</inlineHelpText>
        <label>Enable ALR Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enforce_Agreement_Check_Dealer_Search__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this is Checked then when searching for Dealers then the ECHO agreement check will be enforced. This means that the Dealer would have had to sign  a Partner Agreement with a name of something like &apos;Lead Handling Policy Agreement&apos;.</description>
        <inlineHelpText>If this is Checked then when searching for Dealers then the ECHO agreement check will be enforced. This means that the Dealer would have had to sign  a Partner Agreement with a name of something like &apos;Lead Handling Policy Agreement&apos;.</inlineHelpText>
        <label>Enforce Agreement Check (Dealer Search)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Google_Client_Id_Maps__c</fullName>
        <description>Assigned by Google for accessing their Google Maps API for Business</description>
        <inlineHelpText>Assigned by Google for accessing their Google Maps API for Business</inlineHelpText>
        <label>Google Client Id (Maps)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Google_Private_key_Maps__c</fullName>
        <description>Assigned by Google for accessing their Google Maps API for Business</description>
        <inlineHelpText>Assigned by Google for accessing their Google Maps API for Business</inlineHelpText>
        <label>Google Private key (Maps)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Test_First_Name__c</fullName>
        <description>If the Lead record was a test record then this is what would be its first name.</description>
        <inlineHelpText>If the Lead record was a test record then this is what would be its first name.</inlineHelpText>
        <label>Lead Test First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Dealer General</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Dealer_Assignment_Date__c</fullName>
        <description>SPD: on this date the lead was assigned to the dealer.</description>
        <label>Dealer Assignment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dealer_Locator_Selection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Selection</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Dealer Locator Selection)</relationshipLabel>
        <relationshipName>Leads3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Manufacturer__c</fullName>
        <label>Lead Manufacturer</label>
        <picklist>
            <picklistValues>
                <fullName>SunPower</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <businessProcess>SunPower Master Lead Process</businessProcess>
        <description>Partner Leads</description>
        <label>Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <businessProcess>SunPower Residential Leads Process</businessProcess>
        <description>Residential Leads</description>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestDealerUtilityIII.cls
@IsTest
public with sharing class TestDealerUtilityIII {

	@TestSetup
	static void createALRTheaters() {
		List<ALR_Theaters__c> theaters = new List<ALR_Theaters__c>();
		ALR_Theaters__c record1 = new ALR_Theaters__c(name = 'North America');
		theaters.add(record1);
		ALR_Theaters__c record2 = new ALR_Theaters__c(name = 'Central America and the Caribbean');
		theaters.add(record2);
		ALR_Theaters__c record3 = new ALR_Theaters__c(name = 'Europe');
		theaters.add(record3);

		insert theaters;
	}
	public TestDealerUtilityIII() {
	TestALRCommon.CreateCustomSetting();
	}

	static Lead CreateLeadPlain(String CompanyName, String Source_System, String Lead_Inferred_Quality, String Lead_Data_Quality) {
		Lead l = TestALRCommon.CreateRawLead(CompanyName, Source_System, Lead_Inferred_Quality, Lead_Data_Quality);
		insert l;
		return l;
	}    	


	static Lead CreateLeadDealerAssigned(String CompanyName, String Source_System, String Lead_Inferred_Quality, String Lead_Data_Quality, Id DealerId) {
		Lead l = TestALRCommon.CreateRawLead(CompanyName, Source_System, Lead_Inferred_Quality, Lead_Data_Quality);
		l.Dealer_Locator_Selection__c = DealerId;
		insert l;
		return l;
	}    	

	static Opportunity CreateOpportunityWithGenericCampaign(String OppName) {

		Campaign c = new Campaign(Name ='Test', Type = 'Other');
	    insert c;

		Account partner = TestClassFactory.CreateDealer('testdealer1', 'North America');
		
	    Campaign_Partner__c cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	    cp.enabled__c = true;
	    cp.Name = 'A';
	    cp.Partner__c = partner.Id;
	    insert cp;

	                                                                          		
		RecordType RecordTypeOpportunity = [Select  r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Opportunity' and Name = 'Home Owner' LIMIT 1];
	    Account a = TestClassFactory.testAccount('testHOAccount', TestClassFactory.RetrieveRecordTypeId('Account', 'Residential Customer'));
	    a.Theater__c = 'North America';
	    a.BillingCountry = 'United States';
	    a.Geolocation__Latitude__s = 39.718887;
        a.Geolocation__Longitude__s = -104.974036;
	    insert a;

		Opportunity o = new Opportunity();
		o.RecordTypeId = RecordTypeOpportunity.Id;
		o.CampaignId = c.Id;
		o.AccountId = a.Id;
		o.Name = OppName;
		o.StageName = 'New Opportunity';
		o.Lead_Manufacturer__c = 'SunPower';
		o.CloseDate = System.Today();
		o.Theater__c = 'North America';
	    insert o;
	    return o;                        
	                            
	}    

	static Opportunity CreateOpportunityWithPaidCampaign(String OppName) {
		
		Campaign c = new Campaign(Name ='Test', Type = 'Other', AssignRandomPartner__c = true);
	    insert c;

		Account partner = TestClassFactory.CreateDealer('testdealer1', 'North America');
		
	    Campaign_Partner__c cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	    cp.enabled__c = true;
	    cp.Name = 'A';
	    cp.Partner__c = partner.Id;
	    insert cp;

	                                                                          		
		RecordType RecordTypeOpportunity = [Select  r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Opportunity' and Name = 'Home Owner' LIMIT 1];
	    Account a = TestClassFactory.testAccount('testHOAccount', TestClassFactory.RetrieveRecordTypeId('Account', 'Residential Customer'));
	    a.Theater__c = 'North America';
	    a.BillingCountry = 'United States';
	    a.Geolocation__Latitude__s = 39.718887;
        a.Geolocation__Longitude__s = -104.974036;
	    insert a;

		Opportunity o = new Opportunity();
		o.RecordTypeId = RecordTypeOpportunity.Id;
		o.CampaignId = c.Id;
		o.AccountId = a.Id;
		o.Name = OppName;
		o.StageName = 'New Opportunity';
		o.Lead_Manufacturer__c = 'SunPower';
		o.Theater__c = 'North America';
		o.CloseDate = System.Today();
		o.Dealer_Selection__c = partner.Id;
		o.Dealer_Assignment_Date__c = Date.today();
	    insert o;
	    return o;                        
	                            
	}    

	static Opportunity CreateOpportunityWithAllianceCampaign(String OppName) {

		Campaign c = new Campaign(Name ='Test', Type = 'Alliance');
	    insert c;

		Account partner = TestClassFactory.CreateDealer('testdealer1', 'North America');
		
	    Campaign_Partner__c cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	    cp.enabled__c = true;
	    cp.Name = 'A';
	    cp.Partner__c = partner.Id;
	    insert cp;

	                                                                          		
		RecordType RecordTypeOpportunity = [Select  r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Opportunity' and Name = 'Home Owner' LIMIT 1];
	    Account a = TestClassFactory.testAccount('testHOAccount', TestClassFactory.RetrieveRecordTypeId('Account', 'Residential Customer'));
	    a.BillingCountry = 'United States';
	    a.Theater__c = 'North America';
	    a.Geolocation__Latitude__s = 39.718887;
        a.Geolocation__Longitude__s = -104.974036;
	    insert a;

		Opportunity o = new Opportunity();
		o.RecordTypeId = RecordTypeOpportunity.Id;
		o.CampaignId = c.Id;
		o.AccountId = a.Id;
		o.Name = OppName;
		o.StageName = 'New Opportunity';
		o.Lead_Manufacturer__c = 'SunPower';
		o.Theater__c = 'North America';
		o.CloseDate = System.Today();
	    insert o;
	    return o;                        
	                            
	}    
	/*
	static void CreateCustomSetting() {
	    //Add the Custom Setting
	    DealerGeneral__c dg = new DealerGeneral__c();
		dg.Email_Address_For_ALR_Alerts__c 				= 'test@sunpowercorp.com';
		dg.Enable_ALR_Process__c 								= true;
		dg.Enforce_Agreement_Check_Dealer_Search__c 	= false;
		dg.Google_Client_Id_Maps__c 							= '';
		dg.Google_Private_key_Maps__c 						= '';
		dg.Lead_Test_First_Name__c 							= 'SPWR Test';
	    insert dg;

	}
	*/
	static testMethod void testOpportunityWithGenericCampaignAssigned() {
		//TestALRCommon.CreateCustomSetting();		
		Opportunity o = CreateOpportunityWithGenericCampaign('TestCampaign1');
		if(o.Id != null) {
			List<Opportunity> oppIds = new List<Opportunity>();
			oppIds.add(o);
			Test.startTest();
			DealerUtility.AutoAssign(oppIds);
			Test.stopTest();
		}
	}

	static testMethod void testOpportunityWithPaidCampaignAssigned() {
		//TestALRCommon.CreateCustomSetting();
		Opportunity o = CreateOpportunityWithPaidCampaign('TestCampaign2');
		if(o.Id != null) {
			List<Opportunity> oppIds = new List<Opportunity>();
			oppIds.add(o);
			Test.startTest();
			DealerUtility.AutoAssign(oppIds);
			Test.stopTest();
		}
	}

	static testMethod void testOpportunityWithAllianceCampaignAssigned() {
		//TestALRCommon.CreateCustomSetting();
		Opportunity o = CreateOpportunityWithAllianceCampaign('TestCampaign3');
		if(o.Id != null) {
			List<Opportunity> oppIds = new List<Opportunity>();
			oppIds.add(o);
			Test.startTest();
			DealerUtility.AutoAssign(oppIds);
			Test.stopTest();
		}
	}        

}