objects/Answer__c.object
<CustomObject>
    <description>Case# 00615287 - This object will store answers for survey questions - Arokia Nathan</description>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Case# 00615287 - This field will store answer - Arokia Nathan</description>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Choice__c</fullName>
        <description>Case# 00615287 - This field will store choice like 1,2,3... A,B,C... - Arokia Nathan</description>
        <label>Choice</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Case# 00615287 - This field is question reference field - Arokia Nathan</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Answer#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Live_Agent_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Case# 00615287-Deploy Live Agent as replacement chat platform-Arokia Nathan</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Live Agent Settings</label>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Case# 00615287 - This object will store questions for any survey - Arokia Nathan</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Case# 00615287 - This field will store active/inactive flag - Arokia Nathan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>Case# 00615287 - This field will store application, functional area of this question - Arokia Nathan</description>
        <label>Application</label>
        <picklist>
            <picklistValues>
                <fullName>Live Chat Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Link Survey</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Case# 00615287 - This field will store question - Arokia Nathan</description>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Case# 00615287 - This field will store sequence number like 1,2,3... so that we can display questions in this order - Arokia Nathan</description>
        <label>Sequence#</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Case# 00615287 - This field will store question type like signle choice, multiple choise, text... - Arokia Nathan</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text Area</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EnergyLinkPostSurveyControllerTestData.cls
@isTest
public class EnergyLinkPostSurveyControllerTestData {

    @TestVisible Question__c q_1;
    @TestVisible Answer__c a_11, a_12, a_13, a_14, a_15;
    
    @TestVisible
    private void createSettings() {
        List <Live_Agent_Settings__c> settingList = new List <Live_Agent_Settings__c>();
        settingList.add(getNewSetting('Enable Post Chat Survey', 'true'));
        
        insert settingList;
    }

    @TestVisible
    private void createTestData() {
        createSettings();
        // question
        q_1 = getNewQuestion('q_1', 'Single Choice', 'Energy Link Survey', 1, true);
        insert new List <Question__c>{q_1};
        // answer
        a_11 = getNewAnswer(q_1.Id, '1', 'a_11');
        a_12 = getNewAnswer(q_1.Id, '2', 'a_12');
        a_13 = getNewAnswer(q_1.Id, '3', 'a_13');
        a_14 = getNewAnswer(q_1.Id, '4', 'a_14');
        a_15 = getNewAnswer(q_1.Id, '5', 'a_15');
        insert new List <Answer__c>{a_11, a_12, a_13, a_14, a_15};
        
    }
    
    private static Question__c getNewQuestion(String question, String type, String application, Integer sequence, Boolean active) {
        Question__c q = new Question__c();
        q.Question__c = question;
        q.Type__c = type;
        q.Application__c = application;
        q.Sequence__c = sequence;
        q.Active__c = active;
        return q;    
    }
    
    private static Answer__c getNewAnswer(String questionId, String choice, String answer) {
        Answer__c a = new Answer__c();
        a.Question__c = questionId;
        a.Choice__c = choice;
        a.Answer__c = answer;
        return a;    
    } 
        
    @TestVisible
    private static Live_Agent_Settings__c getNewSetting(String name, String value) {
        return new Live_Agent_Settings__c(Name = name, Value__c = value);
    }

}