objects/Bill_To_Site__c.object
<CustomObject>
    <description>Bill to site from Oracle ERP</description>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill to Site</relationshipLabel>
        <relationshipName>Bill_to_Site</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interface_Status__c</fullName>
        <label>Interface Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Bill to Site</label>
    <nameField>
        <label>Bill To Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill to Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Interface_Status__c</fullName>
        <label>Interface Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Oracle_Contact_id__c</fullName>
        <label>Oracle Contact id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Role__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Listed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winning Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Firm Offer Approval (PR1)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved (PR1)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected (PR1)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Contract Approval (PR2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved (PR2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected (PR2)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Opportunity Role</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Opportunity Role Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OracleRealTimeCashOrderOnOffSwitch__mdt.object
<CustomObject>
    <description>This is used to turn real time ordering on/off for cash orders being sent to Oracle. If the value is blank it will be picked up by the real time process. If the value for the Default record is New the SOA process will see it and process the order. This value is being stored in the interface_status__c field on the Purchase Order object.</description>
    <fields>
        <fullName>Interface_Status__c</fullName>
        <label>Interface Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>OracleRealTimeCashOrderOnOffSwitch</label>
    <pluralLabel>OracleRealTimeCashOrderOnOffSwitch</pluralLabel>
</CustomObject>

objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Accept_Terms__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accept Terms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bill_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Purchase Orders (Bill To Contact)</relationshipLabel>
        <relationshipName>Purchase_Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_to_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Site</label>
        <referenceTo>Bill_To_Site__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <label>Contact ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interface_Status__c</fullName>
        <label>Interface Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Taxible_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow dealer to select a checkbox on the order to indicate how they want to be the order to be taxed. The default is to &quot;charge tax&quot;.</description>
        <inlineHelpText>If un-checked, please fax a copy of tax exemption certificate.</inlineHelpText>
        <label>Taxable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oracle_Order_Number__c</fullName>
        <label>Oracle Order Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status_Interface_Message__c</fullName>
        <label>Order staus interface message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Purchase Orders (Ship To Contact)</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Site</label>
        <referenceTo>Ship_to_Site__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Instructions__c</fullName>
        <inlineHelpText>Please enter any special shipping instructions that might be helpful for the shipper</inlineHelpText>
        <label>Special Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Partner PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Order_Line__c.object
<CustomObject>
    <description>This custom object holds the order line information to be passed to Oracle after Online Ordering Process.</description>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <formula>IF(  (Oracle_Item_ID__r.Item_ID__c  =  &apos;500610&apos;), Purchase_Order__r.Requested_Delivery_Date__c + 35 ,Purchase_Order__r.Requested_Delivery_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLine-{0000000000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ship_to_Site__c.object
<CustomObject>
    <description>Ship to site from Oracle ERP</description>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <description>Cash flow redesign- Sangita changed the sharing to read only. This way all partner users who can read their account can create a shipping site.</description>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipping Sites (Dealer Account)</relationshipLabel>
        <relationshipName>Ship_to_Site</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Interface_Status__c</fullName>
        <label>Interface Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Shipping Site</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Ship to Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Sites</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderSubmissionDetails.cls
/*
* OrderSubmissionDetails - controller for post-submit details from cash based ordering system
* SFDC Release - https://na29.salesforce.com/a5B34000000xp2Y
*
* Pivotal Tracker Updates:
* ID #114709951 - Add Contact Phone to the Order Submission Screen - 3/18/16
* ID #114738873 - Purchase Order Re-submission (SFDC) - 4/16/2016
* ID #121852503 - Remove Ok to Ship  - 6/23/2016
* ID #114921295 - Remove Shipping Method Selection - WW32
* ID #128988357 - Real time Oracle order creation via Informatica eliminating SOA
*
*
*
*/

global with sharing class OrderSubmissionDetails extends PageControllerBase {

    //variables etc...
    public Boolean isPartnerUser {get; set;}
    public Purchase_Order__c purchaseOrder {get; set;}
    public List<Purchase_Order_Line__c> orderLines {get; set;}
    public User currentUser {get; set;}
    public String oppId {get; set;}
    public Opportunity opp {get; set;}
    public Bill_To_Site__c bts {get; set;}
    public Ship_To_Site__c sts {get; set;}
    public String shipContactName {get; set;}
    public String poName {get; set;}
    public String OppName {get; set;}
    public String poID;
    public Integer retries {get; private set;}
    public Integer numLines {get; set;}
    public String specialInstructions {
        get {
            return purchaseOrder.Special_Instructions__c;
        }
        set;
    }

    //constructor
    // #121852503 - remove Ok to Ship
    // #114921295 - removed ship to method validation - 07/10/2016
    public OrderSubmissionDetails(ApexPages.StandardController controller) {
        retries = 0;
        poID = ApexPages.currentPage().getParameters().get('POID');

        if(poID != null){
            for(Purchase_Order__c p:[Select p.OwnerID, p.Ship_To_Contact__c, p.Ship_To_Contact__r.Name, p.Is_Taxible_Order__c,
                                            p.Opportunity__c, p.Opportunity__r.Name, p.Opportunity__r.Id,
                                            p.Special_Instructions__c, p.Name, p.Id, p.Contact_ID__c,
                                            p.Oracle_Order_Number__c, p.Order_Status_Interface_Message__c,p.Ship_To_Contact__r.Phone,
                                            p.Order_Total__c,p.Requested_Delivery_Date__c, p.Bill_to_site__c, p.Ship_to_site__c,
                                            p.Dealer_Account__r.Name, Order_Status__c, p.Accept_Terms__c, p.Interface_Status__c,
                                            p.Bill_To_Contact__r.Oracle_Contact_id__c, p.Ship_To_Contact__r.Oracle_Contact_id__c
                                     From Purchase_Order__c p
                                     where p.Id =:poID]){
                purchaseOrder = p;

                //bill to site
                try {
                    bts = [SELECT Id, Address1__c, City__c, State__c, Site_ID__c, Zip__c FROM Bill_To_Site__c WHERE id =: p.Bill_to_site__c];
                }  catch(Exception e) {
                    System.debug('BTS ERROR: ' + e.getMessage());
                }

                //ship to site
                try {
                    sts = [SELECT Id, Address__c, Address1__c, City__c, Country__c, Dealer_Account__c, Oracle_County__c, SiteID__c, State__c, Status__c, Zip__c FROM Ship_To_Site__c WHERE id =: p.Ship_to_site__c];
                }  catch(Exception e) {
                    System.debug('STS ERROR: ' + e.getMessage());
                }
            }
            try {
                orderLines = [SELECT Item_Description__c, Item_ID__c, Quantity__c FROM Purchase_Order_Line__c where Purchase_Order__c=:poID];
                numLines = orderLines.size();
            } catch(Exception e) {
                System.debug('orderLines error: ' + e.getMessage() + ' - ' + e.getStackTraceString());
            }
        }

        currentUser = [Select Id, Name, Profile.Name, UserType, Contact.Country_Domain__c, Contact.Account.RSM__c,
                              ContactId, Contact.AccountID, Contact.Authorized_to_Order__c, Contact.Account.Primary_PSR__c,
                              Contact.Account.Oracle_Operating_Unit__c, Contact.Account.Online_Order_Access__c,
                              Contact.Account.AccountNumber, Contact.Account.Name,
                              Contact.Account.Oracle_Account_Number__c, CurrencyISOCode
                       From User Where Id =: UserInfo.getUserId()];

        isPartnerUser = SPCommunityUtility.isPartnerUser();
    } //end of constructor

    public PageReference init() {
        try {
            // #128988357
            // make sure this isn't a SOA order or already has an order number or has an error
            if(String.isBlank(purchaseOrder.Interface_Status__c) && String.isBlank(purchaseOrder.Oracle_Order_Number__c) && !purchaseOrder.Order_Status__c.contains('Error')) {
                ResultMessage stsResult;
                // #133369091
                // check to see if ship to contact has oracle id
                if(String.isNotBlank(purchaseOrder.Ship_To_Contact__c)) {
                    try {
                       Contact stcon = [SELECT Id, Phone, FirstName, LastName, Email, MobilePhone, Oracle_Contact_id__c, Account.Oracle_Account_Number__c FROM Contact WHERE Id =: purchaseOrder.Ship_To_Contact__c];

                        if(String.isBlank(stcon.Oracle_Contact_id__c)) {
                            String stc = JSON.serialize(stcon);
                            OracleOrderUtility.createOracleContact(stc, 'SHIP_TO', purchaseOrder.Id);
                        }
                    } catch(Exception e2) {
                        SpectrumDebugUtility.createExceptionLog(e2.getMessage(), e2.getStackTraceString(), 'SO Create Oracle Contact Error', purchaseOrder.Id);
                        System.debug('SO Create Oracle Contact Error ' + e2.getMessage() + ' ' + e2.getStackTraceString());
                    }
                }
                // check ship to site
                String siteId = sts.SiteID__c;
                Boolean isNewSite = false;
                // make sure we have a ship to site id that's active
                if(String.isBlank(siteId) || String.isNotBlank(siteId) && sts.Status__c != 'Active') {
                    isNewSite = true;
                    // get the account info for oracle
                    Account a = [SELECT Line_of_Business__c, Oracle_Account_Number__c FROM Account WHERE Id = :sts.Dealer_Account__c];
                    // check to see if it's a combo partner so site type in Oracle is set correctly
                    String channelType;
                    if(a.Line_of_Business__c.toUpperCase() == 'COMBO') {
                        channelType = 'RVAR';
                    } else {
                        channelType = a.Line_of_Business__c.toUpperCase();
                    }
                    // submit to the service for address creation
                    stsResult = OracleOrderService.saveShippingSiteToOracle(sts, a.Oracle_Account_Number__c, 'PURCHASE', channelType);
                    // check result
                    if(stsResult.success) {
                        // deserialize response
                        OracleOrderUtility.InformaticaShipToSiteResponse informaticaResponse = (OracleOrderUtility.InformaticaShipToSiteResponse)JSON.deserialize(stsResult.message, OracleOrderUtility.InformaticaShipToSiteResponse.class);
                        // get site id
                        String newStsId = informaticaResponse.process_customer_response.ship_to_sites.ship_to_site.cust_acct_site_id;
                        // check response
                        if(informaticaResponse.process_customer_response.status == 'S' && String.isNotBlank(newStsId)) {
                            // set the oracle site id
                            siteId = newStsId;
                            sts.SiteID__c = siteId;
                        }
                    }
                }
                // send the order to oracle
                ResultMessage orderResult = OracleOrderUtility.sendNewCashOrder(poID, siteId);
                // check the ship to site
                if(isNewSite) {
                    // log result
                    if(!stsResult.logs.isEmpty()) {
                        SpectrumDebugUtility.generateDebugLog(stsResult.logs);
                    }
                    // check site to make sure it's not a duplicate
                    OracleOrderUtility.checkNewShipToSite(stsResult.message, sts.Id);
                }
                // check the order result
                checkResult(orderResult);
            }
        } catch (Exception e) {
            SpectrumDebugUtility.createExceptionLog(e.getMessage(), e.getStackTraceString(), 'SO Oracle Order Error', purchaseOrder.Id);
            purchaseOrder.Order_Status__c = 'Error';
            purchaseOrder.Order_Status_Interface_Message__c = e.getMessage() + ' - ' + e.getStackTraceString();
            update purchaseOrder;
        }
        return null;
    }

    //#114738873
    public PageReference psrSubmitOrder() {
        if(currentUser.Contact.AccountId == null) {
            if(purchaseOrder.Accept_Terms__c && purchaseOrder.Bill_To_Site__c != null && purchaseOrder.Ship_to_Site__c != null) {
                purchaseOrder.Order_Status__c = 'Submitted';
                // #128988357 - get the interface status from the custom metadata object to turn on/off real time ordering (SOA will see this order if it's set to New)
                if(String.isBlank(purchaseOrder.Interface_Status__c)) {
                    purchaseOrder.Interface_Status__c = [SELECT Interface_Status__c FROM OracleRealTimeCashOrderOnOffSwitch__mdt WHERE DeveloperName = 'Default' LIMIT 1].Interface_Status__c;
                } else purchaseOrder.Interface_Status__c = 'New';

                try {
                    // #128988357
                    if(String.isBlank(purchaseOrder.Interface_Status__c) && String.isBlank(purchaseOrder.Oracle_Order_Number__c)) {
                        ResultMessage result = OracleOrderUtility.SendNewCashOrder(poID, sts.SiteID__c);
                        checkResult(result);
                    } else {
                        update purchaseOrder;
                        PageReference pg = new PageReference('/apex/OrderSubmissionDetails?POID='+purchaseOrder.Id);
                        return pg.setRedirect(true);
                    }
                } catch(Exception e) {
                    System.debug('EXCEPTION: ' + e);
                    ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
                    ApexPages.addMessage(errorMsg);
                    return null;
                }
            }
        }
        return null;
    }

    public PageReference reSubmitOrder() {
        // check retries
        if(retries < 2) {
            retries++;
            ResultMessage result = OracleOrderUtility.sendNewCashOrder(poID, sts.SiteID__c);
            checkResult(result);
            if(String.isNotBlank(purchaseOrder.Oracle_Order_Number__c)) {
                PageReference pg = new PageReference('/apex/OrderSubmissionDetails?POID='+purchaseOrder.Id);
                return pg.setRedirect(true);
            }
        }
        return null;
    }

    public PageReference checkResult(ResultMessage result){
        //SAMPLE Result.message {"sales_order_response": {"status": "S", "status_message": "Successfully Processed", "sales_order_response_header": {"order_number": "12217702"}}}
        try{
			// insert logs
            if(!result.logs.isEmpty()) {
                SpectrumDebugUtility.generateDebugLog(result.logs);
            }
            // check result
            if(result.success) {
                // deserialize the message
                OracleOrderUtility.InformaticaCreateOrderResponse response = (OracleOrderUtility.InformaticaCreateOrderResponse)JSON.deserialize(result.message, OracleOrderUtility.InformaticaCreateOrderResponse.class);
                // set vars
                String status = response.sales_order_response.status;
                String statusMessage = response.sales_order_response.status_message;
                String orderNumber = response.sales_order_response.sales_order_response_header.order_number;
                String oracleId = response.sales_order_response.sales_order_response_header.header_id;
                // check the Oracle status
                if(status == 'S') {
                    // update purchase order
                    purchaseOrder.Oracle_Order_Number__c = orderNumber;
                    purchaseOrder.OracleOrderHeaderId__c = oracleId;
                    purchaseOrder.Order_Status__c = 'Processed';
                    purchaseOrder.Order_Status_Interface_Message__c = statusMessage;
                } else if(status == 'E' && String.isNotBlank(orderNumber)) {
                    // update purchase order
                    purchaseOrder.Oracle_Order_Number__c = orderNumber;
                    purchaseOrder.OracleOrderHeaderId__c = oracleId;
                    purchaseOrder.Order_Status__c = 'Processed';
                    purchaseOrder.Order_Status_Interface_Message__c = statusMessage;
                } else {
                    // Oracle error
                    purchaseOrder.Order_Status__c = 'Error';
                    purchaseOrder.Order_Status_Interface_Message__c = statusMessage;
                }
                // update the purchase order
                update purchaseOrder;

            } else {
                // check for timeout error
                if(result.message.containsIgnoreCase('timeout') || result.message.containsIgnoreCase('timed out')) {
                    purchaseOrder.Order_Status__c = 'Timeout Error';
                    purchaseOrder.Order_Status_Interface_Message__c = result.message;
                } else {
                    purchaseOrder.Order_Status__c = 'Error';
                    purchaseOrder.Order_Status_Interface_Message__c = result.message;
                }
                // update the purchase order
                update purchaseOrder;
            }
        }
        catch(Exception e){
            SpectrumDebugUtility.createExceptionLog(e.getMessage(), e.getStackTraceString(), 'SO Oracle Order Error', purchaseOrder.Id);
            purchaseOrder.Order_Status__c = 'Error';
            purchaseOrder.Order_Status_Interface_Message__c = e.getMessage() + ' - ' + e.getStackTraceString();
            update purchaseOrder;
        }
        return null;
    }
}