objects/Business_Unit__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Business Unit</label>
</CustomObject>

objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Main_Category__c</fullName>
        <formula>Sub_Category__r.Main_Category__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>This field will be use for Opportunity Score related Main Category &gt; Sub=Category&gt;Category&gt;Category Value Score.</description>
        <label>Sub-Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Systems</fullName>
        <active>true</active>
        <label>Systems</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DocGenCommercial__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>this contains the list of json names that needs to be sent to Commercial Opportunity</description>
    <label>DocGenCommercial</label>
</CustomObject>

objects/Main_Category__c.object
<CustomObject>
    <description>This object will be use for Opportunity Score related Main Category.</description>
    <label>Main Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Main Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity_Score__c.object
<CustomObject>
    <description>This object will be use for Opportunity Score result.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>This will use for Category</description>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Category__c</fullName>
        <description>This will store Main Category</description>
        <label>Main Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Score__c</fullName>
        <description>Maximum score of selected category value</description>
        <label>Max Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This field is use for oppty score</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Scores</relationshipLabel>
        <relationshipName>Opportunity_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>This will use for Sub-Category.</description>
        <label>Sub-Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Score</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>CASE( PricebookEntry.Product2.Product_Type__c ,&quot;Contingency&quot;,&quot;Contingency&quot;, 
&quot;Design &amp; Permits&quot;,&quot;Design &amp; Permits&quot;,
&quot;Misc. Materials&quot;,&quot;Misc. Materials&quot;,
&quot;Mounting System&quot;,&quot;Mounting System&quot;,
&quot;Other&quot;,&quot;Other&quot;,
&quot;Procurement and Construction&quot;,&quot;Procurement and Construction&quot;,
&quot;PV&quot;,&quot;PV&quot;,
&quot;Sales Tax %&quot;,&quot;Sales Tax %&quot;,
&quot;Services&quot;,&quot;Services&quot;,
&quot;Total Price&quot;,&quot;Total Price&quot;,
&quot;PV Module&quot;,&quot;PV Module&quot;,
&quot;O&amp;M&quot;,&quot;O&amp;M&quot;,
&quot;Development&quot;,&quot;Development&quot;,
&quot;Balance of System&quot;,&quot;Balance of System&quot;,
&quot;BOS&quot;,&quot;BOS&quot;,
&quot;Storage&quot;,&quot;Storage&quot;,
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Balance of System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Cell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Satcon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total Price</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Sub_Category__c.object
<CustomObject>
    <description>This object will be use for Opportunity Score related Main Category with Sub-Category.</description>
    <fields>
        <fullName>Main_Category__c</fullName>
        <description>This Field will be use for Opportunity Score related Main Category &gt; Sub=Category&gt;Category&gt;Category Value Score.</description>
        <label>Main Category</label>
        <referenceTo>Main_Category__c</referenceTo>
        <relationshipLabel>Sub-Categories</relationshipLabel>
        <relationshipName>Sub_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sub-Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestDocGenCommercial.cls
@isTest(seeAllData = true)
private class TestDocGenCommercial {

 	static Account newAccount;
    static Contact newContact;
    static Opportunity newOpportunity;
  
   
    static testmethod void unitTest(){
        String postFix = String.valueOf(Datetime.now().getTime());
		newAccount = TestUtils.createAccount('TestCommercialAccount' + postFix, TestUtils.getResidentialRecordTypeId(), true);
        newContact = TestUtils.createContact('TestCommercialContact' + postFix, newAccount.Id, true);
        
        List<Opportunity > oppList = new List<Opportunity >();
        Opportunity opp = new Opportunity();
     	newOpportunity = TestUtils.createOpportunities(1, newAccount.id, newContact.Id, true).get(0);
		newOpportunity.Business_Unit__c = 'NA Commercial';
		newOpportunity.RecordTypeId = TestClassFactory.retrieveRecordTypeID('Opportunity', 'Systems');
        newOpportunity.StageName = '01 - Build Single Sales Objective';
        newOpportunity.Country__c = 'United States';
        newOpportunity.Sub_Region__c = 'California - North';
        newOpportunity.Customer_selection_process__c = 'Test Customer selection process';
        newOpportunity.My_Position_vs_Competition__c = 'Test My position v/s compition';
        newOpportunity.Closure_Deal_Risks__c = 'Test closure deal risks';
        newOpportunity.Proposal_Due_Date__c = System.today();      
        update newOpportunity; 		
		Test.startTest();
		List<Pricebook2> pbList = [Select Id From Pricebook2 where Name ='Standard Price Book' limit 1];
        Id pbId;
        if(pbList.size()>0)
            pbId = pbList.get(0).Id;
        Product2 p = new Product2(Name = 'TestProduct', IsActive = true, Family='PV Cell', Product_Type__c = 'PV Module', Unit__c =1000);
        insert p;
        
        PricebookEntry pe = new PricebookEntry(Product2Id = p.Id, Pricebook2Id = pbId, IsActive = true, UnitPrice = 10.0);
        insert pe;  
        
        OpportunityLineItem oppLine = new OpportunityLineItem();
        oppLine.OpportunityId = newOpportunity.Id;
        oppLine.PricebookEntryId = pe.Id;
        oppLine.UnitPrice = 5.0;
        oppLine.Quantity = 2.0; 
        insert oppLine;
    	System.debug('**oppLine==>'+oppLine);
    	List<Opportunity_Score__c> listScore = new List<Opportunity_Score__c>();
    	for(Integer i=0; i<=1 ; i++){
			Opportunity_Score__c oppScore = new Opportunity_Score__c();		
	        oppScore.Opportunity__c = newOpportunity.Id;
	        if(i==0)
	        	oppScore.Main_Category__c = 'Design/Product/EPC';
	        else
	        	oppScore.Main_Category__c = 'Business Case';
	        oppScore.Sub_Category__c = 'Sub';
	        oppScore.Category__c = 'Cat';	
			oppScore.Max_Score__c = 5;
			listScore.add(oppScore);
    	}
		insert listScore;
		System.debug('**listScore==>'+listScore);
		DocGenCommercial docGen = new DocGenCommercial();
		docGen.settings = DocGenCommercial__c.getAll().values();
        docGen.loadSettings();
        docGen.sendDataToDocGen(newOpportunity.Id,'No','Commercial','PR0');
        
        //Negative testing
        Test.stopTest();
    }

}