objects/Business_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Registrations</relationshipLabel>
        <relationshipName>Business_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>License_CIty__c</fullName>
        <description>This field is used to store license city of business registration</description>
        <label>License CIty</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field is used to store the state in which the Partner has business license or simply it tells the license state</description>
        <label>License State</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business Registration</label>
    <nameField>
        <label>Business Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BusinessRegistrationBeforeUpdateHandler.cls
public with sharing class BusinessRegistrationBeforeUpdateHandler extends TriggerHandlerBase {
    public BusinessRegistrationBeforeUpdateHandler() {
        
    }

    // -------- Variables --------
    
    
    
    // -------- Properties --------
    // Qualified records for actions
    private Map<Id, Business_Registration__c> qualifiedBusinessRegs;
    private List<Id> partnerAccountIds;
    private List<String> billingStates;
    private List<Id> businessRegIds;
     

    //Begin processing
    public override void qualifyStartingRecords(List<sObject> newList, List<sObject> oldList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
        Diagnostics.push('BusinessRegistartionBeforeInsert qualifyStartingRecords');

        Map<ID, Business_Registration__c> newBusinessRegMap = (Map<ID, Business_Registration__c>)newMap;
        Map<ID, Business_Registration__c> oldBusinessRegMap = (Map<ID, Business_Registration__c>)oldMap;
        List<Business_Registration__c> newBusinessRegList = (List<Business_Registration__c>)newList;
        List<Business_Registration__c> oldBusinessRegList = (List<Business_Registration__c>)oldList;

        qualifiedBusinessRegs = new Map<Id, Business_Registration__c>();
        partnerAccountIds = new List<Id>();
        billingStates = new List<String>();
        businessRegIds = new List<Id>();
        //getting the list of Partner Ids and states from incoming Business Registrations
        for(Business_Registration__c br : newBusinessRegList){
            if(br.Account__c != null && br.State__c != null){
                qualifiedBusinessRegs.put(br.Id,br);
                partnerAccountIds.add(br.Account__c);
                billingStates.add(br.State__c);
                businessRegIds.add(br.Id);
            }
        }
    }


    public override void start(){
        
        if(qualifiedBusinessRegs.isEmpty()) return;

        List<Business_Registration__c> businessRegList = new List<Business_Registration__c>();        
        if(partnerAccountIds.size() > 0 && billingStates.size() > 0){
            businessRegList = [select id,Account__c,State__c,License_City__c from Business_Registration__c where Account__c IN : partnerAccountIds AND State__c IN :billingStates AND ID NOT IN :businessRegIds];
        }

        for(Business_Registration__c br : qualifiedBusinessRegs.values()){
               if(!businessRegList.isEmpty()){
                    for(Business_Registration__c b : businessRegList){
                        if(br.Id != b.Id && br.Account__c == b.Account__c && br.State__c == b.State__c && br.License_City__c == b.License_City__c && !Util.currentUser.ByPassValidation__c){
                            system.debug('Business Registration already exists');
                            br.addError(System.Label.Business_Registration_Duplicate_Error);
                            break;
                        }
                    }
               }
        }
        
    }

    public override void finish(Boolean fromStart){
        if(fromStart){

        }
        Diagnostics.pop();
    }
}