objects/Business_Unit__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Business Unit</label>
</CustomObject>

objects/Design__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>Text(Opportunity__r.Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site_Information_Form__c</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Design</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_Controller_Activate_Design.cls
public class Test_Controller_Activate_Design
 {         
  public static TestMethod void Test001()
   {    
    Date dt = date.newinstance(2010,1,4);
     Account acc = new Account(Name = 'testaccc',CurrencyIsoCode = 'USD', Account_Status__c = 'Active',SPWR_Relationship_Type__c = 'Off-Taker',BillingStreet = 'West Mare',BillingCity = 'SanFrancisco',BillingPostalCode = '2345', BillingCountry = 'United States of America',Phone = '1234');
      insert acc;
       // Done for case # 00066557 consolidating business units IBD and Components into 'UPP Intl'.
       // Opportunity o = new Opportunity(Name = 'Tesrt',StageName= 'Budgetary Pricing',Business_Unit__c='IBD',CloseDate=dt,AccountId = acc.ID);
       Opportunity o = new Opportunity(Name = 'Tesrt',StageName= 'Budgetary Pricing',Business_Unit__c='UPP Intl',CloseDate=dt,AccountId = acc.ID);
        Insert o;
         Pricebook2 pb = [select Id from Pricebook2 where Name='Systems Price Book'];
          Design__c design = new Design__c(Opportunity__c=o.Id,Price_Book__c=pb.Id);
           insert design;
            /*List<Design__c> dsgn= new List<Design__c>([select id , Site__c,Primary__c from Design__c where Primary__c=true  limit 2 ]);
               List<Design__c> dsgn1 = new List<Design__c>();
                for(Design__c nxdsgn1:dsgn )
                 {
                  dsgn1.add(nxdsgn1.clone(false));
                   }
                    Insert dsgn1;*/
                      list<Design__c> dlist = new list<Design__c>();
                     dlist.add(design);
                    ApexPages.currentPage().getParameters().put('id',design.Id); 
                   ApexPages.StandardSetController assc= new ApexPages.StandardSetController(dlist);
                  Controller_Activate_Design cad=new Controller_Activate_Design(assc);
                 cad.updateDesign();
               cad.ActivateDesign();
              ApexPages.StandardSetController assc1= new ApexPages.StandardSetController(dlist);
            Controller_Activate_Design cad1=new Controller_Activate_Design(assc1); 
          //cad1.updateDesign();
         Delete design;
       cad1.ActivateDesign();
      }
    }