objects/Business_Unit__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Business Unit</label>
</CustomObject>

objects/PSR__c.object
<CustomObject>
    <description>Object used to captured information related to a Project Service Request.</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity__r.Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PSR</relationshipLabel>
        <relationshipName>PSR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>PSR</relationshipLabel>
        <relationshipName>PSR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <formula>Site__r.Site_Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <formula>HYPERLINK( &apos;/&apos;&amp;Site__c , Site__r.Site_Name__c,&apos;_SELF&apos; )</formula>
        <label>Site Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site_Information_Form__c</referenceTo>
        <relationshipLabel>PSR</relationshipLabel>
        <relationshipName>PSR</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{000000}</displayFormat>
        <label>PSR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity.Business_Unit__c)</formula>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSR</label>
        <referenceTo>PSR__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_City__c</fullName>
        <description>Project: GPP
Description: Address of Site for which Quote is for, Stores Address&apos;s City</description>
        <inlineHelpText>Site Address (Property Address)</inlineHelpText>
        <label>Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <description>Project: GPP
Description: Address of Site for which Quote is for, Stores Address&apos;s Country</description>
        <inlineHelpText>Site Address (Property Address)</inlineHelpText>
        <label>Site Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_State__c</fullName>
        <description>Project: GPP
Description: Address of Site for which Quote is for, Stores Address&apos;s State</description>
        <inlineHelpText>Site Address (Property Address)</inlineHelpText>
        <label>Site State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Site_Information_Form__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity_del__r.Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N30000000t6dPEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_City__c</fullName>
        <label>Site City</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <label>Site Country</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <externalId>true</externalId>
        <label>Site Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_State__c</fullName>
        <label>Site State</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Status__c</fullName>
        <description>Field determines the status of a site.</description>
        <label>Site Status</label>
        <picklist>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Comm. Letter signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased/Leased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under evaluation/negotiation</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>SIF{00000}</displayFormat>
        <label>SIF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Global Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Intl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Commercial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Controller_Select_Site.cls
/**********************************************************************
Class                   :   Controller_Select_Site
Related Page            :   Select_Site
Created By              :   Appirio Offshore
Created On              :   Jan 07, 2010
Desciption              :   Controller apex class for vf page Select_Site.
************************************************************************/
//Site_Information_Form__c
public class Controller_Select_Site {
    
    //current PSR record
    PSR__c currentPSR{get;set;}  
    
    //list of site wrapper objects
    public List<SiteWrapper> listSiteWrapper{get;set;}
    //variable binded with hidden input field in vf page
    
    public String selectedSiteOnPage {get;set;}
    
    //variable to decide whether the table on page should be displayed or not
    //if listSiteWrapper is not null or its size > 0 then return true otherwise false
    public Boolean renderTable{
        get{
            if(listSiteWrapper != null && listSiteWrapper.size() > 0)
                return true;
            else
                return false;   
        }
    }
    
    /** Constructor Controller_Select_Site.
     *  @param ApexPages.standardController
     */
    public Controller_Select_Site(ApexPages.StandardController controller){
        //initializing selectedSiteOnPage to blank
        selectedSiteOnPage = '';
        //instantiating listSiteWrapper
        listSiteWrapper = new List<SiteWrapper>();
        //reference of wrapper object
        SiteWrapper wrapper;
        //current psr record
        currentPSR = (PSR__c)controller.getRecord();
        
        //added Business_Unit__c in query for Case#00066255
        currentPSR = [select name, Quote__c, Opportunity__c,site__c,Business_Unit__c 
            from PSR__c where ID =: currentPSR.ID limit 1];
        
        //Case#00108044 - Removing Quote's mandatory check
        /*//modified condition for Case#00066255
        //if the current PSR does not have Quote__c then display a page error message
        if((currentPSR.Business_Unit__c == null || !Controller_Send_PSR.BUsToBypassQuoteCheck.contains(currentPSR.Business_Unit__c.toUpperCase())) 
           && currentPSR.Quote__c == null){
            ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.ERROR, 
                    'The Quote field must be populated.'));
            return;                      
        }*/
         
        //querying child Site_Information_Form__c records of the opportunity
        List<Site_Information_Form__c> listSites = [Select s.id, s.Site_State__c, 
            s.Site_Name__c, s.Site_Status__c, 
            s.Site_Country__c, s.Site_City__c, s.Name 
            From Site_Information_Form__c s 
            where s.Site_Status__c!='Inactive' 
                and s.opportunity_del__c =: currentPSR.Opportunity__c ];
        
        
        //if the associated Opportunity does not have any sites then display a page error message
        if(listSites == null || listSites.size() == 0){
            ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.ERROR, 
                    'The Opportunity does not have any active sites.'));
            return;
        }
        
        //iterating through child site_information_form__c records of Quote__r.Opportunity__c
        for(Site_Information_Form__c site:listSites){           
            //if site.id == currentPSR.site__c means it is to be displayed checked on the vf page 
            if(currentPSR.site__c != null && site.id == currentPSR.site__c) {
                wrapper = new SiteWrapper(true,site);
                selectedSiteOnPage = currentPSR.site__c;
            }
            else
                wrapper = new SiteWrapper(false,site);
                
            listSiteWrapper.add(wrapper);       
        }
    }
    
    /** Action function called from button 'return to PSR' on page 'Select_Site'. 
     *  @return PageReference
     */     
    public PageReference returnToPSR(){
        //boolean variable to decide whether current psr record should be updated or not
        //if the site__c is changed then update current psr record
        Boolean updatePSR = false;
        System.debug('*******value '+selectedSiteOnPage);
        System.debug('*******Size of ListSiteWrapper '+listSiteWrapper.size());
        if(listSiteWrapper != null && listSiteWrapper.size() > 0 
            && selectedSiteOnPage != null && selectedSiteOnPage != ''){
            //iterating through listSiteWrapper
            for(SiteWrapper wrapper:listSiteWrapper){
                //if wrapper.site.id == selectedSiteOnPage means this site is selected by user from the page
                if(String.valueof(wrapper.site.id) == selectedSiteOnPage){
                    currentPSR.site__c = wrapper.site.Id;                   
                    updatePSR = true;
                    break;
                }
            }//end of for-loop
        }//end of if
        
        //updating the currentPSR record
        if(updatePSR)
            update currentPSR;
            
        //initializing selectedSiteOnPage to blank after updating psr
        selectedSiteOnPage = '';
        //return to current psr record  
        return new PageReference('/' + currentPSR.Id);
    }
    
    public PageReference Cancel(){
        return new PageReference('/' + currentPSR.Id);      
    }   
    
    //Inner wrapper class around Site_Information_Form__c
    public class SiteWrapper{
        //variable to display the selected site checked on the page
        public Boolean isSelected{get;set;}
        //Site_Information_Form__c object
        public Site_Information_Form__c site{get;set;}
        
        //constructor
        public SiteWrapper(Boolean isSelected, Site_Information_Form__c site){
            this.isSelected = isSelected;
            this.site = site;
        }
    }
}