objects/Business_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Registrations</relationshipLabel>
        <relationshipName>Business_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expires_On__c</fullName>
        <description>this is used to capture the contractors license expiration date</description>
        <label>Contractors Lic Exp</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>Contractors License #</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field is used to store the state in which the Partner has business license or simply it tells the license state</description>
        <label>License State</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business Registration</label>
    <nameField>
        <label>Business Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/partner360Controller.cls
public with sharing class partner360Controller {
    
    Apexpages.StandardController p360Ctrl;
    public Account pAcc{get;set;}
    public PageReference pRef;
    public List<Business_Registration__c> brList {get;set;}
    
    public partner360Controller(ApexPages.StandardController controller) {
        this.p360Ctrl=controller;
        this.pAcc = (Account)controller.getRecord();
        pRef = new PageReference('/apex/partner360?Id='+pAcc.Id);
        brList = [select id,State__c,License_Number__c,Expires_On__c from Business_Registration__c where Account__c =:pAcc.Id];
    }
    
    public PageReference Save(){  
        p360Ctrl.save();
        return pRef;
    }
    
    public PageReference Cancel(){
        return pRef;
    }
    
    /*
    public PageReference toEditPage(){
         PageReference editPage = new PageReference('/apex/partner360Edit?Id='+pAcc.Id);
         return editPage;
    }*/
    
    public PageReference toShortDetailPage(){
         PageReference editPage = new PageReference('/'+pAcc.Id);
         return editPage;
    }
}