objects/Business_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Registrations</relationshipLabel>
        <relationshipName>Business_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expires_On__c</fullName>
        <description>this is used to capture the contractors license expiration date</description>
        <label>Contractors Lic Exp</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>Contractors License #</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Business Registration</label>
    <nameField>
        <label>Business Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CoverageArea__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Coverage Areas</relationshipLabel>
        <relationshipName>Coverage_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Radius__c</fullName>
        <label>Radius (Mile)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Coverage Area</label>
    <nameField>
        <label>Coverage Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DealerGeneral__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Default_Owner_of_Opportunities_Id__c</fullName>
        <description>This is the Salesforce Id of a User or Queue specific to the Org that will get the ownership of a converted Opportunity where the Dealer does not have a Res Opp Recipient Primary value.</description>
        <inlineHelpText>This is the Salesforce Id of a User or Queue specific to the Org that will get the ownership of a converted Opportunity where the Dealer does not have a Res Opp Recipient Primary value.</inlineHelpText>
        <label>Default Owner of Opportunities (Id)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address_For_ALR_Alerts__c</fullName>
        <description>This is the email address for communicating problems or information during the Automatic Lead Assignment process.</description>
        <inlineHelpText>This is the email address for communicating problems or information during the Automatic Lead Assignment process.</inlineHelpText>
        <label>Email Address For ALR Alerts</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enable_ALR_Dealer_Scoring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked then the ALR Dealer Scoring process is active.</description>
        <inlineHelpText>If checked then the ALR Dealer Scoring process is active.</inlineHelpText>
        <label>Enable ALR Dealer Scoring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_ALR_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked then the ALR process of Auto Conversion and Auto Dealer Assignment is active.</description>
        <inlineHelpText>If checked then the ALR process of Auto Conversion and Auto Dealer Assignment is active.</inlineHelpText>
        <label>Enable ALR Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enforce_Agreement_Check_Dealer_Search__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this is Checked then when searching for Dealers then the ECHO agreement check will be enforced. This means that the Dealer would have had to sign  a Partner Agreement with a name of something like &apos;Lead Handling Policy Agreement&apos;.</description>
        <inlineHelpText>If this is Checked then when searching for Dealers then the ECHO agreement check will be enforced. This means that the Dealer would have had to sign  a Partner Agreement with a name of something like &apos;Lead Handling Policy Agreement&apos;.</inlineHelpText>
        <label>Enforce Agreement Check (Dealer Search)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Google_Client_Id_Maps__c</fullName>
        <description>Assigned by Google for accessing their Google Maps API for Business</description>
        <inlineHelpText>Assigned by Google for accessing their Google Maps API for Business</inlineHelpText>
        <label>Google Client Id (Maps)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Google_Private_key_Maps__c</fullName>
        <description>Assigned by Google for accessing their Google Maps API for Business</description>
        <inlineHelpText>Assigned by Google for accessing their Google Maps API for Business</inlineHelpText>
        <label>Google Private key (Maps)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Test_First_Name__c</fullName>
        <description>If the Lead record was a test record then this is what would be its first name.</description>
        <inlineHelpText>If the Lead record was a test record then this is what would be its first name.</inlineHelpText>
        <label>Lead Test First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Dealer General</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account)</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsAutoConvert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAutoConvert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lat__c</fullName>
        <label>Lat</label>
        <precision>13</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Data_Quality__c</fullName>
        <label>Lead Data Quality</label>
        <picklist>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undetermined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Inferred_Quality__c</fullName>
        <label>Lead Inferred Quality</label>
        <picklist>
            <picklistValues>
                <fullName>Accept</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Eloqua</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>log__c</fullName>
        <label>log</label>
        <precision>13</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <businessProcess>SunPower Master Lead Process</businessProcess>
        <description>Partner Leads</description>
        <label>Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <businessProcess>SunPower Residential Leads Process</businessProcess>
        <description>Residential Leads</description>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestALRCommon.cls
@IsTest
public with sharing class TestALRCommon {

public static void CreateCustomSetting() {
      //Add the Custom Setting
      DealerGeneral__c dg = DealerGeneral__c.getInstance( UserInfo.getOrganizationId() );
      
      if (dg.id == null)
      {    
          dg = new DealerGeneral__c();
        dg.Email_Address_For_ALR_Alerts__c         = 'test@sunpowercorp.com';
      dg.Enable_ALR_Process__c                 = true;
      dg.Enforce_Agreement_Check_Dealer_Search__c   = false;
      dg.Google_Client_Id_Maps__c               = '';
      dg.Google_Private_key_Maps__c             = '';
      dg.Lead_Test_First_Name__c               = 'SPWR Test';
      dg.Default_Owner_of_Opportunities_Id__c      = UserInfo.getUserId();
      dg.Enable_ALR_Dealer_Scoring__c            = true;
          insert dg;
    }
    else
      {    
          dg = new DealerGeneral__c();
        dg.Email_Address_For_ALR_Alerts__c         = 'test@sunpowercorp.com';
      dg.Enable_ALR_Process__c                 = true;
      dg.Enforce_Agreement_Check_Dealer_Search__c   = false;
      dg.Google_Client_Id_Maps__c               = '';
      dg.Google_Private_key_Maps__c             = '';
      dg.Lead_Test_First_Name__c               = 'SPWR Test';
      dg.Default_Owner_of_Opportunities_Id__c      = UserInfo.getUserId();
      dg.Enable_ALR_Dealer_Scoring__c            = true;      
          update dg;
    }
    

}
public static Lead CreateRawLead(String CompanyName, String Source_System, String Lead_Inferred_Quality, String Lead_Data_Quality) {
    Lead l = new Lead();
    Id ResidentialRecordTypeId = DealerUtility.GetResidentialRecordType();
    l.RecordTypeId = ResidentialRecordTypeId;
    l.FirstName   = 'First';
    l.LastName   = 'Last'; 
    l.Company     = CompanyName;
    l.Email       = 'noreply@sunpowercorp.com';
    l.street      = '151 Corona St' ;
    l.city        = 'Denver';
    l.state      = 'CO';
    l.postalcode   = '80218';
    l.country      = 'USA';
    l.Lat__c       = 39.721956;
    l.Log__c     = -104.974382;
    l.LeadSource  = 'Web';
    l.Source_System__c        = Source_System;
    l.Lead_Inferred_Quality__c   = Lead_Inferred_Quality;
    l.Lead_Data_Quality__c     = Lead_Data_Quality;  
    l.Status = 'Open';  
    l.Theater__c = 'North America';
    l.IsAutoConvert__c = false;
    return l;
  }      

	public static Account CreateDealer(String DealerName) 
	{
        //RecordType PartnerRecordTypeAccount = [Select r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Account' and Name= 'Partner' LIMIT 1];

      //Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
       
        //User u = new User(LastName = DealerName ,FirstName = DealerName,Email='testAdmin2@testorg.com', ProfileId = p.Id);
        
        Account a = new Account();
        a.Name                     = DealerName; //'Really Bright Solar';
        a.Type                     = 'Premier-Partner-Residential'; //PartnerRecordTypeAccount .Id;
            
        a.Dealer_Score_Total__c         = 78;
        a.Dealer_Locator_Phone__c       = '888-888-8888';
        a.Phone                   = '888-888-8888';
        a.BillingStreet                  = '150 Corona St';
        a.BillingCity                    = 'Denver';
        a.BillingState                     = 'CO';
        a.BillingCountry                   = 'USA';
        a.BillingPostalCode               = '80218';
        a.website                         = 'www.sunpowercorp.com';
        a.Oracle_Account_Number__c     = '123';
        a.Description                 = 'None';
        a.Partner_Facts__c             = 'None';
        a.Status__c                 = 'Active';
        a.Dealer_Locator_Opt_Out__c     = false;
        a.Lead_Flow_Opt_Out__c        = false;
        a.Alliance_Program_Partner__c     = true;
        a.Geolocation__Latitude__s       = 39.718887;
        a.Geolocation__Longitude__s     = -104.974036;
    //a.Opportunity_Recipient__c      = u.id;
        insert a;
        
        Dealer_Assignment_Audit__c leadAssignment = DealerUtility.ConfigureDealerAssignmentAudit('Test2', a.Id, null, 'test', 'none');
        system.assert(leadAssignment != null);
        
        //2. Insert CoverageArea__c
        CoverageArea__c ca = new CoverageArea__c();
        ca.Account__c             = a.id;
        ca.Geolocation__Latitude__s   = 39.718887;
        ca.Geolocation__Longitude__s   = -104.974036;
        ca.Radius__c               = 1000;
        insert ca;
        
    Business_Registration__c br = new Business_Registration__c();
    br.Name         = a.billingstate;
    br.Account__c     = a.id;
    //br.Expires_On__c   = a.Contractors_Lic_Expiry__c;
    br.License_Number__c = '000000';
    br.Country__c       = a.billingCountry;
    br.State__c       = a.billingstate;
       insert br;        
        return a;
}

	public static Account Lead_CreateDealer(String DealerName) 
	{
        Account a = new Account();
        a.Name                     = DealerName; //'Really Bright Solar';
        a.Type                     = 'Premier-Partner-Residential'; //PartnerRecordTypeAccount .Id;
        a.Dealer_Score_Total__c         = 78;
        a.Dealer_Locator_Phone__c       = '888-888-8888';
        a.Phone                   = '888-888-8888';
        a.BillingStreet                  = '150 Corona St';
        a.BillingCity                    = 'Denver';
        a.BillingState                     = 'CO';
        a.BillingCountry                   = 'United States';
        a.BillingPostalCode               = '80218';
        a.website                         = 'www.sunpowercorp.com';
        a.Oracle_Account_Number__c     = '123';
        a.Description                 = 'None';
        a.Partner_Facts__c             = 'None';
        a.Status__c                 = 'Active';
        a.Dealer_Locator_Opt_Out__c     = false;
        a.Lead_Flow_Opt_Out__c        = false;
        a.Alliance_Program_Partner__c     = true;
        a.Geolocation__Latitude__s       = 39.718887;
        a.Geolocation__Longitude__s     = -104.974036;
        insert a;
        
        Dealer_Assignment_Audit__c leadAssignment = DealerUtility.ConfigureDealerAssignmentAudit('Test2', a.Id, null, 'test', 'none');
        system.assert(leadAssignment != null);
        
        //2. Insert CoverageArea__c
        CoverageArea__c ca = new CoverageArea__c();
        ca.Account__c             = a.id;
        ca.Geolocation__Latitude__s   = 39.718887;
        ca.Geolocation__Longitude__s   = -104.974036;
        ca.Radius__c               = 1000;
        insert ca;
        
	    Business_Registration__c br = new Business_Registration__c();
	    br.Name         = a.billingstate;
	    br.Account__c     = a.id;
	    br.License_Number__c = '000000';
	    br.Country__c       = a.billingCountry;
	    br.State__c       = a.billingstate;
	    insert br;        
	    
	    return a;
	}

public static Account CreateHomeOwnerAccount(String accountName) {
       RecordType PartnerRecordTypeAccount = [Select r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Account' and Name= 'Partner' LIMIT 1];
       
        Account a = new Account();
        a.Name                     = accountName; //'Really Bright Solar';
        a.Type                     = 'Home Owner';
            
        //a.Dealer_Score_Total__c         = 78;
        //a.Dealer_Locator_Phone__c       = '888-888-8888';
        a.Phone                   = '888-888-8888';
        a.BillingStreet                  = '150 Corona St';
        a.BillingCity                    = 'Denver';
        a.BillingState                     = 'CO';
        a.BillingCountry                   = 'USA';
        a.BillingPostalCode               = '80218';
        a.website                         = 'www.sunpowercorp.com';
        a.Oracle_Account_Number__c     = '123';
        a.Description                 = 'None';
        a.Partner_Facts__c             = 'None';
        a.Status__c                 = 'Active';
        a.Dealer_Locator_Opt_Out__c     = false;
        a.Lead_Flow_Opt_Out__c        = false;
        //a.Alliance_Program_Partner__c     = true;
        a.Geolocation__Latitude__s       = 39.718887;
        a.Geolocation__Longitude__s     = -104.974036;

        insert a;
                
        return a;
}
}