objects/Business_Unit__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Business Unit</label>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>GC1040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC1060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC1020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Estimate__c.object
<CustomObject>
    <description>Object used to capture the required services and high level cost of the project.</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity__r.Business_Unit__c)</formula>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Estimates</relationshipLabel>
        <relationshipName>Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <label>Price Book</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>C1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elevated Tracker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Tilt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GFT-0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GFT-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GFT-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GFT-25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GFT-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PowerGuard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T-0 V1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T-20 V2.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T-20 V2.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T-20 V2.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T-5</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Balance of System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Cell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Satcon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total Price</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity.Business_Unit__c)</formula>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estimate</label>
        <referenceTo>Estimate__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>CASE(  PricebookEntry.Product2.Product_Type__c,&quot;Mounting System&quot;,&quot;Mounting System&quot;,&quot;BOS&quot;,&quot;BOS&quot;,&quot;Development&quot;,&quot;Development&quot;,&quot;Balance of System&quot;,&quot;Balance of System&quot;,&quot;Total Price&quot;,&quot;Total Price&quot;,&quot;PV Module&quot;,&quot;PV Module&quot;,&quot;Services&quot;,&quot;Services&quot;,&quot;O&amp;M&quot;,&quot;O&amp;M&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestEstimateQuoteController.cls
public class TestEstimateQuoteController {
    static testMethod void EstimateQuoteController(){ 
        Date dt =Date.newinstance(2010,03,03);
        Account acc = new Account(Name = 'testaccc',CurrencyIsoCode = 'USD', Account_Status__c = 'Active',SPWR_Relationship_Type__c = 'Off-Taker',BillingStreet = 'West Mare',BillingCity = 'SanFrancisco',BillingPostalCode = '2345', BillingCountry = 'United States of America',Phone = '1234');
        insert acc;
        // Done for case # 00066557 Replacing business unit IBD with 'UPP Intl'.
        Opportunity o = new Opportunity(Name = 'Tesrt',StageName= 'Budgetary Pricing',Business_Unit__c='UPP Intl',CloseDate=dt,AccountId = acc.ID);
        Insert o;
        Pricebook2 pb = [select Id from Pricebook2 where IsStandard = true and Name='Standard Price Book'];
        Product2 prd  = new Product2(Name='testp',Product_Type__c='PV Module',Family='O&M',ProductCode='1111');
        insert prd;
        PricebookEntry pE = new PricebookEntry(UnitPrice=0,Product2Id=prd.Id,Pricebook2Id=pb.Id,UseStandardPrice=false,IsActive=true);
        insert pE;
        Estimate__c estimate = new Estimate__c(Opportunity__c=o.Id,Price_Book__c=pb.Id);
        insert estimate;
        Product2 p = [select Family from Product2 where Id=:prd.ID ];
        ApexPages.currentPage().getparameters().put('id',estimate.ID);
        ApexPages.currentPage().getparameters().put('selectedFamily',p.Family);
        EstimateQuoteController dqn = new EstimateQuoteController();
        QuoteLineItem qli = new QuoteLineItem();
        String family=dqn.getSelectedFamily();
        PricebookEntry pbe = new PricebookEntry();
        dqn.setSelectedFamily('fan'); 
        dqn.init();
        dqn.updateFamily();
        dqn.getSize1();
        dqn.getFamily();    
    }
    static testMethod void EstimateQuoteController1(){ 
        Date dt =Date.newinstance(2010,03,03);
        Account acc = new Account(Name = 'testaccc',CurrencyIsoCode = 'USD', Account_Status__c = 'Active',SPWR_Relationship_Type__c = 'Off-Taker',BillingStreet = 'West Mare',BillingCity = 'SanFrancisco',BillingPostalCode = '2345', BillingCountry = 'United States of America',Phone = '1234');
        insert acc;
        // Done for case # 00066557 Replacing business unit IBD with 'UPP Intl'.
        Opportunity o = new Opportunity(Name = 'Tesrt',StageName= 'Budgetary Pricing',Business_Unit__c='UPP Intl',CloseDate=dt,AccountId = acc.ID);
        Insert o;
        Pricebook2 pb = [select Id from Pricebook2 where IsStandard = true and Name='Standard Price Book'];
        Product2 prd  = new Product2(Name='testp',Product_Type__c='PV Module',Family='O&M',ProductCode='1111');
        insert prd;
        PricebookEntry pE = new PricebookEntry(UnitPrice=0,Product2Id=prd.Id,Pricebook2Id=pb.Id,UseStandardPrice=false,IsActive=true);
        insert pE;
        Product2 prd1 = [select Id,family from Product2 limit 1];
        Estimate__c estimate = new Estimate__c(Opportunity__c=o.Id);
        insert estimate;
        Product2 p = [select Family from Product2 where Id=:prd.ID ];
        ApexPages.currentPage().getparameters().put('id',estimate.ID);
        ApexPages.currentPage().getparameters().put('selectedFamily',p.Family);
        ApexPages.currentPage().getparameters().put('TestCall','abc');
        EstimateQuoteController dqn = new EstimateQuoteController();
        dqn.init();
        dqn.updateFamily();
        dqn.getSize1();
        dqn.getFamily();       
     }
     static testMethod void EstimateQuoteController2(){ 
        Date dt =Date.newinstance(2010,03,03);
        Account acc = new Account(Name = 'testaccc',CurrencyIsoCode = 'USD', Account_Status__c = 'Active',SPWR_Relationship_Type__c = 'Off-Taker',BillingStreet = 'West Mare',BillingCity = 'SanFrancisco',BillingPostalCode = '2345', BillingCountry = 'United States of America',Phone = '1234');
        insert acc;
        // Done for case # 00066557 Replacing business unit IBD with 'UPP Intl'.
        Opportunity o = new Opportunity(Name = 'Tesrt',StageName= 'Budgetary Pricing',Business_Unit__c='UPP Intl',CloseDate=dt,AccountId = acc.ID);
        Insert o;
        Pricebook2 pb = [select Id from Pricebook2 where IsStandard = true and Name='Standard Price Book'];
        Product2 prd  = new Product2(Name='testp',Product_Type__c='PV Module',Family='O&M',ProductCode='1111');
        insert prd;
        PricebookEntry pE = new PricebookEntry(UnitPrice=0,Product2Id=prd.Id,Pricebook2Id=pb.Id,UseStandardPrice=false,IsActive=true);
        insert pE;
        Estimate__c estimate = new Estimate__c(Opportunity__c=o.Id,Price_Book__c=pb.Id);
        insert estimate;
        Product2 p = [select Family from Product2 where Id=:prd.ID ];
        ApexPages.currentPage().getparameters().put('id',estimate.ID);
        ApexPages.currentPage().getparameters().put('selectedFamily',p.Family);
        ApexPages.currentPage().getparameters().put('TestCall','abc');
        EstimateQuoteController dqn = new EstimateQuoteController();
        dqn.init();
        dqn.cancel();
        Quote q = new Quote(Name='qtest',OpportunityId=o.Id,Pricebook2Id=pb.Id);
        insert q;
       // Quote q = [select Id from Quote where Name='DummyQuote'];//prd1.Id
        QuoteLineItem qli = new QuoteLineItem(Product__c=pE.Product2Id ,Quantity=1,UnitPrice=0,Estimate__c=estimate.Id,QuoteId=q.Id,PricebookEntryId=pE.Id,isActive__c=true);
        insert qli;
        list<QuoteLineItem > qlis = new list<QuoteLineItem >();
        qlis.add(qli);
        system.debug('padma'+qli);
        dqn.getProductLists();
        dqn.setProductLists(qlis);
        dqn.save1();
                    
       }
}