objects/Business_Unit__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Business Unit</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>RLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Intl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Intl</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Submission_Date__c</fullName>
        <label>Last Submission Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SPWR_Industry_Type__c</fullName>
        <label>SPWR Industry Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College/University</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community-Based Organization-NGO, NPOs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant/Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convention Center/Arena</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation - Offices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution/Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electric Utility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPC contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Government - Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Government - Non-Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotels &amp; Resorts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - Special District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics &amp; Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Facility</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UpdateLeadLastSubmissionDateTest.cls
/****************************************************************************************
AUTHOR: Bharti Mehta(Appirio)
DATE: 28-July-2011
DESCRIPTION: TEST THE LAST SUBMISSION DATE ASSIGNED BY TRIGGER
*****************************************************************************************/
@isTest
private class UpdateLeadLastSubmissionDateTest {
	
	 //variables
	 static List<Lead> leadList = new List<Lead>();
    
    //Test Trigger : Lead Last Submission Date would be set as Task CreatedDate
    static testMethod void checkLastSubmissionDateUpdate() {    	
    	initializeTest();
    	
        //Start Test
        test.startTest(); 
        
        insertTasks();
         
        //Stop Test
        test.stopTest();
                
        //Query Leads
        Map<Id,Lead> mapLeads = new Map<Id,Lead>([Select Last_Submission_Date__c From Lead where Id IN : leadList]);
                
        //Query Tasks
        List<Task> newTaskList = [Select WhoId, CreatedDate From Task where WhoId IN : leadList];
        
        //verify Last_Submission_Date__c value 
        for(Task task: newTaskList){	
        	System.assertEquals(mapLeads.get(task.WhoId).Last_Submission_Date__c , task.CreatedDate);
        }       
        
    }
    
    static void initializeTest()
    {    	
    	//Create Lead
        Lead lead1 = new Lead();
        lead1.Status = 'Open';
        lead1.CurrencyIsoCode='USD';
        lead1.LeadSource='Web';
        lead1.SPWR_Industry_Type__c='Energy Developer';
        lead1.Business_Unit__c='RLC';
        lead1.Theater__c='Europe';
        lead1.LastName='Soral';
        lead1.Email='newlead1@gmail.com';
        leadList.add(lead1);
        
        //Create Lead
        Lead lead2 = new Lead();
        lead2.Status = 'Open';
        lead2.CurrencyIsoCode='USD';
        lead2.LeadSource='Web';
        lead2.SPWR_Industry_Type__c='Energy Developer';
        lead2.Business_Unit__c='RLC';
        lead2.Theater__c='Europe';
        lead2.LastName='Gour';
        lead2.Email='newlead2@gmail.com';
        leadList.add(lead2);
        
        //Insert Lead List
		insert leadList;
    }
    
    static void insertTasks(){  
	 List<Task> taskList = new List<Task>();
	 for(Lead lead : leadList){
	 	Task tsk = new Task();
	    tsk.Subject='Form: IT B2C Website Lead Form';
	    tsk.Status='Completed';
	    tsk.Priority='Normal';
	    tsk.ReminderDateTime=datetime.parse('7/28/2011 08:00 AM');
	    tsk.WhoId = lead.Id;
	    taskList.add(tsk);
	 }
	 insert taskList;
    }
}