objects/Business_Unit__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Business Unit</label>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>ASP_Formula__c</fullName>
        <formula>IF( System_Size_PV_Formula__c  &gt; 0, (TotalPrice  /  (System_Size_PV_Formula__c * 1000)),
IF(System_Size_BOS_Formula__c &gt; 0,  (TotalPrice /  (System_Size_BOS_Formula__c * 1000 ))  , 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BOS_w_Formula__c</fullName>
        <formula>BOS_w__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BOS $/W</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity.Business_Unit__c)</formula>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <picklist>
            <picklistValues>
                <fullName>EPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOS Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV+BOS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DirectMargin_per__c</fullName>
        <formula>IF(TotalPrice !=0, (TotalPrice - Total_Cost__c) / TotalPrice , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Direct Project Margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Direct_Margin__c</fullName>
        <formula>TotalPrice  -  Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Direct Project Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NPV_W__c</fullName>
        <formula>Opportunity.NPV_W__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NPV $/W</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Present_Value__c</fullName>
        <formula>Opportunity.Net_Present_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Present Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PV_w_Formula__c</fullName>
        <formula>PV_w__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PV $/W</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>System_Size_PV_Formula__c</fullName>
        <formula>System_Size_PV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>System Size (PV)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>QuoteLineItem.Total_Cost_new__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>CASE(PricebookEntry.Product2.Family, &quot;Total Price&quot;,&quot;Total Price&quot;,
&quot;PV Module&quot;,&quot;PV Module&quot;,
&quot;PV Cell&quot;,&quot;PV Cell&quot;,
&quot;O&amp;M&quot;,&quot;O&amp;M&quot;,
&quot;Development&quot;,&quot;Development&quot;,
&quot;Services&quot;,&quot;Services&quot;,
&quot;Mounting Systems - Roof&quot;,&quot;Mounting Systems - Roof&quot;,
&quot;Mounting Systems - Ground&quot;,&quot;Mounting Systems - Ground&quot;,
&quot;Mounting Systems - Parking&quot;,&quot;Mounting Systems - Parking&quot;,
&quot;Balance of Plant&quot;,&quot;Balance of Plant&quot;,
&quot;Contingency&quot;,&quot;Contingency&quot;,
&quot;Sales Tax&quot;,&quot;Sales Tax&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>CASE(  PricebookEntry.Product2.Product_Type__c,&quot;Mounting System&quot;,&quot;Mounting System&quot;,&quot;BOS&quot;,&quot;BOS&quot;,&quot;Development&quot;,&quot;Development&quot;,&quot;Balance of System&quot;,&quot;Balance of System&quot;,&quot;Total Price&quot;,&quot;Total Price&quot;,&quot;PV Module&quot;,&quot;PV Module&quot;,&quot;Services&quot;,&quot;Services&quot;,&quot;O&amp;M&quot;,&quot;O&amp;M&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>IF( Contains( Quote.Opportunity.Pricebook2.Name , &quot;System&quot;), Cost__c * Quantity * Multiplier__c, Cost__c * PricebookEntry.Product2.Wattage_Out__c * Quantity )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Global Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Intl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Commercial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UandCDealSheet_CC.cls
public class UandCDealSheet_CC {
    
    public String quoteIdValue {get; set;}  //relatedToType (Quote) Id Value holder 
    public String opportunityIdValue {get; set;} //Opportunity Id Value holder
    
    public Quote quoteDetails { //Quote record details holder
        get { 
            List<Quote> lstQuote = [SELECT Id, Opportunity.Name, Business_Unit__c, Opportunity.Owner.Name, Opportunity.CloseDate, Opportunity.Expected_Commercial_Operation_Date__c,
                                        Opportunity.Probability, Opportunity.StageName, Opportunity.Customer_Funding_Type__c, Opportunity.Contract_Type__c, CurrencyISOCode,
                                        TotalPrice, Total_Cost__c, Opportunity.Net_Present_Value__c, Opportunity.NPV_W__c, ASP_Formula__c, BOS_w_Formula__c, 
                                        PV_w_Formula__c, System_Size_PV_Formula__c, Opportunity.Selling_Strategy__c, Opportunity.My_Position_vs_Competition__c, Opportunity.Project_Margin_Risks__c,
                                        Opportunity.Closure_Deal_Risks__c, Opportunity.Actions_Remaining_to_Close_Deal__c, DirectMargin_per__c, Direct_Margin__c
                                    FROM Quote 
                                    WHERE Id =: quoteIdValue];  
            
            if (!lstQuote.isempty() && quoteDetails == null) quoteDetails = lstQuote[0];
            
            else quoteDetails = new Quote();
            
            return quoteDetails;

        } 
        set;
    } 
    
    public List<QuoteLineItem> mountingSysQueryList{ //Query for Mounting System
    
        get{
            List<QuoteLineItem> mountingSysList = [SELECT Id, Product_Family__c, Product_Name__c, Product_Type__c, PriceBookEntry.Name
                                                   FROM QuoteLineItem
                                                   WHERE Quote.Id =: quoteIdValue
                                                   AND (Product_Family__c LIKE '%Mounting System%')];
                                                   
            mountingSysQueryList = mountingSysList;
            return mountingSysQueryList;
        }
        set;
    
    }
    
    public List<QuoteLineItem> pvModuleQueryList{ //Query for PV Module
    
        get{
            List<QuoteLineItem> pvModuleList = [SELECT Id, Product_Family__c, Product_Name__c, Product_Type__c, PriceBookEntry.Name
                                                   FROM QuoteLineItem
                                                   WHERE Quote.Id =: quoteIdValue
                                                   AND (Product_Type__c = 'PV Module')];
                                                   
            pvModuleQueryList = pvModuleList;
            return pvModuleQueryList;
        }
        set;
    
    }
    
    public List<OpportunityTeamMember> teamMemberQueryList{
        get{
            List<OpportunityTeamMember> lstOppTeamMember = [SELECT Id, User.Name, TeamMemberRole
                                                            FROM OpportunityTeamMember 
                                                            WHERE OpportunityId =: opportunityIdValue 
                                                            AND (TeamMemberRole = 'Sales Analyst' 
                                                            OR TeamMemberRole = 'Project Manager' 
                                                            OR TeamMemberRole = 'Structured Finance' 
                                                            OR TeamMemberRole = 'Designer')];
                                                                 
                                                                 
                                                                 
            teamMemberQueryList = lstOppTeamMember;
            
            return teamMemberQueryList;
        }
        set;
    }
    
    
    public String salesAnalystVals {    //Opportunity Team Members with "Sales Analyst" Role
        
        get{
            String querySalesAnalystRole = '';
        
            if(!teamMemberQueryList.isEmpty()){
                for(OpportunityTeamMember oppTeamSales: teamMemberQueryList){
                    if(oppTeamSales.TeamMemberRole == 'Sales Analyst'){
                    if(querySalesAnalystRole.length() > 0 ) {
                        querySalesAnalystRole += ', ';
                    }
                    
                        querySalesAnalystRole += oppTeamSales.User.Name;
                        // remove last additional comma from string
                        querySalesAnalystRole = querySalesAnalystRole.subString(0,querySalesAnalystRole.length()); 
                    }
                                       
                }
            }

            salesAnalystVals = querySalesAnalystRole;
            
            return salesAnalystVals;
        }
        set;
    }
    
    public String projectManagerVals {  //Opportunity Team Members with "Project Manager" Role
        
        get{
            String queryProjectManagerRole = '';

            if(!teamMemberQueryList.isEmpty()){
                for(OpportunityTeamMember oppTeamProjMan: teamMemberQueryList){
                    if(oppTeamProjMan.TeamMemberRole == 'Project Manager'){
                    if(queryProjectManagerRole.length() > 0) {
                        queryProjectManagerRole += ', ';
                        
                    }
                        queryProjectManagerRole += oppTeamProjMan.User.Name;
                        // remove last additional comma from string
                        queryProjectManagerRole = queryProjectManagerRole.subString(0,queryProjectManagerRole.length());
                    }
                }
            }
            
            projectManagerVals = queryProjectManagerRole;
            
            return projectManagerVals;
        }
        set;
    }
    
    public String structuredFinanceVals {   //Opportunity Team Members with "Structured Finance" Role
        
        get{
            String queryStructuredFinanceRole = '';

            if(!teamMemberQueryList.isEmpty()){
                for(OpportunityTeamMember oppStrucFin: teamMemberQueryList){
                    if(oppStrucFin.TeamMemberRole == 'Structured Finance'){
                        if(queryStructuredFinanceRole.length() > 0) {
                            queryStructuredFinanceRole += ', ';
                        }
                        queryStructuredFinanceRole += oppStrucFin.User.Name;
                        // remove last additional comma from string
                        queryStructuredFinanceRole = queryStructuredFinanceRole.subString(0,queryStructuredFinanceRole.length());
                    }
                }
            }
            
            structuredFinanceVals = queryStructuredFinanceRole;
            
            return structuredFinanceVals;
        }
        set;
    }
    
    public String designerVals {    //Opportunity Team Members with "Designer" Role
        
        get{
            String queryDesignerRole = '';
            
            if(!teamMemberQueryList.isEmpty()){
                for(OpportunityTeamMember oppdesigner: teamMemberQueryList){
                    if(oppdesigner.TeamMemberRole == 'Designer'){
                        if(queryDesignerRole.length() > 0) {
                            queryDesignerRole += ', ';
                        }
                        queryDesignerRole += oppdesigner.User.Name;
                        // remove last additional comma from string
                        queryDesignerRole = queryDesignerRole.subString(0,queryDesignerRole.length());
                    }
                }
            }
            designerVals = queryDesignerRole;
            
            return designerVals;
        }
        set;
    }
    
    public String mountingSystemVals {
    
         get{
            String queryMountingSys = '';
            
            if(!mountingSysQueryList.isEmpty()){
                for(QuoteLineItem mountStys: mountingSysQueryList){
                    if(queryMountingSys.length() > 0) {
                        queryMountingSys += ', ';
                    }
                        queryMountingSys += mountStys.PriceBookEntry.Name;
                        // remove last additional comma from string
                        queryMountingSys = queryMountingSys.subString(0,queryMountingSys.length());
                }
            }
            mountingSystemVals = queryMountingSys;
            
            return mountingSystemVals;
        }
        set;
    
    }
    
    public String pvModuleVals {
    
         get{
            String queryPVModule = '';
            
            if(!pvModuleQueryList.isEmpty()){
                for(QuoteLineItem pvModule: pvModuleQueryList){
                    if(queryPVModule.length() > 0) {
                        queryPVModule += ', ';
                    }
                       queryPVModule += pvModule.PriceBookEntry.Name;
                        // remove last additional comma from string
                        queryPVModule = queryPVModule.subString(0,queryPVModule.length());
                }
            }
            pvModuleVals = queryPVModule;
            
            return pvModuleVals;
        }
        set;
    
    }
}