objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>AssignRandomPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if select Partner Randomly</inlineHelpText>
        <label>Paid Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RLC_Type__c</fullName>
        <description>This is dependent pick list when &quot;RLC&quot; is selected in Business Unit field.</description>
        <inlineHelpText>This is dependent pick list when &quot;RLC&quot; is selected in Business Unit field.</inlineHelpText>
        <label>RLC Type</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Light Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>Case
00150174
Per Stelli Munnis request, this field should be added to Campaign</description>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Alliance</fullName>
        <active>true</active>
        <description>Alliance Campaigns</description>
        <label>Alliance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Campaign</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Partners</relationshipLabel>
        <relationshipName>Campaign_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if Partner is available for Opportunity Routing</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to partner account</description>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Partners</relationshipLabel>
        <relationshipName>Campaign_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Partner</label>
    <nameField>
        <label>Campaign Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dealer_Assignment_Audit__c.object
<CustomObject>
    <description>Holds Dealer assignment information and other metrics around that decision.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Dealer Assignment Audit</relationshipLabel>
        <relationshipName>Dealer_Assignment_Audit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Assigned</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Assignment Audit</relationshipLabel>
        <relationshipName>Dealer_Assignment_Audit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Dealer Assignment Audit</relationshipLabel>
        <relationshipName>Dealer_Assignment_Audit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dealer Assignment Audit</label>
    <nameField>
        <label>Audit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Assignment Audit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Dealer_Locator_Selection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Selection</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Dealer Locator Selection)</relationshipLabel>
        <relationshipName>Leads3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsAutoConvert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAutoConvert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Data_Quality__c</fullName>
        <label>Lead Data Quality</label>
        <picklist>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undetermined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Inferred_Quality__c</fullName>
        <label>Lead Inferred Quality</label>
        <picklist>
            <picklistValues>
                <fullName>Accept</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Manufacturer__c</fullName>
        <label>Lead Manufacturer</label>
        <picklist>
            <picklistValues>
                <fullName>SunPower</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RLC_Type__c</fullName>
        <description>This is dependent pick list when &quot;RLC&quot; is selected in Business Unit field.</description>
        <inlineHelpText>This is dependent pick list when &quot;RLC&quot; is selected in Business Unit field.</inlineHelpText>
        <label>RLC Type</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Light Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EU Commercial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Eloqua</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>false</active>
        <businessProcess>SunPower Master Lead Process</businessProcess>
        <description>Light Commercial Leads</description>
        <label>Commercial</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <businessProcess>SunPower Master Lead Process</businessProcess>
        <description>Partner Leads</description>
        <label>Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <businessProcess>SunPower Residential Leads Process</businessProcess>
        <description>Residential Leads</description>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestDealerUtilityII.cls
@IsTest (SeeAllData=true)
public with sharing class TestDealerUtilityII {


	public TestDealerUtilityII() {
		TestALRCommon.CreateCustomSetting();
	}

	static Lead CreateLeadPlain(String CompanyName, String Source_System, String Lead_Inferred_Quality, String Lead_Data_Quality) {
			Lead l = TestALRCommon.CreateRawLead(CompanyName, Source_System, Lead_Inferred_Quality, Lead_Data_Quality);
			insert l;
			return l;
		}    	

		
	static Lead CreateLeadDealerAssigned(String CompanyName, String Source_System, String Lead_Inferred_Quality, String Lead_Data_Quality, Id DealerId) {
			Lead l = TestALRCommon.CreateRawLead(CompanyName, Source_System, Lead_Inferred_Quality, Lead_Data_Quality);
			l.Dealer_Locator_Selection__c = DealerId;
			insert l;
			return l;
		}    	

	static Opportunity CreateOpportunityWithGenericCampaign(String OppName) {

			Campaign c = new Campaign(Name ='Test', Type = 'Other');
	        insert c;

			Account partner1 = TestALRCommon.CreateDealer('Partner1');
			
	        Campaign_Partner__c cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	        cp.enabled__c = true;
	        cp.Name = 'A';
	        cp.Partner__c = partner1.Id;
	        insert cp;

			Account partner2 = TestALRCommon.CreateDealer('Partner2');
			
	        cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	        cp.enabled__c = true;
	        cp.Name = 'B';
	        cp.Partner__c = partner2.Id;
	        insert cp;

	                                                                              		
			RecordType RecordTypeOpportunity = [Select  r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Opportunity' and Name = 'Home Owner' LIMIT 1];
		    Account a = TestALRCommon.CreateHomeOwnerAccount('Test100');
			Opportunity o = new Opportunity();
			o.RecordTypeId = RecordTypeOpportunity.Id;
			o.CampaignId = c.Id;
			o.AccountId = a.Id;
			o.Name = OppName;
			o.StageName = 'New Opportunity';
			o.Lead_Manufacturer__c = 'SunPower';
			o.CloseDate = System.Today();
			Test.startTest();
	        insert o;
	        Test.stopTest();
	        return o;                        
	                                
		}    

	static Opportunity CreateOpportunityWithPaidCampaign(String OppName, Boolean IncludeAlreadyAssigned) {

			Campaign c = new Campaign(Name ='Test', Type = 'Other', AssignRandomPartner__c = true);
	        insert c;

			Account partner1 = TestALRCommon.CreateDealer('Partner1');
			
	        Campaign_Partner__c cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	        cp.enabled__c = true;
	        cp.Name = 'A';
	        cp.Partner__c = partner1.Id;
	        insert cp;

			Account partner2 = TestALRCommon.CreateDealer('Partner2');
			
	        cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	        cp.enabled__c = true;
	        cp.Name = 'B';
	        cp.Partner__c = partner2.Id;
	        insert cp;

	 		RecordType RecordTypeOpportunity = [Select  r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Opportunity' and Name = 'Home Owner' LIMIT 1];

	 
	 		if (IncludeAlreadyAssigned == true) {
			    RecordType RecordTypeOpportunityCommercial = [Select  r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Opportunity' and Name = 'Commercial' LIMIT 1];
			   
			    Account a2 = TestALRCommon.CreateHomeOwnerAccount('Test300');
				Opportunity o2 = new Opportunity();
				o2.RecordTypeId = RecordTypeOpportunityCommercial.Id;
				o2.CampaignId = c.Id;
				o2.AccountId = a2.Id;
				o2.Name = OppName;
				o2.StageName = 'Contacted';
				o2.Lead_Manufacturer__c = 'Partner';
				o2.CloseDate = System.Today();
		        insert o2;
	 			
	 			
	 			Dealer_Assignment_Audit__c daa = new Dealer_Assignment_Audit__c();
	 			daa.Campaign__c = c.id;
	 			daa.Dealer_Assigned__c = partner1.id;
	 			daa.Opportunity__c = o2.id;
	 			insert daa;
	 		}
	                                                                              		
		    Account a = TestALRCommon.CreateHomeOwnerAccount('Test100');
			Opportunity o = new Opportunity();
			o.RecordTypeId = RecordTypeOpportunity.Id;
			o.CampaignId = c.Id;
			o.AccountId = a.Id;
			o.Name = OppName;
			o.StageName = 'New Opportunity';
			o.Lead_Manufacturer__c = 'SunPower';
			o.CloseDate = System.Today();
			Test.startTest();
	        insert o;
	        Test.stopTest();
	        return o;                        
	                                
		}    
		
	static Opportunity CreateOpportunityWithAllianceCampaign(String OppName) {

			Campaign c = new Campaign(Name ='Test', Type = 'Alliance');
	        insert c;

			Account partner1 = TestALRCommon.CreateDealer('Partner1');
			
	        Campaign_Partner__c cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	        cp.enabled__c = true;
	        cp.Name = 'A';
	        cp.Partner__c = partner1.Id;
	        insert cp;

			Account partner2 = TestALRCommon.CreateDealer('Partner2');
			
	        cp  = new Campaign_Partner__c(Campaign__c = c.Id);
	        cp.enabled__c = true;
	        cp.Name = 'B';
	        cp.Partner__c = partner2.Id;
	        insert cp;
	                                                                                      		
			RecordType RecordTypeOpportunity = [Select  r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Opportunity' and Name = 'Home Owner' LIMIT 1];
		    Account a = TestALRCommon.CreateHomeOwnerAccount('Test100');
			Opportunity o = new Opportunity();
			o.RecordTypeId = RecordTypeOpportunity.Id;
			o.CampaignId = c.Id;
			o.AccountId = a.Id;
			o.Name = OppName;
			o.StageName = 'New Opportunity';
			o.Lead_Manufacturer__c = 'SunPower';
			o.CloseDate = System.Today();
			Test.startTest();
	        insert o;
	        Test.stopTest();
	        return o;                        
	                                
	}     


    static testMethod void testOpportunityWithGenericCampaignAssigned() {
		CreateOpportunityWithGenericCampaign('TestCampaign1');
    }
    
    static TestMethod void testDealerUtilSetLeadAutoConvert() {
    	List<Lead> leadList = new List<Lead>();
    	Lead testLead = new Lead();
    	testLead.lastName = 'testcoLeads';
    	testLead.company = 'testcoLeads';
    	testLead.email = 'testcoleads@noemail.com';
    	testLead.Country = 'USA';
    	testLead.Theater__c = 'North America';
    	testLead.Source_System__c =  'Eloqua';
    	testLead.Lead_Inferred_Quality__c = 'Review';
    	testLead.Lead_Data_Quality__c = 'Qualified';
    	testLead.RecordTypeId = TestClassFactory.retrieveRecordTypeId('Lead', 'Residential');
    	testLead.Lead_Manufacturer__c = 'SunPower';
    	testLead.RLC_Type__c = 'Residential';
    	testLead.Status = 'Open';
    	leadList.add(testLead);

    	Lead testLead2 = new Lead();
    	testLead2.lastName = 'testcoLeads';
    	testLead2.company = 'testcoLeads';
    	testLead2.email = 'testcoleads@noemail.com';
    	testLead2.Country = 'USA';
    	testLead2.Theater__c = 'North America';
    	testLead2.RecordTypeId = TestClassFactory.retrieveRecordTypeId('Lead', 'Residential');
    	testLead2.Lead_Manufacturer__c = 'SunPower';
    	testLead2.RLC_Type__c = 'Residential';
    	testLead2.Status = 'Open';
    	leadList.add(testLead2);

    	Lead testLead3 = new Lead();
    	testLead3.lastName = 'testcoLeads';
    	testLead3.company = 'testcoLeads';
    	testLead3.email = 'testcoleads@noemail.com';
    	testLead3.Country = 'USA';
    	testLead3.Theater__c = 'North America';
    	testLead3.Source_System__c =  'Eloqua';
    	testLead3.Lead_Inferred_Quality__c = 'Reject';
    	testLead3.Lead_Data_Quality__c = 'Qualified';
    	testLead3.RecordTypeId = TestClassFactory.retrieveRecordTypeId('Lead', 'Residential');
    	testLead3.Lead_Manufacturer__c = 'SunPower';
    	testLead3.RLC_Type__c = 'Residential';
    	testLead3.Status = 'Open';
    	leadList.add(testLead3);

    	Lead testLead4 = new Lead();
    	testLead4.lastName = 'testcoLeads';
    	testLead4.company = 'testcoLeads';
    	testLead4.email = 'testcoleads@noemail.com';
    	testLead4.Country = 'USA';
    	testLead4.Theater__c = 'North America';
    	testLead4.Source_System__c =  'Eloqua';
    	testLead4.Lead_Inferred_Quality__c = 'Accept';
    	testLead4.Lead_Data_Quality__c = 'Qualified';
    	testLead4.RecordTypeId = TestClassFactory.retrieveRecordTypeId('Lead', 'Residential');
    	testLead4.Lead_Manufacturer__c = 'SunPower';
    	testLead4.RLC_Type__c = 'Residential';
    	testLead4.Status = 'Open';
    	leadList.add(testLead4);

    	Lead testLead5 = new Lead();
    	testLead5.lastName = 'testcoLeads';
    	testLead5.company = 'testcoLeads';
    	testLead5.email = 'testcoleads@noemail.com';
    	testLead5.Country = 'USA';
    	testLead5.Theater__c = 'North America';
    	testLead5.Source_System__c =  'Eloqua';
    	testLead5.Lead_Inferred_Quality__c = 'Review';
    	testLead5.Lead_Data_Quality__c = 'Disqualified';
    	testLead5.RecordTypeId = TestClassFactory.retrieveRecordTypeId('Lead', 'Residential');
    	testLead5.Lead_Manufacturer__c = 'SunPower';
    	testLead5.RLC_Type__c = 'Residential';
    	testLead5.Status = 'Open';
    	leadList.add(testLead5);

    	Lead testLead6 = new Lead();
    	testLead6.lastName = 'testcoLeads';
    	testLead.company = 'testcoLeads';
    	testLead6.email = 'testcoleads@noemail.com';
    	testLead6.Country = 'USA';
    	testLead6.Theater__c = 'North America';
    	testLead6.Source_System__c =  'Eloqua';
    	testLead6.Lead_Inferred_Quality__c = 'Review';
    	testLead6.Lead_Data_Quality__c = 'Undetermined';
    	testLead6.RecordTypeId = TestClassFactory.retrieveRecordTypeId('Lead', 'Residential');
    	testLead6.Lead_Manufacturer__c = 'SunPower';
    	testLead6.RLC_Type__c = 'Residential';
    	testLead6.Status = 'Open';
    	leadList.add(testLead6);

    	Test.startTest();
    	DealerUtility.SetLeadAutoConvert(leadList);
    	Test.stopTest();
    }  

    static TestMethod void dealerUtilUpdateContactRole() {

    	Set<Id> oppIDs = new Set<Id>();
    	try {
    		OpportunityContactRole o = [SELECT Id, OpportunityID FROM OpportunityContactRole  WHERE Opportunity.CreatedDate = LAST_N_DAYS: 10 
    						AND Opportunity.StageName = 'New Opportunity' AND Opportunity.RecordType.Name = 'Home Owner' 
    						AND Opportunity.Primary_Contact__c != null AND Opportunity.PartnerAccountID != null LIMIT 1];
    		if(o.OpportunityID != null)
    			oppIds.add(o.OpportunityID);
		} catch (exception e) {
    			system.debug('query exception');
		}


    	Test.startTest();
    	if(!oppIds.isEmpty())
    		DealerUtility.updateContactRole(oppIds);
    	Test.stopTest();
	}

	static TestMethod void dealerUtilConvertLead() {
		Lead testLead = new Lead();
    	testLead.lastName = 'testcoLeads';
    	testLead.company = 'testcoLeads';
    	testLead.email = 'testcoleads@noemail.com';
    	testLead.Country = 'USA';
    	testLead.Theater__c = 'North America';
    	testLead.Source_System__c =  'Eloqua';
    	testLead.Lead_Inferred_Quality__c = 'Review';
    	testLead.Lead_Data_Quality__c = 'Qualified';
    	testLead.RecordTypeId = TestClassFactory.retrieveRecordTypeId('Lead', 'Residential');
    	testLead.Lead_Manufacturer__c = 'SunPower';
    	testLead.RLC_Type__c = 'Residential';
    	testLead.Status = 'Contacted';
    	testLead.LeadSource = 'Web';
    	insert testLead;

    	testLead.isAutoConvert__c = true;

    	Test.startTest();
    	DealerUtility.ConvertLead(testLead, new GeocodeAsyncHandler.GeoInfo());
    	Test.stopTest();
	}

	static TestMethod void dealerUtilFixOppName() {
		List<Opportunity> opps = new List<Opportunity>();
		Opportunity o = TestClassFactory.testOpportunity('tstOpp' + System.today(), 'New Opportunity', Date.today(), TestClassFactory.retrieveRecordTypeId('Opportunity', 'Home Owner'));
		opps.add(o);

		Test.startTest();
		DealerUtility.FixOpportunityName(opps);
		Test.stopTest();

	}    


}