objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>AssignRandomPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if select Partner Randomly</inlineHelpText>
        <label>Paid Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>Case
00150174
Per Stelli Munnis request, this field should be added to Campaign</description>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Campaign</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Partners</relationshipLabel>
        <relationshipName>Campaign_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disable_Date__c</fullName>
        <label>Disable Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enable_Date__c</fullName>
        <label>Enable Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if Partner is available for Opportunity Routing</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to partner account</description>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Partners</relationshipLabel>
        <relationshipName>Campaign_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Partner</label>
    <nameField>
        <label>Campaign Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCampPartnerClone.cls
@isTest
public class TestCampPartnerClone  
{
 static testMethod void Test_CampPartnerClone (){
   String recType1 = [SELECT id FROM recordtype WHERE name='Partner' and Sobjecttype = 'Account' limit 1].id;
   Campaign  objalliance =  new Campaign(Name='TestAllianceCampNA' ,IsActive=true,AssignRandomPartner__c=false);
   insert objalliance;
 
     Campaign CloneCamp = objalliance.clone(false,true);
     insert CloneCamp ;
    
     Account objP = new Account(Name = 'test1111',Opportunity_Close_Rate__c=6, recordtypeId=recType1,BillingStreet='Adriatic Way', BillingCity='Santa Clara', BillingState='CA', BillingPostalCode='95051', BillingCountry='United States',Theater__c ='North America',Phone='1234567895',Type='Elite-Partner-Combo');
     Insert objP;
     Campaign_Partner__c objAllianePartner = new Campaign_Partner__c(Name='test1',Disable_Date__c=date.today(),Enable_Date__c=date.today(),Campaign__c=objalliance.Id, Partner__c=objP.Id, Enabled__c=true);
     insert objAllianePartner;
     List<Campaign_Partner__c> CampPartnersNew = new List<Campaign_Partner__c>();
     Campaign_Partner__c newCP = objAllianePartner.clone(false,true);
     newCP.Campaign__c = CloneCamp.id;
     CampPartnersNew.add(newCP);
     insert CampPartnersNew;
     
     PageReference p = new PageReference('/apex/CloneCamapignWPartner');
     Test.setCurrentPage(p);
     
     ApexPages.currentPage().getParameters().put('Id', objalliance.Id);
     
     ApexPages.StandardController sc = new ApexPages.StandardController(objalliance);

     CampPartnerClone campCon = new CampPartnerClone(sc);
     campCon.CloneCamp();
     
  }
}