objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Authorized_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field allows access for a specific dealer user to place orders via the online-order process in Salesforce. The dealer account also needs to be enabled for online ordering.</description>
        <label>Authorized to Order</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Line_Type__c</fullName>
        <description>Used for updating the Oracle Line Type value of Purchase Order Line</description>
        <inlineHelpText>Used for updating the Oracle Line Type value of Purchase Order Line</inlineHelpText>
        <label>Line Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard Line</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Discount__c.object
<CustomObject>
    <description>Used for calculating ordering discount matrix based on dealer tiers and bulk orders

Created for EU Pricing matrix enhancement Dec 2014</description>
    <fields>
        <fullName>Bundle_Quantity__c</fullName>
        <label>Bundle Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country to which the discount record applies</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Netherlands</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Discontinue_Date__c</fullName>
        <description>Date on which the discount discontinues</description>
        <label>Discontinue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Discount Effective Date</description>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maximum_Quantity__c</fullName>
        <defaultValue>99999</defaultValue>
        <description>Maximum Quantity for the order to get discount</description>
        <label>Maximum Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Quantity__c</fullName>
        <description>Minimum Quantity for the order to get discount</description>
        <label>Minimum Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oracle_Item_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Oracle item id</description>
        <label>Oracle Item ID</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Order Discounts</relationshipLabel>
        <relationshipName>Order_Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Region/Market to which the discount applies
Eg.
North America
Australia
Asia Pacific</description>
        <label>Theatre</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>OD-{000000}</displayFormat>
        <label>Order Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Price_List__c.object
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Price_List_Item__c.object
<CustomObject>
    <description>To associate Price List with the Items and keep the item pricing info as well*.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BoS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inverter Accesories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mounting Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Oracle Item ID</description>
        <label>Oracle Item ID</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>Price_List_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>There will be one price list per Operating Unit</description>
        <label>Price List</label>
        <referenceTo>Price_List__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>Price_List_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type_1__c</fullName>
        <description>SmartPack or Ala Carte</description>
        <label>Type 1 Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>Smart Pack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ala Carte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV + Inverter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <label>Price List Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AlaCarteController_Test.cls
@isTest
public class AlaCarteController_Test {
    
    
	public static TestMethod void testAlaCarteController() {
        
        Account testPartner = TestClassFactory.CreateDealer('dealerName', 'North America');

        Contact partnerContact = TestClassFactory.testContact('lastName', 'testcontactpartner@noemail.com', TestClassFactory.retrieveRecordTypeID('Contact', 'Partner'));
        partnerContact.AccountId = testPartner.Id;
        partnerContact.Authorized_To_Order__c = TRUE;
        insert partnerContact;

        UserRole role = [SELECT Id FROM UserRole WHERE Name LIKE '%Partner Executive' LIMIT 1];

        Id execProfileId = SFDCSpecialUtilities.getProfileIdByName('Partner Executive');

        User currentUser = new User(alias = 'cashman1', email = partnerContact.Email, 
                          emailencodingkey='UTF-8', lastname='Testing', 
                          languagelocalekey='en_US', localesidkey='en_US', 
                          profileid = execProfileId,  country='United States', 
                          communityNickName = 'cashman1', timezonesidkey='America/Los_Angeles', 
                          username=string.valueOf(math.random())+'u1@testorg.com',
                          contactId=partnerContact.Id, UserRole = role);
        Price_List__c priceList = TestClassFactory.createPriceList();
        
        Price_List_Item__c pli = new Price_List_Item__c();
        pli.Type_1__c = 'Ala Carte';
        pli.Category__c = 'Monitoring';
        pli.Item_ID__c = [SELECT Id FROM Item__c WHERE Line_Type__c = 'Ala Carte' LIMIT 1].Id;
        pli.Price_List__c = priceList.Id;
        pli.Effective_Start_Date__c = Date.today() - 1;
        pli.Effective_End_Date__c = Date.today().addDays(30);
        insert pli; 
        
        Order_Discount__c o = new Order_Discount__c();
        o.Minimum_Quantity__c = 4;
        o.Maximum_Quantity__c = 100;
        o.Oracle_Item_ID__c = [SELECT Item_ID__c FROM Price_List_Item__c LIMIT 1].Item_ID__c;
        o.Effective_Date__c = Date.today() - 1;
        o.Discontinue_Date__c = Date.today().addDays(30);
        o.Bundle_Quantity__c = 4;
        o.Theatre__c = 'North America';
        o.Country__c = 'United States';
        insert o;
        
        System.runAs(currentUser)  {

            Test.startTest();
            PageReference pageRef = Page.OrderAlaCarteConfiguration;
            Test.setCurrentPage(pageRef);
            
            AlaCarteController controller = new AlaCarteController();

			controller.updateProductLineItemList();            
            
            controller.hdnDelProdLineId = pli.id;
            controller.singleAddedprodId = pli.id;
            controller.addItemToList();
            controller.addItemToList();
            
            controller.changedQty = '4';
            controller.updateQuantity();
            
            controller.changedQty = '8';
            controller.updateQuantity();
            
            controller.setJSON();
            
            controller.delItemFromList();
            
            controller.getQunatityMessage();
            
            string testString = controller.selProductItemsJSON;
            
            Boolean b = controller.hasNext;
            b = controller.hasPrevious;
            integer i = controller.pageNumber;
            controller.first();
            controller.last();
            controller.previous();
            controller.next();
            controller.cancel();
            controller.selectedCategoryKey = null;
            controller.moveAccordingToFilter();
            controller.selectedCategoryKey = 'Module';
            controller.moveAccordingToFilter();
            controller.prodDescFilter = 'RESI';
            controller.moveAccordingToFilter();
            
            //checkChangedQuantity(AlaCarteController.PriceItemWrapper wrapper, String newVal)
            AlaCarteController.PriceItemWrapper w = new AlaCarteController.PriceItemWrapper();
            w.Id = pli.Id;
            w.oracleItemIDRef = pli.Item_ID__c;
            w.Qty = '1';
            Boolean try1 = controller.checkChangedQuantity(w,'2');
            Boolean try2 = controller.checkChangedQuantity(w,'4');
            controller.showQuantityMessage = true;
            controller.getQunatityMessage();
            controller.getCategoryKeys();
            //controller.initilizeSetCon();
            controller.addItemToList();
            
            controller.first();
            controller.next();
            controller.last();
            controller.previous();
            controller.cancel();
            
            Test.stopTest();
        }
    }
}