objects/Community_EndPoint__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Community EndPoint</label>
</CustomObject>

classes/PartnerPortalSiteLoginController.cls
global class PartnerPortalSiteLoginController {

    public PartnerPortalSiteLoginController(){}
    
    public PageReference authCurrentUser() {

            String startURL = ApexPages.currentPage().getParameters().get('startURL'); //Removing reliance on Community Endpoint
            String communityURL = [select ID, Name, URL__c from Community_EndPoint__c where Name = 'SPWRCommunity' limit 1].URL__c;

            PageReference pr = new PageReference(communityURL);
            
            if(startURL!=null){
                pr.getParameters().put('startURL',startURL);
            }  
            return pr;
            
    }
}