objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Issues__c.object
<CustomObject>
    <description>Object created to manage SMS2 Issues related to Case.</description>
    <fields>
        <fullName>Case_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Issues2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>ACPV - Microinverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACPV - Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cells</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G&amp;A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>monitoring</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Product_Sub_Category__c</fullName>
        <label>if other:</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <picklist>
            <picklistValues>
                <fullName>BOS electrical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cells</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module - SPWR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module - Tenesol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>monitoring system</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>mounting system</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site-wide</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Serial__c</fullName>
        <label>Serial#</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>b_Product_Sub_Category__c</fullName>
        <label>Product Sub-Category</label>
        <picklist>
            <controllingField>Product_Category__c</controllingField>
            <picklistValues>
                <fullName>A300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC Disconnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACPV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>alzone RM2C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>alzone RM2T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>alzone RM5C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>alzone RM5T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B65</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C65</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Combiner Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC Disconnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>elettronica santerno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fronius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeruns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KACO-EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NB-245AB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>powerguard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>satcon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER-220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER-228</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER-235</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER-280</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF mounting system</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Inverter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <label>Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>Hold information about location coordinates.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Case_Owner__c</fullName>
        <label>Case Owner</label>
        <relationshipName>Users</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestIssueManagement.cls
/********************************************************************************************
Name   : IssueManagement
Author : Jitendra Kothari
Date   : Sep 26, 2011
Usage  : Test Class for triggers on Issue Object and IssueManagement Class.
Case   : 00079081
********************************************************************************************/
@IsTest
public class TestIssueManagement {
    static testMethod void Test_IssueManagement(){
        String  CSCaseRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Service Case').getRecordTypeId();
        User testUser = [Select Id From User where isActive = true and Profile.Name = 'System Administrator' and Id != :Userinfo.getUserId() limit 1];
        Account acc = new Account();
        acc.Name = 'Test Account-'+ String.valueOf(DateTime.Now());
        acc.Type ='Commercial';
        acc.BillingCity = 'san mateo';
        acc.BillingStreet = 'Concar drive';
        acc.BillingPostalCode ='94402';
        acc.BillingCountry = 'USA'; 
        insert acc;
        
        Contact con = new Contact();
        con.LastName = 'Test Contact-'+ String.valueOf(DateTime.Now());
        con.AccountId = acc.Id;
        con.Email = 'testpqr@gmail.com';
        insert con;
        
        Case newCase = new Case();       
        newCase.Status = 'New';
        newCase.RecordTypeId = CSCaseRecTypeId;        
        newcase.AccountId = acc.Id;
        insert newCase;
        
        Test.startTest();
        Issues__c issue = new Issues__c(Case__c = newCase.Id, Name = 'Test Issue Jitendra', Location__c = 'Inverter', Serial__c ='6566555');
        issue.Product_Category__c ='Inverter';
        issue.b_Product_Sub_Category__c ='Other Inverter';
        issue.Other_Product_Sub_Category__c = 'Other valiue';
        insert issue;
        Issues__c newIssue = [Select Id, Case_Owner__c from Issues__c where Id = :issue.Id];
        System.assertEquals(Userinfo.getUserId(), newIssue.Case_Owner__c);
        
        newCase.OwnerId = testUser.Id;
        update newCase;        
        newIssue = [Select Id, Case_Owner__c from Issues__c where Id = :issue.Id];
        System.assertEquals(testUser.Id, newIssue.Case_Owner__c);
        
        newIssue.Case__c = null;
        update newIssue;        
        newIssue = [Select Id, Case_Owner__c from Issues__c where Id = :issue.Id];
        System.assertEquals(null, newIssue.Case_Owner__c);
        Test.stopTest();
    }
}