objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Authorized_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field allows access for a specific dealer user to place orders via the online-order process in Salesforce. The dealer account also needs to be enabled for online ordering.</description>
        <label>Authorized to Order</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Design__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Status__c</fullName>
        <label>Dealer Status</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Request in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Exported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record Drawings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Exported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Design</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Commercial:
Field created to link document (attachments) to the design object record</description>
        <label>Design</label>
        <referenceTo>Design__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>Field for TPS - this field will be used to identify the documents uploaded by TPS or any other partner</description>
        <label>Document Type</label>
        <picklist>
            <picklistValues>
                <fullName>12 Month Utility Bills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACP5 - Asbestos Inspection Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance Rebate Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANSI C12 Certified Meter Worksheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appendix A - NY State Interconnection Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appendix B and C - NY State Interconnection Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aurora Deliverables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Acceptance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Design Deliverables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete Design Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed ICF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Incentive Claim Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed SRP Final As-Built Worksheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Final LW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Lien Waiver - DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Lien Waiver - DRIP (Interconnect)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Lien Waiver - IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Lien Waiver - IP (Interconnect)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Progress LW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed ICF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Rebate Reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Rebate Resv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Copy of Property Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countersigned Attachment Rebate Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countersigned Rebate Reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countersigned Schedule A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countersigned SREC Reservation Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Acceptance Form</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HelixDesignRequestUtilities_Test.cls
@isTest
private class HelixDesignRequestUtilities_Test {
	
	@isTest 
	private static void testHeadlines() {
		
		List<APPR_PUB__Headline__c> headlines = new List<APPR_PUB__Headline__c>();
		for(Integer i = 0; i < 5; i++) {
			APPR_PUB__Headline__c headline = new APPR_PUB__Headline__c();
			headline.Name = 'Test'+i;
			headline.Display_Name__c = 'Test'+i;
	        headline.APPR_PUB__Long_Description__c = 'Test'+i;
	        headline.APPR_PUB__Tab__c = 'DesignRequestForm'; 
	        headline.APPR_PUB__Active__c = True;
	        headlines.add(headline);
	    }
	    insert headlines;

	    Test.startTest();

	    ApexPages.StandardController sc = new ApexPages.StandardController(headlines[0]);
	    HelixDesignRequestUtilities controller = new HelixDesignRequestUtilities(sc);

	    Test.stopTest();

	}
	
	@isTest 
	private static void testDocuments() {

		Account testPartner = TestClassFactory.CreateDealer('TestDealer', 'North America');

		Contact partnerContact = TestClassFactory.testContact('lastName', 'testpartnercon@noemail.com', TestClassFactory.retrieveRecordTypeID('Contact', 'Partner'));
        partnerContact.AccountId = testPartner.Id;
        partnerContact.Authorized_To_Order__c = TRUE;
        insert partnerContact;

        Design__c d = new Design__c();
        insert d;
        System.assertNotEquals(null, d.Id); 

        Document__c finalDoc = new Document__c();
        finalDoc.Document_Type__c = 'Commercial Design Deliverables';
        finalDoc.Design__c = d.Id;
        finalDoc.Name = 'Test';
        insert finalDoc;     
        
        UserRole role = [SELECT Id FROM UserRole WHERE Name LIKE '%Partner Executive' LIMIT 1];

        Id execProfileId = SFDCSpecialUtilities.getProfileIdByName('Partner Executive');

        User currentUser = new User(alias = 'cashman1', email = partnerContact.Email, 
                          emailencodingkey='UTF-8', lastname='Testing', 
                          languagelocalekey='en_US', localesidkey='en_US', 
                          profileid = execProfileId,  country='United States', 
                          communityNickName = 'cashman1', timezonesidkey='America/Los_Angeles', 
                          username=string.valueOf(math.random())+'u1@testorg.com',
                          contactId=partnerContact.Id, UserRole = role);

        System.runAs(currentUser) {

        	HelixDesignRequestUtilities.fetchDesignDocuments(d.Id);            

            List<Document__c> docs = new List<Document__c>();
            for(Integer i = 0; i < 3; i++) {
            	Document__c doc = new Document__c();
            	doc.Design__c = d.Id;
            	docs.add(doc);
            }
            insert docs;

			List<Attachment> atts = new List<Attachment>();
			for(Document__c record : docs) {	
				Attachment a = new Attachment();
				a.ParentId = record.Id;
				a.Name = 'test';
				a.Body = Blob.valueOf('Test');
				atts.add(a);
			}
			insert atts;

			Test.startTest();

	    	HelixDesignRequestUtilities.fetchDesignDocuments(d.Id);

	    	d.Status__c = 'Completed';
	    	d.Dealer_Status__c = 'Design Delivered';
	    	update d;

	    	HelixDesignRequestUtilities.fetchDesignDocuments(d.Id);

	    	ApexPages.StandardController sc = new ApexPages.StandardController(d);
	    	HelixDesignRequestUtilities controller = new HelixDesignRequestUtilities(sc);

	    	controller.docIdToDelete = docs[0].Id;
	    	controller.deleteDesignDocuments();

	    	controller.docIdToDelete = null;
	    	controller.deleteDesignDocuments();

	    	Test.stopTest();
    	}
	}

	@isTest
	private static void testNegatives() {

		Test.startTest();
		
		HelixDesignRequestUtilities.fetchDesignDocuments('123456');

		Test.stopTest();
	}
	
}