objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Five9WebserviceCalloutSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Maintain settings for Five9 Webservice callouts.</description>
    <fields>
        <fullName>APIURL__c</fullName>
        <label>APIURL</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain_Name__c</fullName>
        <label>Domain Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <description>Endpoint URL value for Five9 web service callouts in Five9Handler</description>
        <label>EndpointURL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F9key__c</fullName>
        <label>F9key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ListName__c</fullName>
        <description>ListName parameter value for addRecordtoListSimple call to Five9</description>
        <label>ListName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MasterSwitchOn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Uncheck will turn off webservice call outs to Five9</description>
        <label>MasterSwitchOn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reminder_List__c</fullName>
        <description>List name for appointment reminders</description>
        <label>Reminder List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPDF9list__c</fullName>
        <label>SPDF9list</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>Username for User Account used to make Five9 webservice callouts.</description>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Five9WebserviceCalloutSettings</label>
</CustomObject>

objects/UserName__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Case # 00222230 - Andrea Grimaldi the task owner, changing to Simona Orofino.</description>
    <label>UserName</label>
</CustomObject>

classes/F9ApptReminder_Test.cls
@isTest
global class F9ApptReminder_Test implements HttpCalloutMock {
    
    static TestMethod void TestF9ReminderCallout_Fail() {
        
        List<Id> oppIdsForCallout = new List<Id>();
        
        Account a = TestClassFactory.testAccount('Testname', TestClassFactory.retrieveRecordTypeID('Account', 'Residential Customer'));
        insert a;
        
        Contact c = TestClassFactory.testContact('TestlastName', 'testcon123@nomail.com', TestClassFactory.retrieveRecordTypeID('Contact', 'Customer'));
        c.Phone = '555-555-1212';
		c.AccountId = a.Id;        
        
        Opportunity o = TestClassFactory.testOpportunity('TestOppname', 'Appointment Confirmed', Date.today().addDays(30), TestClassFactory.retrieveRecordTypeID('Opportunity', 'Home Owner'));
        o.AccountId = a.Id;
        o.Primary_Contact__c = c.Id;
        insert o;
        oppIdsForCallout.add(o.Id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new F9ApptReminder_Test());
        
        F9ApptReminderOutbound.sendFive9ApptReminder(oppIdsForCallout);
        Test.stopTest();
        
    }

    static TestMethod void TestF9ReminderCallout_Pass() {

        Five9WebserviceCalloutSettings__c f9Settings = new Five9WebserviceCalloutSettings__c();
        f9Settings.Name = 'Five9';
        f9Settings.ListName__c = 'Test';
        f9Settings.MasterSwitchOn__c = true;
        f9Settings.Reminder_List__c = 'Test';
        f9Settings.F9key__c = 'salesforce_id';
        f9Settings.APIURL__c = 'https://api.five9.com/web2campaign/AddToList';
        f9Settings.EndpointURL__c = 'https://api.five9.com/wsadmin/v3/AdminWebService';
        f9Settings.Domain_Name__c = 'SunPower';
        f9Settings.Username__c = 'test@sunpower.com';
        f9Settings.SPDF9List__c = 'Test';
        insert f9Settings;
        
        List<Id> oppIdsForCallout = new List<Id>();
        
        Account a = TestClassFactory.testAccount('Testname', TestClassFactory.retrieveRecordTypeID('Account', 'Residential Customer'));
        insert a;
        
        Contact c = TestClassFactory.testContact('TestlastName', 'testcon123@nomail.com', TestClassFactory.retrieveRecordTypeID('Contact', 'Customer'));
        c.Phone = '555-555-1212';
        c.AccountId = a.Id;        
        
        Opportunity o = TestClassFactory.testOpportunity('TestOppname', 'Appointment Confirmed', Date.today().addDays(30), TestClassFactory.retrieveRecordTypeID('Opportunity', 'Home Owner'));
        o.AccountId = a.Id;
        o.Primary_Contact__c = c.Id;
        insert o;
        oppIdsForCallout.add(o.Id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new F9ApptReminder_Test());
        
        F9ApptReminderOutbound.sendFive9ApptReminder(oppIdsForCallout);
        Test.stopTest();
        
    }
    
    global HTTPResponse respond(HTTPRequest req) {
        
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"foo":"bar"}');
        res.setStatusCode(200);
        return res;
    }

}