objects/Content__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Only used for data loading from the external knowledge base system</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the content item</description>
        <label>Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Content</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Content Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContentTrackerUtilTest.cls
@IsTest
public class ContentTrackerUtilTest {

  public static testMethod void checkContentTracker(){
    //setup test data
    //create content
    Content__c contentObj = new Content__c();
    contentObj.Title__c = 'test content';
    contentObj.External_Id__c = 'test123';
    insert contentObj;
    
    ContentTrackerUtilClass.createContentTracker(contentObj.Id, UserInfo.getUserId());    
  }
}