objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications. Used for both SunPower and Partner Users. For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-us</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Check_Request__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Check_Message__c</fullName>
        <description>Loan Project- moving from Account- captures all messages from the vendor</description>
        <label>Credit Check Message</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Send_Lease_Credit_Check_Failure_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to send lease credit check failure email</description>
        <label>Send Lease Credit Check Failure Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Check Application</label>
    <nameField>
        <displayFormat>CCR-{000000}</displayFormat>
        <label>Credit Check Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Check Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <formula>Text($User.Country_Domain__c)</formula>
        <label>Country Domain</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Function__c</fullName>
        <description>GPP-Story1- This field is created for GPP Project. This replaces various checkboxes with one field that will be assigned to a partner user. Based on the values assigned to a user, user will be authorized to perform various activities on the platform. This field will work in conjunction with Corporate Business Functions which will be controlled by SPWR internal users.</description>
        <label>Business Function</label>
        <picklist>
            <picklistValues>
                <fullName>Create Cash Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Lease Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Loan Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Team Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Product SME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create ManualMode Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Equinox Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aurora Design Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Aurora Design Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create PPA Quote</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications.  Used for both SunPower and Partner Users.  For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>rvar-us</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-jp</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CreditCheckUtil.cls
//
public class CreditCheckUtil {
    
    //
    public static Set<String> getPartnerPermissions(){
        Set<String> permissions = new Set<String>();
        if(UserInfo.getUserType()!='Standard'){
            List<User> usrList = [select Id, Contact.Account.Business_Function__c, Business_Function__c, Contact.Account.Lease2_0_Program_Partner__c, Contact.Account.Loan_Partner__c,Contact.Account.Cash_Partner__c  from User WHERE ContactId <> null AND Id=:UserInfo.getUserId() AND isActive= true];
            System.debug('usrList----->'+usrList);
            if(!usrList.isEmpty()){
                if(string.isNotBlank(usrList[0].Business_Function__c)){
                    Set<String> sUsrBF = new Set<String>();
                    sUsrBF.addAll(usrList[0].Business_Function__c.split(';'));
                    if(usrList[0].Contact.Account.Lease2_0_Program_Partner__c == true && sUsrBF.contains('Create Lease Quote') == true ){
                        permissions.add('Lease');
                    }
                    if(usrList[0].Contact.Account.Loan_Partner__c == true && sUsrBF.contains('Create Loan Quote') == true ){
                        permissions.add('Loan');
                    }
                    if(usrList[0].Contact.Account.Cash_Partner__c == true && sUsrBF.contains('Create Cash Quote') == true ){
                        permissions.add('Cash');
                    }
                }    
            }   
        }
        else{
            permissions.add('Lease');
            permissions.add('Loan');
            permissions.add('Cash');
        }
        return permissions;
    }
    
    @future(callout=true)
    public static void SendCreditRequest_LoanPath(String ccrId,String partnerUrl,String sessionId,String strActParam,Boolean newHomes){
        System.debug('----->'+sessionId);
        System.debug('----->'+UserInfo.getUserId());
        System.debug('----->'+UserInfo.getUserName());
        //String nh = newHomes == TRUE ? 'NewHome,true' : 'NewHome,false';
        //String nh = 'NewHome,true';
        User user = [SELECT id, country_domain__c, name FROM User WHERE id=:UserInfo.getUserId()];
        system.debug('nh:'+newHomes);
        system.debug('ccrId:'+ccrId);
        system.debug('partnerUrl:'+partnerUrl);
        system.debug('sessionId:'+sessionId);
        system.debug('strActParam:'+strActParam);
        String result_status = '';
        if(newHomes){
            result_status = TPSSF.TPConnectorService.SubmitExt(
                                               'Credit_Check_Request__c',
                                                ccrId,
                                                 '' ,
                                                 '' ,
                                                'save',
                                                '' ,
                                                '',
                                                UserInfo.getUserId(),
                                                sessionId,
                                                PartnerUrl, 
                                                UserInfo.getUserName(), 
                                                (strActParam == 'ncr' ? 'CreateRequest' : 'ReSendEmail'),
                                                user.country_domain__c.substring(user.country_domain__c.indexOf('-')+1),
                                                'NewHome,true');
         }
         else{
             result_status = TPSSF.TPConnectorService.SubmitExt(
                                               'Credit_Check_Request__c',
                                                ccrId,
                                                 '' ,
                                                 '' ,
                                                'save',
                                                '' ,
                                                '',
                                                UserInfo.getUserId(),
                                                sessionId,
                                                PartnerUrl, 
                                                UserInfo.getUserName(), 
                                                (strActParam == 'ncr' ? 'CreateRequest' : 'ReSendEmail'),
                                                user.country_domain__c.substring(user.country_domain__c.indexOf('-')+1),
                                                'NewHome,false');
         }                                       
        system.debug('result_status:'+result_status);
        
        if((!String.isBlank(result_status) && !result_status.contains('SUCCESS'))){
            Credit_Check_Request__c ccr = new Credit_Check_Request__c(Id=ccrId,Send_Lease_Credit_Check_Failure_Email__c = true, Credit_Check_Message__c = result_status);
            update ccr;
        }
    }
}