objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Authorized_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field allows access for a specific dealer user to place orders via the online-order process in Salesforce. The dealer account also needs to be enabled for online ordering.</description>
        <label>Authorized to Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications. Used for both SunPower and Partner Users. For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-us</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications.  Used for both SunPower and Partner Users.  For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>rvar-us</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-jp</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Edit_Partner_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Edit Partner Users</description>
        <label>Edit Partner Users</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Warranty_Registration__c.object
<CustomObject>
    <description>Warranty Registration Object represent warranty.</description>
    <fields>
        <fullName>Customer_SFDC_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Warranty_Registrations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_SFDC_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Warranty_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Warranty Registration</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranty Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_FDS_Product__c.object
<CustomObject>
    <description>This being used in online warranty registration and is replica of FDS products.</description>
    <fields>
        <fullName>Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Packing Slip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <externalId>true</externalId>
        <label>Serial Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <formula>Text(WR_ORACLE_SalesOrder__r.Partner_Account__r.Theater__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theater</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WR_ORACLE_SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_ORACLE_SalesOrder</label>
        <referenceTo>WR_ORACLE_SalesOrder__c</referenceTo>
        <relationshipLabel>WR_FDS_Products</relationshipLabel>
        <relationshipName>WR_FDS_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WR_FDS_Product</label>
    <nameField>
        <displayFormat>Product - {0000}</displayFormat>
        <label>WR_FDS_Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_FDS_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_Line_Item__c.object
<CustomObject>
    <description>Junction Object with Warranty_Registration and WR_FDS_Product .</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>WR_FDS_Product__r.Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>WR_FDS_Product__r.Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>WR_FDS_Product__r.Serial_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WR_FDS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_FDS_Product</label>
        <referenceTo>WR_FDS_Product__c</referenceTo>
        <relationshipName>WR_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty_Registration__c</fullName>
        <label>Warranty_Registration</label>
        <referenceTo>Warranty_Registration__c</referenceTo>
        <relationshipName>WR_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WR Line Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>WR Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WR_ORACLE_SalesOrder__c.object
<CustomObject>
    <description>Oracle Salesorder Replicate. - Packing slip information for warranty registration - populated by Middleware from Oracle (John Taylor 7/14/2014)</description>
    <fields>
        <fullName>Oracle_Account_Number__c</fullName>
        <label>Oracle Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Packing Slip</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>WR_ORACLE_SalesOrder</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SFDC_NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_ORACLE_SalesOrder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WarrantyRegistrationCSVController_Test.cls
/*
  Test functionality of WarrantyRegistrationCSVController
  
  @Author Anjali Khandelwal (Appirio offhsore)
*/

@isTest
private class WarrantyRegistrationCSVController_Test
{
    static Warranty_Registration__c wrc_test1;
    static WarrantyRegistrationCSVController wrcc;
    public static testMethod void testWarrantyRegistrationCSVController()
    {
        Account acct = getPartnerAccount();
        User test_user =getPartnerPortalUser(acct);               
        System.runAs(test_user){ 
        
        //Start new context       
        Test.startTest();
        acct = test_user.Contact.Account;
        Opportunity test_opp1 = createOpp(acct,test_user);
        insert test_opp1;
        Date edt = System.today();
        Account customer1 = new Account(Name='DummyCustomerAcc1',CurrencyIsoCode='USD',Theater__c='North America',BillingCity='testCity',BillingCountry='testCountry',BillingStreet='testStreet',BillingPostalCode='testZipCode');
        insert customer1;
        wrc_test1 = new Warranty_Registration__c(Delivery_Date__c=edt,Partner_SFDC_ID__c=acct.Id,Customer_SFDC_ID__c=customer1.Id,status__c = 'Draft');
        insert wrc_test1 ;
        
        createTestData();
        //ErrorMsg will be generated as no warrantyId is set
        try{
            wrcc = new WarrantyRegistrationCSVController();
        }
        catch(Exception ex)
        {
            System.assertEquals(ex.getMessage(),'List has no rows for assignment to SObject');
        }
        //No warranty object is get as warrantyId is not set
        System.assertEquals(wrcc.warranty, null);//Assert warranty
        //WarrantyId is set
        ApexPages.currentPage().getParameters().put('warrantyId' , wrc_test1.Id);
        wrcc = new WarrantyRegistrationCSVController();       
        System.assertEquals(wrcc.warranty.Id , wrc_test1.Id);//Assert warranty
        Test.stopTest();
        }
    }
    
     //Create Partner Portal user
     private static User getPartnerPortalUser(Account acct){
        User user = null;
       
        if(acct == null){
            acct =  getPartnerAccount();
        }
        Contact cont = new Contact(AccountID = acct.id,FirstName='testconbyPO2',LastName='testconbyPO2');
        cont.Email ='te@test.com';
        cont.Authorized_to_Order__c = true;
        cont.RecordTypeID = util.GetRecordTypeIdsByDeveloperName(Contact.SObjectType).get('Partner'); //MAM 19.MAY.2015 Get Contact Partner RecordTypeId        
        insert cont;        
        
        String username ='anjalitest@test1.com';      
        user = new User(LastName = 'Hello222'+String.ValueOf(DateTime.Now()) ,FirstName = 'W'+ String.ValueOf(DateTime.Now()));
        user.ContactId = cont.Id;
        user.Username = username;
        user.Alias = 'anjali';
        user.CommunityNickname = username.subString(0,7);
        user.TimeZoneSidKey = 'America/Los_Angeles';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.Email = cont.Email;
        user.LocaleSidKey = 'en_US';
        user.Edit_Partner_Users__c = true;     
        List<Profile> lstProfile = [select Id from Profile where Name = 'Partner Delegated Administrator'];
        if(lstProfile.Size()>0){
            user.ProfileId = lstProfile[0].Id;
            insert user;
        }
        if(user.Id != null)
          for(User u:[select id,Name,contactId,Contact.AccountID, Contact.Account.AccountNumber,Contact.Account.CurrencyIsoCode,Contact.Account.Name,Contact.Account.Country_Domain__c,Contact.Account.Theater__c,Contact.Account.ShippingStreet,Contact.Account.ShippingState,Contact.Account.ShippingCity,Contact.Account.ShippingCountry,Contact.Account.ShippingPostalCode,Contact.Account.Oracle_Operating_Unit__c, Contact.Account.Oracle_Account_Number__c from User where id =:user.ID LIMIT 1])
            user = u; 
        return user;
        
    }
     
     //Create Partner Account 
     private static Account getPartnerAccount(){
        String recType ='';
        for(RecordType r:[select id,Name from RecordType where sObjectType ='Account' and name ='Partner' LIMIT 1])
             recType = r.ID;             
        Account acct = new Account(name='test1'+String.valueOf(DateTime.now().getTime()),recordTypeID=recType);
        acct.ShippingCity = 'Jaipur';
        acct.ShippingStreet = 'Durgapura';
        acct.ShippingCountry = 'India';
        acct.ShippingState='Rajasthan';
        acct.ShippingPostalCode ='302018';
        acct.BillingCity = 'Jaipur';
        acct.BillingStreet = 'Durgapura';
        acct.BillingCountry = 'India';
        acct.BillingState='Rajasthan';
        acct.BillingPostalCode ='302018';
        acct.Online_Order_Access__c = true;
        acct.Oracle_Account_Number__c = 'test_oracle';
        acct.Theater__c = 'North America';
        acct.CurrencyIsoCode='USD';
        acct.Country_Domain__c = 'rvar-us';
        insert acct;
        return acct;                     
    }     
    
    //Create Opportunity between user and account
    private static Opportunity createOpp(Account acct,User u){    
        Opportunity opp = new Opportunity();      
        opp.AccountId = acct.ID;
        opp.Name = 'testOpp';
        opp.StageName = 'won';
        opp.ownerId = u.Id;
        opp.Probability =10;
        opp.CloseDate = System.today();
        opp.Reason_Won_Lost__c = 'Best Economics';             
        return opp;
    }
    private static void createTestData()
    {
        List<WR_ORACLE_SalesOrder__c> lstSalesOrder = new List<WR_ORACLE_SalesOrder__c>();
        List<WR_FDS_Product__c> lstProduct = new List<WR_FDS_Product__c>();
        Date edt = System.today();
        //Test data for salesorder
        WR_ORACLE_SalesOrder__c salesOrder1 = new WR_ORACLE_SalesOrder__c(Sales_Order__c='test_salesorder1',CurrencyIsoCode='USD',Oracle_Account_Number__c='test_oracle',Packing_Slip__c='testPackingSlip1');
        lstSalesOrder.add(salesOrder1);
        WR_ORACLE_SalesOrder__c salesOrder2 = new WR_ORACLE_SalesOrder__c(Sales_Order__c='test_salesorder2',CurrencyIsoCode='USD',Oracle_Account_Number__c='test_oracle',Packing_Slip__c='testPackingSlip2');
        lstSalesOrder.add(salesOrder2);
        insert lstSalesOrder;
        //Test data for products
        WR_FDS_Product__c salesOrderLnItem1 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Packing_Slip__c='testPackingSlip1',WR_ORACLE_SalesOrder__c = salesOrder1.Id,Product_Name__c = 'testproduct1',Product_Type__c = 'testproducttype1',Serial_Number__c = '_testSrNo1');
        lstProduct.add(salesOrderLnItem1);
        WR_FDS_Product__c salesOrderLnItem2 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Packing_Slip__c='testPackingSlip1',WR_ORACLE_SalesOrder__c = salesOrder1.Id,Product_Name__c = 'testproduct2',Product_Type__c = 'testproducttype1',Serial_Number__c = '_testSrNo2');
        lstProduct.add(salesOrderLnItem2);
        WR_FDS_Product__c salesOrderLnItem3 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Packing_Slip__c='testPackingSlip2',WR_ORACLE_SalesOrder__c = salesOrder2.Id,Product_Name__c = 'testproduct3',Product_Type__c = 'testproducttype2',Serial_Number__c = '_testSrNo3');
        lstProduct.add(salesOrderLnItem3);
        WR_FDS_Product__c salesOrderLnItem4 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Packing_Slip__c='testPackingSlip2',WR_ORACLE_SalesOrder__c = salesOrder2.Id,Product_Name__c = 'testproduct4',Product_Type__c = 'testproducttype2',Serial_Number__c = '_testSrNo4');
        lstProduct.add(salesOrderLnItem4);
        insert lstProduct; 
        
        //Test data is for WR_Line_Item__c
           
        List<WR_Line_Item__c> lstWrLnItem = new List<WR_Line_Item__c>(); 
        WR_Line_Item__c wrLnItem1 = new WR_Line_Item__c(WR_FDS_Product__c = salesOrderLnItem1.Id,Warranty_Registration__c = wrc_test1.Id);
        WR_Line_Item__c wrLnItem2 = new WR_Line_Item__c(WR_FDS_Product__c = salesOrderLnItem2.Id,Warranty_Registration__c = wrc_test1.Id);  
        WR_Line_Item__c wrLnItem3 = new WR_Line_Item__c(WR_FDS_Product__c = salesOrderLnItem3.Id,Warranty_Registration__c = wrc_test1.Id);            
        WR_Line_Item__c wrLnItem4 = new WR_Line_Item__c(WR_FDS_Product__c = salesOrderLnItem4.Id,Warranty_Registration__c = wrc_test1.Id);                
        lstWrLnItem.add(wrLnItem1);
        lstWrLnItem.add(wrLnItem2);
        lstWrLnItem.add(wrLnItem3);
        lstWrLnItem.add(wrLnItem4);
        insert lstWrLnItem;      
    }    
}