objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications. Used for both SunPower and Partner Users. For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-us</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LeasePayment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>This Was made Master Detail as the LEase Payment was made private to avoid any visibility issues.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <formula>Text( Agreement__r.echosign_dev1__Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agreement Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>echosign_dev1__SIGN_Agreement__c</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <formula>RIGHT(Account__r.Owner.CountryDomainText__c ,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Lease_Summary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox controls whether the lease schedule summary record should be created. It requires the lease payment lookup to a quote record as well.</description>
        <inlineHelpText>This checkbox controls whether the lease schedule summary record should be created. It requires the lease payment lookup to a quote record as well.</inlineHelpText>
        <label>Create Lease Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Lease_Document_signed__c</fullName>
        <label>Date Lease Document signed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lease_Payments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Multiple_Meters__c</fullName>
        <formula>IF( Account__r.Multiple_Meters__c = True, &quot;Yes&quot;,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Multiple Meters</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Leases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <formula>End_Customer_Account__r.BillingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation with RMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased HO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separation of Lesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disposed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Payment</label>
    <nameField>
        <label>Financial Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account_Billing_Country__c</fullName>
        <formula>Account__r.BillingCountry</formula>
        <label>Account Billing Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <formula>Text($User.Country_Domain__c)</formula>
        <label>Country Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project: GPP
Description: Installer Partner for the Quote.</description>
        <inlineHelpText>Installer Partner for the Quote.</inlineHelpText>
        <label>Installer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Installer)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PrimaryContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes (PrimaryContact)</relationshipLabel>
        <relationshipName>Quotes5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <description>Project: GPP
Description: Address of Site for which Quote is for, Stores Address&apos;s Country</description>
        <inlineHelpText>Site Address (Property Address)</inlineHelpText>
        <label>Site Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Contact_1__c</fullName>
        <label>Temp Contact 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications.  Used for both SunPower and Partner Users.  For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>rvar-us</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-jp</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AgreementManagement.cls
/*
Modified Code -- Sunpower TPO Phase 1 -- 20/10/2013, to update Quote status with Agreement status
Modification:
22-may-2014 : Birlasoft : API Version Changed from 14.0 to 29.0
22-may-2014 : Birlasoft : Added createLeasePayment() method to Create Lease Payment Records For AU Accounts, when Agreement Status is changes to "Wating For Counter-Signature"
02-Jun-2014 : Birlasoft : Added Method to Update Installer Email on Agreement from Primary contact of Installer Account
03-Jun-2014 : Birlasoft : Updated the code to match with Production Copy & with new GPP changes.
20-jun-2014 : Birlasoft : Reduce number of lines in the createLeasePayment() & createLeaseScheduleSummary() methods.
01-jul-2014 : Birlasoft : Modify Code to populate Contact of Leasepayment from PrimaryContact of Quote
*/

public class AgreementManagement 
{
    
    private static Id leaseContractRecTypeId = SFDCSpecialUtilities.getRecordTypeIdsByDeveloperName(echosign_dev1__SIGN_Agreement__c.SobjectType).get('Lease_Contract');
    public static Boolean executeMethod=true;
    public static Boolean isCustomerUpdated = false;
    public static void afterAgreementInsert (List<echosign_dev1__SIGN_Agreement__c> agreementList)
    {
        updateAgreementContract(agreementList);  
              
    }
    public static void afterAgreementUpdate (List<echosign_dev1__SIGN_Agreement__c> agreementList, 
                                             List<echosign_dev1__SIGN_Agreement__c> oldAgreementList)
    {
        updateAgreementContract(agreementList);
        
        //Call updateAccountIsCustomerandCustomerType Method
        if(!isCustomerUpdated)
            updateAccountIsCustomerandCustomerType(agreementList);
    }
    
    
    
    private static void updateAgreementContract(List<echosign_dev1__SIGN_Agreement__c> agreeList)
    {
        List<Contract> conts = new List<Contract>();
        List<Id> contractIds = new List<Id>();
        //New Code -- Sunpower TPO Phase 1 -- 20/10/2013
        List<Quote> quotes = new List<Quote>();
        List<Id> quoteIds = new List<Id>();
        system.Debug('***********AgreeManage1'+agreeList);
        //End New Code -- Sunpower TPO Phase 1 -- 20/10/2013
        
        for(echosign_dev1__SIGN_Agreement__c agree:agreeList){    
            
            if(agree.echosign_dev1__Contract__c!=null){
                contractIds.add(agree.echosign_dev1__Contract__c);
            }
            
            /*CRYSTAL - commented per Sangita Approval 11/3/2015
            //New Code -- Sunpower TPO Phase 1 -- 20/10/2013
            if(agree.Quote__c!=null){
            quoteIds.add(agree.Quote__c);
            }
            system.Debug('***********AgreeManage2'+quoteIds);
            //New Code -- Sunpower TPO Phase 1 -- 20/10/2013
            */
        }
        
        Map<Id,Contract> contractMap = new Map<Id,Contract>(); 
        if(!contractIds.isEmpty())
            contractMap = new Map<Id, Contract>([select Id, Status, Sent_Date__c, Signed_Date__c, Viewed_Date__c from Contract where Id in :contractIds]);
        //New Code -- Sunpower TPO Phase 1 -- 20/10/2013
        //CRYSTAL - commented per Sangita approval 11/3/2015
        //Map<Id,Quote> QuoteMap = new Map<Id,Quote>([select ID, Agreement_Status__c,Account__r.BillingCountry from Quote where ID in :quoteIds and Account__r.BillingCountry = 'France']);
        
        //End New Code -- Sunpower TPO Phase 1 -- 20/10/2013 
        for(echosign_dev1__SIGN_Agreement__c agree:agreeList){    
            //New Code -- Sunpower TPO Phase 1 -- 20/10/2013
            /*if (QuoteMap.containsKey(agree.Quote__c) )
            {            
                Quote qt = QuoteMap.get(agree.Quote__c);
                
                qt.Agreement_Status__c = agree.echosign_dev1__Status__c;
                system.Debug('***********AgreeManage4'+qt);   
                quotes.Add(qt);
            }*/
            //End New Code -- Sunpower TPO Phase 1 -- 20/10/2013         
            if(agree.echosign_dev1__Contract__c==null){
                continue;
            }
            if (contractMap.containsKey(agree.echosign_dev1__Contract__c)){
                
                Contract cont = contractMap.get(agree.echosign_dev1__Contract__c);
                
                if (cont.Status!='Activated'){
                    
                    if(agree.echosign_dev1__Status__c=='Draft')
                        cont.Status = 'New';
                    else                
                        cont.Status = agree.echosign_dev1__Status__c;
                    
                    cont.Sent_Date__c = agree.echosign_dev1__DateSentDate__c;   
                    cont.Signed_Date__c = agree.echosign_dev1__DateSignedDate__c;
                    cont.Viewed_Date__c = agree.echosign_dev1__DateViewedDate__c;                   
                    conts.Add(cont);
                }
            }
        }        
        if (conts.size()>0)
            update conts;
        //New Code -- Sunpower TPO Phase 1 -- 20/10/2013
        if (quotes.size()>0)
            update quotes;
        //End New Code -- Sunpower TPO Phase 1 -- 20/10/2013
    }
    
    //Creates LeasePayment when Agreement Status is Waiting for Counter-Signature for Australia      
    Public static void createLeasePayment(Map<ID,echosign_dev1__SIGN_Agreement__c> mapQIDVsAg)
    {
        List<ID> AccIds=new List<ID>();
        //Map<ID,String> mapQIDvsCon=new Map<ID,String>();
        Map<ID,Quote> mapQuote=new Map<ID,Quote>();
        for(Quote q:[Select Id, Opportunity.AccountId, Opportunity.Account.Name, 
                     OpportunityID, Opportunity.Account.Partner_Account__c,
                     Temp_contact_1__c,PrimaryContact__c,
                     Opportunity.Account.Partner_Account__r.Country_Domain__c ,
                     Account_Billing_Country__c, contactID, Installer__c, Installer__r.Parent.Id,
                     Account__c,Account__r.OwnerId, currencyisocode
                     from Quote where Id IN : mapQIDVsAg.keySet() and (Account_Billing_Country__c='Australia' or Account_Billing_Country__c='australia')                      
                    ])
        {
            mapQuote.put(q.id,q);
        } 
        System.debug('$$$ mapQuote '+((!mapquote.isEmpty())?mapquote.size():null));
        createSharingWithInstaller(mapQuote);
        for(Quote q:mapQuote.values())
        {
            if(q.Account_Billing_Country__c=='Australia')
            {
                AccIds.add(q.Opportunity.AccountId);             
                //mapQIDvsCon.put(q.ID,q.Opportunity.Account.Partner_Account__r.Country_Domain__c.right(2));
            }
        }
        //if(!AccIds.isEmpty() && !mapQIDvsCon.isEmpty())
        System.debug('AAA AccIDs '+AccIds.size());//+' AU Country '+mapQIDvsCon.size());
        Map<Id,LeasePayment__c> mapLeasePmt = new Map<Id,LeasePayment__c>([SELECT id, name, Status__c, Quote__c,Opportunity__c,Account__c,Account__r.Multiple_Meters__c FROM LeasePayment__c WHERE Account__c=:AccIds]);
        List<LeasePayment__c> lstLP=new List<LeasePayment__c>();
        boolean bStatus = false;
        boolean multMetrs = false;
        Set<ID> setAccIds = new Set<ID>();
        Set<String> setLPStatus = new Set<String>();
        Map<Id,Id> mapLP_IdvsLP_Quo = new Map<Id,Id>();
        Map<Id,Id> mapLP_IdvsLP_Opp = new Map<Id,Id>();
        
        if(mapLeasePmt.isEmpty()) // Create LP if there are no existing lease Payments for the Account
        {
            for(Quote q:mapQuote.values())
            {
                if(q.Account_Billing_Country__c == 'Australia')
                {
                    lstLP.add(new LeasePayment__c(Name=q.Opportunity.Account.Name, 
                                                  Agreement__c=mapQIDVsAg.get(q.ID).ID,
                                                  Quote__c= q.ID,
                                                  Opportunity__c= q.OpportunityID,
                                                  Account__c= q.Opportunity.AccountId,
                                                  Partner_Account__c= q.Opportunity.Account.Partner_Account__c,
                                                  End_Customer_Account__c= q.Opportunity.AccountId,
                                                  Contact__c= q.PrimaryContact__c,
                                                  currencyisocode = q.currencyisocode,
                                                  recordtypeid = Label.LeasePaymentRecordTypeID_AU,
                                                  Date_Lease_Document_signed__c = Date.Today() 
                                                 ));  
                }             
            }//End for 
        }
        else
        {
            for(Id LId : mapLeasePmt.keySet())
            {
                setAccIds.add(mapLeasePmt.get(LId).Account__c);
                mapLP_IdvsLP_Quo.put(mapLeasePmt.get(LId).Account__c,mapLeasePmt.get(LId).Quote__c);
                mapLP_IdvsLP_Opp.put(mapLeasePmt.get(LId).Account__c,mapLeasePmt.get(LId).Opportunity__c);
                System.debug('# status '+mapLeasePmt.get(LId).Status__c);
                if(mapLeasePmt.get(LId).Status__c == null)
                    bStatus = true;
                else
                    setLPStatus.add(mapLeasePmt.get(LId).Status__c);// updated by Rashmi on 20/09/2012 to allow duplicate LP when the earlier LP is not active.
                if(mapLeasePmt.get(LId).Account__r.Multiple_Meters__c == true)
                    multMetrs = true;
            }
            for(Quote q : mapQuote.values())
            {
                if(setAccIds.contains(q.Opportunity.AccountId) && ((mapLP_IdvsLP_Quo.get(q.Opportunity.AccountId)!=null && q.ID != mapLP_IdvsLP_Quo.get(q.Opportunity.AccountId) && multMetrs) || (mapLP_IdvsLP_Quo.get(q.Opportunity.AccountId)!=null && q.ID != mapLP_IdvsLP_Quo.get(q.Opportunity.AccountId) &&(setLPStatus.contains('Transferred') ||setLPStatus.contains('Terminated') || setLPStatus.contains('Cancelled') || setLPStatus.contains('Cancellation with RMA') || setLPStatus.contains('Expired') || setLPStatus.contains('Duplicate'))&& !(setLPStatus.contains('Active') ||setLPStatus.contains('Pending Cancellation') || bStatus)))) //Checking for Duplication
                {
                    if(q.Account_Billing_Country__c != null && q.Account_Billing_Country__c == 'Australia')
                    {
                        lstLP.add(new LeasePayment__c(Name=q.Opportunity.Account.Name,
                                                      Agreement__c=mapQIDVsAg.get(q.ID).ID,       
                                                      Quote__c= q.ID,
                                                      Opportunity__c= q.OpportunityID,
                                                      Account__c= q.Opportunity.AccountId,
                                                      Partner_Account__c= q.Opportunity.Account.Partner_Account__c,
                                                      End_Customer_Account__c= q.Opportunity.AccountId,
                                                      Contact__c= q.PrimaryContact__c,
                                                      currencyisocode = q.currencyisocode,
                                                      recordtypeid = Label.LeasePaymentRecordTypeID_AU,
                                                      Date_Lease_Document_signed__c = Date.Today() 
                                                     ));
                    }
                }                       
            }//End for 
        }     
        System.debug('$$$ LeasePayment To be Inserted '+lstLP.size());
        if(!lstLP.isEmpty()) 
            Insert lstLP;
    }//End of Method createLeasePayment
    
    //Called when Agreement Status is updated to Waiting for Counter-Signature and will create LeaseScheduleSummary if Lease Schedule exists for Australia Only.
    Public static void createLeaseScheduleSummary(Set<Id> lstQuote)
    {
        List<LeasePayment__c> lstLPs=[Select Id,Create_Lease_Summary__c,Date_Lease_Document_signed__c from LeasePayment__c where Quote__c=:lstQuote and Site_Country__c='Australia'];
        for(LeasePayment__c lp:lstLPs)
        {
            if(lp.Date_Lease_Document_signed__c==null)
                lp.Date_Lease_Document_signed__c=Date.Today();    lp.Date_Lease_Document_signed__c=lp.Date_Lease_Document_signed__c-1;    lp.Create_Lease_Summary__c=false;
        }
        update lstLPs;
        
        for(LeasePayment__c lp:lstLPs)
        {
            lp.Date_Lease_Document_signed__c=lp.Date_Lease_Document_signed__c+1;    lp.Create_Lease_Summary__c=true;
        }
        update lstLPs;
    }  //End of Method createLeaseScheduleSummary
    
    /*
Sangita added
*/
    
    Public static void createSharingWithInstaller(Map<Id,quote> mapQuote)
    {
        //Create sharing with the installer account in case of self installer or parent account in the case of Service stream type scenario where 
        //contact from the parent should be able to see records
        
        set<id> setInstallerid = new set<id>();
        
        Map<ID,set<ID>> mapAccountInstaller = new Map<ID,set<ID>>();
        Map<ID,set<ID>> mapOppInstaller = new Map<ID,set<ID>>();
        
        set<id> setAccountShareid = new set<id>();
        set<id> setOpportunityShareid = new set<id>();
        for(Quote objQuote : mapQuote.values()){
            //not selft installer
            if(objQuote.Account__c != objQuote.Installer__c){
                
                ID installerID = null;
                if(objQuote.inStaller__r.Parent != null)
                    installerID = objQuote.inStaller__r.Parent.id;
                else
                    installerID = objQuote.Installer__c;
                
                setInstallerid.add(installerID);
                if(objQuote.Account__c!= null){ 
                    setAccountShareid.add(objQuote.Account__c);
                    if(mapAccountInstaller.containsKey(installerID))
                    {
                        set<ID> setID = mapAccountInstaller.get(installerID);
                        setID.add(objQuote.Account__c);
                        mapAccountInstaller.put(installerID,setID);
                    }else
                        mapAccountInstaller.put(installerID,new set<id>{objQuote.Account__c});
                }
                if(objQuote.OpportunityId!= null){
                    setOpportunityShareid.add(objQuote.OpportunityId);
                    if(mapOppInstaller.containsKey(installerID))
                    {
                        set<ID> setID = mapOppInstaller.get(installerID);
                        setID.add(objQuote.OpportunityId);
                        mapOppInstaller.put(installerID,setID);
                    }else
                        mapOppInstaller.put(installerID,new set<id>{objQuote.OpportunityId});
                }   
            }
        }
        //map<ID,Account> mapAccount = new map<ID,Account>([Select id,(Select id from Contacts) from Account where id IN: setAccountShareid]);
        
        
        
        map<ID,set<ID>> mapAccountIDGroup = new map<ID,set<ID>>();
        Map<ID,UserRole> mapUserRole = new Map<ID,UserRole>([SELECT PortalAccountId,name,id FROM UserRole where PortalAccountId IN :setInstallerid and name like '%Partner User%']);
        //Map<ID,User> mapUser =new Map<ID,User>([Select id,UserRoleID from User where UserRoleID IN : mapUserRole.keySet()]);
        Map<ID,Group>  mapGroup = new Map<ID,Group>([Select g.Id,g.RelatedId From Group g where g.Type='Role' and g.RelatedId= :mapUserRole.keySet()]);
        
        map<ID,list<AccountShare>> mapAccountShare = new map<ID,list<AccountShare>>();
        
        for(AccountShare objAccountShare : [Select id,accountID,UserorGroupID,AccountAccessLevel from AccountShare where accountID IN:setAccountShareid and UserorGroupID IN:mapGroup.keySet()]){
            if(mapAccountShare.containsKey(objAccountShare.accountID))
            {
                list<AccountShare> listAccountShare = mapAccountShare.get(objAccountShare.accountID);
                listAccountShare.add(objAccountShare);
                mapAccountShare.put(objAccountShare.accountID,listAccountShare);
            }else
                mapAccountShare.put(objAccountShare.accountID,new list<AccountShare>{objAccountShare});
        }
        
        map<ID,list<OpportunityShare>> mapOpportunityShare = new map<ID,list<OpportunityShare>>();
        
        for(OpportunityShare objOpportunityShare : [Select id,OpportunityId,UserorGroupID,OpportunityAccessLevel from OpportunityShare where OpportunityId IN:setOpportunityShareid and UserorGroupID IN:mapGroup.keySet()]){
            if(mapOpportunityShare.containsKey(objOpportunityShare.OpportunityId))
            {
                list<OpportunityShare> listOpportunityShare = mapOpportunityShare.get(objOpportunityShare.OpportunityId);
                listOpportunityShare.add(objOpportunityShare);
                mapOpportunityShare.put(objOpportunityShare.OpportunityId,listOpportunityShare);
            }else
                mapOpportunityShare.put(objOpportunityShare.OpportunityId,new list<OpportunityShare>{objOpportunityShare});
        }
        
        for(UserRole objUserRole : mapUserRole.values()){
            for(Group objGroup: mapGroup.values()){
                if(objGroup.RelatedId == objUserRole.Id){
                    if(mapAccountIDGroup.containsKey(objuserRole.PortalAccountId))
                    {
                        set<ID> setID = mapAccountIDGroup.get(objuserRole.PortalAccountId);
                        setID.add(objGroup.Id);
                        mapAccountIDGroup.put(objuserRole.PortalAccountId,setID);
                    }else
                        mapAccountIDGroup.put(objuserRole.PortalAccountId,new set<id>{objGroup.Id});
                }
            }
        }
        System.debug('--------------+mapAccountIDGroup'+mapAccountIDGroup);
        System.debug('--------------+mapAccountInstaller'+mapAccountInstaller);
        List<AccountShare> listAccountShare = new List<AccountShare>();
        List<ContactShare> listContactShare = new List<ContactShare>();
        List<OpportunityShare> listOpportunityShare = new List<OpportunityShare>();
        for(ID idInstaller: mapAccountInstaller.keySet()){
            if(!mapAccountInstaller.isEmpty() && mapAccountInstaller.containsKey(idInstaller)){
                for(ID idAccount : mapAccountInstaller.get(idInstaller)){
                    if(!mapAccountIDGroup.isEmpty() && mapAccountIDGroup.containsKey(idInstaller)){
                        for(ID idGrup : mapAccountIDGroup.get(idInstaller)){
                            boolean isExstingAccountShare = false;
                            if(!mapAccountShare.isEmpty() && mapAccountShare.containsKey(idAccount)){
                                for(AccountShare objAccountShare : mapAccountShare.get(idAccount)){
                                    if(!isExstingAccountShare && objAccountShare.accountID == idAccount 
                                       && objAccountShare.UserorGroupID == idGrup
                                       && objAccountShare.AccountAccessLevel == 'Read'){
                                           isExstingAccountShare = true;
                                       }
                                }
                                System.debug('----------------------------isExstingAccountShare'+isExstingAccountShare);
                                
                            }
                            System.debug('----------------------------isExstingAccountShare'+isExstingAccountShare);
                            if(!isExstingAccountShare){
                                AccountShare accountShare =  new AccountShare();
                                accountShare.accountID= idAccount;
                                accountShare.AccountAccessLevel ='Read';
                                accountShare.opportunityAccessLevel ='None';
                                accountShare.UserorGroupID =idGrup;
                                listAccountShare.add(accountShare);
                            }
                        }
                    }
                    
                }
            }
            
            
            if(!mapOppInstaller.isEmpty() && mapOppInstaller.containsKey(idInstaller)){
                for(ID idOpp : mapOppInstaller.get(idInstaller)){
                    if(!mapAccountIDGroup.isEmpty() && mapAccountIDGroup.containsKey(idInstaller)){
                        for(ID idGroup : mapAccountIDGroup.get(idInstaller)){
                            boolean isExstingOppShare = false;
                            if(!mapOpportunityShare.isEmpty() && mapOpportunityShare.containsKey(idOpp)){
                                for(OpportunityShare objOpportunityShare : mapOpportunityShare.get(idOpp)){
                                    if(!isExstingOppShare && objOpportunityShare.OpportunityId == idOpp 
                                       && objOpportunityShare.UserorGroupID == idGroup
                                       && objOpportunityShare.OpportunityAccessLevel == 'Read'){
                                           isExstingOppShare = true;
                                       }
                                }
                                System.debug('----------------------------isExstingOppShare'+isExstingOppShare);
                                
                            }
                            System.debug('----------------------------isExstingOppShare'+isExstingOppShare);
                            if(!isExstingOppShare){
                                OpportunityShare opportunityShare =  new OpportunityShare();
                                opportunityShare.OpportunityId= idOpp;
                                opportunityShare.OpportunityAccessLevel ='Read';
                                opportunityShare.UserorGroupID =idGroup;
                                listOpportunityShare.add(opportunityShare);
                            }
                        }
                    }
                }
            }
            
            
            
        }
        System.debug('------------------------listAccountShare'+listAccountShare);
        if(!listAccountShare.isEmpty())
            insert listAccountShare;
        System.debug('------------------------listOpportunityShare'+listOpportunityShare);
        if(!listOpportunityShare.isEmpty())
            insert listOpportunityShare;
        /*
if(!listContactShare.isEmpty())
insert listContactShare;*/
        
        
        
        
        
    }//end method
    
    //Added By Birlasoft: 2-Jun-2014 : Method to Update Installer Email on Agreement from Primary contact of Installer Account
    ////This method can be eliminated, was part of UpdateInstallerEmail trigger, marked for removal per Sangita recommendation 10/2015
    Public static void UpdateInstallerEmail(List<echosign_dev1__SIGN_Agreement__c> lstAgs)     
    {
        List<ID> qIds=new List<ID>();
        Map<ID,String> mapIDvsEmail=new Map<ID,String>();
        Map<ID,ID> mapInstIDvsQID=new Map<ID,ID>();
        if(executeMethod)
        {
            for(echosign_dev1__SIGN_Agreement__c ag:lstAgs)
            {
                qids.add(ag.Quote__c);
            }
            for(Quote qt:[Select ID, Installer__C, Installer__r.Name,Installer__r.ParentID from Quote where ID=:qids AND Installer__c!=null ])
            {
                if(qt.Installer__r.ParentID!=null)
                    mapInstIDvsQID.put(qt.Installer__r.ParentID,qt.ID);
                else
                    mapInstIDvsQID.put(qt.Installer__c,qt.ID);
            }
            for(Account acc:[Select Id, (Select Id,Primary__c,Email from Contacts) from Account where ID in :mapInstIDvsQID.keySet()])
            {
                for(Contact con: acc.Contacts)
                {
                    if(con.Primary__c)
                        mapIDvsEmail.put(mapInstIDvsQID.get(acc.ID),con.Email);
                }
            }
            for(echosign_dev1__SIGN_Agreement__c ag:lstAgs)
            {
                ag.Installer_Email__c=(!mapIDvsEmail.isEmpty() && mapIDvsEmail.containsKey(ag.Quote__c))?mapIDvsEmail.get(ag.Quote__c):null;
            }
        } 
        executeMethod = false;
    }// Method UpdateInstallerEmail End
    
    
    //Method to update isCustomer flag and Customer Type as Lease when Agreement Status becomes 'Signed'
    public static void updateAccountIsCustomerandCustomerType(List<echosign_dev1__SIGN_Agreement__c> agrmntList){
        
        Set<Id> accountIdSet = new Set<Id>();
        List<Account> acctList = new List<Account>();
        List<Account> acctUpdateList = new List<Account>();
        for(echosign_dev1__SIGN_Agreement__c agrmnt:agrmntList){
            if(agrmnt.Account__c!=null && agrmnt.echosign_dev1__Status__c=='Signed')
                accountIdSet.add(agrmnt.Account__c);
        }
        
        if(!accountIdSet.isEmpty())
            acctList = [select Id,DSE_IsCustomer__c,DSE_CustomerType__c FROM Account where Id in :accountIdSet];
        
        isCustomerUpdated = true;
        
        for(Account acc:acctList){
            if(acc.DSE_IsCustomer__c!=true){
                acc.DSE_IsCustomer__c=true;
                acc.DSE_CustomerType__c='Lease';
                acc.DSE__DS_Synchronize__c=true;
                acctUpdateList.add(acc);
            }
        }
        
        if(!acctUpdateList.isEmpty()){
            update acctUpdateList;
        }
    }
    
    public static void updateDocumnet(list<echosign_dev1__SIGN_Agreement__c> listechosigndevSIGNAgreement){
        map<ID,echosign_dev1__SIGN_Agreement__c> mapAgreement = new map<ID,echosign_dev1__SIGN_Agreement__c>();
        //CRYSTAL - UPDATED TO LOWER SOQL COUNT
        //Recordtype objrecordtype = [Select id from Recordtype where Name='Lease Contract' and SobjectType='echosign_dev1__SIGN_Agreement__c' limit 1];
        
        for(echosign_dev1__SIGN_Agreement__c objAgreement : listechosigndevSIGNAgreement){
            //if(objAgreement.Opportunity__c != null && objAgreement.recordtypeid == objrecordtype.id)
            if(objAgreement.Opportunity__c != null && objAgreement.recordtypeid == leaseContractRecTypeId)
                mapAgreement.put(objAgreement.Opportunity__c , objAgreement);
        }
        
        if(mapAgreement.isEmpty()) return;
        
        list<TPSSF__Document__c> listDocument = new list<TPSSF__Document__c>();
        for(TPSSF__Document__c objDocument: [Select id,Opportunity__c from TPSSF__Document__c where Opportunity__c IN : mapAgreement.keySet()]){
            objDocument.Agreement_Status__c = mapAgreement.get(objDocument.Opportunity__c).echosign_dev1__Status__c;
            listDocument.add(objDocument);
        }
        if(!listDocument.isEmpty())
            update listDocument;
    }
    public static void updateDocumnetDeletedAgreement(list<echosign_dev1__SIGN_Agreement__c> listechosigndevSIGNAgreement){
        set<ID> setOpportunityID = new set<ID>();
        //CRYSTAL - UPDATED TO LOWER SOQL COUNT
        //Recordtype objrecordtype = [Select id from Recordtype where Name='Lease Contract' and SobjectType='echosign_dev1__SIGN_Agreement__c' limit 1];
        for(echosign_dev1__SIGN_Agreement__c objAgreement : listechosigndevSIGNAgreement){
            //if(objAgreement.Opportunity__c != null && objAgreement.recordtypeid == objrecordtype.id)
            if(objAgreement.Opportunity__c != null && objAgreement.RecordTypeId == leaseContractRecTypeId)
                setOpportunityID.add(objAgreement.Opportunity__c);
        }
        list<TPSSF__Document__c> listDocument = new list<TPSSF__Document__c>();
        for(TPSSF__Document__c objDocument: [Select id,Opportunity__c from TPSSF__Document__c where Opportunity__c IN : setOpportunityID]){
            objDocument.Agreement_Status__c = 'Deleted';
            listDocument.add(objDocument);
        }
        if(!listDocument.isEmpty())
            update listDocument;
        
    }
    
    
    
}