objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Authorized_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field allows access for a specific dealer user to place orders via the online-order process in Salesforce. The dealer account also needs to be enabled for online ordering.</description>
        <label>Authorized to Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications. Used for both SunPower and Partner Users. For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-us</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Oracle Item Description</description>
        <label>Description</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications.  Used for both SunPower and Partner Users.  For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>rvar-us</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-jp</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Edit_Partner_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Edit Partner Users</description>
        <label>Edit Partner Users</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Warranty_Registration__c.object
<CustomObject>
    <description>Warranty Registration Object represent warranty.</description>
    <fields>
        <fullName>Customer_SFDC_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Warranty_Registrations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Partner_SFDC_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Warranty_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Warranty Registration</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranty Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_FDS_Product__c.object
<CustomObject>
    <description>This being used in online warranty registration and is replica of FDS products.</description>
    <fields>
        <fullName>Converted_To_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted To Asset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <label>Dealer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>WR_FDS_Products</relationshipLabel>
        <relationshipName>WR_FDS_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Packing Slip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <externalId>true</externalId>
        <label>Serial Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <formula>Text(WR_ORACLE_SalesOrder__r.Partner_Account__r.Theater__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theater</label>
        <type>Text</type>
    </fields>
    <label>WR_FDS_Product</label>
    <nameField>
        <displayFormat>Product - {0000}</displayFormat>
        <label>WR_FDS_Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_FDS_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_Line_Item__c.object
<CustomObject>
    <description>Junction Object with Warranty_Registration and WR_FDS_Product .</description>
    <fields>
        <fullName>AssetID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Name</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>WR_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>WR_FDS_Product__r.Serial_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WR_FDS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_FDS_Product</label>
        <referenceTo>WR_FDS_Product__c</referenceTo>
        <relationshipName>WR_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty_Registration__c</fullName>
        <label>Warranty_Registration</label>
        <referenceTo>Warranty_Registration__c</referenceTo>
        <relationshipName>WR_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WR Line Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>WR Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WR_StagingSelection__c.object
<CustomObject>
    <description>Staging table for user selection rough work on Installation Data Tab of  Online Warranty Registration.</description>
    <fields>
        <fullName>WR_FDS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_FDS_Product</label>
        <referenceTo>WR_FDS_Product__c</referenceTo>
        <relationshipLabel>WR_StagingSelections</relationshipLabel>
        <relationshipName>WR_StagingSelections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WR_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR Line Item</label>
        <referenceTo>WR_Line_Item__c</referenceTo>
        <relationshipLabel>WR_StagingSelections</relationshipLabel>
        <relationshipName>WR_StagingSelections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty_Registration__c</fullName>
        <label>Warranty Registration</label>
        <referenceTo>Warranty_Registration__c</referenceTo>
        <relationshipLabel>WR_StagingSelections</relationshipLabel>
        <relationshipName>WR_StagingSelections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WR_StagingSelection</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>WR_ProductSelectionStaging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_StagingSelections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WR_CreateAssetsBatch_Test.cls
/* Test functionality of WR_CreateAssetsBatch batch class 

  @Author Anjali Khandelwal
*/
@isTest
private class WR_CreateAssetsBatch_Test {

    static testMethod void testWR_CreateAssetsBatch() {
        Account acct = getEUItalyPartnerAccount();
        User test_user =getPartnerPortalUser(acct); 
        System.runAs(test_user){ 
        
              
            acct = test_user.Contact.Account;
            Date edt = System.today();
            
            
            //Insert List of customer in database
            Account customer1 = new Account(Name='DummyCustomerAcc1',CurrencyIsoCode='EUR',Theater__c='Europe',BillingCity='testCity',BillingCountry='Italy',BillingStreet='testStreet',BillingPostalCode='testZipCode',Country_Domain__c = 'combo-it');
            insert customer1;
            //test.startTest();
            List<Warranty_Registration__c> wrList = new List<Warranty_Registration__c>();
            Warranty_Registration__c wrc_test1;
            wrc_test1 = new Warranty_Registration__c(Delivery_Date__c=edt,Partner_SFDC_ID__c=acct.Id,Customer_SFDC_ID__c=customer1.Id,status__c = 'Draft');    
            wrList.add(wrc_test1);
            wrc_test1 = new Warranty_Registration__c(Delivery_Date__c=edt,Partner_SFDC_ID__c=acct.Id,Customer_SFDC_ID__c=customer1.Id,status__c = 'Completed');    
            wrList.add(wrc_test1);
            insert wrList;
            Set<Id> wrIds = new Set<Id>();
            for(Warranty_Registration__c wr : wrList){
                wrIds.adD(wr.Id);
            }
            Test.startTest();
            createTestData(wrList);
            
            
            WR_CreateAssetsBatch job = new WR_CreateAssetsBatch(wrIds);
            ID batchprocessid = Database.executeBatch(job);
            //Database.executeBatch(job,200);
            Test.stopTest();
            
            //Staging data will be deleted for completed warranty
            List<WR_StagingSelection__c> stagingList = new List<WR_StagingSelection__c>();
            for(WR_StagingSelection__c staging : [Select id from WR_StagingSelection__c where Warranty_Registration__c =: wrList[1].Id]){
                stagingList.add(staging);
            }
            system.assertEquals(stagingList.size(),0);
            
            //converted_to_asset__c will be true for completed warranty
            //Asset will be created for completed warranty
            for(WR_Line_Item__c lineItem : [Select id, AssetID__c, Wr_FDS_Product__r.converted_to_asset__c from WR_Line_Item__c where Warranty_Registration__c =: wrList[1].Id]){
                system.assert(lineItem.AssetID__c != null);
                system.assertEquals(lineItem.Wr_FDS_Product__r.converted_to_asset__c, true);
            }
            
            //converted_to_asset__c will be false for drafted warranty
            //Asset will be deleted for drafted warranty
            for(WR_Line_Item__c lineItem : [Select id, AssetID__c, Wr_FDS_Product__r.converted_to_asset__c from WR_Line_Item__c where Warranty_Registration__c =: wrList[0].Id]){
                system.assert(lineItem.AssetID__c == null);
                system.assertEquals(lineItem.Wr_FDS_Product__r.converted_to_asset__c, false);
            }
        }
    }
    
    //Create Partner Portal user
     private static User getPartnerPortalUser(Account acct){
        User user = null;   
           
        if(acct == null){
            acct =  getEUItalyPartnerAccount();
        }
        Contact cont = new Contact(AccountID = acct.id,FirstName='testconbyPO2',LastName='testconbyPO2');
        cont.Email ='te@test.com';
        cont.Authorized_to_Order__c = true;
        cont.RecordTypeID = util.GetRecordTypeIdsByDeveloperName(Contact.SObjectType).get('Partner'); //MAM 19.MAY.2015 Get Contact Partner RecordTypeId
        insert cont;
                
       // User user = [Select id from user where id =: userInfo.getUserId()];  
        String username ='anjalitest@test1.com';      
        user = new User(LastName = 'Hello222'+String.ValueOf(DateTime.Now()) ,FirstName = 'W'+ String.ValueOf(DateTime.Now()));
        user.ContactId = cont.Id;
        user.Username = username;
        user.Alias = 'anjali';
        user.CommunityNickname = username.subString(0,7);
        user.TimeZoneSidKey = 'America/Los_Angeles';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US'; 
        user.Email = cont.Email;
        user.LocaleSidKey = 'en_US';    
        user.Edit_Partner_Users__c = true;
        List<Profile> lstProfile = [select Id from Profile where Name = 'EU Partner Delegated Administrator'];
        if(lstProfile.Size()>0){
            user.ProfileId = lstProfile[0].Id;
            insert user;
        }
        if(user.Id != null)
          for(User u:[select id,Name,contactId,Contact.AccountID, Contact.Account.AccountNumber,Contact.Account.CurrencyIsoCode,Contact.Account.Name,Contact.Account.Country_Domain__c,Contact.Account.Theater__c,Contact.Account.ShippingStreet,Contact.Account.ShippingState,Contact.Account.ShippingCity,Contact.Account.ShippingCountry,Contact.Account.ShippingPostalCode,Contact.Account.Oracle_Operating_Unit__c, Contact.Account.Oracle_Account_Number__c from User where id =:user.ID LIMIT 1])
            user = u; 
        return user;
        
    }
    
    static void createTestData(List<Warranty_Registration__c> wrList){
      
         // creating Customer Account 
        Account customer = new Account(); 
        customer.Name = 'testCustomer';
        customer.BillingCity = 'jaipur';
        customer.BillingState = 'Rajasthan';
        customer.BillingPostalCode = '302021';
        customer.BillingCountry = 'India';
        customer.BillingStreet = 'test streat1';
        customer.Status__c = 'Active';
        customer.Type = 'Home Owner';
        insert customer; 
        // create Item
         Item__c item =  new Item__c();
         item.Description__c = 'PVM, testDesc';
         item.Item_ID__c = 'testItem_ID';
         insert item;
         
        // create Asset
         Asset asset =  new Asset();
         asset.AccountId = customer.id;
         asset.SerialNumber = 'G20J01297002-test'; 
         asset.Name = 'SPR-225-WHT-I N';
         asset.Item__c = item.Id;
         insert asset;
         // WR_FDS_Products
         
         List<WR_FDS_Product__c> products = new List<WR_FDS_Product__c>();
         WR_FDS_Product__c product;
         for(Integer i = 0;i< 5 ;i++){
             product = new WR_FDS_Product__c();
             product.Serial_Number__c = 'G20J01297002-testClsDummy'+i;
             product.Dealer_Name__c = 'test dealer name';
             product.Packing_Slip__c = 'TEST-59011801';
             product.Product_Name__c = 'testDesc';
             product.Converted_To_Asset__c = false;
             products.add(product);
         }
         products[0].Converted_To_Asset__c = true;
         products[1].Converted_To_Asset__c = true;
         products[4].Converted_To_Asset__c = true;
         insert products; 
         
         
         List<WR_Line_Item__c> lstWrLnItem = new List<WR_Line_Item__c>(); 
         WR_Line_Item__c wrLnItem1 = new WR_Line_Item__c(WR_FDS_Product__c = products.get(0).Id,Warranty_Registration__c = wrList[0].Id, AssetID__c = asset.Id);
         lstWrLnItem.add(wrLnItem1);
         wrLnItem1 = new WR_Line_Item__c(WR_FDS_Product__c = products.get(1).Id,Warranty_Registration__c = wrList[0].Id);
         lstWrLnItem.add(wrLnItem1);
         wrLnItem1 = new WR_Line_Item__c(WR_FDS_Product__c = products.get(2).Id,Warranty_Registration__c = wrList[1].Id);
         lstWrLnItem.add(wrLnItem1);
         wrLnItem1 = new WR_Line_Item__c(WR_FDS_Product__c = products.get(3).Id,Warranty_Registration__c = wrList[1].Id);
         lstWrLnItem.add(wrLnItem1);
         wrLnItem1 = new WR_Line_Item__c(WR_FDS_Product__c = products.get(4).Id,Warranty_Registration__c = wrList[0].Id);
         lstWrLnItem.add(wrLnItem1);
         insert lstWrLnItem;
         
         List<WR_StagingSelection__c> stagingList = new List<WR_StagingSelection__c>();
         WR_StagingSelection__c staging = new WR_StagingSelection__c(Warranty_Registration__c = wrList[0].Id);
         stagingList.adD(staging);
         staging = new WR_StagingSelection__c(Warranty_Registration__c = wrList[1].Id);
         stagingList.adD(staging);
         insert stagingList;   
         
    }
    
    /*
        Create Partner Account(Customer) of Italy
    */
    private static Account getEUItalyPartnerAccount(){
        String recType ='';
        for(RecordType r:[select id,Name from RecordType where sObjectType ='Account' and name ='Partner' LIMIT 1])
             recType = r.ID;             
        Account acct = new Account(name='test2'+String.valueOf(DateTime.now().getTime()),recordTypeID=recType);
        acct.ShippingCity = 'Jaipur';
        acct.ShippingStreet = 'Sitapura';
        acct.ShippingCountry = 'Italy';
        acct.ShippingState='Rajasthan';
        acct.ShippingPostalCode ='302020';
        acct.BillingCity = 'Jaipur';
        acct.BillingStreet = 'Sitapura';
        acct.BillingCountry = 'Italy';
        acct.BillingState='Rajasthan';
        acct.BillingPostalCode ='302020';
        acct.Online_Order_Access__c = true;
        acct.Oracle_Account_Number__c = 'test_oracle2';
        acct.Theater__c = 'Europe';
        acct.CurrencyIsoCode='EUR';
        acct.Country_Domain__c = 'combo-it';
        acct.Territory__c = 'Italy';
        acct.Type = 'Partner';
        //acct.OwnerId = WR_Opportunity_Assigned_Owner__c.getInstance('OpportunityOwner').Opportunity_Owner_ID__c; 
        insert acct;
        return acct;                     
    }            
}