objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Include_in_Lease_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Coach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No influence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Buyer</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contractors_License__c</fullName>
        <formula>IF($User.Quote_Creation_Allowed__c,

IF(Account__r.Business_Registration__c!=null,
IF(Account__r.Business_Registration__r.Is_License_Valid__c,&apos;Y&apos;,&apos;N&apos;),

IF(DATEVALUE(Account__r.CreatedDate) &gt;= $Setup.Multi_State_Settings__c.Go_Live_Date__c,
&apos;N&apos;,
&apos;Y&apos;)),



&apos;N&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contractors License #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Modified__c</fullName>
        <description>This field reflects the date quote was locked. This is used in the Sales tax formula calculation for booking template.</description>
        <label>Date Modified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Doc_out_for_signature__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Doc out for signature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_Partner__c</fullName>
        <formula>IF(  Account__r.Partner_Account__r.Lease2_0_Program_Partner__c,&apos;Y&apos;,&apos;N&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lease Partner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module_Oracle_Item_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module Oracle Item Number</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Module_Quantity__c</fullName>
        <label>Module Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checks whether Quote is Primary or Not.</description>
        <inlineHelpText>Quote is Primary or Not.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_type__c</fullName>
        <label>XQuote Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quote with Sales Services - First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote with Sales Services - Requote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote with Additional Services- First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote with Additional Services - Requote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP Quote - First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP Quote - Requote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Number Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential Lease Quotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPS Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential New Homes Lease Quotation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Contact_1__c</fullName>
        <label>Temp Contact 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Contact_2__c</fullName>
        <label>Temp Contact 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Function__c</fullName>
        <description>GPP-Story1- This field is created for GPP Project. This replaces various checkboxes with one field that will be assigned to a partner user. Based on the values assigned to a user, user will be authorized to perform various activities on the platform. This field will work in conjunction with Corporate Business Functions which will be controlled by SPWR internal users.</description>
        <label>Business Function</label>
        <picklist>
            <picklistValues>
                <fullName>Create Cash Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Lease Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Loan Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Team Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Product SME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Services Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create ManualMode Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Equinox Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aurora Design Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Aurora Design Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create PPA Quote</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Quote_Creation_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quote Creation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GPPNewQuoteButtonTest.cls
/********************************************************************************************
Author : Birlasoft
Usage  : Test Class for GPPNewQuoteButton Controller Class
Edits  :    
        2014-03-20 : 
********************************************************************************************/

@isTest(SeeAllData=True)
public class GPPNewQuoteButtonTest 
{
    private static Id residentialCustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Residential Customer').getRecordTypeId();
    private static Id residentialRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Home Owner').getRecordTypeId(); 
    private static Id customerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId(); 

    static Account newAccount,partnerAccount;
    static Contact newContact,partnerContact1;
    static Opportunity newOpportunity;
    static User partnerUser;
    static Quote objQuote;
    private static Id proposalQuoteRecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Proposal Quote').getRecordTypeId();

    private static user getPartnerUser()
    {   
        Test.startTest();
        UserManagement.IS_TEST = true; 

        String postFix = String.valueOf(Datetime.now().getTime());

        
        partnerAccount = TestUtils.createAccount('TEST_BOOYAH', TestUtils.getPartnerRecordTypeId(), false);
        //make lease enabled partner
        partnerAccount.Lease2_0_Program_Partner__c = true;
        partnerAccount.Oracle_Vendor_Number__c = 'VN'+String.ValueOf(DateTime.Now().getTime()).substring(0, 10)+String.ValueOf(Math.random()).substring(0,10);
        partnerAccount.Oracle_Vendor_Site_Code__c  = 'VSC'+String.ValueOf(DateTime.Now().getTime()).substring(0, 10)+String.ValueOf(Math.random()).substring(0,10);
        partnerAccount.Oracle_Warehouse__c  = 'BWGUY'+String.ValueOf(DateTime.Now().getTime()).substring(0, 10)+String.ValueOf(Math.random()).substring(0,10);
        partnerAccount.Certified__c = true;
        
        //insert partnerAccount;
        list<Account> listAccount = new  list<Account>();
        listAccount.add(partnerAccount);
        
        newAccount = TestUtils.createAccount('TAcc' + postFix, TestUtils.getResidentialRecordTypeId(), false);
        newAccount.Partner_Account__c = partnerAccount.id;
        newAccount.Certified__c = true;
        //insert newAccount;
        listAccount.add(newAccount);
        
        insert listAccount;

        
        
        newContact = TestUtils.createContact('TCon1' + postFix, newAccount.Id, true);
        newOpportunity = TestUtils.createOpportunities(1, newAccount.id, newContact.Id, true).get(0);
        
        Partner objPartnet = new Partner();
        objPartnet.AccountFromId =partnerAccount.id;
        objPartnet.AccountToId =newAccount.id;
        objPartnet.Role ='Installer';
        //objPartnet.OpportunityId = newOpportunity.id;
        insert objPartnet;
        
                                             
        
        objQuote=new Quote(Name='TQuote1'+postFix, RecordTypeId=proposalQuoteRecordTypeId, OpportunityId=newOpportunity.ID);
        insert objQuote;

   /*
        partnerContact = TestUtils.createContact( 'PartnerConTest', partnerAccount.Id, false );
       // partnerContact.Business_Function__c='Lease';
        partnerContact1 = TestUtils.createContact( 'PartnerConTest1', partnerAccount.Id, false );
        //partnerContact1.Business_Function__c='Cash';
        partnerContact1.Email=System.now().getTime()+'test1@test.com';
        partnerContact1.Phone='999-888-7770';
        list<Contact> listConatc = new list<Contact>();
        listConatc.add(partnerContact);
        listConatc.add(partnerContact1);
        //insert partnerContact; 
        //insert partnerContact1;
        insert listConatc;*/
        Test.stopTest();

        partnerUser = TestUtils.createPartnerPortalUser( newContact, false );
        partnerUser.ContactId=newContact.ID;
        partnerUser.isActive=true;
        partnerUser.Quote_Creation_Allowed__c=true;
        partnerUser.Business_Function__c='Create Lease Quote';
        return partnerUser;

    }
    public static testMethod void testGPPNewQuoteButton() 
    {
        
        partnerUser = getPartnerUser();
        String postFix = String.valueOf(Datetime.now().getTime());


       
            /*
        Account acc=new Account(Name='AccGppVFTest',RecordTypeID=residentialCustomerRecordTypeId,Status__c='Active',Theater__c='North America'
        ,BillingStreet='1010 State Street Atherton',BillingCity='Atherton',BillingState='CA',BillingPostalCode='94025',BillingCountry='Unied States');
        Insert acc;*/

        /*


        Contact con1=new Contact(FirstName='Con1',LastName='GppVFTest',RecordTypeID=customerRecordTypeId,Email='amit.test@birlasoft.com',Primary__c=true,Role__c='Technical Buyer',Include_in_Lease_Doc__c=true,MailingStreet='1010 State Street',MailingCity='Atherton',MailingState='CA',MailingPostalCode='94025',MailingCountry='United States');
        insert con1;
 
        Opportunity opp=new Opportunity(Name='OppGppVFTest',RecordTypeID=residentialRecordTypeId,AccountID=partnerAccount.id,StageName='10% - Qualified Opportunity',CloseDate=System.Today());
        insert opp;
        
        Quote  newQuote = TestUtils.createQuotes( 1, 'Quick Quote Test ', opp.Id, false).get(0);

     //newQuote.Module_Oracle_Item_Number__c = item1.Id;
      newQuote.Module_Quantity__c = 32;
      newQuote.Date_Modified__c = System.today()+30;
      //newQuote.Contractors_License__c= 'Y';
      //newQuote.Lease_Partner__c='Y';
      newQuote.Doc_out_for_signature__c= false;
      newQuote.Quote_type__c = 'Residential Lease Quotation';
      newQuote.Account__c = partnerAccount.id;
      newQuote.Is_Locked__c = true;
      newQuote.Temp_Contact_1__c ='Test';
      newQuote.Temp_Contact_2__c='Test';
      insert newQuote;*/

        PageReference pageRef = Page.GPPNewQuoteButton;
        pageRef.getParameters().put('acc', newAccount.ID);
        pageRef.getParameters().put('opp', newOpportunity.ID);
        pageRef.getParameters().put('own', partnerUser.ID);
        
        objQuote=new Quote(Name='TQuote1'+postFix, RecordTypeId=proposalQuoteRecordTypeId, OpportunityId=newOpportunity.ID);
        insert objQuote;

        pageRef.getParameters().put('quoteid', objQuote.id);
        

                                    
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.standardController(newOpportunity);
        GPPNewQuoteButton controller = new GPPNewQuoteButton(sc);
        String nextPage;// = controller.NewQuoteInit().getUrl();

        // Verify that page fails without parameters
        //System.assertEquals('http://gpp.cloudapp.net:8180/dealers-portal/auth/authentication-ui.html', nextPage);
     
        // Instantiate a new controller with all parameters in the page
        //controller = new GPPNewQuoteButton();
        //nextPage = controller.NewQuoteInit().getUrl();
        controller.NewQuoteInit();
        controller.GPPInstallerSelectionInit();
        controller.getInstallPartners();
        controller.cancel();
        controller.ChangeSelection();
        controller.submit();
        
        
        //controller.CreateQuoteHeader(acc.id,'invalidID','invalidID');
        // Verify that the success page displays
        //System.assertEquals('/apex/success', nextPage);
        

        
    }
}