objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Best_Time_to_Call__c</fullName>
        <label>Best Time to Call</label>
        <picklist>
            <picklistValues>
                <fullName>08:00am - 09:00am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09:00am - 10:00am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00am - 11:00am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00am - 12:00pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00pm - 01:00pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:00pm - 02:00pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:00pm - 03:00pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:00pm - 04:00pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:00pm - 05:00pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:00pm - 06:00pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:00pm - 07:00pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:00pm - 08:00pm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Language__c</fullName>
        <description>comes on Lead conversion</description>
        <label>Contact Language</label>
        <picklist>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DisplayContactsController.cls
/**************************************************
** Case - 00011814
**Created By- Kapil Goutam
**Created On- Nov 10 2009
**Last Modified- 
**Last Modified On-   
**Desciption- This controller class is load all contact records on the basis of Account in a opportunity.
*****************************************************/ 

public class DisplayContactsController{

public List<Contact> contacts {get;set;}
public boolean isRecordFound{get;set;}
public Account account{get;set;}
public String labelMessage {get;set;}
public Boolean accountRendered {get;set;}
public Boolean isPartner {get;set;}
public DisplayContactsController(){
    isRecordFound = false;
    accountRendered  = false;
    //Case#00087597
    isPartner = false;  
    if(userInfo.getUserType()== 'PowerPartner'){
        isPartner = true;
    }
    
    List<Opportunity> opportunities = [select accountId,account.IsPersonAccount,account.RecordType.Name, account.BillingStreet, account.BillingState, account.BillingPostalCode, account.BillingCountry, account.BillingCity,account.Phone from opportunity where Id =:ApexPages.currentPage().getParameters().get('Id')];
    List<String> accountIds = new List<String>();
    
    for(Opportunity opportunity : opportunities){
        if(opportunity .accountId != null&&(opportunity.account.RecordType.Name.equals('Residential Customer')||opportunity.account.RecordType.Name.equals('Commercial Customer'))){
            accountIds.add(opportunity.accountId);
        }
    }
    if(accountIds.size()>0){
        if(opportunities.size()>0){
            account = opportunities.get(0).account;
        }else{
            account = new Account();
        }
        accountRendered = true;
        contacts = loadContacts(accountIds);
        if(contacts!= null && contacts.size()>0)
              isRecordFound = true;
        else{
            labelMessage = System.Label.DisplayContactNoRecordFound;
        }
    }else{
        labelMessage = System.Label.DisplayContactPartnerAccountMsg;
    }
                 
}

public DisplayContactsController(ApexPages.StandardController stdController){      
    isRecordFound = false;
    accountRendered  = false;    
    //Case#00087597
    isPartner = false;  
    if(userInfo.getUserType()== 'PowerPartner'){
        isPartner = true;
    }
    
    List<Opportunity> opportunities = [select accountId,account.IsPersonAccount,account.RecordType.Name, account.BillingStreet, account.BillingState, account.BillingPostalCode, account.BillingCountry, account.BillingCity,account.Phone from opportunity where Id =:ApexPages.currentPage().getParameters().get('Id')];
    List<String> accountIds = new List<String>();
    
    for(Opportunity opportunity : opportunities){
        if(opportunity .accountId != null&&(opportunity.account.RecordType.Name.equals('Residential Customer')||opportunity.account.RecordType.Name.equals('Commercial Customer'))){
            accountIds.add(opportunity.accountId);
        }
    }
    if(accountIds.size()>0){
        if(opportunities.size()>0){
            account = opportunities.get(0).account;
        }else{
            account = new Account();
        }
        accountRendered = true;
        contacts = loadContacts(accountIds);
        if(contacts!= null && contacts.size()>0)
              isRecordFound = true;
        else{
            labelMessage = System.Label.DisplayContactNoRecordFound;
        }
    }else{
        labelMessage = System.Label.DisplayContactPartnerAccountMsg;
    } 
}


public List<Contact> loadContacts(List<String> accountIdList){
    List<String> recordTypeList = new List<String>();
    recordTypeList.add('Residential Customer');
    recordTypeList.add('Commercial Customer') ;
    //Added field mobilePhone for case 00100955
    List<Contact> contactList = [select Id,Name,Title,Email,Phone,Best_Time_to_Call__c,mobilePhone, Contact_Language__c from Contact where accountId in :accountIdList and account.RecordType.Name  in :recordTypeList  limit 100];
    return contactList;
}
}