objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications. Used for both SunPower and Partner Users. For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-us</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Site__c.object
<CustomObject>
    <description>Used in Inspection Report functionality.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Contact_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Site</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Contact Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Inspection__c.object
<CustomObject>
    <description>Inspections information, all inspections will be related to a case as a parent object.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup User of type Inspector</description>
        <label>Inspector</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Inspection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications.  Used for both SunPower and Partner Users.  For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>rvar-us</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-jp</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestInspectionReportExtension_Refactor.cls
/**************************************************
**Created By- Harsh Mathur
**Created On- July 22 2009
**Last Modified- 
**Last Modified On-   
**Desciption- Test class for class InspectionReportExtension_Refactor
*****************************************************/
public class TestInspectionReportExtension_Refactor{
  
  @isTest
  public static void checkInspectionReportExtension_Refactor(){   
       //Create Account
       Test.startTest();
        Account acct = new Account(name= 'te2221' + String.ValueOf(DateTime.Now()));
        acct.Country_Domain__c = 'rvar-es';
        acct.Type ='Commercial';
        acct.billingCity = 'TestCity';
        acct.BillingCountry = 'TestCountry';
        acct.BillingPostalCode = '12345';
        acct.BillingState = 'TestState';
        acct.BillingStreet = 'TestStreet';
        
        acct.ShippingCity = 'TestCity';
        acct.ShippingCountry = 'TestCountry';
        acct.ShippingPostalCode = '12345';
        acct.ShippingState = 'TestState';
        acct.ShippingStreet = 'TestStreet';
        insert acct;
        //create contact
        Contact con = new Contact();
        con.LastName = 'Test Contact-'+ String.valueOf(DateTime.Now());        
        con.accountID= acct.id;
        con.email='TestInspec@rr.com';
        insert con;
        Test.stopTest();
        //Create sp_site__c
        //SP_Site__c spSite = new SP_Site__c();
        //insert spSite;
        //insert contact site relation
        //Contact_site__c conSite = new contact_site__c(Contact__c=con.id);
        //insert conSite;
        //Create user
        /*String username ='h10101@world.com';
        User user = new User(LastName = 'Hello2221'+String.ValueOf(DateTime.Now()) ,FirstName = 'W'+         String.ValueOf(DateTime.Now()));
        user.ContactId = con.Id;
        user.Username = username;
        user.Alias = 'yoo12322';
        user.Country_Domain__c = 'rvar-it';
        user.CommunityNickname = username.subString(0,7);
        user.TimeZoneSidKey = 'America/Los_Angeles';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.Email = con.Email;
        user.LocaleSidKey = 'en_US';
        Test.startTest();
        List<Profile> lstProfile = [select Id from Profile where Name = 'EU Partner Sales'];
        if(lstProfile.Size()>0){
            user.ProfileId = lstProfile[0].Id;
            insert user;
        }
        Test.stopTest();*/
        //Create Case
        List<RecordType> lstRecordType = new List<RecordType>([Select Id from RecordType where DeveloperName ='Case_Inspection_Audit']);//for Case#00078518
        Case newCase = new Case(AccountID=acct.id,Partner_Account__c=acct.id);
        if(lstRecordType.size()>0)
            newCase.RecordTypeId = lstRecordType.get(0).Id;
        insert newCase;
                
        
        //Create inspection
        Inspection__c newInspection = new Inspection__c(case__c = newCase.id,Contact__c=userinfo.getUserid());
        insert newInspection;
                        
        //Assign query parameters
        ApexPages.currentPage().getParameters().put('siteType','Residential');
        ApexPages.currentPage().getParameters().put('isEdit','true');        
        

        //Call costructor without id & caseid
        InspectionReportExtension_Refactor obj = new InspectionReportExtension_Refactor(new ApexPages.standardController(new inspection__c()));
        obj.createCaseonImageUpload();
        //objInspection.save();
        
        //Call costructor without id & with caseid
        ApexPages.currentPage().getParameters().put('caseid',newCase.id);
        InspectionReportExtension_Refactor obj1 = new InspectionReportExtension_Refactor(new ApexPages.standardController(new inspection__c()));       
        obj1.save();
        obj1.cancelInspection(); 
        
        //Call costructor with id & caseid        
        ApexPages.currentPage().getParameters().put('id',newInspection.id);
        InspectionReportExtension_Refactor objInspection = new InspectionReportExtension_Refactor(new ApexPages.standardController(new inspection__c()));
        objInspection.getSiteType();
        objInspection.getResponseOptionType();
        objInspection.isExistingSharing();
        objInspection.onSeletionOfInspectionType();
        objInspection.selectedSiteType = 'Commercial';
        objInspection.onSeletionOfSiteType();
        objInspection.refreshSiteByName();
        //objInspection.selectedSiteId = spSite.id;
        objInspection.refreshSite();
        objInspection.refreshInspectorByName();
        objInspection.selectedInspectorId = con.id;
        objInspection.refreshInspector();
        objInspection.refreshJobSupervisorByName();
        objInspection.selectedJobSupervisorId = con.id;
        objInspection.refreshJobSupervisor();
        objInspection.refreshScore();
        objInspection.printResidential();
        objInspection.printCommercial();
        //objInspection.ShareObject();
        objInspection.site_ContactID = con.id;
        try{
        Inspection__Share sh = new Inspection__Share();
        sh.UserOrGroupId = newInspection.Contact__c; 
        sh.ParentID =newInspection.id ;
        sh.AccessLevel = 'Read';
        insert sh;
        
        objInspection.save();
        }
        catch(Exception ex){}
        //objInspection.QuickSave(); 
        objInspection.cancelInspection();       
  }
}