objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Authorized_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field allows access for a specific dealer user to place orders via the online-order process in Salesforce. The dealer account also needs to be enabled for online ordering.</description>
        <label>Authorized to Order</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Systems</fullName>
        <active>true</active>
        <label>Systems</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Lease__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <label>Sales Type</label>
        <picklist>
            <picklistValues>
                <fullName>Third Party Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Partner PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EditOrderOverrideController.cls
public with sharing class EditOrderOverrideController {
    private ApexPages.StandardController stdCnt {get;set;}
    private Purchase_Order__c purchaseOrder {get;set;}
    public Boolean isPartnerUser {get;set;}
    public static String POID_KEY = 'POID';
    private User currUser {get;set;}
    
    public EditOrderOverrideController( ApexPages.StandardController stdCnt ) {
        
        this.stdCnt = stdCnt;
        this.purchaseOrder = (Purchase_Order__c)stdCnt.getRecord();
        this.isPartnerUser = [SELECT Id, IsPortalEnabled FROM User WHERE Id = :UserInfo.getUserId()].IsPortalEnabled;
        currUser = [SELECT Profile.Name, ContactId, Contact.AccountId, Contact.Authorized_to_Order__c, Contact.Account.Online_Order_Access__c
                   FROM User WHERE Id =: UserInfo.getUserId()]; 
    }
    
    public PageReference redirect() {
        
        PageReference orderPage;
        System.debug(purchaseOrder.Lease__c + ' ' + purchaseOrder.Id);
        if(currUser.ContactId == null || currUser.Contact.AccountId == null 
           || currUser.Contact.Authorized_to_Order__c == false || currUser.Contact.Account.Online_Order_Access__c == false) {
               
               if(isPartnerUser) {
                   orderPage = Page.SPCommunityOrderErrors;
                   orderPage.setRedirect(true);
                   return orderPage;
               } else {
                   if (purchaseOrder.Lease__c == TRUE || purchaseOrder.Sales_Type__c == 'Loan'){//cdevarapalli Loan Backend
                       orderPage = Page.LeaseOrderWizard;
                       orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                       orderPage.setRedirect(true);
                       return orderPage;
                   }
                   else if(purchaseOrder.Order_Type__c == null) {
                       orderPage = Page.PurchaseOrderWizard;
                       orderPage.getParameters().put( POID_KEY, purchaseOrder.Id);
                   }
                   else if (purchaseOrder.Order_Type__c != null && purchaseOrder.Order_status__c != 'New') {
                       orderPage = Page.OrderSubmissionDetails;
                       orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                   } else {
                       ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.POWizardAccessPermissionsErrorMsg);
                       ApexPages.addMessage(errorMsg); 
                       return null;
                   }
                   orderPage.setRedirect(true);
                   return orderPage;
               }
           }
        else {            
            if(currUser.Profile.Name != null && currUser.Profile.Name.startsWith('AU')) {
                if ( purchaseOrder.Lease__c == null || purchaseOrder.Lease__c == false ){
                    orderPage = Page.PurchaseOrderWizard;
                    orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                }
                else {
                    orderPage = Page.LeaseOrderWizard;
                    orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                }
            }
            else if(Userinfo.getLocale() != 'en_US') {
                if (purchaseOrder.Order_Type__c != null && purchaseOrder.Order_Status__c != 'New'){
                    orderPage = Page.EMEAOrderSubmissionDetails;
                    orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                }
                else if (purchaseOrder.Order_Type__c == null && purchaseOrder.Order_Status__c != 'New' && !String.isBlank(purchaseOrder.Order_Status__c)){
                    orderPage = Page.PurchaseOrderWizard;
                    orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );                
                }
                else{
                    orderPage = Page.EMEAAlaCartePage;
                    orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                }
            }
            
            else if (purchaseOrder.Order_Type__c != null && purchaseOrder.Order_status__c != 'New') {
                orderPage = Page.OrderSubmissionDetails;
                orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
            }
            //else if (purchaseOrder.Order_Type__c != null && purchaseOrder.Order_status__c != 'Submitted'){// only cash order redesign uses Order_type__c field and populates with single/multi systems
            else if(purchaseOrder.Order_Type__c != null && purchaseOrder.Order_Status__c == 'New') {
                orderPage = Page.OrderShipping;
                if(purchaseOrder.Id != null)
                    orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                
            } else {
                
                if ( (purchaseOrder.Lease__c == null || purchaseOrder.Lease__c == false) && purchaseOrder.Sales_Type__c!='Loan'){//cdevarapalli Loan Backend
                    if(purchaseOrder.Id != null)
                        orderPage = Page.PurchaseOrderWizard;
                    else
                        orderPage = Page.OrderTypeSelection;
                    orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                }
                
                else if(purchaseOrder.Lease__c == true || purchaseOrder.Sales_Type__c=='Loan'){//cdevarapalli Loan Backend
                    orderPage = Page.LeaseOrderWizard;
                    orderPage.getParameters().put( POID_KEY, purchaseOrder.Id );
                }
            }
        }
            
        orderPage.setRedirect(true);
        return orderPage;
    }
}