objects/Cost_Matrix__c.object
<CustomObject>
    <description>Commercial:
Object created to store the EPC Cost matrix used by the PPA Proposal tool
Allows for state by state cost breakdown of BOS Costs (Materials,Labor,etc)
PO: Miltiadis Vratimos
PPA Proposal Project: https://www.pivotaltracker.com/epic/show/3273633
Target Release: WW21-24</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Denotes if the Technology System is quotable</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_Technology_Systems__c</fullName>
        <label>Available Technology Systems</label>
        <picklist>
            <controllingField>Technology_System_Category__c</controllingField>
            <picklistValues>
                <fullName>G-Helix Tracker V1.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P-Helix Carport V1.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Helix Dual Tilt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Helix Single Tilt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P-Helix Carport V1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P-Helix Carport V1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P-Non-Helix 360S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P-Non-Helix 360D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P-Non-Helix Garage Long Span</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P-Non-Helix Long Span 360</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Technology_System_Category__c</fullName>
        <description>Commercial:
Field created to store the EPC Cost matrix installation type (Technology System) used by the PPA Proposal tool
PO: Miltiadis Vratimos
PPA Proposal Project: https://www.pivotaltracker.com/epic/show/3273633
Target Release: WW21-24</description>
        <label>Technology System Category</label>
        <picklist>
            <picklistValues>
                <fullName>Garage Top Carport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-SPWR Ground Fixed Tilt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helix Carport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helix Tracker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Span Carport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-SPWR Roof Mounted Rail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunPower Carport (Non-Helix)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helix Roof-Single Tilt-P Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helix Roof-Dual Tilt-P Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helix Roof-Single Tilt-E/X Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helix Roof-Dual Tilt-E/X Series</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cost Matrix</label>
    <nameField>
        <displayFormat>BOS-{0000}</displayFormat>
        <label>Cost Matrix Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Matrix</pluralLabel>
    <recordTypes>
        <fullName>PPA</fullName>
        <active>true</active>
        <description>Costs associated to PPA Proposal BOS Costs</description>
        <label>PPA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Design__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Status__c</fullName>
        <label>Dealer Status</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Request in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Exported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site_Information_Form__c</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record Drawings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Exported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Design</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Design__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Design</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Utility_Code__c.object
<CustomObject>
    <description>Case# 00543268 - This object will store utility code and description - Arokia Nathan</description>
    <fields>
        <fullName>State_Code__c</fullName>
        <description>Case# 00543268 - This field will store 2 char state codes - Arokia Nathan</description>
        <label>State Code</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Utility Code</label>
    <nameField>
        <label>Utility Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HelixPPASavingsController_Test.cls
@isTest
private class HelixPPASavingsController_Test {
    
    private static Design__c ppaDesign;
    private static Quote ppaQuote;
    private static Cost_Matrix__c costMatrix;
    private static Product2 product;

    @isTest 
    private static void test_basic_constructor() {
        Test.startTest();
            HelixPPASavingsController controller = new HelixPPASavingsController();
            System.assertNotEquals(null, controller.creditRatingPicklist);
        Test.stopTest();
    }

    @isTest 
    private static void test_basic_constructor_withQuote() {
        
        ppaDesign = TestFactory_Commercial.createDesignRequest(null, null);
        System.assert(ppaDesign != null);
        System.assertNotEquals(ppaDesign.Opportunity__c, null, 'NO Opportunity found on this design');
        System.assertNotEquals(ppaDesign.Site__c, null, 'NO Site found on this design');

        //set PPA Required fields
        TestFactory_Commercial.closeDesignRequest(ppaDesign,true);
        update ppaDesign;
        System.assertEquals(ppaDesign.Status__c, TestFactory_Commercial.designCompleted, ppaDesign.Status__c);
        System.assertEquals(ppaDesign.Dealer_Status__c, TestFactory_Commercial.designDelivered, ppaDesign.Dealer_Status__c);

        Set<String> designIds = new Set<String>();
        designIds.add(ppaDesign.Id);
        ppaQuote = TestFactory_Commercial.createPPAQuoteWithJunctions(designIds, ppaDesign.Opportunity__c);
        System.assertNotEquals(ppaQuote.Id, null, 'PPA QUOTE FAILED TO INSERT');
        
        Test.startTest();

            //init constructor      
            PageReference pageRef = Page.HelixPPA;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('quoteId', ppaQuote.Id);
            ApexPages.currentPage().getParameters().put('opportunityId', ppaDesign.Opportunity__c);
            HelixPPASavingsController controller = new HelixPPASavingsController();

            System.assertNotEquals(null, controller.creditRatingPicklist);

        Test.stopTest();
    }
    
    @isTest static void test_fetch_utility() {
        Test.startTest();

        List<Utility_Code__c> codes = HelixPPASavingsController.fetchUtilityCodes(null);
        System.assert(codes.size() == 0);

        codes = HelixPPASavingsController.fetchUtilityCodes(SmartFactory.DefaultState);
        System.assert(codes.size() == 0);

        Utility_Code__c u = (Utility_Code__c)SmartFactory.createSObject('Utility_Code__c');
        u.State_Code__c = SmartFactory.DefaultState;
        insert u;

        codes = HelixPPASavingsController.fetchUtilityCodes(SmartFactory.DefaultState);
        System.assertEquals(codes.size(), 1);

        Test.stopTest();
    }
    
    @isTest static void test_calculateSavings() {
        costMatrix = TestFactory_Commercial.createCostMatrix(null);
        costMatrix.Technology_System_Category__c = 'Helix Carport';
        costMatrix.Available_Technology_Systems__c = 'P-Helix Carport V1.0';
        costMatrix.Active__c = true;
        insert costMatrix;
        
        ppaDesign = TestFactory_Commercial.createDesignRequest(null, null);
        System.assert(ppaDesign != null);
        System.assertNotEquals(ppaDesign.Opportunity__c, null, 'NO Opportunity found on this design');
        System.assertNotEquals(ppaDesign.Site__c, null, 'NO Site found on this design');
    
        //set PPA Required fields
        TestFactory_Commercial.closeDesignRequest(ppaDesign,true);
        ppaDesign.HelixDesignType__c = 'Helix Carport';
        ppaDesign.Technology_System__c = 'P-Helix Carport V1.0';
        ppaDesign.ModuleTypeandWattage__c = 'SPR-E20-435-COM';
        update ppaDesign;
        System.assertEquals(ppaDesign.Status__c, TestFactory_Commercial.designCompleted, ppaDesign.Status__c);
        System.assertEquals(ppaDesign.Dealer_Status__c, TestFactory_Commercial.designDelivered, ppaDesign.Dealer_Status__c);
    
        Set<String> designIds = new Set<String>();
        designIds.add(ppaDesign.Id);
        ppaQuote = TestFactory_Commercial.createPPAQuoteWithJunctions(designIds, ppaDesign.Opportunity__c);
        System.assertNotEquals(ppaQuote.Id, null, 'PPA QUOTE FAILED TO INSERT');
        
        Loan_Callout_Settings__c setting_1 = new Loan_Callout_Settings__c(Name='FinEng', Username__c='un_1', Password__c='pw_1',
            Endpoint_URL__c='url_1', Client_Secret__c='secret_1');
        insert new List <Loan_Callout_Settings__c>{setting_1};
        
        product = TestFactory_Commercial.createProduct();
        Opportunity oppty_1 = [SELECT Id, Installation_Date__c FROM Opportunity WHERE Id = :ppaQuote.OpportunityId]; 
        integer q = (Math.floor(((oppty_1.Installation_Date__c.Month()-1)/3)+1)).intValue(); 
        String quarter = 'Q' + String.valueOf(q);
        String year = String.valueOf(oppty_1.Installation_Date__c).left(4).right(2);
        product.CurrencyISOCode = 'USD';
        product.Family = 'PV Module';
        product.Name = quarter + year + '-SPR-E20-435-COM';
        insert product;

        Test.setMock(HttpCalloutMock.class, new HelixPPAFinEngHttpCalloutMock());
        Test.startTest();
        
        HelixPPASavingsController.CalculateSavingsRequest request = new HelixPPASavingsController.CalculateSavingsRequest();
        request.quoteId = ppaQuote.Id;
        request.designIdList = new List <String>{ppaDesign.Id};
        request.finEngRequest = new HelixPPAFinEng.Request();
        HelixPPAFinEng.Batch batch_1 = new HelixPPAFinEng.Batch('1');
        batch_1.inputCommand = new HelixPPAFinEng.InputCommand('inputCommand_1');
        batch_1.outputCommand = new HelixPPAFinEng.OutputCommand('outputCommand_1');
        
        request.finEngRequest.batches = new List <HelixPPAFinEng.Batch>{batch_1};
        
        HelixPPASavingsController.CalculateSavingsResponse response = HelixPPASavingsController.calculateSavings(request);
    
        Test.stopTest();
    }

    @isTest static void test_viewProposal() {
        ppaDesign = TestFactory_Commercial.createDesignRequest(null, null);
        System.assert(ppaDesign != null);
        System.assertNotEquals(ppaDesign.Opportunity__c, null, 'NO Opportunity found on this design');
        System.assertNotEquals(ppaDesign.Site__c, null, 'NO Site found on this design');
    
        Set<String> designIds = new Set<String>();
        designIds.add(ppaDesign.Id);
        ppaQuote = TestFactory_Commercial.createPPAQuoteWithJunctions(designIds, ppaDesign.Opportunity__c);
        System.assertNotEquals(ppaQuote.Id, null, 'PPA QUOTE FAILED TO INSERT');

        Test.startTest();
        
        HelixPPAUtil.SavePPARequest request = new HelixPPAUtil.SavePPARequest();
        request.quote = ppaQuote;
        HelixPPAUtil.SavePPAResponse response = HelixPPASavingsController.viewProposal(request);
        system.assertEquals(true, response.isSuccess);
        
        Test.stopTest();
    }

    @isTest static void test_viewDesign() {
        ppaDesign = TestFactory_Commercial.createDesignRequest(null, null);
        System.assert(ppaDesign != null);
        System.assertNotEquals(ppaDesign.Opportunity__c, null, 'NO Opportunity found on this design');
        System.assertNotEquals(ppaDesign.Site__c, null, 'NO Site found on this design');
    
        Set<String> designIds = new Set<String>();
        designIds.add(ppaDesign.Id);
        ppaQuote = TestFactory_Commercial.createPPAQuoteWithJunctions(designIds, ppaDesign.Opportunity__c);
        System.assertNotEquals(ppaQuote.Id, null, 'PPA QUOTE FAILED TO INSERT');

        Test.startTest();
        
        HelixPPAUtil.SavePPARequest request = new HelixPPAUtil.SavePPARequest();
        request.quote = ppaQuote;
        HelixPPAUtil.SavePPAResponse response = HelixPPASavingsController.viewDesign(request);
        system.assertEquals(true, response.isSuccess);
        
        Test.stopTest();
    }

    @isTest static void test_calculateSavings_request_null() {
        Test.setMock(HttpCalloutMock.class, new HelixPPAFinEngHttpCalloutMock());
        Test.startTest();
        
        HelixPPASavingsController.CalculateSavingsRequest request;
        HelixPPASavingsController.CalculateSavingsResponse response = HelixPPASavingsController.calculateSavings(request);
        system.assertEquals(false, response.isSuccess);
    
        Test.stopTest();
    }

    @isTest static void test_calculateSavings_quoteId_null() {
        Test.setMock(HttpCalloutMock.class, new HelixPPAFinEngHttpCalloutMock());
        Test.startTest();
        
        HelixPPASavingsController.CalculateSavingsRequest request = new HelixPPASavingsController.CalculateSavingsRequest();
        request.quoteId = null;
        HelixPPASavingsController.CalculateSavingsResponse response = HelixPPASavingsController.calculateSavings(request);
        system.assertEquals(false, response.isSuccess);
    
        Test.stopTest();
    }
    
}