objects/Country_Reference__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Country Reference</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Country Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DealerGeneral__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Lead_Test_First_Name__c</fullName>
        <description>If the Lead record was a test record then this is what would be its first name.</description>
        <inlineHelpText>If the Lead record was a test record then this is what would be its first name.</inlineHelpText>
        <label>Lead Test First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Dealer General</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <description>Field which contains Dealer ID from Web to Lead.</description>
        <label>Dealer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Contact__c</fullName>
        <label>Event Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Alex Rein</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allen Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arthur de Cordova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beberly Velasquez</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Kelly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bobby Ram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bob Redlinger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bradley Dakake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brad Souza</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bruce Dickinson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline Mead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chad Tady</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chris Baker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chris Giaras</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cynthia Khatib</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daniel Crouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daryl Franks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Froelich</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Larson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dennis Bora</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derek Noble</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dick Lowry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drew Gibbons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ed Smeloff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emily Humphreys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fnan Araia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geoff Wilcox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greg Werner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>James Brown</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Manufacturer__c</fullName>
        <label>Lead Manufacturer</label>
        <picklist>
            <picklistValues>
                <fullName>SunPower</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Team__c</fullName>
        <label>Lead Team</label>
        <picklist>
            <picklistValues>
                <fullName>AE (Account Executive)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSO</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Override_Theater_Assigned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to bypass the Default Theatre Assignment rule</description>
        <label>Override Theater Assigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>In Process - Holding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Lead / Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Customer - Too Expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Customer - Out of Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Not the Homeowner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Insufficient Roof Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Lost - Incomplete Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Lost - No Return Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Lost - Bad Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Lost - Lost to Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Lost - Unresponsive Dealer (AP/EU)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed to other BU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed to other Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Analysing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Customer – Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Customer - Low Electric Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Qualification Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Duplicate Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to Other BU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign New  Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost -Did not want to be contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost -Not Price Competitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost-Not Solar Candidate - Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost-Not Solar Candidate - Low Electric Bill</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SSO_First_Contact_Date_Time__c</fullName>
        <label>SSO First Contact Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Eloqua</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>false</active>
        <businessProcess>SunPower Master Lead Process</businessProcess>
        <description>Light Commercial Leads</description>
        <label>Commercial</label>
    </recordTypes>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <businessProcess>SunPower Residential Leads Process</businessProcess>
        <description>Residential Leads</description>
        <label>Residential</label>
    </recordTypes>
    <recordTypes>
        <fullName>Systems</fullName>
        <active>true</active>
        <businessProcess>SunPower Systems Lead Process</businessProcess>
        <description>Commercial (Large &amp; Light) and UPP (Utility and Power Plant)</description>
        <label>Systems</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Lead_Team__c</fullName>
        <label>Lead Team</label>
        <picklist>
            <picklistValues>
                <fullName>AE (Account Executive)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSO</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LeadBeforeInsertHandler.cls
public with sharing class LeadBeforeInsertHandler extends TriggerHandlerBase
{  
  // -------- Constants --------
  // 
  //private static String STATES = 'AL:AK:AZ:AR:CA:CO:CT:DE:DC:FL:GA:HI:ID:IL:IN:IA:KS:KY:LA:ME:MD:MA:MI:MN:MS:MO:MT:NE:NV:NH:NJ:NM:NY:'
  //          + 'NC:ND:OH:OK:OR:PA:RI:SC:SD:TN:TX:UT:VT:VA:WA:WV:WI:WY';
  
  // -------- Constructor --------
  public LeadBeforeInsertHandler(){}
  
  // -------- Variables --------
  //private ID ResidentialRecordTypeId = SFDCSpecialUtilities.GetRecordTypeIdsByDeveloperName(Lead.SobjectType).get('Residential');
  //private DealerGeneral__c dealerGeneral = DealerGeneral__c.getInstance();
  
  // -------- Properties --------
  // Qualified records for actions
  private Map<Integer, Lead> qualifiedLeads;
  private Set<Integer> setDealerName;
  private set<Integer> theaterAssignment;
  private Set<Integer>eventLead;
  private Set<Integer>teamLead;
  private Set<Integer>    autoconvertLeads;
  private Set<Integer>  eloquaStatusSet;
 private Set<Integer>     leadCalculateCalendarWeekSet;

  
  //---------Sets for queries----
  private Set<ID> accountDealers;
  private Set<String> countries;
  private Set<String> leadEventContactUser;
  private Set<String> leadEventContactQueue;
  private Set<ID>     leadOwnerIdSet;
  private Set<ID>     leadOwnerIdQueueSet;


  private Set<String> emailDupeCheck;
  
  //Dupe check maps
  private Map<String, Integer> dupCheckByEmail;
  
  
  
  // -------- Methods --------
  // Cast and determine qualified records for various field updates
  public override void qualifyStartingRecords(List<sObject> newList, 
    List<sObject> oldList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap)
  {
    Diagnostics.push('LBI qualifyStartingRecords');

   qualifiedLeads       = new Map<Integer, Lead>();
   setDealerName        = new Set<Integer>();
   theaterAssignment    = new Set<integer>();
   eventLead      = new Set<Integer>();
   teamLead        = new Set<Integer>();
   autoconvertLeads    = new Set<Integer>();
   leadCalculateCalendarWeekSet = new Set<Integer>();   
   eloquaStatusSet = new Set<Integer>();//to help with status change inconsistencies
   
   //query sets
   accountDealers       = new Set<ID>();
   countries            = new Set<String>();
   leadEventContactUser = new Set<String>();
   leadEventContactQueue= new Set<String>();
   leadOwnerIdSet       = new Set<ID>();
   leadOwnerIdQueueSet  = new Set<ID>();
   //leadCalculateCalendarWeekSet  = new Set<ID>();   
   
   //dupe map
   dupCheckByEmail = new Map<String, Integer>();
   
    List<Lead> newLeads = (List<Lead>)newList;
    
    //for leadScore

    for(Integer i = 0; i < newLeads.size(); i++)
    {
       Lead l = newLeads[i];
      //qualify leads for business logic
       //if(!(UserInfo.getUserId()=='00580000003XrG4AAK' || UserInfo.getUserId()=='00580000003XtZwAAK' ||UserInfo.getUserId()=='00580000003Xtm2AAC')){
        if(!Util.isSkipTrigger('LeadUpdateLeadScore',null)){    

            Utility_Lead.setFieldsBasedOnLeadValues(l, null);//set fields that do not need queries to other objects
            
            if(l.Dealer_Name__c!=null){
                setDealerName.add(i);
                accountDealers.add(l.Dealer_Name__c);
                qualifiedLeads.put(i, l);
            }
            if(l.Country != null && !l.Override_Theater_Assigned__c){                          
                theaterAssignment.add(i);
                countries.add(l.Country);
                qualifiedLeads.put(i, l);
            } 
            //set team qualification - all leads qualify...TODO - make more efficient    
            /*
            below is the "setTeam" functionality
            if the lead source is an event, we want to set the owner as the event_contact
            event_contact is just a picklist of names so we have to query the user/group table to make the assignment
            */  
            
            /*KCM_02242017: Commented out code and replaced with the line of code that immediately follows; Pivotal #140449385
            if((l.LeadSource=='Event' || l.LeadSource=='Event/Seminar/Webinar')&& l.Event_Contact__c != null && l.Event_Contact__c != ''){
            */            
            if((l.LeadSource == 'Events / Tradeshow' || l.LeadSource == 'Event/Seminar/Webinar') && l.Event_Contact__c != null && l.Event_Contact__c != ''){
                eventLead.add(i);
                qualifiedLeads.put(i, l);
                if(l.Event_Contact__c.contains('Queue')){
                    leadEventContactQueue.add(l.Event_Contact__c);
                }
                else{
                    leadEventContactUser.add(l.Event_Contact__c);
                }
            }
            if(l.Lead_Team__c==null){//need to set the lead team in the trigger. most all leads will qualify
                if(l.OwnerId != null && String.valueOf(l.OwnerId).startsWith('005')){
                    leadOwnerIdSet.add(l.OwnerId);
                    qualifiedLeads.put(i, l);
                }
                else{
                    leadOwnerIdQueueSet.add(l.OwnerId);
                    qualifiedLeads.put(i, l);
                }
            }

            System.debug('----------l.isConverted'+l.isConverted);
            System.debug('----------l.Status'+l.Status);
            System.debug('----------l.RecordTypeId'+l.RecordTypeId);
            System.debug('----------l.Theater__c'+l.Theater__c);
            System.debug('----------l.Source_System__c'+l.Source_System__c);
            //setLead Status qualifiers
            if(((!l.isConverted && l.Status !='Ready for Conversion') 
              && (l.Status == 'Open' || l.Status == 'Marketing Qualified')
              && l.RecordTypeId == utility_Lead.ResidentialRecordTypeId
              && l.FirstName != utility_Lead.dealerGeneral.Lead_Test_First_Name__c
              && (l.Theater__c == 'North America' || l.Theater__c == 'Central America and the Caribbean')
              && l.Lead_Manufacturer__c == 'SunPower'
              ) || (l.RecordTypeId == Utility_Lead.ResidentialRecordTypeId && l.Theater__c == null && l.Source_System__c == 'Eloqua')) {
                 if(util.isSkipTrigger('isLeadALR', null)) {
                     if(Utility_Lead.setAutoConvertLeadFields(l)){
                         eloquaStatusSet.add(i);//will still set status based on eloqua matrix, but if is new Lead ALR, won't automatically convert anymore
                     }
                 } else if(!util.isSkipTrigger('isLeadALR', null)) {
                     if(Utility_Lead.setAutoConvertLeadFieldsSPD(l)) {
                         eloquaStatusSet.add(i);
                     }
                 }
                  if(util.isSkipTrigger('isLeadALR', Utility_Lead.ResidentialRecordTypeId)) {
                      if ( (l.Source_System__c == 'Eloqua' && l.Status == 'Qualified') || (l.Source_System__c != 'Eloqua' && (l.Status == 'Open' || l.Status == 'Marketing Qualified'))){
                          qualifiedLeads.put(i, l);
                          autoConvertLeads.add(i);
                      }
                  }
                    
                  if(l.Email != null && l.Status != 'Disqualified'){
                      if(dupCheckByEmail.ContainsKey(l.Email)){
                          l.Status = 'Disqualified';
                          l.Reason__c = 'Awaiting Duplicate Review';
                      } else {
                          dupCheckByEmail.put(l.Email, i);
                      }
                  }
              }
    //if(l.SSO_First_Contact_Date_Time__c != null){
              qualifiedLeads.put(i, l);
                leadCalculateCalendarWeekSet.add(i);
          //}
        }
    }
  
    Diagnostics.pop();
  }
  // Start processing field changes and assignments
  public override void start()
  {
    if(qualifiedLeads.size()>0){
      for(ID recordTypeId: LeadManagement.idToLeadRecordTypeInfoMap.keySet()){
        LeadManagement.mapRecordTypeIDName.put(recordTypeId, LeadManagement.idToLeadRecordTypeInfoMap.get(recordTypeId).getName());
        if (LeadManagement.idToLeadRecordTypeInfoMap.get(recordTypeId).getName() == 'Systems') {
          LeadManagement.systemsRecordTypeId = recordTypeId;
        }
      }
    }
    //build maps and perform necessary soql queries for business logic
    Map<ID, Account> mapAccount = new Map<ID, Account>();
    Set<String> existingAccountNames = new Set<String>();
    for(Account a : [Select id, Name from Account where id in :accountDealers OR Name IN :existingAccountNames]){
        mapAccount.put(a.id, a);
        existingAccountNames.add(a.Name);
    }

    
    Map<String,String> countryTheaterMap = new Map<String,String>();
    if(countries.size()>0){
        for(Country_Reference__c cr : [select Country__c, Theater__c from Country_Reference__c where Country__c in : countries]){
            countryTheaterMap.put(cr.country__c, cr.theater__c);
        }
    }
    
    //lead event owner/team setting queries
    Map<String,ID> userEventContact = new Map<String,ID>();
    Map<ID, String> userTeamMap = new Map<ID, String>();
    for(User u : [select id,name,Lead_Team__c,isactive from User where isActive = true AND (id IN: leadOwnerIdSet or name in :leadEventContactUser)]){
        if(leadEventContactUser.size()>0){
            userEventContact.put(u.name,u.id);
        }
        userTeamMap.put(u.id, u.Lead_Team__c);
    }
    
    Map<String,ID> queueEventContact = new Map<String,ID>();
    Map<Id, String> queueNameMap = new Map<ID, String>();
    for(Group g : [select id, Name from Group where id IN: leadOwnerIdQueueSet or name in :leadEventContactQueue]){
        if(leadEventContactQueue.size()>0){
            queueEventContact.put(g.name,g.id);
        }
        queueNameMap.put(g.id, g.Name);
    }
    //checking for duplicates on email via contacts and leads
    set<Integer> duplicateEmailLeads = new set<Integer>();
    if(dupCheckByEmail!=null&&dupCheckByEmail.keyset().size()>0){
        
        for(Lead plResult : [SELECT Id, Email FROM Lead WHERE Email IN :dupCheckByEmail.keySet()])
        {
            if(plResult.Email != null && dupCheckByEmail.containsKey(plResult.Email)){
                duplicateEmailLeads.add(dupCheckByEmail.get(plResult.Email));
                System.debug(dupCheckByEmail.get(plResult.Email));
            }
        }    
        for(Contact pcResult : [SELECT ID, Email FROM Contact WHERE Email IN : dupCheckByEmail.keySet()])
        {
            if(pcResult.Email!=null && dupCheckByEmail.containsKey(pcResult.Email)){
                duplicateEmailLeads.add(dupCheckByEmail.get(pcResult.Email));
                System.debug(dupCheckByEmail.get(pcResult.Email));
            }
        } 
    }
    list<Lead> calculateCalendarWeekLead = new list<Lead>();
    for(Integer i : qualifiedLeads.keySet())
    {
        lead l = qualifiedLeads.get(i);     
        LeadManagement.updateLeadScore(l);
        if(setDealerName.contains(i)&&mapAccount.containsKey(l.Dealer_Name__c)){//set the Dealer_Locator_Selection to the account id
            l.Dealer_Locator_Selection__c = mapAccount.get(l.Dealer_Name__c).id;  
        }
        /*if(!eloquaStatusSet.contains(i)) {//added condition to not set status to open when it is set to something else
            l.Status = 'Marketing Qualified';
        }*/
        if(theaterAssignment.contains(i)&&countryTheaterMap.containsKey(l.Country)){
            l.Theater__c = countryTheaterMap.get(l.Country);
        }
        //set the the owner for the lead event
        if(eventLead.contains(i)){
            if(userEventContact.containsKey(l.Event_Contact__c)){
                l.OwnerID = userEventContact.get(l.Event_Contact__c);
            }
            if(queueEventContact.containsKey(l.Event_Contact__c)){
                l.OwnerID = queueEventContact.get(l.Event_Contact__c);
            }
        }
        //set the Lead Team based on the user or the queue name
        if(teamLead.contains(i)){
            if(l.OwnerId!=null && String.valueOf(l.OwnerId).startsWith('005') && userTeamMap.containsKey(l.ownerId)){                
                l.Lead_Team__c = userTeamMap.get(l.OwnerId);
            }
            else if(l.OwnerId!=null && queueNameMap.containsKey(l.OwnerId)){  
                if(queueNameMap.get(l.OwnerId).contains('NA Commercial Marketing Queue')){             
                    l.Lead_Team__c = 'Marketing';
                }
                else if(queueNameMap.get(l.OwnerId).contains('NA Commercial ISR Queue')){
                    l.Lead_Team__c = 'ISR';
                }
            }
        }
        if(duplicateEmailLeads.contains(i)){
            autoConvertLeads.remove(i);//not ready for conversion so remove from auto-convert set
            //l.Status = 'Awaiting Duplicate Review';
            System.debug(l.Company + ' was flagged as a duplicate!');
            l.Status = 'Disqualified';
            l.Reason__c = 'Awaiting Duplicate Review';
            l.IsAutoConvert__c = false;
        }
        if(autoConvertLeads.contains(i)){
            l.Status = 'Ready for Conversion';
            l.IsAutoConvert__c = true;
            if(existingAccountNames.contains(l.Company)){
                l.Company = l.Company + string.valueOf(system.today());
            }
            
        }
    if(leadCalculateCalendarWeekSet.contains(i))
          calculateCalendarWeekLead.add(l);
    }
    if(calculateCalendarWeekLead.size()>0)
        LeadManagement.CalculateCalendarWeek(calculateCalendarWeekLead);  
    Diagnostics.pop();
  }
  
  // -------- Internal Classes --------
  // None

  
}