objects/Country_Reference__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Country Reference</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Country Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>RLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Intl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Intl</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Aaland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antartica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ascension Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benelux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Time_Fifth_follow_up__c</fullName>
        <label>Date-Time Eloqua Postcard 2</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Time_First_follow_up__c</fullName>
        <label>Date-Time First follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Time_Fourth_follow_up__c</fullName>
        <label>Date-Time Eloqua Postcard 1</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Time_Second_follow_up__c</fullName>
        <label>Date-Time Second follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Time_Third_follow_up__c</fullName>
        <label>Date-Time Third follow-up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dealer_Locator_Selection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Selection</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Dealer Locator Selection)</relationshipLabel>
        <relationshipName>Leads3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <description>Field which contains Dealer ID from Web to Lead.</description>
        <label>Dealer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fifth_follow_up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trigger Eloqua Postcard 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_follow_up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First follow-up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fourth_follow_up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trigger Eloqua Postcard 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RLC_Type__c</fullName>
        <description>This is dependent pick list when &quot;RLC&quot; is selected in Business Unit field.</description>
        <inlineHelpText>This is dependent pick list when &quot;RLC&quot; is selected in Business Unit field.</inlineHelpText>
        <label>RLC Type</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Light Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EU Commercial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SPWR_Industry_Type__c</fullName>
        <label>SPWR Industry Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College/University</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community-Based Organization-NGO, NPOs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant/Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convention Center/Arena</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation - Offices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution/Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electric Utility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPC contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Government - Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Government - Non-Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotels &amp; Resorts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - Special District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics &amp; Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Facility</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Second_follow_up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Second follow-up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <picklist>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central America and the Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle East and Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Third_follow_up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Third follow-up</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <businessProcess>SunPower Residential Leads Process</businessProcess>
        <description>Residential Leads</description>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Global Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Intl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPP Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Commercial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_LeadBeforeInsertHandler.cls
@isTest
public with sharing class Test_LeadBeforeInsertHandler {
	
	private static ID ResidentialRecordTypeId = SFDCSpecialUtilities.GetRecordTypeIdsByDeveloperName(Lead.SobjectType).get('Residential');

	@isTest
	public static void testLeadBeforeInsertBasicFieldAssignment(){
		//test to make sure autoconvert is set to true or false correctly
		ID accountResidentialRT = TestClassFactory.retrieveRecordTypeID('Account', 'Residential Customer');
		Account dealerAccount = TestClassFactory.testAccount('DealerAccount',accountResidentialRT);
		insert dealerAccount;

		

		Lead l = TestClassFactory.testLead('TestOne','TestOne','testOne@leadTest.com');
		l.RecordTypeId = ResidentialRecordTypeId;//residential record type lead
		//RLC_type__c should go to "Residential"
		//Primary Contact should be set to "True"

		//after insert, the lead's Dealer_Locator_Selection should be set to the test dealer Account
		//l.Dealer_Name__c = 'DealerAccount';
		
		//this should get changed to United States and the theater should be set to "North America" based on the Country_Reference object
		Country_Reference__c cr = new Country_Reference__c(Country__c = 'United States', Theater__c = 'North America');
		insert cr;
		//l.Country = 'US';
		l.Country = 'United States';
		l.Street = '123 Test St';
		l.City = 'Denver';
		l.State = 'CO';
		l.PostalCode = '80209';

		l.SPWR_Industry_Type__c = 'Test Industry Type';
		//the HD_ version of this field should get 'Test Industry Type'


		l.leadSource = 'Jigsaw';//should get changed to "Data.Com - Sales"

		l.First_follow_up__c = true;
		//assert Date_Time_First_follow_up__c = todayish
	    l.Second_follow_up__c = true;
	    //    l.Date_Time_Second_follow_up__c = Datetime.now();
	    l.Third_follow_up__c = true;
	    //    l.Date_Time_Third_follow_up__c = Datetime.now();
	    l.Fourth_follow_up__c = true;
	    //    l.Date_Time_Fourth_follow_up__c = Datetime.now();
	    l.Fifth_follow_up__c = true;
	    //    l.Date_Time_Fifth_follow_up__c = Datetime.now();
	    l.Business_Unit__c = 'Test Business Unit';

	    test.startTest();
	    insert l;
	    /*
	    l = [Select ID, 
	    			Dealer_Locator_Selection__c,//dealerAccount.id 
	    			RLC_Type__c, //Residential
	    			Primary_Contact__c, //true
	    			Theater__c, //North America
	    			SPWR_Industry_Type_Hidden__c,//Test Industry Type
	    			LeadSource,//Data.Com - Sales
	    			Country,//United States
	    			Lead_Owner_Mapping__c,//current user
	    			Date_Time_First_follow_up__c,//today
	    			Date_Time_Second_follow_up__c,//today
	    			Date_Time_Third_follow_up__c,//today
	    			Date_Time_Fourth_follow_up__c,//today
	    			Date_Time_Fifth_follow_up__c,//today
	    			HD_Business_Unit__c,//Test Business Unit
	    			HD_Lead_Status__c//open
	    			from Lead where ID = : l.id
	    			];

	    //system.assert(l.Dealer_Locator_Selection__c==dealerAccount.id);
	    system.assert(l.RLC_Type__c == 'Residential');
	    system.assert(l.Primary_Contact__c);
	    system.assert(l.Theater__c == 'North America');
	    system.assert(l.SPWR_Industry_Type_Hidden__c == 'Test Industry Type');
	    system.assert(l.LeadSource == 'Data.com - Sales');
	    system.assert(l.Country__c == 'United States');
	    system.assert(l.HD_Business_Unit__c =='Test Business Unit');
	    Date today = system.today();
	    system.assert(
	    				l.Date_Time_First_follow_up__c.date() == today &&
	    				l.Date_Time_Second_follow_up__c.date() == today &&
	    				l.Date_Time_Third_follow_up__c.date() == today &&
	    				l.Date_Time_Fourth_follow_up__c.date() == today &&
	    				l.Date_Time_Fifth_follow_up__c.date() == today

	    			);*/
	    test.stopTest();


	}	

	
}