objects/CPRFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>CPR_FieldName__c</fullName>
        <label>CPR FieldName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectField__c</fullName>
        <label>sObjectField</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <label>sObjectName</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CPR Fields Mapping</label>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuoteBuilder.cls
public with sharing class QuoteBuilder implements NodeConsumer
{
	public Quote quoteToBuild;
	public Map<String, List<String>> CPRfieldTosObjectField;
	
	public QuoteBuilder(List<CPRFieldMapping__c> allMappings)
	{
		CPRfieldTosObjectField = new Map<String, List<String>>();
		for(CPRFieldMapping__c theMapping : allMappings)
		{
			if(theMapping.sObjectName__c == 'Quote')
			{
				CPRfieldTosObjectField.put(theMapping.CPR_FieldName__c , new List<String>{theMapping.sObjectField__c , theMapping.Type__c});
			}
		}
		initData();
	}
	
	public void initData()
	{
		quoteToBuild = new Quote();
		//quoteToBuild.Name = 'CPR-WebTest Quote';
	}
	
	public void consumeNode(TG_XmlNode theNode)
	{
		 String CPRFieldName = theNode.getAttribute('Name');
		 System.debug( CPRFieldName );
		 System.debug( quoteToBuild );
		 System.debug( CPRfieldTosObjectField );
		 if(CPRfieldTosObjectField.containsKey(CPRFieldName))
		 {
		 	String theValue = theNode.getAttribute('Value');	
		 	String sObjectFieldName = CPRfieldTosObjectField.get(CPRFieldName)[0];
		 	String theType = CPRfieldTosObjectField.get(CPRFieldName)[1];
		 	
		 	if(theType == 'Date')
		 	{
		 		Date theDateValue = Date.parse(theValue); 
		 		quoteToBuild.put(sObjectFieldName , theDateValue);
		 	}
		 	else if(theType == 'Decimal')
		 	{
		 		String replaced = theValue.replace('$',''); //some of these things may contain dollar signs
		 		if(theValue == '' || theValue == null)
		 		{
		 			quoteToBuild.put(sObjectFieldName , null);
		 		}
		 		else
		 		{
					quoteToBuild.put(sObjectFieldName , Decimal.valueOf(replaced));
		 		}
		 	}
		 	else if(theType == 'Number')
		 	{
		 		quoteToBuild.put(sObjectFieldName , Integer.valueOf(theValue));
		 	}
		 	else if(theType == 'Boolean')
		 	{
		 		quoteToBuild.put(sObjectFieldName , Boolean.valueOf(theValue));
		 	}
		 	else if(theType == 'ExternalId')
		 	{
		 		Item__c theItem = new Item__c(Item_ID__c = theValue);
		 		if ( theValue != null )
		 		{
		 			quoteToBuild.putSObject(sObjectFieldName, theItem );
		 		}
		 	}
		 	else
		 	{
		 		quoteToBuild.put(sObjectFieldName , theValue);
		 	}
		 		
		 }
		
	}
	
}