objects/Credit_Check_Request__c.object
<CustomObject>
    <fields>
        <fullName>Application_Id__c</fullName>
        <description>Loan- External Id to credit bureau(Mosaic, Loanpath). Vendors use this to communicate with SFDC</description>
        <label>Application Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Loan- added to capture data from Mosaic. This will be used to send Lending Agreement call. FirstName, Last name will besent to Mosaic as well as updated on the quote- temp contact 1 field</description>
        <label>City</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Email to send the credit request form to.</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Loan- added to capture data from Mosaic. This will be used to send Lending Agreement call. FirstName, Last name will besent to Mosaic as well as updated on the quote- temp contact 1 field</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Loan- added to capture data from Mosaic. This will be used to send Lending Agreement call. FirstName, Last name will besent to Mosaic as well as updated on the quote- temp contact 1 field</description>
        <label>State</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Street2__c</fullName>
        <description>Loan- added to capture data from Mosaic. This will be used to send Lending Agreement call. FirstName, Last name will besent to Mosaic as well as updated on the quote- temp contact 1 field</description>
        <label>Street2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Loan- added to capture data from Mosaic. This will be used to send Lending Agreement call. FirstName, Last name will besent to Mosaic as well as updated on the quote- temp contact 1 field</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Loan- added to capture data from Mosaic. This will be used to send Lending Agreement call. FirstName, Last name will besent to Mosaic as well as updated on the quote- temp contact 1 field</description>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Credit Check Application</label>
    <nameField>
        <displayFormat>CCR-{000000}</displayFormat>
        <label>Credit Check Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Check Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Product__c.object
<CustomObject>
    <description>Object to store credit products- For Lease it will not have any product but for Loan it will have loan products such as 10 years, 20 years and amount</description>
    <fields>
        <fullName>Product_Display_Name__c</fullName>
        <description>Display name</description>
        <label>Product Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credit Product</label>
    <nameField>
        <label>Credit Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Loan_Callout_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Client_ID__c</fullName>
        <description>Store Client ID</description>
        <label>Client ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <description>Client Secret</description>
        <label>Client Secret</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>Endpoint URL</description>
        <label>Endpoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Grant_Type__c</fullName>
        <description>Stores Grant Type value need for Mosaic call outs</description>
        <label>Grant Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepEmail__c</fullName>
        <description>Sales Representative Email</description>
        <label>SalesRepEmail</label>
        <type>Email</type>
    </fields>
    <label>Callout Settings</label>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>Opportunity.City_Location__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consolidated_Lease_Number__c</fullName>
        <formula>IF( ISBLANK(Original_Lease_Number__c) , Final_Lease_Number__c , Original_Lease_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lease Number1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financed_Amount__c</fullName>
        <description>It&apos;s a field to capture the financed amount from FinEng.</description>
        <label>Financed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inverter_Manufacturer_Roof1__c</fullName>
        <label>Inverter Manufacturer</label>
        <picklist>
            <picklistValues>
                <fullName>Sunpower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Powerone</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inverter_Model__c</fullName>
        <label>Inverter Model</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_Rated_Capacity__c</fullName>
        <description>NH- moved from PLI configurator</description>
        <formula>VALUE(Module_Oracle_Item_Number__r.Item_Category_3__c)  *  Module_Count__c  * 0.001</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maximum Rated Capacity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Power_Bill_After_Solar__c</fullName>
        <label>Monthly Power Bill After Solar</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent summary for this quote.  Summary contains 3 quotes.</inlineHelpText>
        <label>Quote Summary</label>
        <referenceTo>Quote_Summary__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Model__c</fullName>
        <label>System Model</label>
        <picklist>
            <picklistValues>
                <fullName>230W (Model SPR-230E-WHT-D)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>230W (Model SPR-230NE-BLK-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>245W (Model SPR-245NE-WHT-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>308W (Model SPR-308E-WHT-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>327W (Model SPR-327NE-WHT-D)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Production_Year_1__c</fullName>
        <label>System Production Year 1</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Price__c</fullName>
        <description>It&apos;s field to populate the system price we received from FinEng.</description>
        <label>Total Contract Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Summaries (Quote)</relationshipLabel>
        <relationshipName>Quote_Summaries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/System_Production__c.object
<CustomObject>
    <description>This data will be moved to lease schedule.</description>
    <fields>
        <fullName>Monthly_Electric_Bill_Without_PV_year1__c</fullName>
        <label>Monthly Electric Bill Without PV year1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>System Production</relationshipLabel>
        <relationshipName>System_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Production</label>
    <nameField>
        <label>System Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Mosaic_API_CallHandler.cls
//Mosiac API Calls
public class Mosaic_API_CallHandler{

    public static Loan_Callout_Settings__c mcs = Loan_Callout_Settings__c.getInstance('Mosaic');
    public static Contact cont = new Contact();
    public static Boolean isUserCreated = false;
    //***************************GET MOSAIC ACCESS TOKEN************************
    public static String getMosaicAccessToken(){
            try{
                String endPointURL = mcs.Endpoint_URL__c+'/api/v1/access-token';
                String clientSecret = mcs.Client_Secret__c;
                String clientId = mcs.Client_Id__c;
                String grantType = mcs.Grant_Type__c;
                
                
                String authString ='?client_id='+clientId+'&client_secret='+clientSecret+'&grant_type='+grantType;    
                
                Httprequest request = new HttpRequest();
                Http http = new Http();
                request.setMethod('POST');
                request.setEndpoint(endPointURL+authString);
                System.debug('requestEndpoint----->'+request.getEndpoint());
                HttpResponse response = http.send(request);
                System.debug('response----->'+response.getBody());
                Map<String,Object> data = (Map<String,Object>)JSON.deserializeUntyped(response.getBody());
                String accessToken = (String)data.get('access_token');
                return accessToken;
                
            }catch(Exception e){
                System.debug('Error::'+e.getMessage());
                return null;
            }
    }
    
    //***********************************CREATE OPPORTUNITY****************************************
    public static MosaicJSONUtil.MosaicResponse mosaic_Create_Opportunity(Contact con){
        system.debug('User Email:'+userinfo.getUserEmail());
        cont = con;
        MosaicJSONUtil.Address addr = new MosaicJSONUtil.Address(con.MailingStreet,'',con.MailingCity,con.MailingState,con.MailingPostalCode);
        MosaicJSONUtil.Opportunity opp = new MosaicJSONUtil.Opportunity(con.FirstName,con.LastName,con.Phone.replaceAll('\\D',''),con.Email,addr,userinfo.getUserEmail(),null);
        System.debug('opp ----->'+opp);
        
        String JSONString = JSON.serialize(opp);
        System.debug('JSONString ----->'+JSONString);
        String endPointURL = mcs.Endpoint_URL__c + '/api/v1/opportunities';
        String authorizationHeader = 'Bearer ' + getMosaicAccessToken();

        Httprequest request = new HttpRequest();
        Http http = new Http();
        request.setMethod('POST');
        request.setEndpoint(endPointURL);
        request.setHeader('Content-Type', 'application/json');
        // Header info with remote server user name and password
        request.setHeader('Authorization', authorizationHeader);
        // timeout in milliseconds       
        request.setTimeout(120000); 
        request.setBody(JSONString);          
        //Making call to external REST API
        HttpResponse response = http.send(request);
        //System.debug('requestBody: '+request.getBody());
        System.debug('responseBody: '+response.getBody());
        
        String JsonResponse = response.getBody();
        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,JsonResponse));
        MosaicJSONUtil.MosaicResponse mosResp = new MosaicJSONUtil.MosaicResponse();
        
        if(response.getStatusCode()==200){
            MosaicJSONUtil.Opportunity resopp =
                (MosaicJSONUtil.Opportunity)JSON.deserialize(JsonResponse, MosaicJSONUtil.Opportunity.class);
            mosResp.opp = resopp;
            mosResp.successful = true;
        }
        else{
            mosResp.successful = false;
            mosResp.responsebody = response.getBody();
            mosaic_CreateLogin();

        }
        mosResp.request = request;
        mosResp.response = response;
        return mosResp;       
    }
    
    public Static void mosaic_CreateLogin(){
        User u = [Select id, FirstName, LastName, Phone from User where id =: userinfo.getUserId()];
        system.debug('u---->'+u);
        MosaicJSONUtil.createLogin cLogin = new MosaicJSONUtil.createLogin(userinfo.getFirstName(),userinfo.getLastName(),u.Phone!=null?u.Phone.replaceAll('\\D',''):'8007867693',userinfo.getUserEmail(),null,'NOTIFICATIONS_ONLY',null);
        System.debug('cLogin ----->'+cLogin);
        
        String JSONString = JSON.serialize(cLogin);
        System.debug('JSONString ----->'+JSONString);
        String endPointURL = mcs.Endpoint_URL__c + '/api/v1/logins';
        String authorizationHeader = 'Bearer ' + getMosaicAccessToken();

        Httprequest request = new HttpRequest();
        Http http = new Http();
        request.setMethod('POST');
        request.setEndpoint(endPointURL);
        request.setHeader('Content-Type', 'application/json');
        // Header info with remote server user name and password
        request.setHeader('Authorization', authorizationHeader);
        // timeout in milliseconds       
        request.setTimeout(120000); 
        request.setBody(JSONString);          
        //Making call to external REST API
        HttpResponse response = http.send(request);
        //System.debug('requestBody: '+request.getBody());
        System.debug('responseBody: '+response.getBody());
        String JsonResponse = response.getBody();
        if(response.getStatusCode()==200){
            isUserCreated = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'A User Has been Created in Mosaic.Please resubmit the Credit Check Application.'));
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,JsonResponse));

        }    
    }
    //***********************************UPDATE OPPORTUNITY****************************************
    public static MosaicJSONUtil.MosaicResponse mosaic_Update_Opportunity(Credit_Check_Request__c cca,Quote qt,Quote_Summary__c qs,Credit_Product__c cp){
        MosaicJSONUtil.Address addr = new MosaicJSONUtil.Address(cca.Street__c,cca.Street2__c,cca.City__c,cca.State__c,cca.Zip__c);
        System_Production__c sp = [select id,Monthly_Electric_Bill_Without_PV_year1__c from System_Production__c where Quote__c = :qt.Id];
        String inverterManufacturer = qt.Inverter_Manufacturer_Roof1__c=='PowerOne'?'ABB':qt.Inverter_Manufacturer_Roof1__c=='Sunpower'?'SunPower':qt.Inverter_Manufacturer_Roof1__c;
        
        MosaicJSONUtil.SolarSystem slrSys = new MosaicJSONUtil.SolarSystem(Double.valueOf(sp.Monthly_Electric_Bill_Without_PV_year1__c), Double.valueOf(qt.Monthly_Power_Bill_After_Solar__c),Integer.valueOf(qt.System_Production_Year_1__c),Double.valueOf(qt.Maximum_Rated_Capacity__c),'SunPower '+qt.System_model__c,inverterManufacturer+' '+qt.Inverter_Model__c,Double.valueOf(qt.Financed_Amount__c), String.valueOf(Datetime.now().format('yyyy-MM-dd')), qt.Consolidated_Lease_Number__c ,String.valueOf(Datetime.now().format('yyyy-MM-dd')),'NONE',cp.Product_Display_Name__c, Double.valueOf(qt.Total_Contract_Price__c));
        MosaicJSONUtil.Opportunity opp = new MosaicJSONUtil.Opportunity(cca.First_Name__c,cca.Last_Name__c,cca.Phone__c.replaceAll('\\D',''),cca.Email__c,addr,mcs.SalesRepEmail__c,slrSys);
        
        System.debug('oppSS ----->'+opp);
        System.debug('slrSys ----->'+slrSys);
        String JSONString = JSON.serialize(opp);
        System.debug('JSONString ----->'+JSONString);
        String endPointURL = mcs.Endpoint_URL__c + '/api/v1/opportunities/';
        String authorizationHeader = 'Bearer ' + getMosaicAccessToken();

        Httprequest request = new HttpRequest();
        Http http = new Http();
        request.setMethod('PUT');
        request.setEndpoint(endPointURL+cca.Application_Id__c);
        request.setHeader('Content-Type', 'application/json');
        // Header info with remote server user name and password
        request.setHeader('Authorization', authorizationHeader);
        // timeout in milliseconds 
        request.setTimeout(120000);
        request.setBody(JSONString);
        System.debug('requestBody: '+request.getBody());
        
        //Making call to external REST API
        HttpResponse response = http.send(request);
        
        System.debug('responseBody: '+response.getBody());
        
        String JsonResponse = response.getBody();
        MosaicJSONUtil.MosaicResponse mosResp = new MosaicJSONUtil.MosaicResponse();
        
        if(response.getStatusCode()==200){
            MosaicJSONUtil.Opportunity resopp =
                (MosaicJSONUtil.Opportunity)JSON.deserialize(JsonResponse, MosaicJSONUtil.Opportunity.class);
            mosResp.opp = resopp;
            mosResp.successful = true;
        }
        else{
            mosResp.successful = false;
            mosResp.responsebody = response.getBody();
        }
        mosResp.request = request;
        mosResp.response = response;
        return mosResp;       
    } 
    
    
    //***********************************SEND CREDIT CHECK****************************************
    public static MosaicJSONUtil.MosaicResponse mosaic_Send_Credit_Application(String oppId){
        String endPointURL = mcs.Endpoint_URL__c+'/api/v1/opportunities/'+oppId+'/send-credit-application';
        String authorizationHeader = 'Bearer ' + getMosaicAccessToken();

        Httprequest request = new HttpRequest();
        Http http = new Http();

        request.setMethod('POST');
        request.setEndpoint(endPointURL);
        request.setHeader('Authorization', authorizationHeader);    
        request.setTimeout(120000);  
        
        HttpResponse response = http.send(request);
        
        System.debug('responseBody: '+response.getBody());
        
        String JsonResponse = response.getBody();
        
        MosaicJSONUtil.MosaicResponse mosResp = new MosaicJSONUtil.MosaicResponse();       
        
        if(response.getStatusCode()==200){
            mosResp.successful=true;
        }
        else{
            mosResp.successful=false;
            mosResp.responsebody = response.getBody();
        }
        mosResp.request = request;
        mosResp.response = response;
        return mosResp;
    }
    
    
    //***********************************SEND LENDING AGREEMENT****************************************
    public static MosaicJSONUtil.MosaicResponse mosaic_Send_Loan_Agreement(String oppId){
        String endPointURL = mcs.Endpoint_URL__c+'/api/v1/opportunities/'+oppId+'/send-loan-agreement';
        String authorizationHeader = 'Bearer ' + getMosaicAccessToken();
        
        Httprequest request = new HttpRequest();
        Http http = new Http();
        
        request.setMethod('POST');
        request.setEndpoint(endPointURL);
        request.setHeader('Authorization', authorizationHeader);    
        request.setTimeout(120000);  
        
        HttpResponse response = http.send(request);
        
        System.debug('responseBody: '+response.getBody());
        
        String JsonResponse = response.getBody();
        
        MosaicJSONUtil.MosaicResponse mosResp = new MosaicJSONUtil.MosaicResponse();       
        
        if(response.getStatusCode()==200){
            mosResp.successful=true;
        }
        else{
            mosResp.successful=false;
            mosResp.responsebody=response.getBody();
        }
        mosResp.request = request;
        mosResp.response = response;
        return mosResp;
    }
    
    
    //*****************************UPLOAD DOCUMENT*****************************
    public static MosaicJSONUtil.MosaicResponse mosaic_Upload_Document(String oppId, String documentType, Attachment att){
        
        if(att!=null){
            String authorizationHeader = 'Bearer ' + getMosaicAccessToken();
            String file_name=att.name;
            Blob file_body = att.Body;
            String endPointURL = mcs.Endpoint_URL__c+'/api/v1/opportunities/'+oppId+'/documents/'+documentType;
            // Repost of code  with fix for file corruption issue
            // Orignal code postings and explanations
            // http://enreeco.blogspot.in/2013/01/salesforce-apex-post-mutipartform-data.html
            // http://salesforce.stackexchange.com/questions/24108/post-multipart-without-base64-encoding-the-body
            // Additional changes commented GW: that fix issue with occasional corruption of files
            String boundary = '----------------------------741e90d31eff';
            String header = '--'+boundary+'\nContent-Disposition: form-data; name="file"; filename="'+file_name+'";\nContent-Type: application/octet-stream';
            // GW: Do not prepend footer with \r\n, you'll see why in a moment
            // String footer = '\r\n--'+boundary+'--'; 
            String footer = '--'+boundary+'--';             
            String headerEncoded = EncodingUtil.base64Encode(Blob.valueOf(header+'\r\n\r\n'));
            while(headerEncoded.endsWith('='))
            {
                header+=' ';
                headerEncoded = EncodingUtil.base64Encode(Blob.valueOf(header+'\r\n\r\n'));
            }
            String bodyEncoded = EncodingUtil.base64Encode(file_body);
            // GW: Do not encode footer yet
            // String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer));
            
            Blob bodyBlob = null;
            String last4Bytes = bodyEncoded.substring(bodyEncoded.length()-4,bodyEncoded.length());
            
            // GW:Get rid of padding without corrupting data
            if(last4Bytes.endsWith('==')) {
                // The '==' sequence indicates that the last group contained only one 8 bit byte
                // 8 digit binary representation of CR is 00001101
                // 8 digit binary representation of LF is 00001010
                // Stitch them together and then from the right split them into 6 bit chunks
                // 0000110100001010 becomes 0000 110100 001010
                // Note the first 4 bits 0000 are identical to the padding used to encode the
                // second original 6 bit chunk, this is handy it means we can hard code the response in
                // The decimal values of 110100 001010 are 52 10
                // The base64 mapping values of 52 10 are 0 K
                // See http://en.wikipedia.org/wiki/Base64 for base64 mapping table
                // Therefore, we replace == with 0K
                // Note: if using \n\n instead of \r\n replace == with 'oK'
                last4Bytes = last4Bytes.substring(0,2) + '0K';
                bodyEncoded = bodyEncoded.substring(0,bodyEncoded.length()-4) + last4Bytes;
                // We have appended the \r\n to the Blob, so leave footer as it is.
                String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer));
                bodyBlob = EncodingUtil.base64Decode(headerEncoded+bodyEncoded+footerEncoded);
            } else if(last4Bytes.endsWith('=')) {
                // '=' indicates that encoded data already contained two out of 3x 8 bit bytes
                // We replace final 8 bit byte with a CR e.g. \r
                // 8 digit binary representation of CR is 00001101
                // Ignore the first 2 bits of 00 001101 they have already been used up as padding
                // for the existing data.
                // The Decimal value of 001101 is 13
                // The base64 value of 13 is N
                // Therefore, we replace = with N
                // Note: if using \n instead of \r replace = with 'K'
                last4Bytes = last4Bytes.substring(0,3) + 'N';
                bodyEncoded = bodyEncoded.substring(0,bodyEncoded.length()-4) + last4Bytes;
                // We have appended the CR e.g. \r, still need to prepend the line feed to the footer
                footer = '\n' + footer;
                String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer));
                bodyBlob = EncodingUtil.base64Decode(headerEncoded+bodyEncoded+footerEncoded);              
            } else {
                // Prepend the CR LF to the footer
                footer = '\r\n' + footer;
                String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer));
                bodyBlob = EncodingUtil.base64Decode(headerEncoded+bodyEncoded+footerEncoded);  
            }
            
            HttpRequest req = new HttpRequest();
            req.setHeader('Authorization', authorizationHeader);
            req.setHeader('Content-Type','multipart/form-data; boundary='+boundary);
            req.setMethod('POST');
            req.setEndpoint(endPointURL);
            req.setBodyAsBlob(bodyBlob);
            req.setTimeout(120000);
            
            Http http = new Http();
            HTTPResponse response = http.send(req);
            System.debug('res----->'+response);
            
            MosaicJSONUtil.MosaicResponse mosResp = new MosaicJSONUtil.MosaicResponse();
            if(response.getStatusCode()==200){
                mosResp.successful=true;
            }
            else{
                mosResp.successful=false;
                mosResp.responsebody=response.getBody();
            }
            mosResp.request = req;
            mosResp.response = response;
            return mosResp;
        }
        return null;
    }

    //***********************************SUBMIT PHOTO PROOF OF INSTALLATION****************************************
    public static MosaicJSONUtil.MosaicResponse mosaic_Submit_Photo_Proof_Installation(String oppId){
        String endPointURL = mcs.Endpoint_URL__c+'/api/v1/opportunities/'+oppId+'/install-complete-photo';
        String authorizationHeader = 'Bearer ' + getMosaicAccessToken();
        
        Httprequest request = new HttpRequest();
        Http http = new Http();
        
        request.setMethod('POST');
        request.setEndpoint(endPointURL);
        request.setHeader('Authorization', authorizationHeader);    
        request.setTimeout(120000);  
        
        HttpResponse response = http.send(request);
        
        System.debug('responseBody: '+response.getBody());
        
        String JsonResponse = response.getBody();
        
        MosaicJSONUtil.MosaicResponse mosResp = new MosaicJSONUtil.MosaicResponse();       
        
        if(response.getStatusCode()==200){
            mosResp.successful=true;
        }
        else{
            mosResp.successful=false;
            mosResp.responsebody=response.getBody();
        }
        mosResp.request = request;
        mosResp.response = response;
        return mosResp;
    }

    //***********************************SUBMIT FOR FINAL REVIEW****************************************
    public static MosaicJSONUtil.MosaicResponse mosaic_Submit_Final_Review(String oppId){
        String endPointURL = mcs.Endpoint_URL__c+'/api/v1/opportunities/'+oppId+'/submit-for-final';
        String authorizationHeader = 'Bearer ' + getMosaicAccessToken();
        
        Httprequest request = new HttpRequest();
        Http http = new Http();
        
        request.setMethod('POST');
        request.setEndpoint(endPointURL);
        request.setHeader('Authorization', authorizationHeader);    
        request.setTimeout(120000);  
        
        HttpResponse response = http.send(request);
        
        System.debug('responseBody: '+response.getBody());
        
        String JsonResponse = response.getBody();
        
        MosaicJSONUtil.MosaicResponse mosResp = new MosaicJSONUtil.MosaicResponse();       
        
        if(response.getStatusCode()==200){
            mosResp.successful=true;
        }
        else{
            mosResp.successful=false;
            mosResp.responsebody=response.getBody();
        }
        mosResp.request = request;
        mosResp.response = response;
        return mosResp;
    }

}