objects/Credit_Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Applications</relationshipLabel>
        <relationshipName>Credit_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Bill_To_State__c</fullName>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Limit_Requested__c</fullName>
        <label>Credit Limit Requested</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Legal_Company_Name__c</fullName>
        <label>Legal Company Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ship_To_City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_State__c</fullName>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Credit Application</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Credit Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CreateCreditApplication.cls
/*************************************************************************
Name     : CreateCreditApplication
Author   : Aslam Bari
Date     : May 01, 2009
Usage    : This class called from Create Credit Application button, which is
           available at Credit Application related list section of the
           Account Page. It creates a new Credit_Application__c record.
**************************************************************************/

public class CreateCreditApplication{
    
    public string accountId {get;set;}
    public Account accountObj {get;set;}
    public Boolean isError {get;set;}

    public CreateCreditApplication(){
        accountId = ApexPages.currentPage().getParameters().get('id');
        if(accountId != null && accountId.trim().length() > 0){
            List<Account> lstAccount = [select id, name, BillingStreet, BillingState, 
                          BillingPostalCode,BillingCountry, BillingCity,
                          ShippingStreet, ShippingState, ShippingPostalCode,
                          ShippingCountry, ShippingCity, NumberOfEmployees, Phone
                          FROM Account WHERE id=:accountId];
            if(lstAccount != null && lstAccount.size() > 0){
                accountObj = lstAccount.get(0);
            }
                          
        }
    }
    
    public PageReference saveCreditApplication()
    {
        if(accountObj == null)
        {
            isError = true;
            String errorStr = 'Invalid Account ID Given';
            if(SPCommunityUtility.isPartnerUser())
            {
                System.debug('**** error: '+errorStr);
                PageReference pr = Page.CreateCreditApplicationPartnerError;
                pr.getParameters().put('message', errorStr);
                pr.setRedirect(true);
                return pr;
            }
            else
            {
                ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.Error, errorStr);
                ApexPages.addMessage(errorMsg);
                return null;
            }
        }
         
        try
        {
            Credit_Application__c creditApplication = new Credit_Application__c();
            creditApplication.Legal_Company_Name__c = accountObj.Name;             
            creditApplication.Number_of_Employees__c = accountObj.NumberOfEmployees;
            creditApplication.Bill_To_Phone__c = accountObj.Phone;
            creditApplication.Bill_To_Zip__c = accountObj.BillingPostalCode;
            creditApplication.Bill_To_State__c = accountObj.BillingState;
            creditApplication.Bill_To_Country__c = accountObj.BillingCountry;
            creditApplication.Bill_To_City__c = accountObj.BillingCity;
            creditApplication.Bill_To_Address__c = accountObj.BillingStreet;
            creditApplication.Ship_To_Zip__c = accountObj.ShippingPostalCode;
            creditApplication.Ship_To_State__c = accountObj.ShippingState;
            creditApplication.Ship_To_Country__c = accountObj.ShippingCountry;
            creditApplication.Ship_To_City__c = accountObj.ShippingCity;
            creditApplication.Ship_To_Address__c = accountObj.ShippingStreet;
            creditApplication.Account__c = accountObj.id;
            creditApplication.Credit_Limit_Requested__c = 0;
             
            insert creditApplication;
             
            PageReference creditEditPage = new PageReference('/'+creditApplication.id +'/e?retURL=%2F'+accountObj.id);
            creditEditPage.setRedirect(true);
            return creditEditPage;

        }
        catch(Exception ex)
        {
            isError = true;
            if(SPCommunityUtility.isPartnerUser())
            {
                System.debug('**** error: '+ex.getMessage());
                PageReference pr = Page.CreateCreditApplicationPartnerError;
                pr.getParameters().put('message', ex.getMessage());
                pr.setRedirect(true);
                return pr;
            }
            else
            {
                ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage());
                ApexPages.addMessage(errorMsg);
                return null;
            }
        }
    }
    
}