objects/Credit_Application__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Reference_Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Limit_Requested__c</fullName>
        <label>Credit Limit Requested</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Tax_ID__c</fullName>
        <label>Federal Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Reference_1_Company__c</fullName>
        <label>Trade Reference 1 Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Reference_1_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Trade_Reference_2_Company__c</fullName>
        <label>Trade Reference 2 Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Reference_2_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Credit Application</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Credit Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestCreditAppPdfController.cls
/**************************************************
** PR- 01923
**Created By- Kapil Goutam
**Created On- June 10 2009
**Last Modified- 
**Last Modified On-   
**Desciption- Test class for Controller 
*****************************************************/
public class TestCreditAppPdfController {
    @isTest
    public static void Test_CreditAppPdfController(){
        Credit_Application__c creditApp = new Credit_Application__c();
        creditApp.Credit_Limit_Requested__c = 1000;        
        creditApp.Bank_Reference_Name__c = 'TestReference';
        creditApp.Trade_Reference_1_Company__c = 'Trade Reference1';
        creditApp.Trade_Reference_1_Phone__c = '12345' ;
        creditApp.Trade_Reference_2_Company__c = 'Trade Reference1';
        creditApp.Trade_Reference_2_Phone__c = '6789';
        creditApp.Federal_Tax_ID__c = '1234';
        creditApp.VAT_Number__c = '56789';
        insert creditApp;
        
        Apexpages.currentPage().getParameters().put('id', creditApp.Id);
        Apexpages.Standardcontroller controller = new Apexpages.Standardcontroller(creditApp);
        CreditAppPdfController creditPdf = new CreditAppPdfController(controller);
        //TestCreditApplicationManagement.test_CreditApplicationManagement();
        
    }

}