objects/Customer_Survey_Result__c.object
<CustomObject>
    <fields>
        <fullName>Cash__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cash</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_Placed_In_Service__c</fullName>
        <formula>IF( Opportunity_ID__r.Lease_Placed_in_Service__c == True, &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lease Placed In Service</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity Id to which Installation Survey is linked</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Survey Results</relationshipLabel>
        <relationshipName>Customer_Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Survey Result</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>survey result number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Survey Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Post_Visit_Follow_Up_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Post Visit Follow Up Surveys</relationshipLabel>
        <relationshipName>Post_Visit_Follow_Up_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Post Visit Follow Up Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Post Visit Follow Up Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/X1Y_Satisfaction_Survey_Result__c.object
<CustomObject>
    <fields>
        <fullName>Cash__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field helps to identified the Case survey type.</description>
        <label>Cash</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_Placed_In_Service__c</fullName>
        <formula>IF( Opportunity__r.Lease_Placed_in_Service__c == True, &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lease Placed In Service</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field helps to identify the lease record.</description>
        <label>Lease</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>1Y Satisfaction Survey Results</relationshipLabel>
        <relationshipName>X1Y_Satisfaction_Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>1Y Satisfaction Survey Result</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Survey Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1Y Satisfaction Survey Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SurveyUtilityTest.cls
@isTest
public class SurveyUtilityTest {

    private static testMethod void testSalesSurvey() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppForSalesSurvey conditions
        td.oppty_1.Lead_Manufacturer__c = 'SunPower';
        td.oppty_1.StageName = '12% - Qualified Opportunity';    // <> 'Installation Completed'
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <Post_Visit_Follow_Up_Survey__c> surveyList = [SELECT Id FROM Post_Visit_Follow_Up_Survey__c 
            WHERE Opportunity_ID__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
    }

    private static testMethod void testInstallSurvey_cash_nonSPD() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppForInstallSurvey conditions
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Installation_Completed_Date__c = system.today();    
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <Customer_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM Customer_Survey_Result__c
            WHERE Opportunity_ID__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
        system.assertEquals(true, surveyList[0].Cash__c);        
        system.assertEquals(false, surveyList[0].Lease__c);        
    }

    private static testMethod void testInstallSurvey_cash_SPD() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppForInstallSurvey conditions
        td.oppty_1.Partner_Account_Id__c = td.spdPartnerAccount_1.Id;
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Installation_Completed_Date__c = system.today(); 
        td.oppty_1.Date_PTO_Letter_Received_Promised__c = system.today().addDays(-10);    // <= system.today()  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <Customer_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM Customer_Survey_Result__c
            WHERE Opportunity_ID__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
        system.assertEquals(true, surveyList[0].Cash__c);        
        system.assertEquals(false, surveyList[0].Lease__c);        
    }

    private static testMethod void testInstallSurvey_cash_SPD_Date_PTO_Blank() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppForInstallSurvey conditions
        td.oppty_1.Partner_Account_Id__c = td.spdPartnerAccount_1.Id;
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Installation_Completed_Date__c = system.today(); 
        td.oppty_1.Date_PTO_Letter_Received_Promised__c = null;    // <= system.today()  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <Customer_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM Customer_Survey_Result__c
            WHERE Opportunity_ID__c = :td.oppty_1.Id];

        system.assertEquals(0, surveyList.size());        
    }

    private static testMethod void testInstallSurvey_cash_SPD_Date_PTO_gt_today() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppForInstallSurvey conditions
        td.oppty_1.Partner_Account_Id__c = td.spdPartnerAccount_1.Id;
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Installation_Completed_Date__c = system.today(); 
        td.oppty_1.Date_PTO_Letter_Received_Promised__c = system.today().addDays(1);    // <= system.today()  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <Customer_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM Customer_Survey_Result__c
            WHERE Opportunity_ID__c = :td.oppty_1.Id];

        system.assertEquals(0, surveyList.size());        
    }

    private static testMethod void testInstallSurvey_lease_nonSPD() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppForInstallSurvey conditions
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Installation_Completed_Date__c = system.today(); 
        td.oppty_1.Lease__c = true;
        td.oppty_1.Lease_Placed_in_Service__c = true;  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <Customer_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM Customer_Survey_Result__c
            WHERE Opportunity_ID__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
        system.assertEquals(false, surveyList[0].Cash__c);        
        system.assertEquals(true, surveyList[0].Lease__c);        
    }

    private static testMethod void testInstallSurvey_lease_SPD() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppForInstallSurvey conditions
        td.oppty_1.Partner_Account_Id__c = td.spdPartnerAccount_1.Id;
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Installation_Completed_Date__c = system.today(); 
        td.oppty_1.Lease__c = true;
        td.oppty_1.Lease_Placed_in_Service__c = true;  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <Customer_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM Customer_Survey_Result__c
            WHERE Opportunity_ID__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
        system.assertEquals(false, surveyList[0].Cash__c);        
        system.assertEquals(true, surveyList[0].Lease__c);        
    }

    private static testMethod void test1YearSurvey_cash_nonSPD() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppFor1YrSurveys conditions
        td.oppty_1.StageName = 'Installation Completed';
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <X1Y_Satisfaction_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM X1Y_Satisfaction_Survey_Result__c
            WHERE Opportunity__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
        system.assertEquals(true, surveyList[0].Cash__c);        
        system.assertEquals(false, surveyList[0].Lease__c);        
    }

    private static testMethod void test1YearSurvey_cash_SPD() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppFor1YrSurveys conditions
        td.oppty_1.Partner_Account_Id__c = td.spdPartnerAccount_1.Id;
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Date_PTO_Letter_Received_Promised__c = system.today().addDays(-10);    // <= system.today()  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <X1Y_Satisfaction_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM X1Y_Satisfaction_Survey_Result__c
            WHERE Opportunity__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
        system.assertEquals(true, surveyList[0].Cash__c);        
        system.assertEquals(false, surveyList[0].Lease__c);        
    }

    private static testMethod void test1YearSurvey_lease_nonSPD() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppFor1YrSurveys conditions
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Lease__c = true;
        td.oppty_1.Lease_Placed_in_Service__c = true;  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <X1Y_Satisfaction_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM X1Y_Satisfaction_Survey_Result__c
            WHERE Opportunity__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
        system.assertEquals(false, surveyList[0].Cash__c);        
        system.assertEquals(true, surveyList[0].Lease__c);        
    }

    private static testMethod void test1YearSurvey_lease_SPD() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppFor1YrSurveys conditions
        td.oppty_1.Partner_Account_Id__c = td.spdPartnerAccount_1.Id;
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Date_PTO_Letter_Received_Promised__c = system.today().addDays(-10);    // <= system.today()  
        td.oppty_1.Lease__c = true;
        td.oppty_1.Lease_Placed_in_Service__c = true;  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <X1Y_Satisfaction_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM X1Y_Satisfaction_Survey_Result__c
            WHERE Opportunity__c = :td.oppty_1.Id];

        system.assertEquals(1, surveyList.size());        
        system.assertEquals(false, surveyList[0].Cash__c);        
        system.assertEquals(true, surveyList[0].Lease__c);        
    }

    private static testMethod void test1YearSurvey_cash_SPD_Date_PTO_Blank() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppFor1YrSurveys conditions
        td.oppty_1.Partner_Account_Id__c = td.spdPartnerAccount_1.Id;
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Date_PTO_Letter_Received_Promised__c = null;    // <= system.today()  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <X1Y_Satisfaction_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM X1Y_Satisfaction_Survey_Result__c
            WHERE Opportunity__c = :td.oppty_1.Id];

        system.assertEquals(0, surveyList.size());        
    }

    private static testMethod void test1YearSurvey_cash_SPD_Date_PTO_gt_today() {
        SurveyUtilityTestData td = new SurveyUtilityTestData(); 
        td.createTestData();
        
        // isValidOppFor1YrSurveys conditions
        td.oppty_1.Partner_Account_Id__c = td.spdPartnerAccount_1.Id;
        td.oppty_1.StageName = 'Installation Completed';
        td.oppty_1.Date_PTO_Letter_Received_Promised__c = system.today().addDays(1);    // <= system.today()  
           
        insert td.oppty_1;
        
        // verify sales survey is create
        List <X1Y_Satisfaction_Survey_Result__c> surveyList = [SELECT Id, Cash__c, Lease__c FROM X1Y_Satisfaction_Survey_Result__c
            WHERE Opportunity__c = :td.oppty_1.Id];

        system.assertEquals(0, surveyList.size());        
    }

}