objects/Dealer_Utility_Pricing_File__c.object
<CustomObject>
    <description>Mapping of Dealer Name, Utility , State and the Leasing File name</description>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Utility Pricing Files</relationshipLabel>
        <relationshipName>Dealer_Utility_Pricing_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_File_Name__c</fullName>
        <description>It is the Pricing File name which should be sent to CPR(which in turn sends for ABC)</description>
        <label>Pricing File Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>It contains the State Code</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utility_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case# 00543268 - Unlike the text name of the utility, the encoded name is a unique value that does not change. We will need to capture the encoded name in the quote and match it up with the price file - Arokia Nathan</description>
        <label>Utility Code</label>
        <referenceTo>Utility_Code__c</referenceTo>
        <relationshipLabel>Dealer Utility Pricing Files</relationshipLabel>
        <relationshipName>Dealer_Utility_Pricing_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <description>It contains Utility information</description>
        <label>Utility</label>
        <picklist>
            <picklistValues>
                <fullName>Anaheim Public Utilities Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azusa Light &amp; Water Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colton Public Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glendale Water &amp; Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Imperial Irrigation District (IID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lompoc, City of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles Department of Water &amp; Power  (LADWP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modesto Irrigation District (MID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreno Valley Utility (MVU)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific Gas and Electric Company (PG&amp;E)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Riverside Utilities Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Diego Gas &amp; Electric (SDG&amp;E)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern California Edison (SCE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turlock Irrigation District (TID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unisource Energy Services (UES)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii Electric Light Company (HELCO) (Big Island of Hawaii)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaiian Electric Company (HECO) (Oahu)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maui Electric Co. (MECO) (Maui)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Hudson Gas &amp; Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated Edison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Island Power Authority (LIPA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York State Electric and Gas (NYSEG)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orange and Rockland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSEGLI (formerly Long Island Power Authority (LIPA))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic City Electric (Conectiv)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSE&amp;G (Public Service Electric and Gas Co.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tucson Electric Power (TEP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sacramento Municipal Utility District (SMUD)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dealer Utility Pricing File</label>
    <nameField>
        <displayFormat>DUPF-{0000}</displayFormat>
        <label>Dealer Utility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Utility Pricing Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Utility_Code__c.object
<CustomObject>
    <description>Case# 00543268 - This object will store utility code and description - Arokia Nathan</description>
    <label>Utility Code</label>
    <nameField>
        <label>Utility Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DealerUtilityPricingFile.cls
public class DealerUtilityPricingFile {

    public static String getPricingFile(Account acc, String utilityCode, String state, String utilityDescription) {
        String pricingFile;      

        List <Dealer_Utility_Pricing_File__c> dupfList = [SELECT Id, 
                Dealer__c, 
                State__c, 
                Utility__c,
                Utility_Code__c, 
                Pricing_File_Name__c 
            FROM Dealer_Utility_Pricing_File__c
            WHERE 
                Pricing_File_Name__c != null
            ORDER BY CreatedDate ASC];
        
        // load utility codes
        Set <String> utilityCodeIdSet = new Set <String>();
        Map <String, Utility_Code__c> nameUtilityCodeMap = new Map <String, Utility_Code__c>();
        for (Dealer_Utility_Pricing_File__c dupf : dupfList) {
            if (dupf.Utility_Code__c != null) {
                utilityCodeIdSet.add(dupf.Utility_Code__c);
            }
        }
        if (utilityCodeIdSet.size() > 0) {
            for (Utility_Code__c uc : [SELECT Id, Name FROM Utility_Code__c WHERE Id IN :utilityCodeIdSet]) {
                nameUtilityCodeMap.put(uc.Name.toUpperCase(), uc);
            }
        }
                    
        final String GRP_DEALER_UTILITY_CODE = 'GRP_DEALER_UTILITY_CODE';    
        final String GRP_DEALER_UTILITY_DESC_STATE = 'GRP_DEALER_UTILITY_DESC_STATE';    
        final String GRP_UTILITY_CODE = 'GRP_UTILITY_CODE';
        final String GRP_UTILITY_DESC_STATE = 'GRP_UTILITY_DESC_STATE';    
        final String GRP_DEALER_STATE = 'GRP_DEALER_STATE';    
        final String GRP_STATE = 'GRP_STATE';    
                
        List <String> groupingList = new List <String>();
        groupingList.add(GRP_DEALER_UTILITY_CODE);
        groupingList.add(GRP_DEALER_UTILITY_DESC_STATE);
        groupingList.add(GRP_UTILITY_CODE);
        groupingList.add(GRP_UTILITY_DESC_STATE);
        groupingList.add(GRP_DEALER_STATE);
        groupingList.add(GRP_STATE);

        Map <String, Map <String, Dealer_Utility_Pricing_File__c>> groupingMap = new Map <String, Map <String, Dealer_Utility_Pricing_File__c>>();
        for (String grouping : groupingList) {
            groupingMap.put(grouping, new Map <String, Dealer_Utility_Pricing_File__c>());
        }
        
        for (Dealer_Utility_Pricing_File__c dupf : dupfList) {
            if (dupf.Dealer__c != null && dupf.Utility_Code__c != null) {
                groupingMap.get(GRP_DEALER_UTILITY_CODE).put(getKey(dupf.Dealer__c, dupf.Utility_Code__c), dupf);
            }
            if (dupf.Dealer__c != null && dupf.Utility__c != null && dupf.State__c != null) {
                groupingMap.get(GRP_DEALER_UTILITY_DESC_STATE).put(getKey(dupf.Dealer__c, dupf.Utility__c, dupf.State__c), dupf);
            }
            if (dupf.Dealer__c == null && dupf.Utility_Code__c != null) {
                groupingMap.get(GRP_UTILITY_CODE).put(getKey(dupf.Utility_Code__c), dupf);
            }
            if (dupf.Dealer__c == null && dupf.Utility__c != null && dupf.State__c != null) {
                groupingMap.get(GRP_UTILITY_DESC_STATE).put(getKey(dupf.Utility__c, dupf.State__c), dupf);
            }
            if (dupf.Dealer__c != null && dupf.Utility_Code__c == null && dupf.Utility__c == null && dupf.State__c != null) {
                groupingMap.get(GRP_DEALER_STATE).put(getKey(dupf.Dealer__c, dupf.State__c), dupf);
            }
            if (dupf.Dealer__c == null && dupf.Utility_Code__c == null && dupf.Utility__c == null && dupf.State__c != null) {
                groupingMap.get(GRP_STATE).put(getKey(dupf.State__c), dupf);
            }
        }

        List <String> codeList = new List <String>();
        if (nameUtilityCodeMap.size() > 0) {
            codeList = new List <String>(nameUtilityCodeMap.keySet());
            // sort the list. we will match the logner code in the for loop
            // example: OH_COLUMBUS, OH_COLUMBUS_SOUTHERN
            // last one will match. i am not breaking for loop after first match
            codeList.sort();
        }
        // GRP_DEALER_UTILITY_CODE
        if (acc != null && acc.Partner_Account__c != null && String.IsNotBlank(utilityCode)) {
            Map <String, Dealer_Utility_Pricing_File__c> fileMap = groupingMap.get(GRP_DEALER_UTILITY_CODE);
            for (String code : codeList) {
                if (utilityCode.startsWithIgnoreCase(code)) {
                    Utility_Code__c uc = nameUtilityCodeMap.get(code);
                    String key = getKey(acc.Partner_Account__c, uc.Id);
                    if (fileMap.containsKey(key)) {
                        pricingFile = fileMap.get(key).Pricing_File_Name__c;
                    }    
                }
            }
        }
        if (String.IsNotBlank(pricingFile)) {
            return pricingFile;
        }
        // GRP_DEALER_UTILITY_DESC_STATE
        if (acc != null && acc.Partner_Account__c != null && String.IsNotBlank(utilityDescription) && acc.Billingstate != null) {
            Map <String, Dealer_Utility_Pricing_File__c> fileMap = groupingMap.get(GRP_DEALER_UTILITY_DESC_STATE);
            String key = getKey(acc.Partner_Account__c, utilityDescription, acc.Billingstate);
            if (fileMap.containsKey(key)) {
                pricingFile = fileMap.get(key).Pricing_File_Name__c;
            }    
        }
        if (String.IsNotBlank(pricingFile)) {
            return pricingFile;
        }
        // GRP_UTILITY_CODE
        if (String.IsNotBlank(utilityCode)) {
            Map <String, Dealer_Utility_Pricing_File__c> fileMap = groupingMap.get(GRP_UTILITY_CODE);
            for (String code : codeList) {
                if (utilityCode.startsWithIgnoreCase(code)) {
                    Utility_Code__c uc = nameUtilityCodeMap.get(code);
                    String key = getKey(uc.Id);
                    if (fileMap.containsKey(key)) {
                        pricingFile = fileMap.get(key).Pricing_File_Name__c;
                    }    
                }
            }
        }
        if (String.IsNotBlank(pricingFile)) {
            return pricingFile;
        }
        // GRP_UTILITY_DESC_STATE
        if (acc != null && String.IsNotBlank(utilityDescription) && acc.Billingstate != null) {
            Map <String, Dealer_Utility_Pricing_File__c> fileMap = groupingMap.get(GRP_UTILITY_DESC_STATE);
            String key = getKey(utilityDescription, acc.Billingstate);
            if (fileMap.containsKey(key)) {
                pricingFile = fileMap.get(key).Pricing_File_Name__c;
            }    
        }
        if (String.IsNotBlank(pricingFile)) {
            return pricingFile;
        }
        // GRP_DEALER_STATE
        if (acc != null && acc.Partner_Account__c != null && acc.Billingstate != null) {
            Map <String, Dealer_Utility_Pricing_File__c> fileMap = groupingMap.get(GRP_DEALER_STATE);
            String key = getKey(acc.Partner_Account__c, acc.Billingstate);
            if (fileMap.containsKey(key)) {
                pricingFile = fileMap.get(key).Pricing_File_Name__c;
            }    
        }
        if (String.IsNotBlank(pricingFile)) {
            return pricingFile;
        }
        // GRP_STATE
        if (acc != null && acc.Billingstate != null) {
            Map <String, Dealer_Utility_Pricing_File__c> fileMap = groupingMap.get(GRP_STATE);
            String key = getKey(acc.Billingstate);
            if (fileMap.containsKey(key)) {
                pricingFile = fileMap.get(key).Pricing_File_Name__c;
            }    
        }
        if (String.IsNotBlank(pricingFile)) {
            return pricingFile;
        }
        // default
        if (String.IsBlank(pricingFile)) {
            pricingFile = Label.CPRToABCFileName;
        }
        return pricingFile;
    }
            
    private static String getKey(String val_1) {
        String key;
        if (String.IsNotBlank(val_1)) {
            key = val_1.toUpperCase();
        }
        return key;
    }
    private static String getKey(String val_1, String val_2) {
        String key;
        if (String.IsNotBlank(val_1) && String.IsNotBlank(val_2)) {
            key = val_1.toUpperCase() + '_' + val_2.toUpperCase();
        }
        return key;
    }
    private static String getKey(String val_1, String val_2, String val_3) {
        String key;
        if (String.IsNotBlank(val_1) && String.IsNotBlank(val_2) && String.IsNotBlank(val_3)) {
            key = val_1.toUpperCase() + '_' + val_2.toUpperCase()  + '_' + val_3.toUpperCase();
        }
        return key;
    }
                
}