objects/Dealer_Utility_Pricing_File__c.object
<CustomObject>
    <description>Mapping of Dealer Name, Utility , State and the Leasing File name</description>
    <fields>
        <fullName>Utility_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case# 00543268 - Unlike the text name of the utility, the encoded name is a unique value that does not change. We will need to capture the encoded name in the quote and match it up with the price file - Arokia Nathan</description>
        <label>Utility Code</label>
        <referenceTo>Utility_Code__c</referenceTo>
        <relationshipLabel>Dealer Utility Pricing Files</relationshipLabel>
        <relationshipName>Dealer_Utility_Pricing_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dealer Utility Pricing File</label>
    <nameField>
        <displayFormat>DUPF-{0000}</displayFormat>
        <label>Dealer Utility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Utility Pricing Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Utility_Code__c.object
<CustomObject>
    <description>Case# 00543268 - This object will store utility code and description - Arokia Nathan</description>
    <label>Utility Code</label>
    <nameField>
        <label>Utility Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DealerUtilityPricingFileTest.cls
@isTest
public class DealerUtilityPricingFileTest {

    private static testMethod void test_DealerUtilityCode() {
        DealerUtilityPricingFileTestData td = new DealerUtilityPricingFileTestData();    
        td.createTestData();

        Utility_Code__c utilityCode_1 = DealerUtilityPricingFileTestData.getNewUtilityCode('CA_ALAMEDA', 'CA', 'Alameda Municpal Power');  
        insert new List <Utility_Code__c>{utilityCode_1};

        // GRP_DEALER_UTILITY_CODE
        Dealer_Utility_Pricing_File__c dupf_1 = DealerUtilityPricingFileTestData.getNewDUPF(td.partnerAccount_1.Id, utilityCode_1.Id, null, null, 'pricing_file_1');
        insert new List <Dealer_Utility_Pricing_File__c>{dupf_1};

        system.assertEquals('pricing_file_1', DealerUtilityPricingFile.getPricingFile(td.account_1, 'CA_ALAMEDA_D1', null, null));            
    }

    private static testMethod void test_DealerUtilityState() {
        DealerUtilityPricingFileTestData td = new DealerUtilityPricingFileTestData();    
        td.createTestData();

        Utility_Code__c utilityCode_1 = DealerUtilityPricingFileTestData.getNewUtilityCode('CA_ALAMEDA', 'CA', 'Alameda Municpal Power');  
        insert new List <Utility_Code__c>{utilityCode_1};

        // GRP_DEALER_UTILITY_DESC_STATE
        Dealer_Utility_Pricing_File__c dupf_1 = DealerUtilityPricingFileTestData.getNewDUPF(td.partnerAccount_1.Id, null, 'CA', 'utility_1', 'pricing_file_1');
        insert new List <Dealer_Utility_Pricing_File__c>{dupf_1};

        system.assertEquals('pricing_file_1', DealerUtilityPricingFile.getPricingFile(td.account_1, 'CA_ALAMEDA_D1', 'CA', 'utility_1'));            
    }

    private static testMethod void test_UtilityCode() {
        DealerUtilityPricingFileTestData td = new DealerUtilityPricingFileTestData();    
        td.createTestData();

        Utility_Code__c utilityCode_1 = DealerUtilityPricingFileTestData.getNewUtilityCode('CA_ALAMEDA', 'CA', 'Alameda Municpal Power');  
        insert new List <Utility_Code__c>{utilityCode_1};

        // GRP_UTILITY_CODE
        Dealer_Utility_Pricing_File__c dupf_1 = DealerUtilityPricingFileTestData.getNewDUPF(null, utilityCode_1.Id, null, null, 'pricing_file_1');
        insert new List <Dealer_Utility_Pricing_File__c>{dupf_1};

        system.assertEquals('pricing_file_1', DealerUtilityPricingFile.getPricingFile(td.account_1, 'CA_ALAMEDA_D1', 'CA', 'utility_1'));            
    }

    private static testMethod void test_UtilityState() {
        DealerUtilityPricingFileTestData td = new DealerUtilityPricingFileTestData();    
        td.createTestData();

        Utility_Code__c utilityCode_1 = DealerUtilityPricingFileTestData.getNewUtilityCode('CA_ALAMEDA', 'CA', 'Alameda Municpal Power');  
        insert new List <Utility_Code__c>{utilityCode_1};

        // GRP_UTILITY_DESC_STATE
        Dealer_Utility_Pricing_File__c dupf_1 = DealerUtilityPricingFileTestData.getNewDUPF(null, null, 'CA', 'utility_1', 'pricing_file_1');
        insert new List <Dealer_Utility_Pricing_File__c>{dupf_1};

        system.assertEquals('pricing_file_1', DealerUtilityPricingFile.getPricingFile(td.account_1, 'CA_ALAMEDA_D1', 'CA', 'utility_1'));            
    }

    private static testMethod void test_DealerState() {
        DealerUtilityPricingFileTestData td = new DealerUtilityPricingFileTestData();    
        td.createTestData();

        Utility_Code__c utilityCode_1 = DealerUtilityPricingFileTestData.getNewUtilityCode('CA_ALAMEDA', 'CA', 'Alameda Municpal Power');  
        insert new List <Utility_Code__c>{utilityCode_1};

        // GRP_DEALER_STATE
        Dealer_Utility_Pricing_File__c dupf_1 = DealerUtilityPricingFileTestData.getNewDUPF(td.partnerAccount_1.Id, null, 'CA', null, 'pricing_file_1');
        insert new List <Dealer_Utility_Pricing_File__c>{dupf_1};

        system.assertEquals('pricing_file_1', DealerUtilityPricingFile.getPricingFile(td.account_1, 'CA_ALAMEDA_D1', 'CA', 'utility_1'));            
    }

    private static testMethod void test_State() {
        DealerUtilityPricingFileTestData td = new DealerUtilityPricingFileTestData();    
        td.createTestData();

        Utility_Code__c utilityCode_1 = DealerUtilityPricingFileTestData.getNewUtilityCode('CA_ALAMEDA', 'CA', 'Alameda Municpal Power');  
        insert new List <Utility_Code__c>{utilityCode_1};

        // GRP_STATE
        Dealer_Utility_Pricing_File__c dupf_1 = DealerUtilityPricingFileTestData.getNewDUPF(null, null, 'CA', null, 'pricing_file_1');
        insert new List <Dealer_Utility_Pricing_File__c>{dupf_1};

        system.assertEquals('pricing_file_1', DealerUtilityPricingFile.getPricingFile(td.account_1, 'CA_ALAMEDA_D1', 'CA', 'utility_1'));            
    }

    private static testMethod void test_NoMatch_NoUtilityCodes() {
        DealerUtilityPricingFileTestData td = new DealerUtilityPricingFileTestData();    
        td.createTestData();

        system.assertEquals(Label.CPRToABCFileName, DealerUtilityPricingFile.getPricingFile(td.account_1, 'CA_ANAHEIM', 'CA', 'utility_1'));            
    }

    private static testMethod void test_NoMatch() {
        DealerUtilityPricingFileTestData td = new DealerUtilityPricingFileTestData();    
        td.createTestData();

        Utility_Code__c utilityCode_1 = DealerUtilityPricingFileTestData.getNewUtilityCode('CA_IID', 'CA', 'Imperial Irrigation District (IID)');  
        insert new List <Utility_Code__c>{utilityCode_1};

        // GRP_STATE
        Dealer_Utility_Pricing_File__c dupf_1 = DealerUtilityPricingFileTestData.getNewDUPF(td.partnerAccount_1.Id, utilityCode_1.Id, 'CA', 'utility_1', 'pricing_file_1');
        insert new List <Dealer_Utility_Pricing_File__c>{dupf_1};

        system.assertEquals(Label.CPRToABCFileName, DealerUtilityPricingFile.getPricingFile(td.account_1, 'CA_ANAHEIM', 'CA', 'utility_2'));            
    }

}