objects/Dealer_Utility_Pricing_File__c.object
<CustomObject>
    <description>Mapping of Dealer Name, Utility , State and the Leasing File name</description>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Utility Pricing Files</relationshipLabel>
        <relationshipName>Dealer_Utility_Pricing_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_File_Name__c</fullName>
        <description>It is the Pricing File name which should be sent to CPR(which in turn sends for ABC)</description>
        <label>Pricing File Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <description>Case# 00543268 - This is formula field refereing to state code of utility code object - Arokia Nathan</description>
        <formula>TEXT(Utility_Code__r.State_Code__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>It contains the State Code</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utility_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case# 00543268 - Unlike the text name of the utility, the encoded name is a unique value that does not change. We will need to capture the encoded name in the quote and match it up with the price file - Arokia Nathan</description>
        <label>Utility Code</label>
        <referenceTo>Utility_Code__c</referenceTo>
        <relationshipLabel>Dealer Utility Pricing Files</relationshipLabel>
        <relationshipName>Dealer_Utility_Pricing_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Name__c</fullName>
        <description>Case# 00543268 - This is formula field refereing to utility name of utility code object - Arokia Nathan</description>
        <formula>Utility_Code__r.Utility_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility__c</fullName>
        <description>It contains Utility information</description>
        <label>Utility</label>
        <picklist>
            <picklistValues>
                <fullName>Anaheim Public Utilities Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azusa Light &amp; Water Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colton Public Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glendale Water &amp; Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Imperial Irrigation District (IID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lompoc, City of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles Department of Water &amp; Power  (LADWP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modesto Irrigation District (MID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moreno Valley Utility (MVU)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific Gas and Electric Company (PG&amp;E)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Riverside Utilities Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Diego Gas &amp; Electric (SDG&amp;E)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern California Edison (SCE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turlock Irrigation District (TID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unisource Energy Services (UES)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii Electric Light Company (HELCO) (Big Island of Hawaii)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaiian Electric Company (HECO) (Oahu)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maui Electric Co. (MECO) (Maui)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Hudson Gas &amp; Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated Edison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Island Power Authority (LIPA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York State Electric and Gas (NYSEG)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orange and Rockland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSEGLI (formerly Long Island Power Authority (LIPA))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic City Electric (Conectiv)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSE&amp;G (Public Service Electric and Gas Co.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tucson Electric Power (TEP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sacramento Municipal Utility District (SMUD)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dealer Utility Pricing File</label>
    <nameField>
        <displayFormat>DUPF-{0000}</displayFormat>
        <label>Dealer Utility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Utility Pricing Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Utility_Code__c.object
<CustomObject>
    <description>Case# 00543268 - This object will store utility code and description - Arokia Nathan</description>
    <fields>
        <fullName>State_Code__c</fullName>
        <description>Case# 00543268 - This field will store 2 char state codes - Arokia Nathan</description>
        <label>State Code</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utility_Name__c</fullName>
        <description>Case# 00543268 - This field will store utility description - Arokia Nathan</description>
        <label>Utility Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Utility Code</label>
    <nameField>
        <label>Utility Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DealerUtilityPricingFileTestData.cls
@isTest
public class DealerUtilityPricingFileTestData {

    @TestVisible private Account partnerAccount_1, partnerAccount_2, account_1;
    
    @TestVisible
    private void createTestData() {
        // partner account
        partnerAccount_1 = new Account();
        partnerAccount_1.Name = 'partnerAccount_1'; 
        partnerAccount_1.BillingStreet = '100 XYZ Plaza';
        partnerAccount_1.BillingCity = 'Sunnyvale';
        partnerAccount_1.BillingState = 'CA';
        partnerAccount_1.BillingCountry = 'United States'; 
        partnerAccount_1.BillingPostalCode = '94086';  

        partnerAccount_2 = new Account();
        partnerAccount_2.Name = 'partnerAccount_2'; 
        partnerAccount_2.BillingStreet = '200 ABC Plaza';
        partnerAccount_2.BillingCity = 'Sunnyvale';
        partnerAccount_2.BillingState = 'CA';
        partnerAccount_2.BillingCountry = 'United States'; 
        partnerAccount_2.BillingPostalCode = '94086';  
        
        insert new List <Account>{partnerAccount_1, partnerAccount_2};  
        
        // Account
        account_1 = new Account();    
        account_1.Name = 'account_1'; 
        account_1.BillingStreet = '300 Test Plaza';
        account_1.BillingCity = 'San Jose';
        account_1.BillingState = 'CA';
        account_1.BillingCountry = 'United States'; 
        account_1.BillingPostalCode = '95086'; 
        account_1.Partner_Account__c = partnerAccount_1.Id; 

        insert new List <Account>{account_1};  
    }
    
    @TestVisible
    private static Utility_Code__c getNewUtilityCode(String name, String stateCode, String utilityName) {
        return new Utility_Code__c(Name = name, State_Code__c = stateCode, Utility_Name__c = utilityName);    
    }
    
    @TestVisible
    private static Dealer_Utility_Pricing_File__c getNewDUPF(String dealerId, String utilityCodeId, String state, 
        String utility, String fileName) {
    
        Dealer_Utility_Pricing_File__c dupf = new Dealer_Utility_Pricing_File__c();
        dupf.Dealer__c = dealerId;
        dupf.Utility_Code__c = utilityCodeId;
        dupf.State__c = state;
        dupf.Utility__c = utility;
        dupf.Pricing_File_Name__c = fileName;
        return dupf;
    }

}