objects/Design__c.object
<CustomObject>
    <fields>
        <fullName>Actual_System_Size__c</fullName>
        <description>What was the actual system size of the drawing?
This field is no longer used. New fields Actual System Size PV and BOS are created for the purpose.</description>
        <label>Actual System Size (kWp)</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Final_Design__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pivot # 127833081</description>
        <label>Final Design</label>
        <type>Checkbox</type>
    </fields>
    <label>Design</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DesignAfterUpdateHandler.cls
public without sharing class DesignAfterUpdateHandler extends TriggerHandlerBase {
    
    private List<Design__c> newList;
    private List<Design__c> oldList;
    private Map<ID, Design__c> newMap;
    private Map<ID, Design__c> oldMap;
    private List<Design__c> finalDesignQualifyList = new List<Design__c>();
    
    public DesignAfterUpdateHandler() {}
    
    public override void qualifyStartingRecords(List<sObject> newList, List<sObject> oldList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
        this.newList = (List<Design__c>)newList;
        this.oldList = (List<Design__c>)oldList;
        this.newMap = (Map<ID, Design__c>)newMap;
        this.oldMap = (Map<ID, Design__c>)oldMap;
        
        for (Integer i=0; i<this.newList.size(); i++) {
            Design__c newDesign = this.newList[i];
            if (this.oldMap != null && newDesign.Id != null && this.oldMap.containsKey(newDesign.Id)) {
                Design__c oldDesign = this.oldMap.get(newDesign.Id); 
                if (newDesign.Final_Design__c != oldDesign.Final_Design__c || newDesign.Actual_System_Size__c != oldDesign.Actual_System_Size__c || newDesign.RecordTypeId != oldDesign.RecordTypeId) {
                    finalDesignQualifyList.add(newDesign);
                }
            }
        }
    }
    
    public override void start() {
        if (finalDesignQualifyList.size() > 0) {
            DesignTriggerUtil.setOpportunitySystemSize(finalDesignQualifyList);
        }
    }
    
    public override void finish(Boolean fromStart) {}

}