objects/Design__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>Text(Opportunity__r.Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>text( Opportunity__r.Country__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSR</label>
        <referenceTo>PSR__c</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site_Information_Form__c</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record Drawings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Exported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Design</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PSR__c.object
<CustomObject>
    <description>Object used to captured information related to a Project Service Request.</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity__r.Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>text(Opportunity__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PSR</relationshipLabel>
        <relationshipName>PSR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>PSR</relationshipLabel>
        <relationshipName>PSR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site_Information_Form__c</referenceTo>
        <relationshipLabel>PSR</relationshipLabel>
        <relationshipName>PSR</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSR</label>
    <nameField>
        <displayFormat>PSR-{000000}</displayFormat>
        <label>PSR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity.Business_Unit__c)</formula>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSR</label>
        <referenceTo>PSR__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Steps__c</fullName>
        <label>Quote Type</label>
        <picklist>
            <picklistValues>
                <fullName>0. Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1. PSR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. PSR In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. PSR Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Proposal Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Approved - Sent to Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Proposal Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgetary Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binding Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Management Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting PV Availability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Single_Line__c.object
<CustomObject>
    <description>Object used to capture high level electrical and single line information for a project.</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>PSR__r.Business_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Single Lines</relationshipLabel>
        <relationshipName>Single_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSR</label>
        <referenceTo>PSR__c</referenceTo>
        <relationshipLabel>Single Lines</relationshipLabel>
        <relationshipName>Single_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Single Lines</relationshipLabel>
        <relationshipName>Single_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site_Information_Form__c</referenceTo>
        <relationshipLabel>Single Lines</relationshipLabel>
        <relationshipName>Single_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Single Line</label>
    <nameField>
        <displayFormat>ES-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Single Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Site_Information_Form__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>TEXT(Opportunity_del__r.Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N30000000t6dPEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Status__c</fullName>
        <description>Field determines the status of a site.</description>
        <label>Site Status</label>
        <picklist>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Comm. Letter signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased/Leased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under evaluation/negotiation</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>SIF{00000}</displayFormat>
        <label>SIF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PSRDateTrigger_Test.cls
@isTest(seeAllData=true)
private class PSRDateTrigger_Test{
    static testMethod void testAddPSRRecord(){
   
    //Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true, isStandard=true);
    //insert pb;
    
    Pricebook2 pb = [Select Id From Pricebook2 Where isActive=true AND isStandard=true Limit 1];

    Product2 product = new Product2();
    product.Name='Test Product';
    product.IsActive=true;
    insert product;

    // Create a pricebook entry for custom pricebook
    PricebookEntry pbe = new PricebookEntry();
    pbe.UseStandardPrice = false;
    pbe.Pricebook2Id=pb.id;
    pbe.Product2Id=product.id;
    pbe.IsActive=true;
    pbe.UnitPrice=99;
    insert pbe;

      //Create Opportunity
    Opportunity opp =new Opportunity();
    opp.name = 'TestOppPSR';  
    opp.StageName= 'Binding Offer';
    opp.Closedate = System.today(); 
    opp.Business_Unit__c = 'UPP Intl';
    opp.country__c='United States';
    insert opp;
    
    Opportunity oppty = [SELECT StageName FROM Opportunity WHERE Id =: opp.Id];
    
    System.debug('+++ Opp Stage: '+oppty.StageName);
    
     //Create Site
    Site_Information_Form__c site =new Site_Information_Form__c();   
    site.Site_Status__c='Active';
    site.opportunity_del__c = opp.ID;
    insert site;
    
    //Create Quote    
    Quote quote = new Quote();
    quote.Name = 'TestQuote';            
    quote.opportunityid =opp.id;
    quote.Quote_Steps__c = 'Array Layout';    
    insert quote; 
           
    //Create PSR record
    PSR__c psr = new PSR__c();
    psr.Quote__c = quote.ID;
    psr.site__c = site.ID;
    psr.opportunity__c = opp.ID;
    psr.PV_Module_Type__c = product.Id;
    psr.Array_Layout__c = false;
    psr.Product_Type__c = 'T-10';
    psr.Module_Type__c = 'SunPower 230'; 
    psr.Requested_System_Size__c = 1000.00;
    psr.Site_Survey_SubContractor__c=false;
    psr.Array_Layout_Due__c = Date.newInstance(2014, 06, 26);
    psr.Electrical_Support_Due__c = Date.newInstance(2014, 07, 28);
    insert psr;
    
    psr.Array_Layout_Due__c = Date.newInstance(2015, 06, 26);
    psr.Electrical_Support_Due__c = Date.newInstance(2015, 07, 28);
    update psr;

    Design__c design = new Design__c();
    design.psr__c =psr.id;
    design.site__c=site.id;
    design.Date_of_Agreed_Delivery__c = Date.newInstance(2001, 06, 26);
    insert design;
    
    design.Date_of_Agreed_Delivery__c = Date.newInstance(2000, 06, 26);
    update design;
    
    psr.Array_Layout_Due__c = design.Date_of_Agreed_Delivery__c;
    update design;
    
    System.assertEquals(psr.Array_Layout_Due__c, Date.newInstance(2000, 06, 26));
    
    design.Date_of_Agreed_Delivery__c = Date.newInstance(2014, 06, 28);
    update design;
    
    psr.Array_Layout_Due__c = design.Date_of_Agreed_Delivery__c;
    update psr;
    
    System.assertEquals(psr.Array_Layout_Due__c, Date.newInstance(2014, 06, 28));
    
    psr.Array_Layout_Due__c = Date.newInstance(2028, 06, 28);
    update psr;
    
    design.Date_of_Agreed_Delivery__c = psr.Array_Layout_Due__c;
    update design;
    Single_Line__c single = new Single_Line__c();
    single.psr__c=psr.id;
    single.design__c=design.id;
    single.site__c=site.id;
    single.status__c='Active';
    single.Negotiated_Due_Date__c = Date.newInstance(2007, 01, 01);
    insert single;
    
    single.Negotiated_Due_Date__c = Date.newInstance(2011, 01, 01);
    update single;
    
    psr.Electrical_Support_Due__c = single.Negotiated_Due_Date__c;
    update psr;
    
    System.assertEquals(psr.Electrical_Support_Due__c, Date.newInstance(2011, 01, 01));
    
    psr.Electrical_Support_Due__c = Date.newInstance(1990, 06, 28);
    update psr;
    
    single.Negotiated_Due_Date__c = psr.Electrical_Support_Due__c;
    update single;
    
    }
}