objects/Design__c.object
<CustomObject>
    <fields>
        <fullName>Roof_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Commercial:
Field added to record information from Helix Design Studio integration
Rel 09 - 2017
PO: Miltos Vratimos</description>
        <label>Roof Design</label>
        <referenceTo>Roof_Design__c</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site_Information_Form__c</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Design</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Loan_Callout_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>AuthURL_Production__c</fullName>
        <description>Auth URL used to launch user into respective Aurora project or design</description>
        <label>AuthURL_Production</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>AuthURL_Sandbox__c</fullName>
        <description>Aurora Authentication Endpoint URL to launch user to respective Project or User</description>
        <label>AuthURL_Sandbox</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <description>Client Secret</description>
        <label>Client Secret</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint_URL_Sandbox__c</fullName>
        <description>Using a different Endpoint URL for Sandbox</description>
        <label>Endpoint_URL_Sandbox</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>Endpoint URL</description>
        <label>Endpoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Redirect_URI_Production__c</fullName>
        <description>Redirect URI for Aurora</description>
        <label>Redirect URI Production</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URI_Sandbox__c</fullName>
        <description>Aurora Redirect URI</description>
        <label>Redirect URI Sandbox</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tenant_Id__c</fullName>
        <description>Used to Store Aurora Tenant ID</description>
        <label>Tenant Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserType_Internal__c</fullName>
        <description>Used to Construct Aurora Auth URL. Created for Aurora Design Integration Project</description>
        <label>UserType_Internal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserType_Partner__c</fullName>
        <description>Used to Construct Aurora Auth URL. Created for Aurora Design Integration Project</description>
        <label>UserType_Partner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Callout Settings</label>
</CustomObject>

objects/Roof_Design__c.object
<CustomObject>
    <fields>
        <fullName>Design_DesignId__c</fullName>
        <description>Field to Save Aurora Design Id</description>
        <externalId>true</externalId>
        <label>Aurora Design Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Commercial:
Field added to record information from Helix Design Request information forms
Rel WW09 - 2017
PO: Miltos Vratimos</description>
        <label>Design</label>
        <referenceTo>Design__c</referenceTo>
        <relationshipLabel>Roof Designs</relationshipLabel>
        <relationshipName>Roof_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roof Design</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Design ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roof Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Site_Information_Form__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Project_Id__c</fullName>
        <description>Commercial: 
Field added to record information from Helix Design Studio integration 
Rel WW09 - 2017 
PO: Miltos Vratimos</description>
        <externalId>true</externalId>
        <label>Internal Project Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>SIF{00000}</displayFormat>
        <label>SIF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AuroraRedirectControllerTestData.cls
@isTest
public class AuroraRedirectControllerTestData {
    public Site_Information_Form__c site_1;
    public Design__c design_1;
    public Roof_Design__c roofDesign_1;
    
    public void createTestData_newInternalProject() {
        Loan_Callout_Settings__c s_1 = getNewCustomSetting();
        insert new List <Loan_Callout_Settings__c>{s_1};
    
        site_1 = createSite(null);
        insert new List <Site_Information_Form__c>{site_1};
    }

    public void createTestData_oldInternalProject() {
        Loan_Callout_Settings__c s_1 = getNewCustomSetting();
        insert new List <Loan_Callout_Settings__c>{s_1};
    
        site_1 = createSite(null);
        site_1.Internal_Project_Id__c = 'testInternalProjectId';
        insert new List <Site_Information_Form__c>{site_1};
    }

    public void createTestData_newDesign_newInternalProject() {
        Loan_Callout_Settings__c s_1 = getNewCustomSetting();
        insert new List <Loan_Callout_Settings__c>{s_1};
    
        site_1 = createSite(null);
        insert new List <Site_Information_Form__c>{site_1};
        
        design_1 = getNewDesign(site_1.Id);
        insert new List <Design__c>{design_1};
    }

    public void createTestData_newDesign_oldInternalProject() {
        Loan_Callout_Settings__c s_1 = getNewCustomSetting();
        insert new List <Loan_Callout_Settings__c>{s_1};
    
        site_1 = createSite(null);
        site_1.Internal_Project_Id__c = 'testInternalProjectId';
        insert new List <Site_Information_Form__c>{site_1};
        
        design_1 = getNewDesign(site_1.Id);
        insert new List <Design__c>{design_1};
    }

    public void createTestData_oldDesign() {
        Loan_Callout_Settings__c s_1 = getNewCustomSetting();
        insert new List <Loan_Callout_Settings__c>{s_1};
    
        site_1 = createSite(null);
        insert new List <Site_Information_Form__c>{site_1};
        
        roofDesign_1 = getNewRoofDesign();
        roofDesign_1.Design_DesignId__c = 'testDesignId';
        insert new List <Roof_Design__c>{roofDesign_1};
        
        design_1 = getNewDesign(site_1.Id);
        design_1.Roof_Design__c = roofDesign_1.Id;
        insert new List <Design__c>{design_1};
    }
    
    private static Site_Information_Form__c createSite(Id opptyId) {
        return TestFactory_Commercial.createBasicSite(opptyId).clone();    
    }
    
    private static Design__c getNewDesign(String siteId) {
        Design__c design = new Design__c();
        design.Site__c = siteId;
        return design;
    }
    
    private static Roof_Design__c getNewRoofDesign() {
        Roof_Design__c roofDesign = new Roof_Design__c();
        return roofDesign;
    }
    
    private static Loan_Callout_Settings__c getNewCustomSetting() {
        Loan_Callout_Settings__c s = new Loan_Callout_Settings__c();
        s.Name = 'Aurora';
        s.AuthURL_Production__c = 'testAuthURLProduction';
        s.AuthURL_Sandbox__c = 'testAuthURLSandbox';
        s.Client_Secret__c = 'testClientSecret';
        s.Endpoint_URL__c = 'testEndpointURL';
        s.Endpoint_URL_Sandbox__c = 'testEndpointURLSandbox';
        s.Redirect_URI_Production__c = 'testRedirectURIProduction';
        s.Redirect_URI_Sandbox__c = 'testRedirectURISandbox';
        s.Tenant_Id__c = 'testTenantId';
        s.UserType_Internal__c = 'testUserTypeInternal';
        s.UserType_Partner__c = 'testUserTypePartner';
        
        return s;
    }
}