objects/Design__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Status__c</fullName>
        <label>Dealer Status</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Request in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Exported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GCR_Requirement__c</fullName>
        <description>Helix Design Request-128905217 Helix Tracker</description>
        <label>GCR Requirement</label>
        <picklist>
            <picklistValues>
                <fullName>0.35</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0.45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0.6</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Roof_Type__c</fullName>
        <label>Roof Type</label>
        <picklist>
            <picklistValues>
                <fullName>Flat Tile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Tile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Shingle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other - see Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Design</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to provide access to documents on the account level</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Commercial:
Field created to link document (attachments) to the design object record</description>
        <label>Design</label>
        <referenceTo>Design__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>Field for TPS - this field will be used to identify the documents uploaded by TPS or any other partner</description>
        <label>Document Type</label>
        <picklist>
            <picklistValues>
                <fullName>12 Month Utility Bills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACP5 - Asbestos Inspection Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance Rebate Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANSI C12 Certified Meter Worksheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appendix A - NY State Interconnection Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appendix B and C - NY State Interconnection Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aurora Deliverables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Acceptance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Design Deliverables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete Design Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed ICF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Incentive Claim Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed SRP Final As-Built Worksheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Final LW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Lien Waiver - DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Lien Waiver - DRIP (Interconnect)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Lien Waiver - IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Lien Waiver - IP (Interconnect)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Progress LW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed ICF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Rebate Reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Rebate Resv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Copy of Property Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countersigned Attachment Rebate Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countersigned Rebate Reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countersigned Schedule A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countersigned SREC Reservation Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Acceptance Form</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Roof_Details__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Roof Details</relationshipLabel>
        <relationshipName>Roof_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Helix Design Request-Commercial project</description>
        <label>Design</label>
        <referenceTo>Design__c</referenceTo>
        <relationshipLabel>Roof Details</relationshipLabel>
        <relationshipName>Roof_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Air_Barrier__c</fullName>
        <description>Commercial:
Field added to record information from Helix Design Request information forms
Rel WW45 - 2016
PO: Miltos Vratimos</description>
        <label>Functional Air Barrier</label>
        <picklist>
            <picklistValues>
                <fullName>Monlithic Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vapor or Air Barrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Existing Roof</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Roof_Membrane__c</fullName>
        <description>Commercial:
Field added to record information from Helix Design Request information forms
Rel WW45 - 2016
PO: Miltos Vratimos</description>
        <label>Roof Membrane</label>
        <picklist>
            <picklistValues>
                <fullName>Fully Adhered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mechanically Attached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballasted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Roof_Type__c</fullName>
        <label>Roof Type</label>
        <picklist>
            <picklistValues>
                <fullName>Built Up Roofing (BUR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modified Bitumen (Mod-Bit)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Ply Membrane - TPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Ply Membrane - PVC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Ply Membrane - Hypalon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Ply Membrane - EPDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR (T.Clear LightGuard Panels or Pavers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR or IRMA Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Polyurethane Foam (PUF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (Please specify)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Roof Details</label>
    <nameField>
        <label>Roof Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roof Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Site_Information_Form__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Site to Account Lookup Relationship</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Site_Information_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N30000000t6dPEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site</label>
    <nameField>
        <displayFormat>SIF{00000}</displayFormat>
        <label>SIF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <recordTypes>
        <fullName>Standard_Site</fullName>
        <active>true</active>
        <description>Use this to create a standard site related to an account and/or opportunity.</description>
        <label>Standard Site</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HelixDesignRequestUtilities.cls
global with sharing class HelixDesignRequestUtilities {

    public transient Map<Decimal, APPR_PUB__Headline__c> headlines {get;set;}
    @TestVisible private final String none = '--None--';

    //Select Options//
    public List<SelectOption> gcrOptions {
        get {
            if(gcrOptions == null) {
                gcrOptions = new List<SelectOption>();
                gcrOptions.add(new SelectOption('', none));
                for(Schema.PicklistEntry p : Design__c.GCR_Requirement__c.getDescribe().getPicklistValues()) {
                    gcrOptions.add(new SelectOption(p.getValue(), p.getLabel()));
                }
            }
            return gcrOptions;
        }
        set;
    }
    public List<SelectOption> roofTypeOptions {
        get {
            if(roofTypeOptions == null) {
                roofTypeOptions = new List<SelectOption>();
                roofTypeOptions.add(new SelectOption('', none));
                for(Schema.PicklistEntry p : Roof_Details__c.Roof_Type__c.getDescribe().getPicklistValues()) {
                    roofTypeOptions.add(new SelectOption(p.getValue(), p.getLabel()));
                }
            }
            return roofTypeOptions;
        }
        set;
    }
    public List<SelectOption> roofMembraneOptions {
        get {
            if(roofMembraneOptions == null) {
                roofMembraneOptions = new List<SelectOption>();
                roofMembraneOptions.add(new SelectOption('', none));
                for(Schema.PicklistEntry p : Roof_Details__c.Roof_Membrane__c.getDescribe().getPicklistValues()) {
                    roofMembraneOptions.add(new SelectOption(p.getValue(), p.getLabel()));
                }
            }
            return roofMembraneOptions;
        }
        set;
    }
    public List<SelectOption> airBarrierOptions {
        get {
            if(airBarrierOptions == null) {
                airBarrierOptions = new List<SelectOption>();
                airBarrierOptions.add(new SelectOption('', none));
                for(Schema.PicklistEntry p : Roof_Details__c.Functional_Air_Barrier__c.getDescribe().getPicklistValues()) {
                    airBarrierOptions.add(new SelectOption(p.getValue(), p.getLabel()));
                }
            }
            return airBarrierOptions;
        }
        set;
    }


    public HelixDesignRequestUtilities (ApexPages.StandardController controller) {
        headlines = new Map<Decimal, APPR_PUB__Headline__c>();

        for(APPR_PUB__Headline__c headline : [SELECT Id, Name, Display_Name__c, 
                                                     APPR_PUB__Long_Description__c, 
                                                     APPR_PUB__Image_Path__c, 
                                                     APPR_PUB__Image_Url__c, 
                                                     APPR_PUB__Tab__c,
                                                     APPR_PUB__Sort_Order__c, 
                                                     APPR_PUB__Active__c 
                                              FROM APPR_PUB__Headline__c
                                              WHERE APPR_PUB__Tab__c = 'DesignRequestForm' 
                                              AND APPR_PUB__Active__c = True]) {
            headlines.put(headline.APPR_PUB__Sort_Order__c, headline);
        }
    }


    /* Remote Action Methods:
    * fetchDesignDocuments() - get the attachments for the design record being referenced 
    *  createNewSite(String siteJSON) - creates new site from JSON payload/JS google map
    * 
    * 
    */

    @RemoteAction
    global static ResultMessage createNewSite(String siteJSON) { //TODO: 

        System.debug('JSON: ' + siteJSON);
        ResultMessage result = new ResultMessage();
        result.success = false;
        result.payloadMap.put('newsite', '');

        try {
            Site_Information_Form__c site = (Site_Information_Form__c)JSON.deserializeStrict(siteJSON, Site_Information_Form__c.class);
            //site.OwnerId = UserInfo.getUserId();  KM_07142017: removing OwnerId field as Opportunity_del__c type was changed to Master-Detail
            site.RecordTypeId = SFDCSpecialUtilities.getRecordTypeIdsByDeveloperName(Site_Information_Form__c.sObjectType).get('Standard_Site');
            site.Account__c = [SELECT AccountId FROM Opportunity WHERE Id =: site.Opportunity_del__c].AccountId;
            insert site;
            result.success = true;
            result.payloadMap.put('newsite', site);
        } catch(Exception e) {
            result.payloadMap.put('error', e.getMessage());
        }
        return result;
    }



    @RemoteAction
    global static ResultMessage fetchDesignDocuments(String designId) {


        String deliveredStatus = 'Design Delivered';
        ResultMessage result = new ResultMessage();
        result.success = true;

        try {
            Design__c des = [SELECT Id, Dealer_Status__c FROM Design__c WHERE Id =: designId];

            result.payloadMap.put('attachments', new List<Attachment>());

            Set<String> docIds = new Set<String>(); 
            for(Document__c d : [SELECT Id, Document_Type__c, CreatedBy.UserType FROM Document__c WHERE Design__c =: designId]) {
                
                if(des.Dealer_Status__c == deliveredStatus && d.Document_Type__c == 'Commercial Design Deliverables')
                    docIds.add(d.Id);
                else {
                    if(d.CreatedBy.UserType == 'PowerPartner')
                        docIds.add(d.Id);
                }
            }
            if(docIds.isEmpty()) {
                return result;
            } else {    
                result.payloadMap.put('attachments', [SELECT Id, Name, ContentType, ParentId, Parent.Name 
                                                      FROM Attachment 
                                                      WHERE ParentId IN: docIds]);                   
                return result;
            }
        } catch(Exception e) {
            result.success = false;
            result.payload.add(e);
        }

        return result;
    }

    public String docIdToDelete {get;set;}
    public PageReference deleteDesignDocuments() {
        System.debug('docIdToDelete: ' + docIdToDelete);

        try {
            delete [SELECT Id FROM Document__c WHERE Id =: docIdToDelete];
        } catch(Exception e) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
            ApexPages.addMessage(msg);
            System.debug('MSG ERROR DELETE: ' + e);
        }
        return null;
    }
    
}