objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>File_Type__c</fullName>
        <label>File Type</label>
        <picklist>
            <picklistValues>
                <fullName>DXF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XML</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/S3_Credentials__c.object
<CustomObject>
    <description>Store S3 key and secret for the AWS account</description>
    <fields>
        <fullName>BucketName__c</fullName>
        <label>BucketName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>Store Key Value</description>
        <label>Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <label>OrgId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <description>Store Secret Value</description>
        <label>Secret</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>S3 Credentials</label>
    <nameField>
        <label>Credentials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>S3 Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestS3DocumentUploadController.cls
@isTest
public class TestS3DocumentUploadController {
    
    public static testmethod void t1() {
        Document__c a = new Document__c(Name= 'TestS3DocUpload', File_Type__c ='PDF');
        insert a;
      
        S3DocumentUploadController s3 = new S3DocumentUploadController(
            new ApexPages.StandardController( a ) );
        
        S3_Credentials__c testKey = new S3_Credentials__c(name='test keys',key__c='key',secret__c='secret', OrgId__c='OrgId__c', BucketName__c='BucketName__c');
        insert testKey;

        s3.AWSCredentialName = testKey.name;
        s3.constructor();
        system.debug( s3.secret + ' '+ s3.key ); 
        system.debug( s3.getpolicy() ); 
        system.debug( s3.getSignedPolicy() ); 
        system.debug( s3.getHexPolicy() ); 
        
        PageReference pageRef = Page.S3DocumentUpload;
        pageRef.getParameters().put('urlParam','https://na22.salseforce.com/services/soap/14.0/c/');
        Test.setCurrentPage(pageRef);
        
        s3.save1();
        s3.page2onLoad(); 
        system.debug( s3.getBucketOptions() );
    }
    
    public static testmethod void t2() {
        Document__c a = new Document__c();
        S3DocumentUploadController s3 = new S3DocumentUploadController(new ApexPages.StandardController( a ) );
        //s3.AWSCredentialName = 'bad key name';
        s3.constructor();
    }

}