objects/Electric_Bill_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Current_Quantity_kWh__c</fullName>
        <label>Current Quantity (kWh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Electric Bill Details</relationshipLabel>
        <relationshipName>Electric_Bill_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Electric Bill Detail</label>
    <nameField>
        <label>Electric Bill Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Electric Bill Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchUpdateQuoteTest.cls
/*********************************************************************
    Test Class For Class "BatchUpdateQuote".
*********************************************************************/
@isTest(seealldata = true) 
private class BatchUpdateQuoteTest{
    
    static testMethod void BatchCloneQSMarked2Test() { 

        List<Quote> lstQ = new List<Quote>();
        Database.BatchableContext BC;
        BatchUpdateQuote batMarkQ = new BatchUpdateQuote();
            
        batMarkQ.Query=' Select id, (select id, quote__c, Current_Quantity_kWh__c from Electric_Bill_Details__r) from quote where createddate >= 2013-06-17T00:00:00.000Z And RecordtypeId=\'01280000000PzNK\' limit 10 ';
            
        Database.executeBatch(batMarkQ, 200);         

        Test.startTest();
          batMarkQ.execute(BC, lstQ);
        Test.stopTest();
                       

    }
}