objects/EnergyProductionYr1__c.object
<CustomObject>
    <description>Aurora- A new object to capture energy production for the first year. This will contain monthly, annual or attachment to hourly energy production estimates from Aurora for year 1. Actual design will also use this object. Quote year 1 will also populate first year production in this field.</description>
    <label>Energy Production Year1</label>
    <nameField>
        <displayFormat>DEP-{0000}</displayFormat>
        <label>Energy Production Year1 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Productions Year1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Roof_Design__c.object
<CustomObject>
    <label>Roof Design</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Design ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roof Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Roof_Details__c.object
<CustomObject>
    <fields>
        <fullName>Roof_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Roof Design</label>
        <referenceTo>Roof_Design__c</referenceTo>
        <relationshipLabel>Roof Details</relationshipLabel>
        <relationshipName>Roof_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Roof Details</label>
    <nameField>
        <label>Roof Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roof Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RoofDesignUtility.cls
//Utility Class for Roof Design
public class RoofDesignUtility {
    
    //Wrapper Class for RoofDesign
    public class RoofDesignWrapper{
        public Roof_Design__c roofDesign{get;set;}
        public EnergyProductionYr1__c energyProdYr1{get;set;}
        public String moduleCount{get;set;}
        public String inverters{get;set;}
        
        public RoofDesignWrapper(Roof_Design__c rDesign,EnergyProductionYr1__c enerProd,String modCount,String inv){
            roofDesign = rDesign;
            energyProdYr1 =enerProd;
            moduleCount = modCount;
            inverters = inv;
        }
    }
    
    //Wrapper Class for Roof Detail
    public class RoofDetailWrapper{
        public Roof_Details__c roofDetail{get;set;}
        public String inverter{get;set;}
        public String module{get;set;}
        public String moduleCount{get;set;}
        
        public RoofDetailWrapper(Roof_Details__c rDetail,String inv,String mod,String modCount){
            roofDetail = rDetail;
            inverter = inv;
            module = mod;
            moduleCount = modCount;
        }
    }
    
}