objects/Estimate__c.object
<CustomObject>
    <description>Object used to capture the required services and high level cost of the project.</description>
    <fields>
        <fullName>Negotiated_Due_Date__c</fullName>
        <label>Negotiated Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_PPP_Review_Tracking_Date__c</fullName>
        <label>PM-PPP Review Tracking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_PPP_Tracking_Date__c</fullName>
        <label>PM-PPP Tracking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Refresh_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Refresh Count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estimate Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Refresh_Estimate_Extension.cls
public class Refresh_Estimate_Extension 
{
  Estimate__c Estimate;
  public ID Estimateid = ApexPages.currentPage().getParameters().get('id');
  
  public Refresh_Estimate_Extension(ApexPages.StandardController stdController)     
  {        
    this.Estimate = (Estimate__c)stdController.getRecord();        
  }
  
  public PageReference Refresh()
  {
    Estimate__c des = [Select Id, Name,Status__c,Refresh_Count__c FROM Estimate__c WHERE id =:Estimateid LIMIT 1];
    Double Rcount = 0;
      Rcount += 1;                               
    if((des.Status__c != 'Completed') && (des.Status__c != 'Invalid') && (des.Status__c != 'De-Activated')) 
    {
      des.Status__c = 'Not Started';
      des.Refresh_Count__c += Rcount;
      //des.Due_Date__c =null;
      des.Negotiated_Due_Date__c =null;
      des.PM_PPP_Tracking_Date__c =null;
      des.PM_PPP_Review_Tracking_Date__c =null;
      update des;
    }
          
    PageReference EstimatePage = new ApexPages.StandardController(Estimate).view();
    EstimatePage.setRedirect(true);
    return EstimatePage;
  }
  
}