objects/Exception_log__c.object
<CustomObject>
    <description>To Capture exception log</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Error Message</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Exception log</label>
    <nameField>
        <label>Exception log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Loan_Callout_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>BackupUrl__c</fullName>
        <description>this field contains the backup url of this api which we need to call when the primary one is down for any reason. for the error code 4, we will call this</description>
        <label>BackupUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BackupZipCodeUrl__c</fullName>
        <description>this field contains the backup url of this api which we need to call when the primary one is down for any reason. for the error code 4, we will call this</description>
        <label>BackupZipCodeUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <description>Store Client ID</description>
        <label>Client ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>Endpoint URL</description>
        <label>Endpoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>NameSpace__c</fullName>
        <description>Namespace for Service Objects</description>
        <label>NameSpace</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipCodeUrl__c</fullName>
        <description>this url is used to call service objects when we get Invalid address from the API call</description>
        <label>ZipCodeUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Callout Settings</label>
</CustomObject>

objects/Sunpower_Spectrum_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sunpower Spectrum Debug Log</relationshipLabel>
        <relationshipName>Sunpower_Spectrum_Debug_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exception_log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Saves the link to the exception logs for Spectrum messages</description>
        <label>Exception log</label>
        <referenceTo>Exception_log__c</referenceTo>
        <relationshipLabel>Sunpower Spectrum Debug Log</relationshipLabel>
        <relationshipName>Sunpower_Spectrum_Debug_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSON_Payload__c</fullName>
        <description>The Payload sent or received from Spectrum.</description>
        <label>JSON Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Status_Code__c</fullName>
        <description>Store Response status code from callouts (ie: 200 for success, 401 for errors, etc.)</description>
        <label>Response Status Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>The response from the Spectrum service or the response sent to Spectrum.</description>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <description>The service that created the log. Inbound Lead, Outbound Lead, Inbound Quote...</description>
        <label>Service</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Sunpower Spectrum Debug Log</label>
    <nameField>
        <label>Sunpower Spectrum Debug Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sunpower Spectrum Debug Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesTaxRateAPICall.cls
public class SalesTaxRateAPICall {
 
    public static List<Sunpower_Spectrum_Debug_Log__c> spectrumDebugList = new List<Sunpower_Spectrum_Debug_Log__c>();
    public static List<Exception_Log__c> exceptionLogList = new List<Exception_Log__c>();
    public static Decimal retrieveSalesTax(String billingStreet,String billingCity,String billingState,String billingPostalCode,Id accId){
        try{
            Loan_Callout_Settings__c mcs = Loan_Callout_Settings__c.getInstance('ServiceObjects');
            String city = billingCity != null ? EncodingUtil.urlEncode(billingCity, 'UTF-8'):'';
            String state = billingState != null ? EncodingUtil.urlEncode(billingState, 'UTF-8'):'';
            String postalcode = billingPostalCode != null ? EncodingUtil.urlEncode(billingPostalCode, 'UTF-8'):'';
            String address = billingStreet != null ? EncodingUtil.urlEncode(billingStreet, 'UTF-8'):'';
            String taxType = 'sales';
            String LicenseKey = mcs.Client_Id__c;
            String url = mcs.Endpoint_URL__c + address + '&City=' + city +'&State=' + state + '&ZipCode=' + postalcode + '&TaxType=' + taxtype + '&LicenseKey=' + LicenseKey;
            String res = callSalesTaxAPI(url,mcs.NameSpace__c,accId);            
            if(res != null && Decimal.valueOf(res) < 1){
                return Decimal.valueOf(res)*100;
            }
            else if(res == '4'){
                 url = mcs.BackupUrl__c + address + '&City=' + city +'&State=' + state + '&ZipCode=' + postalcode + '&TaxType=' + taxtype + '&LicenseKey=' + LicenseKey;
                 res = callSalesTaxAPI(url,mcs.NameSpace__c,accId);
                 if(res != null && Decimal.valueOf(res) < 1){
                    return Decimal.valueOf(res)*100; 
                 }
                 else if(res == '2'){
                    url = mcs.ZipCodeUrl__c + postalcode + '&TaxType=' + taxtype + '&LicenseKey=' + LicenseKey;
                    res = callSalesTaxAPI(url,mcs.NameSpace__c,accId);
                    if(res != null && Decimal.valueOf(res) < 1){
                       return Decimal.valueOf(res)*100;   
                    }
                    else if(res == '4'){
                         url = mcs.BackupZipCodeUrl__c + postalcode + '&TaxType=' + taxtype + '&LicenseKey=' + LicenseKey;
                         res = callSalesTaxAPI(url,mcs.NameSpace__c,accId);
                         if(res != null && Decimal.valueOf(res) < 1){
                            return Decimal.valueOf(res)*100;
                         }
                    } 
                 } 
            }
            else if(res == '2'){
                    url = mcs.ZipCodeUrl__c + postalcode + '&TaxType=' + taxtype + '&LicenseKey=' + LicenseKey;
                    res = callSalesTaxAPI(url,mcs.NameSpace__c,accId);
                    if(res != null && Decimal.valueOf(res) < 1){
                       return Decimal.valueOf(res)*100;   
                    }
                    else if(res == '4'){
                         url = mcs.BackupZipCodeUrl__c + postalcode + '&TaxType=' + taxtype + '&LicenseKey=' + LicenseKey;
                         res = callSalesTaxAPI(url,mcs.NameSpace__c,accId);
                         if(res != null && Decimal.valueOf(res) < 1){
                            return Decimal.valueOf(res)*100;
                         }
                    }
            }    
        }
        catch(Exception e){
            Exception_Log__c exceptionLog = new Exception_Log__c();
            exceptionLog.Account__c = accId;
            exceptionLog.Error_Message__c = e.getMessage();
            exceptionLog.Stack_Trace__c = e.getStackTraceString();
            exceptionLog.Type__c = 'SalesTaxRateAPICall';
            exceptionLogList.add(exceptionLog);
            system.debug('Error is '+e.getMessage()+ ' and stack trace is '+e.getStackTraceString());
            return null;
        }
        return null;
    }
    
    public static String callSalesTaxAPI(String url,String nameSpace,Id accId){
        String response = null;
        HttpRequest request = new HttpRequest(); 
        request.setEndpoint(url);
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/xml');
        request.setTimeout(60000);
        Http http1 = new Http();
        HttpResponse res = http1.send(request); 
        if(res != null && res.getStatusCode() == 200){
            String stringResponse = res.getBody();
            system.debug('response is '+stringResponse);
            Dom.Document doc = res.getBodyDocument();
            Dom.XMLNode addressResponse = doc.getRootElement();
            Dom.XmlNode Error = addressResponse.getChildElement('Error', nameSpace);
            if(Error == null){
                if(stringResponse != null && stringResponse.contains('TotalTaxRate'))
                  response = stringResponse.subString(stringResponse.indexOf('<TotalTaxRate>')+14,stringResponse.indexOf('</TotalTaxRate>'));
            }
            else if(Error != null && Error.getChildElement('Number', nameSpace) != null){
                response = Error.getChildElement('Number', nameSpace).getText();
            }
        }
        
        Sunpower_Spectrum_Debug_Log__c debugLog = new Sunpower_Spectrum_Debug_Log__c();
        debugLog.JSON_Payload__c = url;
        debugLog.Account__c = accId;
        debugLog.Response__c = res != null ? res.getBody():null;
        debugLog.Response_Status_Code__c = res != null ? res.getStatusCode():null; 
        debugLog.Service__c = 'SalesTaxRateAPICall';
        spectrumDebugList.add(debugLog); 
        return response;
    }
}