objects/Exclusive_Zip_codes__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Aaland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antartica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ascension Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benelux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Look up to Partner Account</description>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ALR_Exclusivities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zip_code__c</fullName>
        <externalId>true</externalId>
        <label>Zip code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Exclusive  Zip codes</label>
    <nameField>
        <displayFormat>X-{00000}</displayFormat>
        <label>Exclusive  Zip code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusive  Zip codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCheckDupExclusivPartner.cls
@isTest(SeeAllData=true)
private class TestCheckDupExclusivPartner {

    static testMethod void Test_CheckDupExclusivPartner (){
  
    map<String,Exclusive_Zip_codes__c> mapZipcodeExclusive = new map<String,Exclusive_Zip_codes__c>();
    List <Exclusive_Zip_codes__c> ExZipRslt = new List <Exclusive_Zip_codes__c>();
    String recType1 = [SELECT id FROM recordtype WHERE name='Partner' and Sobjecttype = 'Account' limit 1].id;
    
    Account objP1 = new Account(Name = 'test22',recordtypeId=recType1, BillingStreet='Adriatic Way', BillingCity='Santa Clara', BillingState='CA', BillingPostalCode='95051', BillingCountry='United States',Theater__c ='North America',Phone='1234567895',Type='Elite-Partner-Combo');
    
    Insert objP1;
    
     date myDate = System.Today();  
     
     List<Exclusive_Zip_codes__c> InsertList = new List<Exclusive_Zip_codes__c>();
  try{  
    for(Integer i=0;i<5; i++){
         Exclusive_Zip_codes__c objZipCode = new Exclusive_Zip_codes__c();
         objZipCode.Partner__c =objP1.Id;
         objZipCode.Country__c = 'United States';
         objZipCode.Zip_code__c = '95051';
         if(i == 0 || i == 1){
             objZipCode.Start_Date__c = null;
             objZipCode.End_Date__c = null;
         }
         else if (i == 2){
            date newDate = mydate.addDays(2);
            objZipCode.Start_Date__c = null;
            objZipCode.End_Date__c = newDate;
         }
         else if (i == 3){
            date newDate = mydate.addDays(1);
            objZipCode.Start_Date__c = newDate;
            objZipCode.End_Date__c = mydate;
         }   
         else if (i == 4){
            date newDate = mydate.addDays(1);
            objZipCode.Start_Date__c = newDate;
            objZipCode.End_Date__c = null;
         }       
         InsertList.add(objZipCode);
     }
 
    if(InsertList.size() > 0){
        insert InsertList;
    }
  }catch(Exception ex){
  }
   
  }    
 
}