objects/Fee_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Commision__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Partner gets different commission based on different selling price ranges.</description>
        <label>Commission</label>
        <precision>5</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <description>It&apos;s picklist field to store the deal type . Distribution fee vary for different deal type.</description>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fixed_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <description>It&apos;s a fixed fee for partner . It depend on partner role and deal Type.</description>
        <label>Fixed Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MaxFit_Reduction__c</fullName>
        <defaultValue>0</defaultValue>
        <description>It&apos;s being used to reduce the amount from the Partner Commision if partner opt for MaxFit in the state.</description>
        <label>MaxFit Reduction</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Module_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to module for Module based pricing.</description>
        <label>Module Configuration</label>
        <referenceTo>Module_Configuration__c</referenceTo>
        <relationshipLabel>Fees Distribution</relationshipLabel>
        <relationshipName>Fees_Distribution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <description>Every Fee Distributuin should be associated</description>
        <label>Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fees Distribution</relationshipLabel>
        <relationshipName>Fees_Distribution</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Role__c</fullName>
        <description>Its a field to define a partner role . Partner&apos;s Fee structure can be different based on his role in the deal</description>
        <label>Partner Role</label>
        <picklist>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Split_Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <description>this is created to  tell what percentage of sold price- minimum price should be given to dealer</description>
        <label>Split Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Fee Distribution</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Fee Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees Distribution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Installation_Model__c.object
<CustomObject>
    <fields>
        <fullName>Financing_Option__c</fullName>
        <description>Financing Option picklist field created for Loan Backend</description>
        <label>Financing Option</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Business Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Indirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <description>Partner Roles Muti picklist field created for Loan backend</description>
        <label>Roles</label>
        <picklist>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>If Auto, Installation Model will be automatically assigned if criteria are met. If Manual, a user will need to manually assign the Installation Model</description>
        <label>Assignment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Auto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Installation Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <formula>CASE(Opportunity.Type_of_Installation__c,
&quot;Standard&quot;,&quot;Standard&quot;,
&quot;Access (Lease)&quot;,&quot;Access (Lease)&quot;,
&quot;Select (Options)&quot;,&quot;Select (Options)&quot;,&quot;update opportunity record&quot;) &amp; &quot; - &quot; &amp;CASE(Opportunity.Type_of_Building__c,
&quot;Production Home Community&quot;,&quot;Production Home Community&quot;,
&quot;Retrofit Home&quot;,&quot;Retrofit Home&quot;,
&quot;Multi-Family&quot;,&quot;Multi-Family&quot;,
&quot;Commercial&quot;,&quot;Commercial&quot;,&quot;update opportunity record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installation_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Installation Model. Created for Loan Backend Project</description>
        <label>Installation Model</label>
        <referenceTo>Installation_Model__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Quote_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This controls whether the entire quote is locked.</description>
        <inlineHelpText>This controls whether the entire quote is locked.</inlineHelpText>
        <label>Is Quote Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum_Rated_Capacity_Watts__c</fullName>
        <description>This is a field which contains the Maximum Rated capacity in Watts to be used on Workflow Email Template</description>
        <formula>VALUE(Module_Oracle_Item_Number__r.Item_Category_3__c) * Module_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maximum Rated Capacity (Watts)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Rated_Capacity__c</fullName>
        <description>NH- moved from PLI configurator</description>
        <formula>VALUE(Module_Oracle_Item_Number__r.Item_Category_3__c)  *  Module_Count__c  * 0.001</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maximum Rated Capacity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Id__c</fullName>
        <formula>Account__r.Partner_Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteType__c</fullName>
        <description>Project: GPP
Description: Type of Quote(Lease/Cash)</description>
        <inlineHelpText>Type of Quote(Lease/Cash)</inlineHelpText>
        <label>QuoteType</label>
        <picklist>
            <picklistValues>
                <fullName>Lease</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Cost__c</fullName>
        <label>System Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>System_Model__c</fullName>
        <label>System Model</label>
        <picklist>
            <picklistValues>
                <fullName>230W (Model SPR-230E-WHT-D)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>230W (Model SPR-230NE-BLK-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>245W (Model SPR-245NE-WHT-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>308W (Model SPR-308E-WHT-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>327W (Model SPR-327NE-WHT-D)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Partner_Role__c</fullName>
        <label>Partner Role</label>
        <picklist>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>text( Contact.Account.Type )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Dealerfee_cal_Utility_ModelBased.cls
/* **************************************************************************************
* Class Name     : Dealer_fee_calculation_Utility
* Version        : 1.0
* Created Date   : 12 Aug 2015
* Function       : It's a class to calculate different Dealer's Fee

* Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------
* Ankit                        12 Aug 2015          Original Version
*************************************************************************************/
public class Dealerfee_cal_Utility_ModelBased {

  public static List<Opportunity> lstOpp;
  public static List<Quote> lstQuote;
  public static Map<Id,Installation_Model__c> mInstallationModel ;
  public static Map<Id,Account> mAccounts ;
  public static Map<string,Id> mPartnerRoleWithAccId;
  public static Fee_Distribution__c fdTPS;

/*
@Name        : fIdentifiedRoleAndRelatedPartners
@description : It's function to identify OpportunityTeamMember Partner and thier Role. It call the fucntion to calcualte the Fee and return the Quote.
@parameters  :  List <Quote> lQuote
@returns     :  List <Quote> lQuote.
*/
public static Set<Quote> fIdentifiedRoleAndRelatedPartners (Map <Id,Quote> mQuote){
        System.debug('----->Inside fIdentifiedRoleAndRelatedPartners');
        set<Id> sRelatedUserId  = new set<Id>();   //  Set to store the UserId of all OpportunityTeamMember
        set<Id> sRelatedModelId = new set<Id> ();
        set<Id> sRelatedPartnerId = new set<Id>();  // set to store the related partner Id for a OpportunityTeamMember
        set<Id> sOppId = new set<Id> (); // set to store all the Opportunities Id related to a quote.
        set<Id> sAccId = new set<Id>();
        lstQuote = mQuote.values();  // assign the list of Quote to Static variable for later use
        mPartnerRoleWithAccId = new Map<string,Id> ();
        set<Quote> sQuoteToUpdate = new set<Quote> ();

        for (Quote Q : lstQuote){    //  Looping through the Quote and populte the set of Opportuniyt.
             sRelatedModelId.add(Q.Installation_Model__c);
          }

        mInstallationModel = new Map<Id,Installation_Model__c>([select id,name,Financing_Option__c,Partner__c,Roles__c,Type__c from Installation_Model__c where Id IN : sRelatedModelId ]);
        system.debug('installation' + mInstallationModel);

        if(mInstallationModel.isEmpty())
             return null ;

        for(Quote Q : lstQuote){
           if(mInstallationModel.get(Q.Installation_Model__c).Type__c <> 'Auto')
               sOppId.add(Q.OpportunityId);
           }

       if(sOppId.isEmpty())
            return null;

        // Querying the data frmo Oppteammember, Opp and Related Quotes.
        lstOpp = [select Id,name,Partner_Account_Id__c,Partner_Account_Id__r.NH_SSE_Type__c,Account.BillingState,
                                    (select Id,OpportunityId, TeamMemberRole,User.ContactId,User.Contact.AccountId from OpportunityTeamMembers where User.ContactId <> Null),
                                    (select Id,Name,opportunityId,Maximum_Rated_Capacity__c,Installation_Model__c,QuoteType__c,System_Cost__c,System_Model__c,
                                      Maximum_Rated_Capacity_Watts__c,Is_Locked__c,Is_Quote_Locked__c from Quotes where Id IN : mQuote.keySet())
                                     from Opportunity where Id =: sOppId ];

          for(Opportunity opp : lstOpp){
              for(OpportunityTeamMember oOTM : opp.OpportunityTeamMembers){
                sAccId.add(oOTM.User.Contact.AccountId);
              }
          }

         mAccounts = new map<Id,Account> ([select id,name,billingState,(select Commision__c,
                                                     Deal_Type__c, Name, Fixed_Fee__c,  Partner_Name__c,
                                                     Partner_Role__c, Id,Split_Percentage__c,MaxFit_Reduction__c,Module_Configuration__r.Name,State__c,Selling_Price_Max__c, Selling_Price_Min__c FROM Fees_Distribution__r where Deal_Type__c=:lstQuote[0].QuoteType__c) from Account where Id IN : sAccId]);

        system.debug('---mAccounts---' + mAccounts);

        for(Opportunity opp : lstOpp){

                    for(Quote Q : opp.Quotes){
                            Quote otriggerQuote = mQuote.get(Q.Id);
                            for(OpportunityTeamMember oOTM : opp.OpportunityTeamMembers){
                                    boolean bIsError = true;
                                    mPartnerRoleWithAccId.put(oOTM.TeamMemberRole=='Opportunity Owner'?'TPS':oOTM.TeamMemberRole,oOTM.User.Contact.AccountId);
                                 if(mAccounts.get(oOTM.user.contact.accountId).Fees_Distribution__r == Null || mAccounts.get(oOTM.user.contact.accountId).Fees_Distribution__r.size() == 0)
                                     otriggerQuote.addError('Fee distribution are not setup for ' + mAccounts.get(oOTM.user.contact.accountId).Name);
                                 for(Fee_Distribution__c oFD : mAccounts.get(oOTM.user.contact.accountId).Fees_Distribution__r){
                                        system.debug('==TeamMemberRole===' + oOTM.TeamMemberRole +'==oFD.Partner_Role__c===' + oFD.Partner_Role__c  );
                                        system.debug('---state account---' + opp.account.BillingState + '----state FD----' + oFD.state__c );
                                        system.debug('---QUOTE Model------' + otriggerQuote.System_Model__c +'-----FD Model-----'+oFD.Module_Configuration__r.Name);
                                    if( ((oFD.Partner_Role__c == oOTM.TeamMemberRole &&  mInstallationModel.get(otriggerQuote.Installation_Model__c).Roles__c.contains(oOTM.TeamMemberRole))|| (oOTM.TeamMemberRole == 'Opportunity Owner' && oFD.Partner_Role__c == Label.TPS_Partner_Role)) && otriggerQuote.System_Model__c == oFD.Module_Configuration__r.Name && opp.account.BillingState == oFD.state__c) {
                                              sQuoteToUpdate.add(fcalculateFees((Quote)Trigger.newMap.get(otriggerQuote.Id),oFD,oOTM.TeamMemberRole));
                                              system.debug('==Inside===' + oOTM.TeamMemberRole);
                                              bIsError = false;
                                        }
                                 }
                            if(bIsError)
                              fDetectErrors(otriggerQuote,opp);
                          }
                      }
                   }
             system.debug('---TPS Debug----'+ mQuote);
             return sQuoteToUpdate;
       }

/*
@Name        :  fCalculateFees
@description :  It's function to calculate the fee based on Partner role in the related opp.
@parameters  :  Quote Q,Fee_Distribution__c oFD,String sPartnerRole
@returns     :  Quote
*/

  static Quote fCalculateFees(Quote Q,Fee_Distribution__c oFD,String sPartnerRole){
            if(oFD.Partner_Role__c=='TPS')
                fdTPS=oFD;
             system.debug('--------' + Q.Maximum_Rated_Capacity_Watts__c + '------' + oFD.Split_Percentage__c);
            if(Q.Maximum_Rated_Capacity_Watts__c <> Null && oFD.Split_Percentage__c <> Null ){

              decimal iPricePerWatt = (Q.System_Cost__c - Q.Adder_Fee__c)/ Q.Maximum_Rated_Capacity_Watts__c;
                system.debug('----------' + iPricePerWatt);
                if(iPricePerWatt >= oFD.Selling_Price_Min__c){
                    system.debug('----------' + oFD.Fixed_Fee__c+'----------' +Q.Maximum_Rated_Capacity_Watts__c+'----------' +oFD.Commision__c+'----------' +iPricePerWatt+'----------' +oFD.Selling_Price_Min__c+'----------' +oFD.Split_Percentage__c+'----------' +oFD.MaxFit_Reduction__c);
                     double dfees = (oFD.Fixed_Fee__c + (Q.Maximum_Rated_Capacity_Watts__c * ((oFD.Commision__c +((iPricePerWatt - oFD.Selling_Price_Min__c) * oFD.Split_Percentage__c)/100) - oFD.MaxFit_Reduction__c))) ;
                    Q.put(Quote_Fees_Fields_API__c.getInstance(sPartnerRole=='Opportunity Owner'?'TPS':sPartnerRole).Field_API_Name__c,dfees) ;
                  system.debug('-----dfee-----' + dfees + '----sPatnerRole----'+ sPartnerRole);
                }
            }

      return Q;
    }

    /*
    @Name        :  fCalculateFees
    @description :  It's function to calculate the fee based on Partner role in the related opp.
    @parameters  :  Quote Q,Fee_Distribution__c oFD,String sPartnerRole
    @returns     :  Quote
    */

    static void fDetectErrors (Quote oQuote, Opportunity oOpp){

          string sfinalError = ''; boolean bisError = true;
          Map<string,OpportunityTeamMember> mOppTeamMem = new Map<string,OpportunityTeamMember> ();

          for(OpportunityTeamMember oOppTeamMember : oOpp.OpportunityTeamMembers){
                 if(!mOppTeamMem.containsKey(oOppTeamMember.TeamMemberRole))
                     mOppTeamMem.put(oOppTeamMember.TeamMemberRole,oOppTeamMember);
            }

          for(OpportunityTeamMember oOTM : mOppTeamMem.values()){
                   boolean bModuleFound = true; boolean bStatefound = true;  boolean bPartnerRole = true;
                   string sError;
                   for(Fee_Distribution__c oFD : mAccounts.get(oOTM.user.contact.accountId).Fees_Distribution__r){
                          if(oFD.Module_Configuration__r.Name == oQuote.System_Model__c)
                                bModuleFound = false;
                          if(oFD.state__c == oOpp.account.billingState)
                                bStatefound = false;
                          if(oFD.Partner_Role__c == oOTM.TeamMemberRole || oFD.Partner_Role__c == 'TPS')
                                bPartnerRole = false;
                      }
                  if(bModuleFound){
                      bisError = true;
                      sfinalError = sfinalError + oQuote.System_Model__c +' Module not defined in FD for for Account: ' + mAccounts.get(oOTM.user.contact.accountId).Name + ';';
                     }
                  if(bStatefound){
                      bisError = true;
                      sfinalError = sfinalError + oOpp.account.billingState +' State not defined in FD for Account: ' + mAccounts.get(oOTM.user.contact.accountId).Name + ';';
                   }
                  if(bPartnerRole){
                      bisError = true;
                      sfinalError = sfinalError + oOTM.TeamMemberRole +' Role not defined in FD for Account: ' + mAccounts.get(oOTM.user.contact.accountId).Name + ';';
                   }
          }
        if(bIsError){
            if(sfinalError <> null && sfinalError <> '')
              oQuote.addError(sfinalError);
            else
              oQuote.addError('Fee distribution is not defined for related module,state,and Partner role.');
         }
      }

   /*
     @Name        :  fMinSellingPriceCheck
     @description : function to check the minimum price for the Quote
     @parameters  :  Quote
     @returns     :  boolean
   */
   public static boolean fMinSellingPriceCheck ( Quote Q){
            system.debug('----Quote-Ankit------' + Q);
              if(Q.adder_fee__c == Null )
                  Q.adder_fee__c = 0;
              double QuoteSellingPrice =  (Q.System_Cost__c - Q.adder_fee__c)/(double.valueof(Q.Module_Oracle_Item_Number__r.Item_Category_3__c) * Q.Module_Count__c);
            // double sFDMinSellingPrice = [select Selling_Price_Min__c from Fee_Distribution__c where Partner_Name__c =: Q.Opportunity.Partner_Account_Id__c AND Deal_Type__c =:Q.QuoteType__c AND Rank__c = '1'].Selling_Price_Min__c;
              List<Fee_Distribution__c> lstFD = [select Selling_Price_Min__c from Fee_Distribution__c where Partner_Name__c =: Q.Opportunity.Partner_Account_Id__c AND Deal_Type__c =:Q.QuoteType__c AND State__c =: Q.Opportunity.Account.BillingState AND Module_Configuration__r.Name =: Q.System_Model__c Limit 1];
             // system.debug('---QuoteSellingPrice----'+ QuoteSellingPrice + '-------sFDMinSellingPrice------' + sFDMinSellingPrice);
              system.debug('----lstFD------' + lstFD);
             if (lstFD <> Null && lstFD.size() > 0) {
                   if (QuoteSellingPrice < lstFD[0].Selling_Price_Min__c )
                          return true;
                      else
                         return false;
               }
               else {
                       ApexPages.addMessage( new ApexPages.Message( ApexPages.Severity.Error,Label.TPS_Fee_Distribution_does_not_exist) );
                       return true;
                     }
         }
  }