objects/FMV_Rate__c.object
<CustomObject>
    <description>This object houses $/watt rates used for calculating Fair Market Value. Each rate record holds a single rate for a specified set of criteria (Financier, Date, State, Lease Type, System Size).</description>
    <fields>
        <fullName>FMV_Rate__c</fullName>
        <description>This is the FMV $ per watt rate that is applicable to the given set of criteria (other fields on the rate object)</description>
        <label>FMV Rate</label>
        <precision>9</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financier__c</fullName>
        <label>Financier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <description>This field indicates whether the FMV rate is for monthly or pre-paid leases</description>
        <label>Lease Type</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>FMV Rate</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>FMV Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FMV Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LeasePayment__c.object
<CustomObject>
    <fields>
        <fullName>Date_Countersigned__c</fullName>
        <formula>IF( NOT(ISBLANK(Date_Countersigned_old__c  )) , Date_Countersigned_old__c,Quote__r.Lease_doc_Signed_Date__c   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Countersigned</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Countersigned_old__c</fullName>
        <label>Date Countersigned old</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FMV_Rate__c</fullName>
        <description>This is the FMV $/watt rate that is used by to calculate Fair Market Value. This field is populated by a Apex trigger that fires when Placed in service is populated.</description>
        <label>FMV Rate</label>
        <precision>9</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funding_Tranche__c</fullName>
        <label>Financier</label>
        <picklist>
            <picklistValues>
                <fullName>Access 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConEdison Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corona Sands, LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helios II Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helios Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinite Sunshine 2015-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lux II Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lux Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mosaic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photon Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR-ITC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR MS 2013-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR – Non US Treasury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR SG 2013-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR SR 2013-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR USB 2013-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR USB 2013-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR USB 2013-3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunPower Capital LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunPower Residential I LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunpower Resi II, LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunrise 2 LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunrise 3 LLC</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <formula>IF(NOT(ISBLANK( Lease_Type_old__c)), Lease_Type_old__c, ((IF( Full_Prepayment_Amt__c &gt; 0, &quot;Prepaid&quot;, &quot;Monthly&quot; ))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lease Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Type_old__c</fullName>
        <label>Lease Type old</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placed_In_Service__c</fullName>
        <label>Placed In Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_State_Prov__c</fullName>
        <formula>IF(  NOT(ISBLANK( Site_State_Prov_old__c )) ,Site_State_Prov_old__c ,  End_Customer_Account__r.BillingState   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site State/Prov</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_State_Prov_old__c</fullName>
        <label>Site State/Prov old</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <label>Financial Payment</label>
    <nameField>
        <label>Financial Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestLeasePaymentTrigger.cls
@isTest
private class TestLeasePaymentTrigger {
    static testMethod void testApplyFMVRateOnUpdate()
    {
        SFDCSpecialUtilities.isRunningTest = True;  
        
        final String LEASE_TYPE = 'some type';
        final String STATE = 'MI';
        final Double RATE = 1.23;

        TestLeasePaymentSetup.setup();
        TestLeasePaymentSetup.setupFinancierCustomSettings();

        FMV_Rate__c testRate1 = TestUtils.createRate(TestLeasePaymentSetup.currentDate.addDays(-2), TestLeasePaymentSetup.currentDate.addDays(2), STATE, RATE, false);
        testRate1.Financier__c = TestLeasePaymentSetup.FINANCIER;
        testRate1.Lease_Type__c = LEASE_TYPE;
        insert testRate1;

        List<LeasePayment__c> leasePayments = TestUtils.createLeasePayments(1, TestLeasePaymentSetup.newAccount.Id, false);
        leasePayments[0].Date_Countersigned_old__c = TestLeasePaymentSetup.currentDate;
        leasePayments[0].Site_State_Prov_old__c = STATE;
        leasePayments[0].Funding_Tranche__c = TestLeasePaymentSetup.FINANCIER;
        leasePayments[0].Lease_Type_old__c = LEASE_TYPE;

        insert leasePayments;
        leasePayments = [SELECT Lease_Type__c, Funding_Tranche__c, Site_State_Prov__c, Date_Countersigned__c, Placed_In_Service__c FROM LeasePayment__c WHERE Id IN :leasePayments];
        
        Test.startTest();
            leasePayments[0].Placed_In_Service__c = TestLeasePaymentSetup.currentDate;
            update leasePayments;        
        Test.stopTest();
        
        List<LeasePayment__c> actualLeasePayments = [SELECT FMV_Rate__c FROM LeasePayment__c WHERE Id IN :leasePayments];
        //System.assertEquals(RATE, actualLeasePayments[0].FMV_Rate__c, 'The rate should have been updated');
    }

    static testMethod void testApplyFMVRateOnUpdate_Bulk()
    {
        SFDCSpecialUtilities.isRunningTest = True;  
        
        final String LEASE_TYPE = 'some type';
        final String STATE = 'MI';
        final Double RATE = 1.23;
        final Integer NUM_LEASEPAYMENTS = 50;

        TestLeasePaymentSetup.setup();
        TestLeasePaymentSetup.setupFinancierCustomSettings();

        FMV_Rate__c testRate1 = TestUtils.createRate(TestLeasePaymentSetup.currentDate.addDays(-2), TestLeasePaymentSetup.currentDate.addDays(2), STATE, RATE, false);
        testRate1.Financier__c = TestLeasePaymentSetup.FINANCIER;
        testRate1.Lease_Type__c = LEASE_TYPE;
        insert testRate1;

        List<LeasePayment__c> leasePayments = TestUtils.createLeasePayments(NUM_LEASEPAYMENTS, TestLeasePaymentSetup.newAccount.Id, false);
        for(LeasePayment__c leasePayment : leasePayments) {
            leasePayment.Date_Countersigned_old__c = TestLeasePaymentSetup.currentDate;
            leasePayment.Site_State_Prov_old__c = STATE;
            leasePayment.Funding_Tranche__c = TestLeasePaymentSetup.FINANCIER;
            leasePayment.Lease_Type_old__c = LEASE_TYPE;
        }

        insert leasePayments;

        leasePayments = [SELECT Lease_Type__c, Funding_Tranche__c, Site_State_Prov__c, Date_Countersigned__c, Placed_In_Service__c FROM LeasePayment__c WHERE Id IN :leasePayments];

        Test.startTest();
            for(LeasePayment__c leasePayment : leasePayments) {
                leasePayment.Placed_In_Service__c = TestLeasePaymentSetup.currentDate;
            }
            update leasePayments;
        Test.stopTest();
        
        List<LeasePayment__c> actualLeasePayments = [SELECT FMV_Rate__c FROM LeasePayment__c WHERE Id IN :leasePayments];
        //System.assertEquals(NUM_LEASEPAYMENTS, actualLeasePayments.size(), 'None of the lease payments should be deleted');
        /*for(LeasePayment__c leasePayment : actualLeasePayments) {
            System.assertEquals(RATE, leasePayment.FMV_Rate__c, 'The rate should have been updated');
        }*/
        
    }
}