objects/FPO_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Item_Number__c</fullName>
        <description>TPS Phase 2- This field will capture the service line item number</description>
        <label>Item Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Payment__c</fullName>
        <label>Lease Payment</label>
        <referenceTo>LeasePayment__c</referenceTo>
        <relationshipLabel>FPO Order Lines</relationshipLabel>
        <relationshipName>FPO_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>FPO Order Line</label>
    <nameField>
        <displayFormat>FPOL-{000000}</displayFormat>
        <label>FPO Order Lines Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FPO Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LeasePayment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>This Was made Master Detail as the LEase Payment was made private to avoid any visibility issues.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Payment</label>
    <nameField>
        <label>Financial Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestFPOOrderRedirect.cls
@isTest
private class TestFPOOrderRedirect
{
    // NOTE: Partner users don't have permissions to Read/Write the FPO_Order_Line object. Without that,
    // tests running as partner users fail. Only non-partner users are tested here.
	@isTest
	static void testNew()
	{
		FPO_Order_Line__c myDoc = new FPO_Order_Line__c();
		ApexPages.StandardController sc = new ApexPages.StandardController(myDoc);

		FPOOrderNewRedirect redirect = new FPOOrderNewRedirect(sc);
		PageReference pr = redirect.redirect();
		System.assert(pr != null);
	}

	@isTest
	static void testDetail()
	{
		Account testPartner = TestClassFactory.CreateDealer('TestDealer', 'North America');

		LeasePayment__c lp = new LeasePayment__c();
		lp.Account__c = testPartner.Id;
		insert lp;

		FPO_Order_Line__c myDoc = new FPO_Order_Line__c();
		myDoc.Item_Number__c = 'Item';
		myDoc.Lease_Payment__c = lp.Id;
		insert myDoc;

		ApexPages.StandardController sc = new ApexPages.StandardController(myDoc);

		FPOOrderRedirect redirect = new FPOOrderRedirect(sc);
		PageReference pr = redirect.redirect();
		System.assert(pr != null);
	}

	@isTest
	static void testEdit()
	{
		FPO_Order_Line__c myDoc = new FPO_Order_Line__c();
		ApexPages.StandardController sc = new ApexPages.StandardController(myDoc);

		FPOOrderEditRedirect redirect = new FPOOrderEditRedirect(sc);
		PageReference pr = redirect.redirect();
		System.assert(pr != null);
	}
}