objects/Installation_Model__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country of the Installation Model</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financing_Option__c</fullName>
        <description>Financing Option picklist field created for Loan Backend</description>
        <label>Financing Option</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Business Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Indirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>If Auto, Installation Model will be automatically assigned if criteria are met. If Manual, a user will need to manually assign the Installation Model</description>
        <label>Assignment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Auto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Installation Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/InvoiceDocumentUtility.cls
public with sharing class InvoiceDocumentUtility {
	private static List<Installation_Model__c> installationModels;

	// Select a Installation Model that matches finance type, business channel, country and is of type 'Auto'
	public static Id findInstallationModel(String financingOption, String channel, String country){
		if(installationModels == NULL) installationModels = [SELECT Id, Partner__c, Financing_Option__c, Country__c FROM Installation_Model__c WHERE Type__c = 'Auto'];
		for(Installation_Model__c im : installationModels){
			if(im.Financing_Option__c.contains(financingOption) && channel == im.Partner__c && country == im.Country__c) return im.Id;
		}
		return NULL;
	}
}