objects/Installation_Model__c.object
<CustomObject>
    <fields>
        <fullName>Roles__c</fullName>
        <description>Partner Roles Muti picklist field created for Loan backend</description>
        <label>Roles</label>
        <picklist>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>If Auto, Installation Model will be automatically assigned if criteria are met. If Manual, a user will need to manually assign the Installation Model</description>
        <label>Assignment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Auto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Installation Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/LeasePayment__c.object
<CustomObject>
    <fields>
        <fullName>Multiple_Meters__c</fullName>
        <formula>IF( Account__r.Multiple_Meters__c = True, &quot;Yes&quot;,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Multiple Meters</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Leases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation with RMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased HO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separation of Lesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disposed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Payment</label>
    <nameField>
        <label>Financial Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Payments</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <description>Created for Loan Backend Project</description>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Create_TPS_PO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create TPS PO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Installation_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Installation Model. Created for Loan Backend Project</description>
        <label>Installation Model</label>
        <referenceTo>Installation_Model__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_Doc_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuoteType__c</fullName>
        <description>Project: GPP
Description: Type of Quote(Lease/Cash)</description>
        <inlineHelpText>Type of Quote(Lease/Cash)</inlineHelpText>
        <label>QuoteType</label>
        <picklist>
            <picklistValues>
                <fullName>Lease</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quote_type__c</fullName>
        <label>XQuote Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quote with Sales Services - First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote with Sales Services - Requote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote with Additional Services- First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote with Additional Services - Requote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP Quote - First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP Quote - Requote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Number Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential Lease Quotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPS Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential New Homes Lease Quotation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreatePOUtil.cls
/* **************************************************************************************
* Class Name     : createPOUtil 
* Version        : 1.0 
* Created Date   : 13 Aug 2015
* Function       : Class to verify if it's ok to create PO and check Create PO checkbox

* Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Chaitanya Devarapalli       13 Aug 2015          Original Version
*************************************************************************************/
global class CreatePOUtil {
    
    webService static String checkPOCreation(Id qotId,String FinancialOffering){
        String errorReason=null;
        if(qotId!=null){
            
            Quote qot = [select OpportunityId,Create_TPS_PO__c,Opportunity.Account.Multiple_Meters__c,Quote_type__c,QuoteType__c,Installation_Model__c, Lease_Doc_Signed__c from Quote where Id = :qotId];
            if(qot.Installation_Model__c!=null){
                Installation_Model__c iModel = [select Roles__c,Type__c from Installation_Model__c where Id=:qot.Installation_Model__c];
                Opportunity opp = [select Id,Name,Account.Partner_Account__r.NH_SSE_Type__c,(select UserId,TeamMemberRole,OpportunityId from OpportunityTeamMembers) from Opportunity where Id=:qot.OpportunityId];
                Set<String> teamMemRoleSet = new Set<String>();
            
                for(OpportunityTeamMember otm:opp.OpportunityTeamMembers){
                    teamMemRoleSet.add(otm.TeamMemberRole);
                }
            
                if(qot.QuoteType__c=='Lease'){
                    String nP=PrepPOLineItems.findMissingRoles(opp.OpportunityTeamMembers,iModel);
                    if(nP==null){
                            List<echosign_dev1__SIGN_Agreement__c> agrmntList = new List<echosign_dev1__SIGN_Agreement__c>([select Id,Quote__c from echosign_dev1__SIGN_Agreement__c where echosign_dev1__Status__c ='Signed' and Quote__c=:qotId]);
                            List<LeasePayment__c> lpList = new List<LeasePayment__c>([select Id from LeasePayment__c where Opportunity__c=:opp.Id and Quote__c!=:qotId  and Status__c!='Terminated']);
                            System.debug('agrmntList ----->'+agrmntList);
                            System.debug('lpList ----->'+lpList);
                            if(!agrmntList.isEmpty()){
                                
                                if(qot.Lease_Doc_Signed__c==false){
                                    if(qot.Opportunity.Account.Multiple_Meters__c==true ||(qot.Opportunity.Account.Multiple_Meters__c==false && lpList.isEmpty())){
                                        qot.Lease_Doc_Signed__c=true;
                                        update qot;
                                    }
                                    else if(qot.Opportunity.Account.Multiple_Meters__c==false && !lpList.isEmpty()){
                                        errorReason = 'Please terminate the existing active lease';
                                    }
                                }
                                else{
                                    errorReason = 'Purchase Order Exists';
                                }
                            }
                            else
                                errorReason = 'Quote does not have a siged agreement';  
                    }
                    else{
                        errorReason = 'The following Opportunity Team Members are not setup: '+nP;
                    }
                }
                else if(qot.QuoteType__c=='Loan'){

                        if(iModel.Type__c=='Manual'){
                            List<String> imList = iModel.Roles__c.split(';');
                            String nP=PrepPOLineItems.findMissingRoles(opp.OpportunityTeamMembers,iModel);
                            
                            System.debug('nP----->'+nP);
                            if(nP!=null){
                                errorReason = 'The following Opportunity Team Members are not setup: '+nP;
                            }  
                            else{
                                if(qot.Lease_Doc_Signed__c==false){
                                    qot.Lease_Doc_Signed__c = true;
                                    update qot;
                                }
                                else{
                                    errorReason = 'Contract Already Signed. Purchase Order Exists';
                                }
                            }
                            
                            
                        }
                        else if(iModel.Type__c=='Auto'){
                            errorReason = 'Not Applicable for Auto type of Installation Model';
                        }
                    
                        
                }
                else{
                    errorReason = 'Not Applicable for this Quote type'+qot.QuoteType__c;
                }
            
            }
            else{
                errorReason = 'There is no Installation Model populated for this Quote';
            }
            return errorReason;
        }
        
        else
            return 'Error: Quote Id is null';
    }
}