objects/Installation_Model__c.object
<CustomObject>
    <fields>
        <fullName>Financing_Option__c</fullName>
        <description>Financing Option picklist field created for Loan Backend</description>
        <label>Financing Option</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Business Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Indirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <description>Partner Roles Muti picklist field created for Loan backend</description>
        <label>Roles</label>
        <picklist>
            <picklistValues>
                <fullName>DRIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>If Auto, Installation Model will be automatically assigned if criteria are met. If Manual, a user will need to manually assign the Installation Model</description>
        <label>Assignment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Auto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Installation Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account_Billing_Country__c</fullName>
        <formula>Account__r.BillingCountry</formula>
        <label>Account Billing Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amended_Lease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amended Lease Scenario</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Quote.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Quote.Lease_Doc_Signed__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amendment_Type__c</fullName>
        <label>Amendment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Copy_SM_Before_Lock__c</fullName>
        <label>Copy SM Before Lock</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installation_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Installation Model. Created for Loan Backend Project</description>
        <label>Installation Model</label>
        <referenceTo>Installation_Model__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_Doc_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>OpportunityId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Id__c</fullName>
        <formula>Account__r.Partner_Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteType__c</fullName>
        <description>Project: GPP
Description: Type of Quote(Lease/Cash)</description>
        <inlineHelpText>Type of Quote(Lease/Cash)</inlineHelpText>
        <label>QuoteType</label>
        <picklist>
            <picklistValues>
                <fullName>Lease</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>NH- With NH, we have two sectors- NH and Residential</description>
        <label>Sector</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Model__c</fullName>
        <label>System Model</label>
        <picklist>
            <picklistValues>
                <fullName>230W (Model SPR-230E-WHT-D)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>230W (Model SPR-230NE-BLK-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>245W (Model SPR-245NE-WHT-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>308W (Model SPR-308E-WHT-D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>327W (Model SPR-327NE-WHT-D)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteBeforeUpdateHandler.cls
public without sharing class QuoteBeforeUpdateHandler extends TriggerHandlerBase {

    public QuoteBeforeUpdateHandler() {}

    private Map<ID, Quote> oldMap;
    private Map<ID, Quote> newMap;
    private List<Quote> newList;
    private List<Quote> oldList;
    private Map<Integer, Quote> qualifyOriginalLeaseNumberMap = new Map<Integer, Quote>();
    private Map<Id, Quote> qualifyFranceAccMap = new Map<Id, Quote>();
    private Set<Id> qIdSet = new Set<Id>();
    private Map<Id, Quote> QuoteNewMap;
    private List<Installation_Model__c> lIM = new List<Installation_Model__c>();
    private Map<Id,Quote> dealerFeeQuoteMap = new Map<Id,Quote>();
    private List<Quote> lstQ = new List<Quote>();
    private Set<String> saTVals = new Set<String>{'Product','Lessee','Production'};
    private List<Id> lstOppIds = new List<Id>();
    private List<Id> lstAcctIds = new List<Id>();
    private Map<Id, String> mapSEmail = new Map<Id, String>();
    private Map<Id, String> mapAccCountry = new Map<Id, String>();   //New Code -- Sunpower TPO Phase 1 -- 20/10/2013
    private list<Quote> updateSystemModelList = new List<Quote>();
    private List<Quote> updateAmendmentType = new List<Quote>();
    private List<Quote> lockedQuotes = new List<Quote>();


    public override void qualifyStartingRecords(List<sObject> newList, List< sObject > oldList, Map<ID, sObject > newMap, Map<ID, sObject > oldMap) {
        this.newMap = (Map<ID, Quote>)newMap;
        this.oldMap = (Map<ID, Quote>)oldMap;
        this.newList = (List<Quote>)newList;
        this.oldList = (List<Quote>)oldList;
		
		//Filtering for locked quotes
        for(Quote qt : this.newList){
            if(qt.Is_Locked__c == true && this.oldMap.get(qt.Id).Is_Locked__c != true){
                lockedQuotes.add(qt);
            }
        }

       //  filtering records to udpate AmendmentType and Update Lease doc
         for(Quote Q : this.newList){
                Quote oldRec = this.oldMap.get(Q.Id);
                if(Q.Amended_Lease__c != null && Q.Amended_Lease__c != oldRec.Amended_Lease__c){
                     updateAmendmentType.add(Q);
                     break;
                }
             }

         for (Integer i=0; i<this.newList.size(); i++) {
            Id recId = this.newList[i].Id;
            Quote newRec = this.newMap.get(recId);
            Quote oldRec = this.oldMap.get(recId);

            // Merging UpdateSystemModelField Trigger Code

            if(newRec.System_Model__c == null && newRec.Copy_SM_Before_Lock__c != null){
                 updateSystemModelList.add(newRec);
            }
            // End of Merging.
            // Merging beforeQuoteUpdate Trigger Code
            if(newRec.Is_Locked__c && newRec.Amendment_Type__c != null && saTVals.contains(newRec.Amendment_Type__c) && newRec.Amended_Lease__c != null)
              lstQ.add(newRec);
            if (newRec.Account_Billing_Country__c != null && newRec.Account_Billing_Country__c.equalsIgnoreCase('France')) {
                qualifyFranceAccMap.put(newRec.id, newRec);
            }
            if((newRec.QuoteType__c == 'Loan' || newRec.QuoteType__c == 'Lease' || newRec.QuoteType__c == 'Cash') && newRec.Is_Locked__c && newRec.Lease_Doc_Signed__c && (newRec.Lease_Doc_Signed__c != oldRec.Lease_Doc_Signed__c)){
                qIdSet.add(newRec.Id);
            }
        }

        if(!qIdSet.isEmpty())
                QuoteNewMap = new Map<Id, Quote>([select Id,QuoteType__c,Account_Billing_Country__c, Installation_Model__c,sector__c,Opportunity.Partner_Account_Id__r.NH_SSE_Type__c,Opportunity.Partner_Account_Id__r.Name,Opportunity.Partner_Account_Id__r.Channel__c  from Quote where Id in :newList]);

       for (Integer i=0; i<this.newList.size(); i++) {
            Id recId = this.newList[i].Id;
            Quote newRec = this.newMap.get(recId);
            Quote oldRec = this.oldMap.get(recId);
            if((newRec.QuoteType__c == 'Loan' || newRec.QuoteType__c == 'Lease' || newRec.QuoteType__c == 'Cash') && newRec.Is_Locked__c && newRec.Lease_Doc_Signed__c && (newRec.Lease_Doc_Signed__c != oldRec.Lease_Doc_Signed__c)){
                if(QuoteNewMap.size() > 0 && QuoteNewMap.get(newRec.Id).Opportunity.Partner_Account_Id__r.NH_SSE_Type__c == Null ||(QuoteNewMap.get(newRec.Id).Opportunity.Partner_Account_Id__r.NH_SSE_Type__c <> Null && (!QuoteNewMap.get(newRec.Id).Opportunity.Partner_Account_Id__r.NH_SSE_Type__c.contains('TPS')))){

                    // New Homes Installation Model Assignment
                    if (QuoteNewMap.get(newRec.Id).Sector__c == 'New Homes'){
                        system.debug('inside NH');
                        //lIM  = [select Id,Name from Installation_Model__c where Type__c = 'Auto' AND Partner__c = 'New Homes' AND Financing_Option__c includes (:QuoteNewMap.get(newRec.Id).QuoteType__c)];
                        newRec.Installation_Model__c = InvoiceDocumentUtility.findInstallationModel(QuoteNewMap.get(newRec.Id).QuoteType__c, 'New Homes', QuoteNewMap.get(newRec.Id).Account_Billing_Country__c);

                    }
                    else if (QuoteNewMap.get(newRec.Id).Opportunity.Partner_Account_Id__c != NULL){
                        // SPD Installation Model Assignment
                        if(QuoteNewMap.get(newRec.Id).Opportunity.Partner_Account_Id__r.Channel__c == 'Direct' || QuoteNewMap.get(newRec.Id).Opportunity.Partner_Account_Id__r.Name.contains('SPWR') || QuoteNewMap.get(newRec.Id).Opportunity.Partner_Account_Id__r.Name.contains('SunPower') || QuoteNewMap.get(newRec.Id).Opportunity.Partner_Account_Id__r.Name.contains('SPD')){
                            newRec.Installation_Model__c = InvoiceDocumentUtility.findInstallationModel(QuoteNewMap.get(newRec.Id).QuoteType__c, 'SPD', QuoteNewMap.get(newRec.Id).Account_Billing_Country__c);
                        }
                        // Indirect Installation Model Assignment
                        else{
                            newRec.Installation_Model__c = InvoiceDocumentUtility.findInstallationModel(QuoteNewMap.get(newRec.Id).QuoteType__c, 'Indirect', QuoteNewMap.get(newRec.Id).Account_Billing_Country__c);
                        }
                    }

                }
             }

            if((newRec.QuoteType__c == 'Loan' || newRec.QuoteType__c == 'Lease' || newRec.QuoteType__c == 'Cash') && newRec.Is_Locked__c && newRec.Lease_Doc_Signed__c && ((newRec.Lease_Doc_Signed__c != oldRec.Lease_Doc_Signed__c) ||(newRec.Installation_Model__c!=null && oldRec.Installation_Model__c==null))){
                if(newRec.Installation_Model__c!=null && oldRec.Installation_Model__c==null){
                    Installation_Model__c iModel = [select Roles__c,Type__c from Installation_Model__c where Id=:newRec.Installation_Model__c];
                    if(iModel.Type__c!='Auto'){
                        List<OpportunityTeamMember> otmList = [select TeamMemberRole from OpportunityTeamMember where OpportunityId = :newRec.Opportunity_ID__c];
                        String missingRoles = PrepPOLineItems.findMissingRoles(otmList,iModel);
                        if(missingRoles!=null){
                            newRec.addError('The following Opportunity Team Members are not setup: '+missingRoles);
                            return;
                        }
                    }
                    dealerFeeQuoteMap.put(newRec.Id,newRec);
                }
                else{
                    dealerFeeQuoteMap.put(newRec.Id,newRec);
                }
            }
        }
       // Merge Ends
    }

    public override void start() {
		
		//To populate Lessee field on Quote
        if(!lockedQuotes.isEmpty()){
            QuoteTriggerUtility.populateLessee(lockedQuotes);
        }

        if(!qualifyFranceAccMap.isEmpty()){
            QuoteManagement.updateQuoteFromStringSizerTool(qualifyFranceAccMap, oldMap);
        }
        // Calling the function to update Invertervalues on Quote.
        QuoteTriggerUtility.UpdateQuoteInverterValues(newList);
        // Calling the function to update System Model  on Quote.
        QuoteTriggerUtility.UpdateQuoteSystemModelField(updateSystemModelList);
        if(!dealerFeeQuoteMap.isEmpty())
            System.debug('Updated Loan Quotes ----->'+ Dealerfee_cal_Utility_ModelBased.fIdentifiedRoleAndRelatedPartners(dealerFeeQuoteMap));
        // Merging CopyQuoteValuesUpdate Trigger code
        if(!lstQ.isEmpty()) {
           CloneQuote cq = new CloneQuote();
           cq.quoteUpdate(lstQ);
        }
        // End of Merging.

        // Calling the function QuoteforAgreement for both beforeInsert & beforeUpdate
              QuoteTriggerUtility.QuoteforAgreement(newList);

        if(updateAmendmentType.size() > 0){
              QuoteTriggerUtility.updateAmendmentType(updateAmendmentType);
          }
    }


    public override void finish(Boolean fromStart) {}

}