objects/Installation_Model__c.object
<CustomObject>
    <label>Installation Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installation Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Project_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Residential_Project__c</fullName>
        <label>Residential Project</label>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>Project_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Commissioning Technician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crew Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Support Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineer of Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Superintendent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Products Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Partner Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interconnection Technician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Support Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Runner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Technician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Design Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate and Interconnection Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Operations Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Surveyor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Sales Project Manager</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM{0000000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order__c.object
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Partner PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Residential_Project__c.object
<CustomObject>
    <fields>
        <fullName>Homeowner_Scheduled_Installation_Date__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This date field is manually populated by the Project Coordinator or Project manager once either role has scheduled a system installation date with a homeowner.
This field provides a central date for operations team members to know when the system installation will commence.</description>
        <label>Homeowner Scheduled Installation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Installation_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Residential Installation Project Mgmt
Relates an installation model to a project. Populated programmatically or manually</description>
        <label>Installation Model</label>
        <referenceTo>Installation_Model__c</referenceTo>
        <relationshipLabel>Residential Projects</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Installation_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Name: Residential Installation Management 
Requester: Priti Rastogi 
Populated manually or programmatically based on zip code rules.</description>
        <label>Installation Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Residential Projects (Installation Partner)</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This pick list field defaults to the &quot;Normal&quot; value upon record creation. Changes to the project priority are made manually by Project Managers on a case-by-case basis.</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Fast-tracked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Name: Residential Installation Management 
Requester: Priti Rastogi 
A lookup to the project template, this is used to auto create all the supporting template records and also to keep the template in sync.</description>
        <label>Project Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Residential_Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project Template</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Residential Projects</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO Reference</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Residential Project</relationshipLabel>
        <relationshipName>Residential_Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This text entry field is manually populated by Partner Support Representatives (PSRs) and is used to provide a sales order number reference for the operations team.</description>
        <label>Sales Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This pick list value is automatically populated at record creation with a default value of &quot;Active.&quot; This is a pick list field that can be manually updated by a project team member at any point during the installation project lifecycle in order to communicate project status to the whole team and to track project status data.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Residential Project</label>
    <nameField>
        <label>Residential Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/StandardLineItem__c.object
<CustomObject>
    <description>This is a generic line item to be used when the ordering process doesn&apos;t use the quoting process but still needs to create sales orders in Oracle.</description>
    <fields>
        <fullName>Residential_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residential Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Residential_Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>New Home</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Standard Line Items</relationshipLabel>
        <relationshipName>Standard_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Line Item</label>
    <nameField>
        <displayFormat>SLI-{0}</displayFormat>
        <label>Standard Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ByPassValidation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ResidentialProjectValidationUtility.cls
/*
    Project Field Edit Validation
    -----------------------------
    Installation Partner                    ------> Technical Sales Project Manager, Regional Operations Manager
    Homeowner Scheduled Installation Date   ------> Project Coordinator, Regional Operations Manager
    Priority                                ------> Regional Operations Manager
    Sales Order Number                      ------> Partner Support Representative, Technical Sales Project Manager
    Status                                  ------> Regional Operations Manager
    Installation Model 						------> Project Manager
    Purchase Order 		                    ------> Partner Support Representative
*/

public with sharing class ResidentialProjectValidationUtility {

	// Validate that the current user has permission to update specific fields
	public static Map<Id, String> fieldValidation(List<Residential_Project__c> newProjects, Map<Id, Residential_Project__c> oldProjectMap){

		Map<Id, String> errorMap = new Map<Id, String>();
		Boolean bypassVal = [SELECT ByPassValidation__c FROM User WHERE Id =: UserInfo.getuserId() LIMIT 1].ByPassValidation__c;
		Boolean runVal = Test.isRunningTest() ? TRUE : bypassVal ? FALSE : TRUE ;

		// Create map of all Team Members for a specific project
		Map<Id, List<Project_Team_Member__c>> roleMap = new Map<Id, List<Project_Team_Member__c>>();
		for(Residential_Project__c rp : newProjects){
			roleMap.put(rp.Id, new List<Project_Team_Member__c>());
		}
		for(Project_Team_Member__c ptm : [SELECT Id, User__c, Role__c, Residential_Project__c FROM Project_Team_Member__c WHERE Residential_Project__c IN: newProjects AND User__c =: UserInfo.getUserId()]){
			if(roleMap.containsKey(ptm.Residential_Project__c)){
				roleMap.get(ptm.Residential_Project__c).add(ptm);
			}else{
				roleMap.put(ptm.Residential_Project__c, new List<Project_Team_Member__c>{ptm});
			}
		}

		// Loop through fields that were updated and validate the current user is playing the right role for edit access
		if(runVal){
			for(Residential_Project__c p : newProjects){
	            Residential_Project__c oldP = oldProjectMap.get(p.Id);

	            if(p.RecordTypeId == ResidentialProjectUtility.spdId){

		            if(p.Project_Template__c != NULL && oldP.Project_Template__c != NULL ){

		            	if(roleMap.containsKey(p.Id)){

			            	/* Status */
				            if(oldP.Status__c != p.Status__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Regional Operations Manager' || ptm.Role__c == 'PC Supervisor' || ptm.Role__c == 'Installation Partner Manager') valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Status can only be changed by the Regional Operations Manager, Installation Partner Manager or PC Supervisor');
				            }

				            /* Homeowner Schedule Installation Date */
				            if(oldP.Homeowner_Scheduled_Installation_Date__c != p.Homeowner_Scheduled_Installation_Date__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Project Coordinator' || ptm.Role__c == 'Regional Operations Manager' || ptm.Role__c == 'Scheduler') valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Homeowner Scheduled Installation Date can only be edited by the Project Coordinator or Regional Operations Manager or Scheduler');
				            }

				            /* Priority */
				            if(oldP.Priority__c != p.Priority__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Regional Operations Manager') valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Priority can only be edited by the Regional Operations Manager');
				            }

				            /* Sales Order Number */
				            if(oldP.Sales_Order_Number__c != p.Sales_Order_Number__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Partner Support Representative' || ptm.Role__c == 'Technical Sales Project Manager') valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Sales Order Number Date can only be edited by the Partner Support Representative or the Technical Sales Project Manager');
				            }
			            }else{
			            	if(oldP.Sales_Order_Number__c != p.Sales_Order_Number__c || oldP.Priority__c != p.Priority__c || oldP.Homeowner_Scheduled_Installation_Date__c != p.Homeowner_Scheduled_Installation_Date__c || oldP.Status__c != p.Status__c || oldP.Installation_Partner__c != p.Installation_Partner__c) errorMap.put(p.Id,'You have restricted edit access to this project because you are not assigned to a  project team member role.');
			            }
			        }
			    }
			    if(p.RecordTypeId == ResidentialProjectUtility.tpsId){
			    	if(p.Project_Template__c != NULL && oldP.Project_Template__c != NULL){

			    		if(roleMap.containsKey(p.Id)){

			                /* Installation Model */
			            	if(oldP.Installation_Model__c != p.Installation_Model__c){
			                    Boolean valid = FALSE;
			                    for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
			                        if(ptm.Role__c == 'Project Manager' || ptm.Role__c == 'Technical Sales Project Manager') valid = TRUE;
			                    }
			                    if(valid == FALSE) errorMap.put(p.Id,'Installation Model can only be edited by the Project Manager or Technical Sales Project Manager');
			                }

			            	/* Status */
				            if(oldP.Status__c != p.Status__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Project Manager' || ptm.Role__c == 'PC Supervisor' || ptm.Role__c == 'Installation Partner Manager') valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Status can only be changed by the Project Manager, Installation Partner Manager or PC Supervisor');
				            }

				            /* Priority */
				            if(oldP.Priority__c != p.Priority__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Project Manager') valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Priority can only be edited by the Project Manager');
				            }

				            /* Sales Order Number */
				            if(oldP.Sales_Order_Number__c != p.Sales_Order_Number__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Partner Support Representative' ) valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Sales Order Number Date can only be edited by the Partner Support Representative');
				            }
			            }else{
		            		if(oldP.Sales_Order_Number__c != p.Sales_Order_Number__c || oldP.Priority__c != p.Priority__c || oldP.Status__c != p.Status__c || oldP.Installation_Model__c != p.Installation_Model__c) errorMap.put(p.Id,'You have restricted edit access to this project because you are not assigned to a  project team member role.');
			            }
			        }
			    }
			    if(p.RecordTypeId == ResidentialProjectUtility.nhId){

			    	if(p.Project_Template__c != NULL && oldP.Project_Template__c != NULL){

			    		if(roleMap.containsKey(p.Id)){
					    	/* Priority */
				            if(oldP.Priority__c != p.Priority__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Project Administrator' || ptm.Role__c == 'Project Manager') valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Priority can only be edited by the Project Administrator or Project Manager');
				            }
				            /* Status */
				            if(oldP.Status__c != p.Status__c){
				                Boolean valid = FALSE;
				                for(Project_Team_Member__c ptm : roleMap.get(p.Id)){
				                    if(ptm.Role__c == 'Project Manager' || ptm.Role__c == 'Project Admin' || ptm.Role__c == 'Installation Partner Manager') valid = TRUE;
				                }
				                if(valid == FALSE) errorMap.put(p.Id,'Status can only be changed by the Project Manager, Installation Partner Manager or Project Admin');
				            }
				            /* Purchase Order */
				            if(oldP.Purchase_Order__c != p.Purchase_Order__c) {
				            	Boolean valid = FALSE;
				            	for(Project_Team_Member__c ptm : roleMap.get(p.Id)) {
				            		if(ptm.Role__c == 'Partner Support Representative') valid = TRUE;
				            	}
				            	if(valid == FALSE) errorMap.put(p.Id,'Purchase Order can only be edited by the Partner Support Representative');
				            }
				            /* Sales Order Number */
				            if(oldP.Sales_Order_Number__c != p.Sales_Order_Number__c) {
				            	Boolean valid = FALSE;
				            	for(Project_Team_Member__c ptm : roleMap.get(p.Id)) {
				            		if(ptm.Role__c == 'Partner Support Representative') valid = TRUE;
				            	}
				            	if(valid == FALSE) errorMap.put(p.Id,'Sales Order Number can only be edited by the Partner Support Representative');
				            }
			            }else{
			            	if(oldP.Status__c != p.Status__c || oldP.Priority__c != p.Priority__c) errorMap.put(p.Id,'You have restricted edit access to this project because you are not assigned to a  project team member role.');
			            }
			        }
			    }
		    }
		}
	    return errorMap;
	}

	// check to ensure user can create material lines or purchase order
	public static Boolean canCreate(Id rpId, String objectType) {
		Boolean result = false;
		// map for objects and set of roles for create rights
		Map<String, Set<String>> objectTypesMap = new Map<String, Set<String>>();
		objectTypesMap.put('StandardLineItem__c', new Set<String> {'Design Engineer', 'Engineer of Record', 'Partner Support Representative'});
		objectTypesMap.put('Purchase_Order__c', new Set<String> {'Partner Support Representative'});

		// check roles for user
		for(Project_Team_Member__c ptm : [SELECT Role__c FROM Project_Team_Member__c WHERE Residential_Project__c =: rpId AND User__c =: UserInfo.getUserId()]) {
			Set<String> roles = objectTypesMap.get(objectType);
			if(roles != null && roles.contains(ptm.Role__c)) result = true;
		}
		return result;
	}
}