objects/Inverter_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Inverter item lookup from Oracle Item ID
Release WW22 - 2016</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Inverter Configurations</relationshipLabel>
        <relationshipName>Inverter_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inverter Configuration</label>
    <nameField>
        <label>Inverter Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inverter Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Module_Configuration__c.object
<CustomObject>
    <description>This object stores an Module configuration whose only element is the Module item. 
This will be the associated with the master configuration and related inverters/monitoring via junction objects. 
This is being used in Cash ordering and Lease/Loan.
Release WW 22 - 2016</description>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Item lookup field to Oracle Item Id of one module
Release WW22 - 2016</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Module Configurations</relationshipLabel>
        <relationshipName>Module_Configurations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Module Configuration</label>
    <nameField>
        <label>Module Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Module Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Monitoring_Item_junction__c.object
<CustomObject>
    <description>Junction to establish many to many</description>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Cash Orders Redesign - lookup field to Item record that is selected when creating a monitoring line item based on it&apos;s module configuration record</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Monitoring_Item_junction</relationshipLabel>
        <relationshipName>Monitoring_Item_junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Monitoring_Item_junction</label>
    <nameField>
        <label>Monitoring_Item_junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring_Item_junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Purchase_Order_Line__c.object
<CustomObject>
    <description>This custom object holds the order line information to be passed to Oracle after Online Ordering Process.</description>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLine-{0000000000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Racking_Item_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Cash Orders Redesign - lookup field to tie a racking configuration to a specific item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Racking Item Junctions</relationshipLabel>
        <relationshipName>Racking_Item_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of selected components in this kit.</description>
        <inlineHelpText>Number of selected components in this kit.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Racking Item Junction</label>
    <nameField>
        <label>Racking Item Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racking Item Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Residential_Project__c.object
<CustomObject>
    <fields>
        <fullName>Inverter_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup is used to link the project to a inverter so that PO Lines can be created accurately</description>
        <label>Inverter Configuration</label>
        <referenceTo>Inverter_Configuration__c</referenceTo>
        <relationshipLabel>Residential Projects</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inverter_Quantity__c</fullName>
        <description>Residential Installation Project Management
Pat Hevrdejs</description>
        <label>Inverter Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Module_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup is used to link the project to a module so that PO Lines can be created accurately</description>
        <label>Module Configuration</label>
        <referenceTo>Module_Configuration__c</referenceTo>
        <relationshipLabel>Residential Projects</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MonitoringIncluded__c</fullName>
        <description>When this field is checked, the Monitoring item that&apos;s part of the Inverter configuration will be added to the PO Lines when a new PO is created.</description>
        <label>Monitoring?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mounting_Type__c</fullName>
        <description>Residential Installation Project Management
Pat Hevrdejs</description>
        <label>Mounting Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invisimount - SunModo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount - SunModo - Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount - Inset - SunModo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount - Inset - SunModo - Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount - Over Tile - QuickHook (Standard Height)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount - Over Tile - QuickHook (Low Height)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount - Over Tile - Stanchion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount - Flat Roof - Stanchion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount - Metal Roof - S5 Mini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunPower Smart Mount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UniRac Solar Mount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InvisiMount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SolarMount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – Flat Roof – Stanchion</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – Inset - SunModo</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – Inset – SunModo - Deck</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – Metal Roof – S5 Mini</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – Over Tile – QuickHook (Low Height)</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – Over Tile – QuickHook (Standard Height)</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – Over Tile – Stanchion</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – SunModo</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <picklistValues>
                <fullName>Invisimount – SunModo – Deck</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Panels__c</fullName>
        <description>Residential Installation Project Management
Pat Hevrdejs</description>
        <label>Number of Panels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Storage_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup is used to link the project to a storage configuration so that PO Lines can be created accurately</description>
        <label>Storage Configuration</label>
        <referenceTo>Storage_Configuration__c</referenceTo>
        <relationshipLabel>Residential Projects</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Residential Project</label>
    <nameField>
        <label>Residential Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/StandardLineItem__c.object
<CustomObject>
    <description>This is a generic line item to be used when the ordering process doesn&apos;t use the quoting process but still needs to create sales orders in Oracle.</description>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Item__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Item__c.Line_Type__c</field>
                <operation>equals</operation>
                <value>Standard Line</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Standard Line Items</relationshipLabel>
        <relationshipName>Standard_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Residential_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residential Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Residential_Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>New Home</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Standard Line Items</relationshipLabel>
        <relationshipName>Standard_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Line Item</label>
    <nameField>
        <displayFormat>SLI-{0}</displayFormat>
        <label>Standard Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Storage_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order Management - This field ties the Storage Configuration record to an item record
Release WW24 - 2016</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Storage Configurations</relationshipLabel>
        <relationshipName>Storage_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Storage Configuration</label>
    <nameField>
        <label>Storage Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Storage Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ResidentialProjectCreateLines.cls
global without sharing class ResidentialProjectCreateLines {
	// this is used to create standard lines for the project based on the selected configurations
    // these lines are used in the order creation process (Purchase Order)
    webservice static String createStandardLineItemsForProject(Id projectId) {
        String result = 'Initializing';
        try {
			// check to make sure the user has right to create lines
            if(!ResidentialProjectValidationUtility.canCreate(projectId, 'StandardLineItem__c')) {
                SObjectException e = new SObjectException();
                e.setMessage('You do not have rights to create a material lines for this project because you are not assigned to proper team member role.');
                throw e;
            }

            List<StandardLineItem__c> lines = new List<StandardLineItem__c>();
            for(Residential_Project__c rp : [SELECT Module_Configuration__c, Number_of_Panels__c, Inverter_Configuration__c, Inverter_Quantity__c, Storage_Configuration__c, MonitoringIncluded__c, Mounting_Type__c, Module_Configuration__r.Item__r.Module_Width__c FROM Residential_Project__c WHERE Id = :projectId]) {

                // create module line
                if(String.isNotBlank(rp.Module_Configuration__c) && rp.Number_of_Panels__c > 0) {
                    for(Module_Configuration__c module : [SELECT Item__c FROM Module_Configuration__c WHERE Id = :rp.Module_Configuration__c]) {
                        if(String.isNotBlank(module.Item__c)) {
                            lines.add(createStandardLineItem(projectId, module.Item__c, Integer.valueOf(rp.Number_of_Panels__c)));
                        }
                    }
                }
                // create inverter line
                if(String.isNotBlank(rp.Inverter_Configuration__c) && rp.Inverter_Quantity__c > 0) {
                    for(Inverter_Configuration__c inverter : [SELECT Item__c, Monitoring__c FROM Inverter_Configuration__c WHERE Id = :rp.Inverter_Configuration__c]) {
                        if(String.isNotBlank(inverter.Item__c)) {
                            lines.add(createStandardLineItem(projectId, inverter.Item__c, Integer.valueOf(rp.Inverter_Quantity__c)));

                            // check/create monitoring
                            if(rp.MonitoringIncluded__c == 'Yes') {
                                for(Monitoring_Item_junction__c mon : [SELECT Item__c FROM Monitoring_Item_junction__c WHERE Monitoring_Configuration__c = :inverter.Monitoring__c]) {
                                    if(String.isNotBlank(mon.Item__c)) {
                                        lines.add(createStandardLineItem(projectId, mon.Item__c, 1));
                                    }
                                }
                            }
                        }
                    }
                }
                // create racking lines
                if(String.isNotBlank(rp.Mounting_Type__c) && rp.Number_of_Panels__c > 0) {
                    String mountingType = rp.Mounting_Type__c;
                    // get the items
                    Map<Id, Racking_Item_Junction__c> rackingItems = ProductConfigurationUtility.fetchRackingByModule(rp.Module_Configuration__c, mountingType);
                    // check items
                    if(!rackingItems.isEmpty()) {
                        // racking item junction for solarmount
                        Racking_Item_Junction__c selectedRacking;
                        // create map for items
                        Map<String, Id> itemIds = new Map<String, Id>();
                        for(Racking_Item_Junction__c rij : rackingItems.values()) {
                            itemIds.put(rij.Item__r.Item_Id__c, rij.Item__c);
                            selectedRacking = rij;
                        }
                        // get racking lines
                        RackingCalculationUtility rcu = new RackingCalculationUtility();
                        if(mountingType == 'InvisiMount') {
                            Map<String, Integer> items = rcu.calculateInvisimount(rackingItems, rp.Number_of_Panels__c);
                            // create lines for project
                            for(String kit : items.keySet()) {
                                lines.add(createStandardLineItem(projectId, itemIds.get(kit), items.get(kit)));
                            }
                        } else if(mountingType == 'SolarMount') {
                            Purchase_Order_Line__c poLine = rcu.calculateSolarmount(selectedRacking, rp.Number_of_Panels__c, rp.Module_Configuration__r.Item__r.Module_Width__c);
                            lines.add(createStandardLineItem(projectId, poLine.Oracle_Item_ID__c, Integer.valueOf(poLine.Quantity__c)));
                        }
                    }
                }
                // create storage line
                if(String.isNotBlank(rp.Storage_Configuration__c)) {
                    for(Storage_Configuration__c sc : [SELECT Item__c FROM Storage_Configuration__c WHERE Id = :rp.Storage_Configuration__c]) {
                        lines.add(createStandardLineItem(projectId, sc.Item__c, 1));
                    }
                }
            }
            if(lines.size() > 0) {
                insert lines;
            }
            result = String.valueOf(lines.size()) + ' Line(s) Created';
        }
        catch(Exception e) {
            SpectrumDebugUtility.createExceptionLog(e.getMessage(), e.getStackTraceString(), 'Create Lines for Project Error', projectId);
            result = e.getMessage() + ' - ' + e.getStackTraceString();
        }
        return result;
    }

    private static StandardLineItem__c createStandardLineItem(Id projectId, Id itemId, Integer qty) {
        StandardLineItem__c sli = new StandardLineItem__c();
        sli.Residential_Project__c = projectId;
        sli.Item__c = itemId;
        sli.Quantity__c = qty;
        return sli;
    }
}