objects/Invoice_Compliance_Document__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Payment</label>
        <referenceTo>LeasePayment__c</referenceTo>
        <relationshipLabel>Invoice Compliance Documents</relationshipLabel>
        <relationshipName>Invoice_Compliance_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <label>Invoice Type</label>
        <picklist>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interconnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Origination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residential_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residential Project</label>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Invoice Compliance Documents</relationshipLabel>
        <relationshipName>Invoice_Compliance_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Compliance Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Compliance Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Residential_Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This pick list value is automatically populated at record creation with a default value of &quot;Active.&quot; This is a pick list field that can be manually updated by a project team member at any point during the installation project lifecycle in order to communicate project status to the whole team and to track project status data.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Residential Project</label>
    <nameField>
        <label>Residential Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/InvoiceComplianceDocAfterInsertHandler.cls
public class InvoiceComplianceDocAfterInsertHandler extends TriggerHandlerBase {
	// -------- Constants --------

	// -------- Variables --------
	Map<Id, Invoice_Compliance_Document__c> newICDmap;
    Set<Id> updateLastDocSubmission;
    Set<Id> icdForSharing;

	// -------- Constructor --------
	public InvoiceComplianceDocAfterInsertHandler() {}

	// Cast and determine qualified records
	public override void qualifyStartingRecords(List<sObject> newList, List<sObject> oldList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
		Diagnostics.push('InvoiceComplianceDocAfterInsertHandler qualifyStartingRecords');

		List<Invoice_Compliance_Document__c> newRecords = (List<Invoice_Compliance_Document__c>)newList;
        newICDmap = (Map<Id, Invoice_Compliance_Document__c>)newMap;
        icdForSharing = new Set<Id>();
        updateLastDocSubmission = new Set<Id>();

        for(Invoice_Compliance_Document__c icd : newRecords){

        	// filtering the install and interconnect document with new pending status
            if((icd.Invoice_Type__c == 'Install' || icd.Invoice_Type__c == 'Interconnect') && icd.status__c == 'Pending') updateLastDocSubmission.add(icd.Financial_Payment__c);

            if(icd.Residential_Project__c != NULL) icdForSharing.add(icd.Id);
        }
        Diagnostics.pop();
	}

    public override void start() {
    	Diagnostics.push('InvoiceComplianceDocBeforeInsertHandler start');

        Diagnostics.pop();
    }

    public override void finish(Boolean fromStart) {
        Diagnostics.push('InvoiceComplianceDocBeforeInsertHandler finish');

        if(fromStart) {
	        InvoiceComplianceDocumentUtility.rollups_Count(null, newICDmap);

	        if(!updateLastDocSubmission.isEmpty())  InvoiceComplianceDocumentUtility.updateLastDocSubmissionDate(updateLastDocSubmission);

            if(!icdForSharing.isEmpty())            InvoiceComplianceDocSharingUtility.newICDSharing(icdForSharing);
        }
        Diagnostics.pop();
    }
}