objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Oracle Item Description</description>
        <label>Description</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <label>Long Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Price_List__c.object
<CustomObject>
    <fields>
        <fullName>DSR_PO_Group_Email__c</fullName>
        <label>DSR PO Group Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Expedite_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expedite Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oracle_Operating_Unit__c</fullName>
        <label>Oracle Operating Unit</label>
        <picklist>
            <picklistValues>
                <fullName>SPAU OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPEB OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPNA OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPSA OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPES OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPDE OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPKR OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPCN OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPPT OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPRQ OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPMLL OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPSV OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPML OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPFR OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPBE OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPSW OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPGB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPNL OU</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Packaged_System_Item_ID__c</fullName>
        <description>This is the Oracle item ID used for a SmartPack &apos;PACKAGED SYSTEM&apos; line item on a Purchase Order.</description>
        <label>Packaged System Item ID</label>
        <picklist>
            <picklistValues>
                <fullName>102868</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shipping_Codes__c</fullName>
        <label>Shipping Codes</label>
        <picklist>
            <picklistValues>
                <fullName>McCollister-Truck-DTH LiftGate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>McCollister-Truck-DTH SunPack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>McCollister-Truck-DTW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>McCollister-Truck-FTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>McCollister-Truck-LTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Pick Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schenker-Truck-LTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schenker-Truck-FTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schenker-Ocean-LCL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schenker-Ocean-FCL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schenker-Air-Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schenker-Air-Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Van Brunt-Truck-FTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Van Brunt-Truck-LTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSE – Truck FTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSE – Truck LTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport Via Truck</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Will_Call_Fee__c</fullName>
        <label>Will Call Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <recordTypes>
        <fullName>EU</fullName>
        <active>true</active>
        <description>European price list</description>
        <label>EU</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Price_List_Item__c.object
<CustomObject>
    <description>To associate Price List with the Items and keep the item pricing info as well*.</description>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Oracle Item ID</description>
        <label>Oracle Item ID</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>Price_List_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>There will be one price list per Operating Unit</description>
        <label>Price List</label>
        <referenceTo>Price_List__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>Price_List_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pricing_1__c</fullName>
        <label>Pricing 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_2__c</fullName>
        <label>Pricing 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_3__c</fullName>
        <label>Pricing 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity_1__c</fullName>
        <label>Quantity 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_2__c</fullName>
        <label>Quantity 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_1__c</fullName>
        <description>SmartPack or Ala Carte</description>
        <label>Type 1 Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>Smart Pack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ala Carte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV + Inverter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_2__c</fullName>
        <description>For EU Dealers [In-Roof or On-Roof]
For NA Dealers [SmartMount]</description>
        <label>Type 2 Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>SmartMount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solrif (flashings)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solrif (non-flashings)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_3_Criteria__c</fullName>
        <description>For EU pricing only, Inverter type [SMA or Fronius]</description>
        <label>Type 3 Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>SMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Santerno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Powerone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power-One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SolarEdge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <label>Price List Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <recordTypes>
        <fullName>EU</fullName>
        <active>true</active>
        <description>EU</description>
        <label>EU</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestPriceListManagePDFController.cls
/*
	Last Modified By :- Jitendra Appirio
    Purpose:- No changes done. deployed only for updating the last modified by on this class
*/
/* This test class for PriceListManagePDFController */

public with sharing class TestPriceListManagePDFController {
@isTest
    public static void testPriceListManagePDF1(){
        Price_List__c p = createPriceList();
        String dateString = Date.Today().day()+'~'+Date.Today().month()+'~'+Date.Today().year();
        Test.setCurrentPage(Page.PriceListManagePDFPage);
        ApexPages.currentPage().getParameters().put('ID',p.ID);
        ApexPages.currentPage().getParameters().put('date',dateString);
        ApexPages.Standardcontroller stdController = new Apexpages.Standardcontroller(p);
        PriceListManagePDFController plManagePDFController = new PriceListManagePDFController(stdController);                           
    }

@isTest
    public static void testPriceListManagePDF2(){
        //Price_List__c p = createPriceList();
        Price_List__c p = new Price_List__c();
        //String dateString = Date.Today().day()+'~'+Date.Today().month()+'~'+Date.Today().year();
        //Test.setCurrentPage(Page.PriceListManagePDFPage);
        //ApexPages.currentPage().getParameters().put('ID',p.ID);
        //ApexPages.currentPage().getParameters().put('date',dateString);
        ApexPages.Standardcontroller stdController = new Apexpages.Standardcontroller(p);
        PriceListManagePDFController plManagePDFController = new PriceListManagePDFController(stdController);                       
    }   
    private static Price_List__c createPriceList(){
        Price_List__c priceList = new Price_List__c();
        try{    
            priceList.Name = 'testpricelist';
            priceList.DSR_PO_Group_Email__c = 'test@test.com';      
            priceList.CurrencyIsoCode = 'USD';
            priceList.Oracle_Operating_Unit__c = 'SPEB OU';
            insert priceList;
        }catch(Exception e){
            for(Price_List__c p : [Select p.Will_Call_Fee__c, p.Shipping_Codes__c, p.RecordTypeId, p.Packaged_System_Item_ID__c, p.Oracle_Operating_Unit__c, p.Name, p.Id, p.Expedite_Fee__c, p.CurrencyIsoCode From Price_List__c p where p.Oracle_Operating_Unit__c like 'SPEB OU' LIMIT 1])
                priceList = p;
        }
        System.debug('***************'+pricelist.ID+'***************');
        Map<String,ID> recTypes = new Map<String,ID>();
        List<Price_List_Item__c> lstSmartPackItems = new List<Price_List_Item__c> ();
        List<Price_List_Item__c> lstAlaCarteItems = new List<Price_List_Item__c> ();
        String recType = 'EU';
        for (RecordType rec : [Select id,name,developerName from RecordType where sObjectType='Price_List_Item__c']){
            recTypes.put(rec.developerName,rec.ID);          
        }
        
        for(integer i = 0;i < 5;i++){
            Item__c testItem = new Item__c();
            testItem.Name = 'OracleItemId'+i;
            testItem.CurrencyIsoCode = 'USD';
            testItem.Description__c = 'test description'+i;
            testItem.Long_Description__c = 'test long description'+i;
            testItem.Item_ID__c = 'test'+i;
            insert testItem;
            
            Price_List_Item__c p = new Price_List_Item__c();        
            p.Price_List__c = priceList.ID;
            //p.Description__c = 'TESTITEM'+i;  
            p.Effective_End_Date__c =Date.Today().addMonths(2);
            p.Effective_Start_Date__c = Date.Today().addMonths(-1);
            p.Name = 'For Testing Purpose';
            p.Item_ID__c = testItem.ID;
            //p.Oracle_Item_ID__c = '100' + i;
            p.Pricing_1__c = 100 + i;
            p.Pricing_2__c = 200 + i;
            p.Pricing_3__c = 300 + i;
            p.RecordTypeID = recTypes.get(recType);
            p.Quantity_1__c = 1 + i;
            p.Quantity_2__c = 5 + i;
            p.Type_1__c = 'Smart Pack';
            p.Type_2__c = 'In-Roof';
            p.Type_3_Criteria__c = 'SMA';           
            lstSmartPackItems.add(p);           
        }
        insert lstSmartPackItems;
        
        for(integer i = 0; i < 5; i++){
            Item__c testItem = new Item__c();
            testItem.Name = 'OracleItemId'+i;
            testItem.CurrencyIsoCode = 'USD';
            testItem.Description__c = 'test description'+i;
            testItem.Long_Description__c = 'test long description'+i;
            testItem.Item_ID__c = 'testing'+i;
            insert testItem;
            Price_List_Item__c p = new Price_List_Item__c();        
            p.Price_List__c = priceList.ID;
            p.Item_ID__c = testItem.ID;
            //p.Description__c = 'TESTITEMALACARTE'+i;  
            p.Effective_End_Date__c =Date.Today().addMonths(2);
            p.Effective_Start_Date__c = Date.Today().addMonths(-1);
            p.Name = 'For Testing Purpose ALACARTE';
            //p.Oracle_Item_ID__c = '200' + i;
            p.Pricing_1__c = 100 + i;           
            p.RecordTypeID = recTypes.get(recType);         
            p.Type_1__c = 'Ala Carte';                      
            lstAlaCarteItems.add(p);            
        }
        insert lstAlaCarteItems;
        
        return priceList;
    }

}