objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warranty_Registration__c.object
<CustomObject>
    <description>Warranty Registration Object represent warranty.</description>
    <fields>
        <fullName>Customer_SFDC_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Warranty_Registrations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Warranty Registration</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranty Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_FDS_Product__c.object
<CustomObject>
    <description>This being used in online warranty registration and is replica of FDS products.</description>
    <fields>
        <fullName>Converted_To_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted To Asset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>WR_FDS_Products</relationshipLabel>
        <relationshipName>WR_FDS_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_Modified_by_CastIron__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not Modified by CastIron</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <externalId>true</externalId>
        <label>Serial Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>WR_FDS_Product</label>
    <nameField>
        <displayFormat>Product - {0000}</displayFormat>
        <label>WR_FDS_Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_FDS_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_Line_Item__c.object
<CustomObject>
    <description>Junction Object with Warranty_Registration and WR_FDS_Product .</description>
    <fields>
        <fullName>AssetID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Name</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>WR_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>WR_FDS_Product__r.Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>WR_FDS_Product__r.Serial_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WR_FDS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_FDS_Product</label>
        <referenceTo>WR_FDS_Product__c</referenceTo>
        <relationshipName>WR_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty_Registration__c</fullName>
        <label>Warranty_Registration</label>
        <referenceTo>Warranty_Registration__c</referenceTo>
        <relationshipName>WR_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WR Line Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>WR Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WR_StagingSelection__c.object
<CustomObject>
    <description>Staging table for user selection rough work on Installation Data Tab of  Online Warranty Registration.</description>
    <fields>
        <fullName>WR_FDS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_FDS_Product</label>
        <referenceTo>WR_FDS_Product__c</referenceTo>
        <relationshipLabel>WR_StagingSelections</relationshipLabel>
        <relationshipName>WR_StagingSelections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WR_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR Line Item</label>
        <referenceTo>WR_Line_Item__c</referenceTo>
        <relationshipLabel>WR_StagingSelections</relationshipLabel>
        <relationshipName>WR_StagingSelections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty_Registration__c</fullName>
        <label>Warranty Registration</label>
        <referenceTo>Warranty_Registration__c</referenceTo>
        <relationshipLabel>WR_StagingSelections</relationshipLabel>
        <relationshipName>WR_StagingSelections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WR_StagingSelection</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>WR_ProductSelectionStaging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_StagingSelections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WR_CreateAssetsBatch.cls
global class WR_CreateAssetsBatch implements Database.Batchable<sObject>{
	global Set<Id> WarrantyIDs;
	global String query;
	
	global WR_CreateAssetsBatch(Set<Id> warrIDs){
		WarrantyIDs = warrIDs;
		query = 'select Id,Warranty_Registration__c,AssetID__c,WR_FDS_Product__r.Product_Name__c,Warranty_Registration__r.Status__c,Warranty_Registration__r.Customer_SFDC_ID__c,WR_FDS_Product__r.Serial_Number__c,Warranty_Registration__r.Delivery_Date__c,Warranty_Registration__r.Customer_SFDC_ID__r.Country_Domain__c,WR_FDS_Product__r.Item__c from WR_Line_Item__c where Warranty_Registration__c in: WarrantyIDs Order By Warranty_Registration__c';
	}
	global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		Set<Id> completedWarrantyIds = new Set<ID>();
		List<Asset> deletedAssets = new List<Asset>();
		Set<ID> productIds = new Set<ID>();
		List<Asset> assetList = new List<Asset>();
		List<WR_Line_Item__c> wrLineItemList = new List<WR_Line_Item__c>();
		Map<ID,WR_FDS_Product__c> fdsProductsMap = new Map<ID,WR_FDS_Product__c>();
		Set<String> productNames = new Set<String>();
		Asset asset;
		
		for(WR_Line_Item__c wrLineItem : (List<WR_Line_Item__c>)scope){
			if(wrLineItem.Warranty_Registration__r.Status__c == 'Completed'){
				completedWarrantyIds.add(wrLineItem.Warranty_Registration__c);
		        if(wrLineItem.WR_FDS_Product__r.Product_Name__c != null)
		            productNames.add(wrLineItem.WR_FDS_Product__r.Product_Name__c);
			}
	        // if Warranty Status of Product get Draft
	        if(wrLineItem.Warranty_Registration__r.Status__c == 'Draft'){
	        	if(wrLineItem.AssetID__c != null)
	        		deletedAssets.add(new Asset(id = wrLineItem.AssetID__c));
	        	productIds.add(wrLineItem.WR_FDS_Product__c);
	        }
	        
	    } 
	    //Collect map of Product2
	    Map<String,Product2> productMap = new Map<String,Product2>(); 
	    for(Product2 product : [select ID,Name From Product2 where Name IN :productNames]){
	        productMap.put(product.Name,product);
	    }
		for(WR_Line_Item__c wrLineItem : (List<WR_Line_Item__c>)scope){
			if(wrLineItem.Warranty_Registration__r.Status__c == 'Draft')
				continue;
			if(wrLineItem.WR_FDS_Product__r.Product_Name__c != null)
	            productNames.add(wrLineItem.WR_FDS_Product__r.Product_Name__c);
			wrLineItemList.add(wrLineItem);
			asset = new Asset();
			asset.Name = wrLineItem.WR_FDS_Product__r.Product_Name__c; 
			if(productMap.containsKey(wrLineItem.WR_FDS_Product__r.Product_Name__c))
                asset.Product2Id = productMap.get(wrLineItem.WR_FDS_Product__r.Product_Name__c).id;
            asset.AccountId = wrLineItem.Warranty_Registration__r.Customer_SFDC_ID__c;
            asset.IsCompetitorProduct = false;
            asset.SerialNumber = wrLineItem.WR_FDS_Product__r.Serial_Number__c;
            asset.Quantity = 1;
            asset.InstallDate = wrLineItem.Warranty_Registration__r.Delivery_Date__c;
            //setting Asset currency EU for EU, $ for NA
            if(wrLineItem.Warranty_Registration__r.Customer_SFDC_ID__r.Country_Domain__c != null){
                if(wrLineItem.Warranty_Registration__r.Customer_SFDC_ID__r.Country_Domain__c.endsWith('us'))
                   asset.CurrencyIsoCode = 'USD';
                else
                   asset.CurrencyIsoCode = 'EUR';
            }
            asset.Description = ''; 
            asset.item__c = wrLineItem.WR_FDS_Product__r.Item__c;
            
            assetList.add(asset);
            WR_FDS_Product__c product = new WR_FDS_Product__c(id=wrLineItem.WR_FDS_Product__c,CONVERTED_TO_ASSET__c = true, Not_Modified_by_CastIron__c = true);
			fdsProductsMap.put(wrLineItem.WR_FDS_Product__c,product); 
		}
		
		if(assetList.size() > 0){
			insert assetList;
		}
		
		if(!fdsProductsMap.isEmpty())
	        update fdsProductsMap.values();
		
		for(Integer i=0; i<wrLineItemList.size(); i++){
	        //setting Asset to WR_Line_iem
	        wrLineItemList.get(i).AssetID__c = assetList.get(i).id; 
	    }
	    update wrLineItemList; 
	    
	    if(deletedAssets.size() > 0){
	    	delete deletedAssets;
	    }
	    List<WR_FDS_Product__c> fdsProductList = new List<WR_FDS_Product__c>();
	    if(productIds.size() > 0){
	    	WR_FDS_Product__c product;
	    	for(Id pId : productIds){
	    		product = new WR_FDS_Product__c(id = pId,CONVERTED_TO_ASSET__c = false, Not_Modified_by_CastIron__c = true);
		        fdsProductList.add(product);
	    	}
	    }
	    
	    if(fdsProductList.size() > 0){
	    	update fdsProductList;
	    }
	    if(!completedWarrantyIds.isEmpty()){
		    List<WR_StagingSelection__c> stagingListToDel = new List<WR_StagingSelection__c>();
		 	for(WR_StagingSelection__c stagingRec : [Select id from WR_StagingSelection__c where Warranty_Registration__c in: completedWarrantyIds]){
		 		stagingListToDel.adD(stagingRec);
		 	}
		 	if(stagingListToDel.size() > 0){
		 		delete stagingListToDel;
		 	}	    	
	    }
	    
	}
	global void finish(Database.BatchableContext BC){
			System.debug('Finished Warranty Finish Batch Job..........');
	}
}