objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Oracle Item Description</description>
        <label>Description</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Racking_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Kit_Size__c</fullName>
        <description>Cash Orders - Order Management, field to capture the size in kW of Invisimount kits. PT ID #114754241</description>
        <inlineHelpText>The size, in kW, of portrait layout modules that a single kit of racking supports.</inlineHelpText>
        <label>Kit Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Cash Orders Redesign - field to note what type of racking is being defined. Used to perform item specific automated calculations of racking quantities</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invisimount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SolarMount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SmartMount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunFrame</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-SunPower Ground Mount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-SunPower Roof Mount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Racking Configuration</label>
    <nameField>
        <label>Racking Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racking Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Racking_Item_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Cash Orders Redesign - lookup field to tie a racking configuration to a specific item</description>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Racking Item Junctions</relationshipLabel>
        <relationshipName>Racking_Item_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of selected components in this kit.</description>
        <inlineHelpText>Number of selected components in this kit.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Racking_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Cash Orders Redesign - lookup field used to tie an item to a specific racking configuration that can then be tied to one or more module configurations</description>
        <label>Racking Configuration</label>
        <referenceTo>Racking_Configuration__c</referenceTo>
        <relationshipLabel>Racking Item Junctions</relationshipLabel>
        <relationshipName>Racking_Item_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Racking Item Junction</label>
    <nameField>
        <label>Racking Item Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racking Item Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RackingCalculationUtility_Test.cls
@isTest(SeeAllData=true)
global class RackingCalculationUtility_Test{
   
    public static testMethod void testInvisimount(){
        RackingCalculationUtility rcuTest = new RackingCalculationUtility();
        Map<Id, Racking_Item_Junction__c> rackingMap = new Map<Id, Racking_Item_Junction__c>(); 
        for(Racking_Item_Junction__c item : [SELECT Id, Quantity__c, Item__c, Item__r.Item_Id__c, Item__r.Description__c,
                                                         Racking_Configuration__r.Kit_Size__c, Racking_Configuration__r.Type__c,
                                                         Racking_Configuration__r.Name, Racking_Configuration__c                                                     
                                            FROM Racking_Item_Junction__c
                                            WHERE Racking_Configuration__r.Name LIKE '%Panel AC%']) {
          rackingMap.put(item.Id, item);          
        }                
        rcuTest.calculateInvisimount(rackingMap, 31);
    }
}