objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Item_Category_3__c</fullName>
        <description>Aaron Imler, Appirio 10-Nov-2010 - Item Category 3 value from Oracle product table</description>
        <label>Inventory Category 3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Aaron Imler, Appirio 10-Nov-2010 - Product value from Oracle product table</description>
        <label>Product Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Module_Oracle_Item_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module Oracle Item Number</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modules_Per_String_Roof1__c</fullName>
        <label>Modules Per String 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Yr_1_Production__c</fullName>
        <description>Updated from PV Sim Int Class with system production latest Record</description>
        <label>Total Yr1 Production</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestTPO_Requestxml_ABC.cls
/*** Class added in Sunpower TPO Phase 1 -- 20/10/2013, to cover TPO_Requestxml_ABC Class ***/
//@isTest(seealldata=true)
public class TestTPO_Requestxml_ABC
{/*

    static testMethod void TestTPO_Requestxml_ABC(){
        Account newAccount;
        newAccount = TestUtils.createAccount('QuickQuote ACCOUNT 1', TestUtils.getResidentialRecordTypeId() , false);
        newAccount.Oracle_County__c ='Hautes-Alpes';
        insert newAccount;
        
        Item__c newItem = new Item__c(Item_ID__c = '1234124123123x',Product_Type__c= 'testtype',Item_Category_3__c='222');
        insert newItem;
        
        Opportunity newOpportunity;
        Quote newQuote;
        newOpportunity = [Select Id from Opportunity Where name='Test Class DO NOT TOUCH'];
        newQuote = TestUtils.createQuotes( 1, 'Quick Quote Test ', newOpportunity.Id, false).get(0);
        newQuote.Total_Yr_1_Production__c = 0.0;
        newQuote.Modules_Per_String_Roof1__c = 2;
        newQuote.Module_Oracle_Item_Number__c = newItem.ID;
        
        insert newQuote;
        
        
        
        Attachment newAttachment;
        newAttachment = TestUtils.createAttachments(1, 'ABC Request XML' ,false).get(0);
        newAttachment.parentId = newQuote.id;
        insert newAttachment;
        
              
        TPO_Requestxml_ABC reqABC = new TPO_Requestxml_ABC();
        reqABC.accountId = newAccount.id;
        reqABC.quoteId = newQuote.id;
      //  reqABC.generateABCXml(reqABC.quoteId,reqABC.accountId, 0.0, 0.0, 0.0);
        reqABC.generateABCXml(reqABC.quoteId,reqABC.accountId, 8900.0, 0.029, 2.0);
        
        
       
       
    }
    
    static testMethod void TestTPO_Requestxml_ABC2(){
        Account newAccount;
        newAccount = TestUtils.createAccount('QuickQuote ACCOUNT 1', TestUtils.getResidentialRecordTypeId() , false);
        newAccount.Oracle_County__c ='Hautes-Alpes';
        insert newAccount;
        
        Item__c newItem = new Item__c(Item_ID__c = '1234124123123x',Product_Type__c= 'testtype',Item_Category_3__c='WHITE B SNO2');
        insert newItem;
        
        Opportunity newOpportunity;
        Quote newQuote;
        newOpportunity = [Select Id from Opportunity Where name='Test Class DO NOT TOUCH'];
        newQuote = TestUtils.createQuotes( 1, 'Quick Quote Test ', newOpportunity.Id, false).get(0);
        newQuote.Total_Yr_1_Production__c = 0.0;
        newQuote.Modules_Per_String_Roof1__c = 2;
        newQuote.Module_Oracle_Item_Number__c = newItem.ID;
        
        insert newQuote;
        
        
        
        Attachment newAttachment;
        newAttachment = TestUtils.createAttachments(1, 'ABC Request XML' ,false).get(0);
        newAttachment.parentId = newQuote.id;
        insert newAttachment;
        
        TPO_Requestxml_ABC reqABC = new TPO_Requestxml_ABC();
        reqABC.accountId = newAccount.id;
        reqABC.quoteId = newQuote.id;
      //  reqABC.generateABCXml(reqABC.quoteId,reqABC.accountId, 0.0, 0.0, 0.0);
        reqABC.generateABCXml(reqABC.quoteId,reqABC.accountId, 0.0, null,null );
        
        
       
    }
    */
    }