objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RMA_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipName>RMA_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RMA Line Item</label>
    <nameField>
        <label>RMA Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RMALineItemTest.cls
@isTest
public class RMALineItemTest {
    private static testMethod void test_setItem() {
        RMALineItemTestData td = new RMALineItemTestData();
        td.createTestData_setItem();
        
        // Item__c lookup is set
        RMA_Line_Item__c li = [SELECT Item__c FROM RMA_Line_Item__c WHERE Id = :td.line_item_1.Id];
        system.assertEquals(td.item_1.Id, li.Item__c);
        
        // change item
        li.Name = 'item_2';
        update li;
        li = [SELECT Item__c FROM RMA_Line_Item__c WHERE Id = :td.line_item_1.Id];
        system.assertEquals(td.item_2.Id, li.Item__c);
        
        // item does not exist
        li.Name = 'item_3';
        update li;
        li = [SELECT Item__c FROM RMA_Line_Item__c WHERE Id = :td.line_item_1.Id];
        system.assertEquals(null, li.Item__c);
        
    }
    
}