objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Item_Category_3__c</fullName>
        <description>Aaron Imler, Appirio 10-Nov-2010 - Item Category 3 value from Oracle product table</description>
        <label>Inventory Category 3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lease_Schedule_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Operation_and_Maintenance_Fee__c</fullName>
        <description>Monthly O&amp;M Fee</description>
        <formula>IF(Country_Domain__c &lt;&gt; &apos;au&apos;,System_Size__c * 0.4 / 240,0)</formula>
        <inlineHelpText>Monthly O&amp;M Fee</inlineHelpText>
        <label>Calculated Operation and Maintenance Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Placed_in_Service__c</fullName>
        <description>In Service Date</description>
        <formula>Lease_Payment__r.Placed_In_Service__c</formula>
        <inlineHelpText>In Service Date</inlineHelpText>
        <label>Placed in Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Y1_MLP__c</fullName>
        <description>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</description>
        <inlineHelpText>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</inlineHelpText>
        <label>Y1 MLP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y2_MLP__c</fullName>
        <description>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</description>
        <inlineHelpText>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</inlineHelpText>
        <label>Y2 MLP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y3_MLP__c</fullName>
        <description>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</description>
        <inlineHelpText>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</inlineHelpText>
        <label>Y3 MLP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y4_MLP__c</fullName>
        <description>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</description>
        <inlineHelpText>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</inlineHelpText>
        <label>Y4 MLP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y5_MLP__c</fullName>
        <description>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</description>
        <inlineHelpText>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</inlineHelpText>
        <label>Y5 MLP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y6_MLP__c</fullName>
        <description>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</description>
        <inlineHelpText>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</inlineHelpText>
        <label>Y6 MLP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y7_MLP__c</fullName>
        <description>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</description>
        <inlineHelpText>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</inlineHelpText>
        <label>Y7 MLP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y8_MLP__c</fullName>
        <description>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</description>
        <inlineHelpText>This takes the total yearly payment summed up from the lease schedules that are calculated via code and then subtracts the monthly O&amp;M fee to show the ACH payment per month, which is used to calculate the IRR.</inlineHelpText>
        <label>Y8 MLP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Lease Schedule Summary</label>
    <nameField>
        <displayFormat>LSS-{0000}</displayFormat>
        <label>Lease  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Schedule Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LeasePayment__c.object
<CustomObject>
    <fields>
        <fullName>Date_Countersigned_old__c</fullName>
        <label>Date Countersigned old</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fair_Market_Value_acctg__c</fullName>
        <description>This field contains the Fair Market value - the value will be calculated outside of SFDC by Sunpower Finance, and manually entered into the system.</description>
        <label>Fair Market Value (acctg)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funding_Tranche__c</fullName>
        <label>Financier</label>
        <picklist>
            <picklistValues>
                <fullName>Access 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConEdison Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corona Sands, LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helios II Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Helios Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinite Sunshine 2015-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lux II Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lux Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mosaic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photon Resi Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR-ITC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR MS 2013-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR – Non US Treasury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR SG 2013-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR SR 2013-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR USB 2013-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR USB 2013-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPWR USB 2013-3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunPower Capital LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunPower Residential I LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunpower Resi II, LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunrise 2 LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunrise 3 LLC</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ITC_Cash_Grant_Valuation_acctg__c</fullName>
        <label>ITC/Cash Grant Valuation (acctg)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lease_Type_old__c</fullName>
        <label>Lease Type old</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partial_prepayment__c</fullName>
        <formula>IF(TEXT(Quote__r.QuoteType__c) = &apos;Loan&apos;,  Quote__r.Down_Payment__c, IF(( Partial_prepayment_old__c &gt; 0 ) , Partial_prepayment_old__c, Quote__r.Partial_Prepayment__c  ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partial prepayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Placed_In_Service__c</fullName>
        <label>Placed In Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_State_Prov_old__c</fullName>
        <label>Site State/Prov old</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <label>Financial Payment</label>
    <nameField>
        <label>Financial Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>First_Monthly_Payment_Base_Amount__c</fullName>
        <label>First Monthly Payment: Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_PrePayment_Amount_Base_Amount__c</fullName>
        <label>Full PrePayment Amount: Base Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Module_Oracle_Item_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module Oracle Item Number</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Module_Quantity__c</fullName>
        <label>Module Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partial_Prepayment__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Partial Prepayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solar_Rebate_Amount__c</fullName>
        <label>Solar Rebate Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>System_Cost__c</fullName>
        <label>System Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestLeaseCalcModel.cls
@isTest(SeeAllData=true)
private class TestLeaseCalcModel 
{
    static Account newAccount;
    static Contact newContact;
    static Opportunity newOpportunity;
    static Quote newQuote;
    
    static void setup()
    {
        newAccount = TestUtils.createAccount('CPR TEST ACCOUNT 1', TestUtils.getResidentialRecordTypeId() , true );
        newContact = TestUtils.createContact('CPR TEST CONTACT 1', newAccount.Id, true );
        newOpportunity = TestUtils.createOpportunities( 1 , newAccount.Id, newContact.Id, true)[0];
    }
    
    static testMethod void testModelConstructor() 
    {
        setup();
        
        
        newQuote = TestUtils.createQuotes( 1, 'Sample Quote Name', newOpportunity.Id, true )[0];
        
        LeasePayment__c leasePayment = TestUtils.createLeasePayment( 'Lease Payment', newAccount.Id, newQuote.Id, false );
        leasePayment.Funding_Tranche__c  ='SPWR';
        leasePayment.Site_State_Prov_old__c ='CA';
        leasePayment.Date_Countersigned_old__c =system.today()-30;
       
        insert leasePayment;
         Test.startTest();
        leasePayment.Placed_In_Service__c =System.today()+30;
        leasePayment.Opportunity__c = newOpportunity.id;
        update  leasePayment;
        
        Lease_Schedule_Summary__c scheduleSummary = TestUtils.createLeaseScheduleSummary( newQuote.Id, leasePayment.Id, true );
     
        
        
        
            LeaseCalcModel leaseCalcModel = new LeaseCalcModel( scheduleSummary );
        
        Test.stopTest();

        //System.assertEquals( scheduleSummary.Id, leaseCalcModel.leaseScheduleSummary.Id , 'The models record should be set by constructor.' );  
    }
    
    static testMethod void testBuildMonthlyPayments()
    {
        setup();
        
        final String ITEM_ID1 = '111178xxasdfasdf';
        Item__c moduleItem = new Item__c();
        moduleItem.Item_ID__c = ITEM_ID1;
        //represents (formula) the Maximum Rated Capacity (Watts), ex: category3 * module_quantity
        moduleItem.Item_Category_3__c = '230';
        insert moduleItem;
        
        newQuote = TestUtils.createQuotes( 1, 'Sample Quote Name', newOpportunity.Id, false )[0];
        //represents (formula) the System Size in Lease Schedule Summary
        newQuote.Module_Oracle_Item_Number__c = moduleItem.Id;
        newQuote.Module_Quantity__c = 32;
        insert newQuote;
        
        LeasePayment__c leasePayment = TestUtils.createLeasePayment( 'Lease Payment', newAccount.Id, newQuote.Id, false );
        leasePayment.Funding_Tranche__c = 'SPWR';
        leasePayment.Lease_Type_old__c = 'Monthly';
        insert leasePayment;
        
        Lease_Schedule_Summary__c scheduleSummary = TestUtils.createLeaseScheduleSummary( newQuote.Id, leasePayment.Id, false );
        
        
        for(Integer i = 1; i<=20; i++)
        {
            
            scheduleSummary.put('Y'+i+'_MLP__c',i*100);
        
        }
        insert scheduleSummary;
        
        Test.startTest();

            LeaseCalcModel calcModel = LeaseCalcModel.retrieveLeaseCalcModels(new List<Id>{scheduleSummary.Id})[0];
            List<Double> monthlyPayments = calcModel.buildMonthlyPayments();
            
        Test.stopTest();
        
        Double constantFee = (Double) calcModel.leaseScheduleSummary.get( 'Calculated_Operation_and_Maintenance_Fee__c' );
       // System.assertEquals(240, monthlyPayments.size(),'There should be 240 numbers in the list.');
        
        Integer k = 0;
        
        
        
        for(Integer i = 1; i<=20; i++)
        {
            Double payment = (Double) calcModel.leaseScheduleSummary.get('Y'+i+'_MLP__c');
            Double expectedValue = payment-constantFee;
                
            for(Integer j = 0; j<12; j++)
            {
               // System.assertNotEquals(null,payment,'Payment should not be null. ');
                //System.assertNotEquals(null,monthlyPayments[k],'Monthly payments should not be null. ');
               // System.assertEquals(expectedValue, monthlyPayments[k],'There should be 12 payments for each field from the map. ');
                k++;
            }
        }
    }
    
    static testMethod void testBuildMonthlyPaymentsPrePaid()
    {//taken from lease no. 31445 Anthony Currans
        setup();
        
        final String ITEM_ID1 = '111178xxasdfasdf';
        Item__c moduleItem = new Item__c();
        moduleItem.Item_ID__c = ITEM_ID1;
        //represents (formula) the Maximum Rated Capacity (Watts), ex: category3 * module_quantity
        moduleItem.Item_Category_3__c = '230';
        insert moduleItem;
        
        newQuote = TestUtils.createQuotes( 1, 'Sample Quote Name', newOpportunity.Id, false )[0];
        //represents (formula) the System Size in Lease Schedule Summary
        newQuote.Module_Oracle_Item_Number__c = moduleItem.Id;
        newQuote.Module_Quantity__c = 24;
        //customer prepayment on lease summary
        newQuote.Full_PrePayment_Amount_Base_Amount__c = 8361.73;
        insert newQuote;
        
        LeasePayment__c leasePayment = TestUtils.createLeasePayment( 'Lease Payment', newAccount.Id, newQuote.Id, false );
        leasePayment.Funding_Tranche__c = 'CITI2';
        leasePayment.Lease_Type_old__c = 'Prepaid';
        insert leasePayment;
        
        Lease_Schedule_Summary__c scheduleSummary = TestUtils.createLeaseScheduleSummary( newQuote.Id, leasePayment.Id, false );
        
        
        for(Integer i = 1; i<=20; i++)
        {
            
            scheduleSummary.put('Y'+i+'_MLP__c',i*0);
        
        }
        insert scheduleSummary;
        
        Test.startTest();

            LeaseCalcModel calcModel = LeaseCalcModel.retrieveLeaseCalcModels(new List<Id>{scheduleSummary.Id})[0];
            List<Double> monthlyPayments = calcModel.buildMonthlyPayments();
            
        Test.stopTest();
        
        //System.assertEquals(240, monthlyPayments.size(),'There should be 240 numbers in the list.');
        
        Integer k = 0;
        
        
        
        for(Integer i = 1; i<=20; i++)
        {
            Double payment = (Double) calcModel.leaseScheduleSummary.get('Y'+i+'_MLP__c');
            Double expectedValue = 0;
                
            for(Integer j = 0; j<12; j++)
            {
                //System.assertNotEquals(null,payment,'Payment should not be null. ');
                //System.assertNotEquals(null,monthlyPayments[k],'Monthly payments should not be null. ');
                //System.assertEquals(expectedValue, monthlyPayments[k],'There should be 12 payments for each field from the map. ');
                k++;
            }
        }
    }
    
    static testMethod void testCalculateIRRPrePaid()
    {
        //lease#31445, can be found in full-box and production (as a lease payment record)
        
        //year1month1 field on spreadsheet
        Double year1Month1 = 0;
        
        //customer prepayment field on spreadsheet
        Double downPayment = 8361.73;
        
        //Unguaranteed Resid. from spredsheet
        Double unguaranteedResidual = 3218.16;
        
        // Lease FMV for 90% test (cost-ITC)
        Double fmv = 24044.91621;
        
        //no monthly payments           
        List < Double > monthlyPayments = new List< Double >();
        for ( Integer j = 0; j < 50; j++ )
        {
                monthlyPayments.add( 0 );
        }
        
        Test.startTest();
            
            LeaseCalcModel leaseCalcModel = new LeaseCalcModel( new Lease_Schedule_Summary__c() );
            
            Double OMFee = 4.6*240;
            
            Decimal irrValue = Decimal.valueOf(  leaseCalcModel.calculateIRR( monthlyPayments, year1Month1, fmv, downPayment, OMFee, unguaranteedResidual ) );
            
        Test.stopTest();
        
        //taken from macro enabled CITI spreadsheet
        Double spreadSheetIRR = -8.2306738915013;
        
        Decimal expectedIrr = Decimal.valueOf( spreadSheetIRR );
        
        final Integer SCALE = 4;
        
        //System.assertEquals( expectedIrr.setScale( SCALE, System.Roundingmode.HALF_UP ), irrValue.setScale( SCALE, System.Roundingmode.HALF_UP ), 'The method should return the correct IRR value' );
    }
    
    static testMethod void testCalculateIRRMonthly()
    {
        //lease#11377, can be found in full-box and production (as a lease payment record)
        
        //year1month1 field on spreadsheet
        Double year1Month1 = 242.52;
        
        //CSI-Rebate field on spreadsheet
        Double downPayment = 2229.78;
        
        //Unguaranteed Resid. from spredsheet
        Double unguaranteedResidual = 5679.00;
        
        // Lease FMV for 90% test (cost-ITC)
        Double fmv =  41336.00;
        
        // w/o o&m w/ACH discount Payment
        List<Double> monthlyPaymentsPerYear = new List<Double>
            {242.52, 253.71, 265.40, 277.62, 290.39, 303.73, 317.67, 332.24, 347.47, 363.38, 
            380.01, 397.39, 415.55, 434.52, 454.35, 475.07, 496.73, 519.36, 543.00, 567.72 };
            
        List < Double > monthlyPayments = new List< Double >();
        for ( Integer j = 0; j < 2; j++ )
        {
            for ( Integer i = 0; i < 12; i++ )
            {
                monthlyPayments.add( monthlyPaymentsPerYear[j] );
            }
        }
        
        Test.startTest();
            
            LeaseCalcModel leaseCalcModel = new LeaseCalcModel( new Lease_Schedule_Summary__c() );
            
            Double OMFee = 0;
            
            Decimal irrValue = Decimal.valueOf(  leaseCalcModel.calculateIRR( monthlyPayments, year1Month1, fmv, downPayment, OMFee, unguaranteedResidual ) );
            
        Test.stopTest();
        
        //taken from macro enabled SPWR spreadsheet
        Double spreadSheetIRR = 8.87765285784034;
        
        Decimal expectedIrr = Decimal.valueOf( spreadSheetIRR );
        
        final Integer SCALE = 4;
        
        //System.assertEquals( expectedIrr.setScale( SCALE, System.Roundingmode.HALF_UP ), irrValue.setScale( SCALE, System.Roundingmode.HALF_UP ), 'The method should return the correct IRR value' );
    }
        
    static testMethod void testCalculateIRRWithPartialPrepayment()
    {
        //lease#31881, can be found in full-box and production (as a lease payment record)
        
        //year1month1 field on spreadsheet
        Double year1Month1 = 717.79;
        
        //CSI-Rebate field on spreadsheet
        Double downPayment = 1146.59;
        
        //Unguaranteed Resid. from spredsheet
        Double unguaranteedResidual = 3075.00;
        
        // Lease FMV for 90% test (cost-ITC)
        Double fmv =  23197.25;
        
        Double monthlyAmount = 117.785;
        
        List < Double > monthlyPayments = new List< Double >();
        for ( Integer j = 0; j < 2; j++ )
        {
            for ( Integer i = 0; i < 12; i++ )
            {
                monthlyPayments.add( monthlyAmount );
            }
        }
        
        Test.startTest();
            
            LeaseCalcModel leaseCalcModel = new LeaseCalcModel( new Lease_Schedule_Summary__c() );
            
            Double OMFee = 0;
            
            Decimal irrValue = Decimal.valueOf(  leaseCalcModel.calculateIRR( monthlyPayments, year1Month1, fmv, downPayment, OMFee, unguaranteedResidual ) );
            
        Test.stopTest();
        
        //taken from macro enabled SPWR spreadsheet
        Double spreadSheetIRR = 3.7164344487839;
        
        Decimal expectedIrr = Decimal.valueOf( spreadSheetIRR );
        
        final Integer SCALE = 4;
        
        //System.assertEquals( expectedIrr.setScale( SCALE, System.Roundingmode.HALF_UP ), irrValue.setScale( SCALE, System.Roundingmode.HALF_UP ), 'The method should return the correct IRR value' );
    }   
    
 /*   static testMethod void testRunCalculationsOnIRRAndNPV() 
    {
        //lease#11377, can be found in full-box and production (as a lease payment record)
        
        setup();
        
        final String ITEM_ID1 = '111178xxasdfasdf';
        Item__c moduleItem = new Item__c();
        moduleItem.Item_ID__c = ITEM_ID1;
        //represents (formula) the Maximum Rated Capacity (Watts), ex: category3 * module_quantity
        moduleItem.Item_Category_3__c = '230';
        insert moduleItem;
        
        newQuote = TestUtils.createQuotes( 1, 'Sample Quote Name', newOpportunity.Id, false )[0];
        //represents (formula) the System Size in Lease Schedule Summary
        newQuote.Module_Oracle_Item_Number__c = moduleItem.Id;
        newQuote.Module_Quantity__c = 32;
        //represents (formula) FMV in Lease Schedule Summary
        newQuote.System_Cost__c = 56792.00;
        // Lease_FMV for 90% = FMV - ITC
        newQuote.Partial_Prepayment__c = 0.00;
        newQuote.First_Monthly_Payment_Base_Amount__c = 248.65 + 7.50;
        
        //calculates Downpayment = CSI Rebate (Solar Rebate Amount) + Customer Prepayment ( full Prepayment amount base amount) 
        newQuote.Solar_Rebate_Amount__c = 2229.78;
        newQuote.Full_PrePayment_Amount_Base_Amount__c = 0;

        insert newQuote;
        
        LeasePayment__c leasePayment = TestUtils.createLeasePayment( 'Lease Payment', newAccount.Id, newQuote.Id, false );
        leasePayment.Funding_Tranche__c = 'SPWR';
        leasePayment.Lease_Type_old__c = 'Monthly';
        //ITC = system_cost * .3   ---> 56792.00 * .3 = 17037.60 
        leasePayment.ITC_Cash_Grant_Valuation_acctg__c = 15456;
        leasePayment.Fair_Market_Value_acctg__c = 56792;
        insert leasePayment;
        
        Lease_Schedule_Summary__c scheduleSummary = TestUtils.createLeaseScheduleSummary( newQuote.Id, leasePayment.Id, false );
        scheduleSummary.Y1_MLP__c = 248.65;
        scheduleSummary.Y2_MLP__c = 259.84;
        scheduleSummary.Y3_MLP__c = 271.53;
        scheduleSummary.Y4_MLP__c = 283.75;
        scheduleSummary.Y5_MLP__c = 296.52;
        scheduleSummary.Y6_MLP__c = 309.86;
        scheduleSummary.Y7_MLP__c = 323.81;
        scheduleSummary.Y8_MLP__c = 338.38;
        scheduleSummary.Y9_MLP__c = 353.61;
        scheduleSummary.Y10_MLP__c = 369.52;
        scheduleSummary.Y11_MLP__c = 386.15;
        scheduleSummary.Y12_MLP__c = 403.52;
        scheduleSummary.Y13_MLP__c = 421.68;
        scheduleSummary.Y14_MLP__c = 440.66;
        scheduleSummary.Y15_MLP__c = 460.49;
        scheduleSummary.Y16_MLP__c = 481.21;
        scheduleSummary.Y17_MLP__c = 502.86;
        scheduleSummary.Y18_MLP__c = 525.49;
        scheduleSummary.Y19_MLP__c = 549.14;
        scheduleSummary.Y20_MLP__c = 573.85;
        insert scheduleSummary;
        
        Test.startTest();

            LeaseCalcModel calcModel = LeaseCalcModel.retrieveLeaseCalcModels(new List<Id>{scheduleSummary.Id})[0];
            
            //a test to ensure the formula fields are properly configured
            Decimal actualYear1Month1 = calcModel.leaseScheduleSummary.Gross_Cash_Payments_Year_1_Month_1__c.setScale( 2, System.Roundingmode.HALF_UP );
            
           // System.assertEquals( 242.52, actualYear1Month1, 'The year1 month1 value should match what is expected (from the spreasheet, lease#11377)' );
            
            calcModel.runCalculations();
            
        Test.stopTest();
        
       // System.assert(calcModel.leaseScheduleSummary.Lease_Calculations_Finished__c,'The flag should be set to true after calculations are finished');
        
        //System.assertNotEquals( null, calcModel.leaseScheduleSummary.Implicit_Rate__c, 'The implicit rate should be calculated and have a value' );         
        
        //System.assertNotEquals( null, calcModel.leaseScheduleSummary.Implicit_Rate__c, 'The implicit rate should not be null' );        
        Decimal expectedIRR = 8.88;
        Decimal actualIRR = calcModel.leaseScheduleSummary.Implicit_Rate__c.setScale( 2, System.Roundingmode.HALF_UP );
        //System.assertEquals( expectedIRR, actualIRR, 'The implicit rate should be the same as the value calculated in the excel macro-spreadsheet' );       
        
        //System.assertNotEquals( null, calcModel.leaseScheduleSummary.NPV_of_MLP__c, 'The NPV should not be null' );         
        Decimal expectedNpv = 40367.66;
        Decimal actualNpv = calcModel.leaseScheduleSummary.NPV_of_MLP__c.setScale( 2, System.Roundingmode.HALF_UP );
      //  System.assertEquals( expectedNpv, actualNpv, 'The NPV should be the same as the value calculated in the excel macro-spreadsheet' );
                
        //System.assertNotEquals( null, calcModel.leaseScheduleSummary.NPV_of_UGRV__c, 'The NPV ungar should not be null' );      
        Decimal expectedNpvUngar = 968.30;
        Decimal actualNpvUngar = calcModel.leaseScheduleSummary.NPV_of_UGRV__c.setScale( 2, System.Roundingmode.HALF_UP );
       // System.assertEquals( expectedNpvUngar, actualNpvUngar, 'The NPV Ungar should be the same as the value calculated in the excel macro-spreadsheet' );         
    }  */
  /*  static testMethod void testRunCalculationsOnIRRAndNPVOnPrepaid() 
    {
        //lease#31445, can be found in full-box and production (as a lease payment record)
        
        setup();
        
        final String ITEM_ID1 = '111178xxasdfasdf';
        Item__c moduleItem = new Item__c();
        moduleItem.Item_ID__c = ITEM_ID1;
        //represents (formula) the Maximum Rated Capacity (Watts), ex: category3 * module_quantity
        moduleItem.Item_Category_3__c = '230';
        insert moduleItem;
        
        newQuote = TestUtils.createQuotes( 1, 'Sample Quote Name', newOpportunity.Id, false )[0];
        //represents (formula) the System Size in Lease Schedule Summary
        newQuote.Module_Oracle_Item_Number__c = moduleItem.Id;
        newQuote.Module_Quantity__c = 24;
        //represents (formula) FMV in Lease Schedule Summary
        newQuote.System_Cost__c = 32181.60;
        // Lease_FMV for 90% = FMV - ITC
        newQuote.Partial_Prepayment__c = 0.00;
        newQuote.First_Monthly_Payment_Base_Amount__c = 0;
        
        //calculates Downpayment = CSI Rebate (Solar Rebate Amount) + Customer Prepayment ( full Prepayment amount base amount) 
        newQuote.Solar_Rebate_Amount__c = 0;
        newQuote.Full_PrePayment_Amount_Base_Amount__c = 8361.73;

        insert newQuote;
        
        LeasePayment__c leasePayment = TestUtils.createLeasePayment( 'Lease Payment', newAccount.Id, newQuote.Id, false );
        leasePayment.Funding_Tranche__c = 'SPWR';
        leasePayment.Lease_Type_old__c = 'Prepaid';
        leasePayment.ITC_Cash_Grant_Valuation_acctg__c = 8136.68;
        leasePayment.Fair_Market_Value_acctg__c = 32181.60;
        insert leasePayment;
        
        Lease_Schedule_Summary__c scheduleSummary = TestUtils.createLeaseScheduleSummary( newQuote.Id, leasePayment.Id, false );
        scheduleSummary.Y1_MLP__c = 0;
        scheduleSummary.Y2_MLP__c = 0;
        scheduleSummary.Y3_MLP__c = 0;
        scheduleSummary.Y4_MLP__c = 0;
        scheduleSummary.Y5_MLP__c = 0;
        scheduleSummary.Y6_MLP__c = 0;
        scheduleSummary.Y7_MLP__c = 0;
        scheduleSummary.Y8_MLP__c = 0;
        scheduleSummary.Y9_MLP__c = 0;
        scheduleSummary.Y10_MLP__c = 0;
        scheduleSummary.Y11_MLP__c = 0;
        scheduleSummary.Y12_MLP__c = 0;
        scheduleSummary.Y13_MLP__c = 0;
        scheduleSummary.Y14_MLP__c = 0;
        scheduleSummary.Y15_MLP__c = 0;
        scheduleSummary.Y16_MLP__c = 0;
        scheduleSummary.Y17_MLP__c = 0;
        scheduleSummary.Y18_MLP__c = 0;
        scheduleSummary.Y19_MLP__c = 0;
        scheduleSummary.Y20_MLP__c = 0;
        insert scheduleSummary;
        
        Test.startTest();

            LeaseCalcModel calcModel = LeaseCalcModel.retrieveLeaseCalcModels(new List<Id>{scheduleSummary.Id})[0];
            
            //a test to ensure the formula fields are properly configured
            Decimal actualYear1Month1 = calcModel.leaseScheduleSummary.Gross_Cash_Payments_Year_1_Month_1__c.setScale( 2, System.Roundingmode.HALF_UP );
            
            //System.assertEquals( 0, actualYear1Month1, 'The year1 month1 value should match what is expected (from the spreasheet, lease#31445)' );
            
        //    calcModel.runCalculations();
            
        Test.stopTest();
        
       // System.assert(calcModel.leaseScheduleSummary.Lease_Calculations_Finished__c,'The flag should be set to true after calculations are finished');
        
        //System.assertNotEquals( null, calcModel.leaseScheduleSummary.Implicit_Rate__c, 'The implicit rate should be calculated and have a value' );         
        
        //System.assertNotEquals( null, calcModel.leaseScheduleSummary.Implicit_Rate__c, 'The implicit rate should not be null' );        
        Decimal expectedIRR = -8.23;
        Decimal actualIRR = calcModel.leaseScheduleSummary.Implicit_Rate__c.setScale( 2, System.Roundingmode.HALF_UP );
       // System.assertEquals( expectedIRR, actualIRR, 'The implicit rate should be the same as the value calculated in the excel macro-spreadsheet' );       
        
        //System.assertNotEquals( null, calcModel.leaseScheduleSummary.NPV_of_MLP__c, 'The NPV should not be null' );         
        Decimal expectedNpv = 7257.73;
        Decimal actualNpv = calcModel.leaseScheduleSummary.NPV_of_MLP__c.setScale( 2, System.Roundingmode.HALF_UP );
       // System.assertEquals( expectedNpv, actualNpv, 'The NPV should be the same as the value calculated in the excel macro-spreadsheet' );
                
       // System.assertNotEquals( null, calcModel.leaseScheduleSummary.NPV_of_UGRV__c, 'The NPV ungar should not be null' );
        //this will be 16787.19 if the decimal places are increased from a schema perspective.      
        Decimal expectedNpvUngar = 16787.16;
        Decimal actualNpvUngar = calcModel.leaseScheduleSummary.NPV_of_UGRV__c.setScale( 2, System.Roundingmode.HALF_UP );
       // System.assertEquals( expectedNpvUngar, actualNpvUngar, 'The NPV Ungar should be the same as the value calculated in the excel macro-spreadsheet' );         
    }  */
    
    static testMethod void testCalculateNPV()
    {
        //lease#11377, can be found in full-box and production (as a lease payment record)
        
        //year1month1 field on spreadsheet
        Double year1Month1 = 242.52;
        
        //CSI-Rebate field on spreadsheet
        Double downPayment = 2229.78;
        
        //Unguaranteed Resid. from spredsheet
        Double unguaranteedResidual = 5679.20;
        
        // Lease FMV for 90% test (cost-ITC)
        Double fmv =  39754.40;
        
        // w/o o&m w/ACH discount Payment
        List<Double> monthlyPaymentsPerYear = new List<Double>
            {242.52, 253.71, 265.40, 277.62, 290.39, 303.73, 317.68, 332.25, 347.48, 363.39, 
            380.02, 397.39, 415.55, 434.53, 454.36, 475.08, 496.73, 519.36, 543.01, 567.72 };
            
        List < Double > monthlyPayments = new List< Double >();
        for ( Integer j = 0; j < 2; j++ )
        {
            for ( Integer i = 0; i < 12; i++ )
            {
                monthlyPayments.add( monthlyPaymentsPerYear[j] );
            }
        }
        
        LeaseCalcModel leaseCalcModel = new LeaseCalcModel( new Lease_Schedule_Summary__c() );
        Double OMFee = 0;
        Double irrValue = leaseCalcModel.calculateIRR( monthlyPayments, year1Month1, fmv, downPayment, OMFee, unguaranteedResidual );
        Test.startTest();
            
            
            Decimal actualNPV = Decimal.valueOf( leaseCalcModel.calculateNPV(monthlyPayments, year1Month1, downPayment , OMFee, irrValue/100) ).setScale(2, System.Roundingmode.HALF_UP);           
            
        Test.stopTest();
        
        //taken from macro enabled SPWR spreadsheet
        Double expectedNPV = 38873.54;
        
       // System.assertEquals( expectedNPV, actualNPV, 'The method should return the correct NPV value' );
    }
    
    static testMethod void testCalculateNPVPrePaid()
    {
        //lease#31445, can be found in full-box and production (as a lease payment record)
        
        //year1month1 field on spreadsheet
        Double year1Month1 = 0;
        
        //customer prepayment field on spreadsheet
        Double downPayment = 8361.73;
        
        //Unguaranteed Resid. from spredsheet
        Double unguaranteedResidual = 3218.16;
        
        // Lease FMV for 90% test (cost-ITC)
        Double fmv = 24044.91621;
        
        //no monthly payments           
        List < Double > monthlyPayments = new List< Double >();
        for ( Integer j = 0; j < 50; j++ )
        {
                monthlyPayments.add( 0 );
        }
        
        LeaseCalcModel leaseCalcModel = new LeaseCalcModel( new Lease_Schedule_Summary__c() );
        Double OMFee = 4.6*240;
        
        Double irrValue = leaseCalcModel.calculateIRR( monthlyPayments, year1Month1, fmv, downPayment, OMFee, unguaranteedResidual );
        Test.startTest();
        
            
            Decimal actualNPV = Decimal.valueOf( leaseCalcModel.calculateNPV(monthlyPayments, year1Month1, downPayment , OMFee, irrValue/100) ).setScale(2, System.Roundingmode.HALF_UP);                   
            
        Test.stopTest();
        
        //taken from macro enabled CITI spreadsheet
        Double expectedNPV = 7257.73;
        
       // System.assertEquals( expectedNPV, actualNPV, 'The method should return the correct NPV value' );
    }
    
    static testMethod void testcalculateNPVOfUnguaranteedResidual()
    {
        //lease#11377, can be found in full-box and production (as a lease payment record)
        
        //year1month1 field on spreadsheet
        Double year1Month1 = 242.52;
        
        //CSI-Rebate field on spreadsheet
        Double downPayment = 2229.78;
        
        //Unguaranteed Resid. from spredsheet
        Double unguaranteedResidual = 5679.20;
        
        // Lease FMV for 90% test (cost-ITC)
        Double fmv =  39754.40;
        
        // w/o o&m w/ACH discount Payment
        List<Double> monthlyPaymentsPerYear = new List<Double>
            {242.52, 253.71, 265.40, 277.62, 290.39, 303.73, 317.68, 332.25, 347.48, 363.39, 
            380.02, 397.39, 415.55, 434.53, 454.36, 475.08, 496.73, 519.36, 543.01, 567.72 };
            
        List < Double > monthlyPayments = new List< Double >();
        for ( Integer j = 0; j < 2; j++ )
        {
            for ( Integer i = 0; i < 12; i++ )
            {
                monthlyPayments.add( monthlyPaymentsPerYear[j] );
            }
        }
        
        LeaseCalcModel leaseCalcModel = new LeaseCalcModel( new Lease_Schedule_Summary__c() );
        Double OMFee = 0;
        Double irrValue = leaseCalcModel.calculateIRR( monthlyPayments, year1Month1, fmv, downPayment, OMFee, unguaranteedResidual );

        Test.startTest();
            
            Decimal actualNPVUngar = Decimal.valueOf( leaseCalcModel.calculateNPVOfUnguaranteedResidual(unguaranteedResidual, irrValue/100) ).setScale(2, System.Roundingmode.HALF_UP);         
            
        Test.stopTest();
        
        //taken from macro enabled SPWR spreadsheet
        Decimal expectedNPV = 880.82;
        
       // System.assertEquals( expectedNPV, actualNPVUngar, 'The method should return the correct NPV value' );
    }
    
    static testMethod void testCalculateNPVOfUnguaranteedResidualPrePaid()
    {
        //lease#31445, can be found in full-box and production (as a lease payment record)
        
        //year1month1 field on spreadsheet
        Double year1Month1 = 0;
        
        //customer prepayment field on spreadsheet
        Double downPayment = 8361.73;
        
        //Unguaranteed Resid. from spredsheet
        Double unguaranteedResidual = 3218.16;
        
        // Lease FMV for 90% test (cost-ITC)
        Double fmv = 24044.91621;
        
        //no monthly payments           
        List < Double > monthlyPayments = new List< Double >();
        for ( Integer j = 0; j < 50; j++ )
        {
                monthlyPayments.add( 0 );
        }
        
        LeaseCalcModel leaseCalcModel = new LeaseCalcModel( new Lease_Schedule_Summary__c() );
        Double OMFee = 4.6*240;
        Double irrValue = leaseCalcModel.calculateIRR( monthlyPayments, year1Month1, fmv, downPayment, OMFee, unguaranteedResidual );
        
        Test.startTest();
            
            Decimal actualNPVUngar = Decimal.valueOf( leaseCalcModel.calculateNPVOfUnguaranteedResidual(unguaranteedResidual, irrValue/100) ).setScale(2, System.Roundingmode.HALF_UP);         
            
        Test.stopTest();
        
        //taken from macro enabled CITI spreadsheet
        //this will be 16787.19 if the decimal places are increased from a schema perspective.
        Decimal expectedNPV = 16787.15;
        
        //System.assertEquals( expectedNPV, actualNPVUngar, 'The method should return the correct NPV value' );
    }

}