objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Oracle Item Description</description>
        <label>Description</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Discount__c.object
<CustomObject>
    <description>Used for calculating ordering discount matrix based on dealer tiers and bulk orders

Created for EU Pricing matrix enhancement Dec 2014</description>
    <fields>
        <fullName>Bundle_Quantity__c</fullName>
        <label>Bundle Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discontinue_Date__c</fullName>
        <description>Date on which the discount discontinues</description>
        <label>Discontinue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Discount Effective Date</description>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <formula>Oracle_Item_ID__r.Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_Quantity__c</fullName>
        <defaultValue>99999</defaultValue>
        <description>Maximum Quantity for the order to get discount</description>
        <label>Maximum Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Quantity__c</fullName>
        <description>Minimum Quantity for the order to get discount</description>
        <label>Minimum Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oracle_Item_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Oracle item id</description>
        <label>Oracle Item ID</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Order Discounts</relationshipLabel>
        <relationshipName>Order_Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Discount</label>
    <nameField>
        <displayFormat>OD-{000000}</displayFormat>
        <label>Order Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Price_List__c.object
<CustomObject>
    <fields>
        <fullName>Oracle_Operating_Unit__c</fullName>
        <label>Oracle Operating Unit</label>
        <picklist>
            <picklistValues>
                <fullName>SPAU OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPEB OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPNA OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPSA OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPES OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPDE OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPKR OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPCN OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPPT OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPRQ OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPMLL OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPSV OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPML OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPFR OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPBE OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPSW OU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPGB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPNL OU</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <recordTypes>
        <fullName>EU</fullName>
        <active>true</active>
        <description>European price list</description>
        <label>EU</label>
    </recordTypes>
    <recordTypes>
        <fullName>NA</fullName>
        <active>true</active>
        <description>North America Price List</description>
        <label>NA</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Price_List_Item__c.object
<CustomObject>
    <description>To associate Price List with the Items and keep the item pricing info as well*.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BoS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inverter Accesories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mounting Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Disc_Item_Description__c</fullName>
        <formula>Disc_Item_ID__r.Description__c</formula>
        <label>Disconnect Item Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disc_Item_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Oracle Item ID for Inverter Disconnect</description>
        <label>Disconnect Item ID</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Price List Items (Disconnect Item ID)</relationshipLabel>
        <relationshipName>Price_List_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>IF(Item_ID__r.Active__c, &apos;true&apos;, &apos;false&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <description>Old formula: BLANKVALUE(Item_ID__r.Long_Description__c, Item_ID__r.Description__c)</description>
        <formula>If ((RIGHT($User.CountryDomainText__c,2) != &apos;us&apos;)&amp;&amp; Item_ID__r.Product_Family__c!=&apos;&apos;,Item_ID__r.Product_Family__c, Item_ID__r.Description__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Oracle Item ID</description>
        <label>Oracle Item ID</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>Price_List_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>There will be one price list per Operating Unit</description>
        <label>Price List</label>
        <referenceTo>Price_List__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>Price_List_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pricing_2__c</fullName>
        <label>Pricing 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_3__c</fullName>
        <label>Pricing 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity_1__c</fullName>
        <label>Quantity 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_2__c</fullName>
        <label>Quantity 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_1__c</fullName>
        <description>SmartPack or Ala Carte</description>
        <label>Type 1 Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>Smart Pack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ala Carte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV + Inverter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_2__c</fullName>
        <description>For EU Dealers [In-Roof or On-Roof]
For NA Dealers [SmartMount]</description>
        <label>Type 2 Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>SmartMount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fronius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solrif (flashings)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solrif (non-flashings)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <label>Price List Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <recordTypes>
        <fullName>EU</fullName>
        <active>true</active>
        <description>EU</description>
        <label>EU</label>
    </recordTypes>
    <recordTypes>
        <fullName>NA</fullName>
        <active>true</active>
        <description>NA</description>
        <label>NA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Order_Line__c.object
<CustomObject>
    <description>This custom object holds the order line information to be passed to Oracle after Online Ordering Process.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BoS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <label>Item ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Item_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Oracle Item ID reference field of Item Type</description>
        <label>Oracle Item ID</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLine-{0000000000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AlaCarteController.cls
public class AlaCarteController extends ComponentControllerBase{
    
    public void setJSON(){
        selProductItemsJSON = JSON.serialize(selProductItems);
    }
    
    
    //select options, etc.
    public User currentUser {get;set;}
    public final static string NONESELECT = '--None--';
    public Integer PAGINATION_COUNTER {get;set;}
    public List<Price_List_Item__c> products {get;set;}
    public String changedQty {get;set;}  
    public String hdnDelProdLineId {get;set;}
    public boolean showQuantityMessage {get;set;}
    public boolean showErrorBlock {get;set;}
    public String prodDescFilter {get;set;}
    //quantity of a line items
    public String inputQuantity {get;set;}
    //For Product Items Wrapper,which show in Page
    public List<PriceItemWrapper> selProductItems {get;set;}
    public String selProductItemsJSON {get;set;}

    //Ship to state - used for state specific item selection
    public String shippingState {get;set;}     
    
    //Quantity validations
    Map<Id,List<Order_Discount__c>> orderDiscountMap = new Map<Id,List<Order_Discount__c>>();
    
    //counter variable
    public ApexPages.StandardSetController setCon{get;set;}
    
    public Date currentDate = Date.today();
    public String opunit {get;set;}
    public String qry = 'Select p.Disc_Item_ID__c, p.Disc_Item_Description__c, p.Disc_Item_ID__r.Name, p.CurrencyIsoCode, p.Type_2__c, p.Type_1__c, p.Quantity_2__c, ' +
        'p.Quantity_1__c, p.Pricing_2__c,p.Pricing_3__c, p.Price_List__r.Oracle_Operating_Unit__c, p.Price_List__r.Name, ' +
        'p.Price_List__c, p.Item_ID__c, p.Item_ID__r.Item_Id__c, p.Item_ID__r.Name, p.Name, p.Effective_Start_Date__c, p.Effective_End_Date__c, p.Item_Description__c, p.Category__c ' +
        'From Price_List_Item__c p where p.category__c != null ' +
        'and (p.Price_List__r.Oracle_Operating_Unit__c =: opunit OR (p.Price_List__r.State__C != null AND p.Price_List__r.State__c =: shippingState)) ' +
        'and p.Effective_Start_Date__c <=:currentDate and p.Effective_End_Date__c >=:currentDate ' +
        'and p.Is_Active__c = \'true\' and type_1__c = \'Ala Carte\' ';
    public Map<String, List<Price_List_Item__c>> categoryItemsListMap = new Map<String, List<Price_List_Item__c>>();
    
    public string selectedCategoryKey {get;set;}

    public AlacarteController() {
        
        currentUser = [Select Id, Name, Profile.Name, Contact.Account.Oracle_Operating_Unit__c, Contact.Account.BillingCountry,
                       Contact.Account.Online_Order_Access__c, CurrencyISOCode, Contact.Account.Theater__c
                       From User Where Id =: UserInfo.getUserId()];
        
        opunit = currentUser.Contact.Account.Oracle_Operating_Unit__c;
        
        List<Price_List_Item__c> temp = Database.query(qry);
        for(Price_List_Item__c pli : temp) {
            if(categoryItemsListMap.containsKey(pli.Category__c)) {
                categoryItemsListMap.get(pli.Category__c).add(pli);
            }
            else {
                categoryItemsListMap.put(pli.Category__c, new List<Price_List_Item__c>());
                categoryItemsListMap.get(pli.Category__c).add(pli);
            }
        }
        showQuantityMessage = false;
        showErrorBlock = false;
        
        //defaulting selected category to All.
        selectedCategoryKey = 'All';
        updateProductLineItemList();
        List<Order_Discount__c> dealerTierDiscounts = new List<Order_Discount__c>([SELECT Minimum_Quantity__c, Maximum_Quantity__c, Oracle_Item_ID__c, Effective_Date__c, 
                                                                                            Discontinue_Date__c, Bundle_Quantity__c
                                                                                    FROM Order_Discount__c 
                                                                                    WHERE Effective_Date__c <= TODAY 
                                                                                    AND (Discontinue_Date__c > TODAY OR Discontinue_Date__c = NULL) 
                                                                                    AND Theatre__c =: currentUser.Contact.Account.Theater__c 
                                                                                    AND Country__c INCLUDES(: currentUser.Contact.Account.BillingCountry)]);   
        
        for(Order_Discount__c od : dealerTierDiscounts){
            if(!orderDiscountMap.containskey(od.Oracle_Item_Id__c))
                orderDiscountMap.put(od.Oracle_Item_Id__c,new List<Order_Discount__c>());
            
            orderDiscountMap.get(od.Oracle_Item_Id__c).add(od);
        }
        getProductsList();        
    }
    
    
    public List<SelectOption> getCategoryKeys() {
        List<SelectOption> options = new List<SelectOption>();
        for(String s : categoryItemsListMap.keySet()) {
            options.add(new SelectOption(s,s));
        }
        options.add(new SelectOption('All','All'));
        return options;
    }
    
    /** This getter function is to get the records from standard set controller 
    *  and set them to list of price list items.
    *  @return  List<Price_List_Item__c>
    */
    public void getProductsList() {
        if(setCon == null){ 
            initilizeSetCon();  
        }
        if(setCon != null) {
            if(setCon.getResultSize() != 0){
                
                products = (List<Price_List_Item__c>) setCon.getRecords();
            }
            else
                products = new List<Price_List_Item__c>();
        }
    }
    
    /** This function initializes standard set controller of price list items.
    *  
    */
    private void initilizeSetCon(){
        PAGINATION_COUNTER= Integer.valueof(System.Label.PAGE_DISPLAY_SIZE);
        
        List<Price_List_Item__c> items = new List<Price_List_Item__c>();
        if(setCon == null){                                   
            for(Price_List_Item__c pli : [Select p.Item_Description__c,p.Disc_Item_ID__r.Name, p.Type_2__c, p.Name,
                                                 p.Item_ID__c, p.Item_ID__r.Item_Id__c, p.Item_ID__r.Name,p.Category__c 
                                          From Price_List_Item__c p 
                                          WHERE (p.Price_List__r.Oracle_Operating_Unit__c =: opunit 
                                                OR (p.Price_List__r.State__c =: shippingState 
                                                AND p.Price_List__r.State__c != null))
                                          AND p.category__c = :selectedCategoryKey  
                                          AND p.Effective_Start_Date__c <=:currentDate 
                                          AND p.Effective_End_Date__c >=:currentDate 
                                          AND p.Is_Active__c = 'true' 
                                          AND p.Type_1__c ='Ala Carte'
                                          ORDER BY p.Item_Description__c]) {
                items.add(pli);
            }
            setCon = new ApexPages.StandardSetController(items);
            setCon.setPageSize(PAGINATION_COUNTER);
            
        }else if(setCon != null && setCon.getResultSize() != 0){      
            setCon.setPageSize(PAGINATION_COUNTER);
            products = (List<Price_List_Item__c>) setCon.getRecords();
        }else{
            products = new List<Price_List_Item__c>();
        }
    }
    
    
    
    /** This function is responsible to filter the price list items according to selected Category.
    *  @return  PageReference
    */
    public PageReference updateProductLineItemList(){       
        if(selectedCategoryKey != null){
            PAGINATION_COUNTER=Integer.valueof(System.Label.PAGE_DISPLAY_SIZE);
            List<Price_List_Item__c> items = new List<Price_List_Item__c>();

            if(selectedCategoryKey != 'All')
            for(Price_List_Item__c pli : [Select p.Item_Description__c,p.Disc_Item_ID__r.Name, p.Type_2__c, p.Name,
                                                 p.Item_ID__c, p.Item_ID__r.Item_Id__c, p.Item_ID__r.Name,p.Category__c 
                                          From Price_List_Item__c p 
                                          WHERE (p.Price_List__r.Oracle_Operating_Unit__c =: opunit 
                                                OR (p.Price_List__r.State__c =: shippingState 
                                                AND p.Price_List__r.State__c != null))
                                          AND p.category__c = :selectedCategoryKey  
                                          AND p.Effective_Start_Date__c <=:currentDate 
                                          AND p.Effective_End_Date__c >=:currentDate 
                                          AND p.Is_Active__c = 'true' 
                                          AND p.Type_1__c ='Ala Carte'
                                          ORDER BY p.Item_Description__c]) {
                items.add(pli);
            }
            else{
            
                for(Price_List_Item__c pli : [Select p.Item_Description__c,p.Disc_Item_ID__r.Name, p.Type_2__c, p.Name,
                                                 p.Item_ID__c, p.Item_ID__r.Item_Id__c, p.Item_ID__r.Name,p.Category__c 
                                          From Price_List_Item__c p 
                                          WHERE (p.Price_List__r.Oracle_Operating_Unit__c =: opunit 
                                                OR (p.Price_List__r.State__c =: shippingState 
                                                AND p.Price_List__r.State__c != null)) 
                                          AND p.Effective_Start_Date__c <=:currentDate 
                                          AND p.Effective_End_Date__c >=:currentDate 
                                          AND p.Is_Active__c = 'true' 
                                          AND p.Type_1__c ='Ala Carte'
                                          ORDER BY p.Item_Description__c]) {
                    items.add(pli);
                }
            
            
            }
            setCon = new ApexPages.StandardSetController(items);
            
            if(setCon != null){
                if(setCon.getResultSize() != 0){
                    setCon.setPageSize(PAGINATION_COUNTER);
                    products = (List<Price_List_Item__c>) setCon.getRecords();
                }
            }
        }else{          
            initilizeSetCon();
        }
        return null; 
    }
    
    
    /*Section For Products List starts Here */
    public String singleAddedprodId{get;set;}
    
    
    /** This function takes the list of price lite items .
    *  @return  PageReference
    */
    public void addItemToList(){

        changedQty='';
        inputQuantity='1';
        if(singleAddedprodId == null || singleAddedprodId=='' )
            return ;
           
        for(Price_List_Item__c prod:products){
            try{
                if(prod.ID == singleAddedprodId){
                    addProductItemToList(prod); 
                }
            }catch(Exception e){
                
            }
        }
    }
    
    
    /** This function adds a price list item to the list of selected price list items.
    *  @param  Price_List_Item__c
    */
    private void addProductItemToList(Price_List_Item__c prod){        
        if (prod ==null) return;
        PriceItemWrapper productWrapper = new PriceItemWrapper();
        //Removing Below condition for Case-00872916, Now EU and NA should see Product Name only not description for ALA CARTE and Selected Item List
       /* if(currentUser.Contact.Account.Theater__c != 'Europe')
            productWrapper = new PriceItemWrapper(prod.ID, prod.Item_Description__c, prod.Type_2__c, String.valueof(inputQuantity));  
        else*/ 
            productWrapper = new PriceItemWrapper(prod.ID, prod.Name, prod.Type_2__c, String.valueof(inputQuantity));                              
        productWrapper.oracleItemIDRef = prod.Item_ID__c;  
        productWrapper.itemID = prod.Item_ID__r.Item_ID__c;      
        
        if(selProductItems != null && selProductItems.size()>0){
            boolean isAdded =false;
            for(PriceItemWrapper prodWrapper :selProductItems){
                if(prodWrapper.ID == prod.ID){                      
                    isAdded =true;
                    break;
                }  
            }
            if(!isAdded){
                selProductItems.add(0,productWrapper);                              
            }
            
        }else{                  
            if(selProductItems == null) {            
                selProductItems = new List<PriceItemWrapper>();               
            }                                        
            if(selProductItems.size() == 0){
                selProductItems.add(productWrapper);          
            }else{
                selProductItems.add(0,productWrapper);                   
            }
        }
        Boolean showQtyMessage = checkChangedQuantity(productWrapper, '1');
    }
    
    /** This function is to synchronize the quantity values of price list items.
    * 
    */
    
    @TestVisible
    private Boolean checkChangedQuantity(AlaCarteController.PriceItemWrapper wrapper, String newVal) {
        wrapper.error = null;
        if(!orderDiscountMap.containsKey(wrapper.oracleItemIDRef))
            return true;
        for(Order_Discount__c od : orderDiscountMap.get(wrapper.oracleItemIDRef)){
            if(Double.valueOf(newVal) >= od.Minimum_Quantity__c && Double.valueOf(newVal) <= od.Maximum_Quantity__c){
                wrapper.bundleSize = od.Bundle_Quantity__c;

                if(wrapper.bundleSize == null || (Math.mod(Integer.valueOf(newVal),wrapper.bundleSize.intValue()) == 0)){
                    return true;
                }
                else{
                    wrapper.error = '(' + wrapper.bundleSize.intValue() + ')';
                    return false;
                }
            }
        }
        return wrapper.error == null;
    }
    
    /** This function deletes a price list item from the list of PriceItemWrapper.
    *  
    */
    public PageReference delItemFromList() {
        changedQty='';
        if(hdnDelProdLineId == null || hdnDelProdLineId =='')
            return null;
        //Delete Item Product Wrap Here
        deleteFromProductWrapperList(hdnDelProdLineId);

        return null;    
    }
    
    /** This function deletes a price list item from the list of PriceItemWrapper.
    *  @param id 
    */
    private void deleteFromProductWrapperList(String id){
        
        if(selProductItems == null || selProductItems.size()==0) return;
        List<PriceItemWrapper> tempProdList = new List<PriceItemWrapper>();  
        
        for(PriceItemWrapper wrapProd:selProductItems){
            
            if(wrapProd.ID != id ){
                tempProdList.add(wrapProd);                          
            }
        }
        selProductItems.clear();      
        
        selProductItems.addAll(tempProdList);
    }
    
    public PageReference updateQuantity() {

        for(AlaCarteController.PriceItemWrapper prodWrapper :selProductItems){

            if(prodWrapper.ID == singleAddedprodId){
                if(checkChangedQuantity(prodWrapper, changedQty)) {
                    prodWrapper.Qty = changedQty ;
                    break;
                }
            }           
        }
        return null;
    }
    
    public void getQunatityMessage(){
        if(showQuantityMessage){
            ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.ERROR,System.Label.POQuantityErrorMessage);
            ApexPages.addMessage(errorMsg);
            showErrorBlock = true;
        }
        else{
            showErrorBlock = false;
        }
    }
    
    /** This function is responsible to filter the price list items according to type.
    *  @return  PageReference
    */
    public PageReference moveAccordingToFilter(){       
        if(selectedCategoryKey != null){
            PAGINATION_COUNTER=Integer.valueof(System.Label.PAGE_DISPLAY_SIZE);
            setCon = getPriceListFilterByDesc(selectedCategoryKey,prodDescFilter);
            if(setCon != null){
                if(setCon.getResultSize() != 0){
                    setCon.setPageSize(PAGINATION_COUNTER);
                    products = (List<Price_List_Item__c>) setCon.getRecords();
                }
            }
        }else{          
            initilizeSetCon();
        }
        return null; 
    }
    
    /** This function fetches price list items of selected category for selected dealer account. 
    *  @return ApexPages.Standardsetcontroller
    */
    private ApexPages.Standardsetcontroller getPriceListFilterByDesc(String selectedCategory,String productDescFilter)
    {
        
        List<Price_List_Item__c> priceList = null; 
        String prodFilter='';
        if(productDescFilter != null && productDescFilter !=''){
            String reg = '^[0-9]{6}$';
            Pattern pat = Pattern.compile(reg);  
            Matcher pm = pat.matcher(productDescFilter);
            if(pm.find())          
                prodFilter = ' and p.Item_ID__r.Item_Id__c like \'%' + productDescFilter + '%\'';
            else
                prodFilter = ' and p.Item_ID__r.Description__c like \'%' + productDescFilter + '%\'';
        }  
        

        Date currentDate = Date.today();
        String qry = null;                      
        
        if(selectedCategory != 'All' && selectedCategory != null && selectedCategory != System.Label.POWizardNonePicklistValue){
            selectedCategory = selectedCategory.trim();
            qry = 'Select p.Disc_Item_ID__c,p.Disc_Item_Description__c,p.Disc_Item_ID__r.Name,p.CurrencyIsoCode,p.Type_2__c, p.Type_1__c, p.Quantity_2__c, p.Quantity_1__c, p.Price_List__r.Oracle_Operating_Unit__c, p.Item_ID__c, p.Item_ID__r.Item_Id__c, p.Item_ID__r.Name, p.Name, p.Effective_Start_Date__c, p.Effective_End_Date__c, p.Item_Description__c, p.Category__c From Price_List_Item__c p where (p.Price_List__r.Oracle_Operating_Unit__c =: opunit OR (p.Price_List__r.State__C != null AND p.Price_List__r.State__c =: shippingState)) and p.Effective_Start_Date__c <=:currentDate and p.Effective_End_Date__c >=:currentDate and p.Is_Active__c = \'true\' and type_1__c = \'Ala Carte\' and p.Category__c = \''+selectedCategory +'\'' + prodFilter;
        }
        else{
            qry = 'Select p.Disc_Item_ID__c,p.Disc_Item_Description__c,p.Disc_Item_ID__r.Name,p.CurrencyIsoCode,p.Type_2__c, p.Type_1__c, p.Quantity_2__c, p.Quantity_1__c, p.Price_List__r.Oracle_Operating_Unit__c, p.Item_ID__c, p.Item_ID__r.Item_Id__c, p.Item_ID__r.Name,p.Item_ID__r.Item_Displayable_Description__c, p.Name, p.Effective_Start_Date__c, p.Effective_End_Date__c, p.Item_Description__c, p.Category__c From Price_List_Item__c p where (p.Price_List__r.Oracle_Operating_Unit__c =: opunit OR (p.Price_List__r.State__C != null AND p.Price_List__r.State__c =: shippingState)) and p.Effective_Start_Date__c <=:currentDate and p.Effective_End_Date__c >=:currentDate and p.Is_Active__c = \'true\' and type_1__c = \'Ala Carte\'' + prodFilter ;
        }
        qry += ' order by p.Item_Description__c';
        ApexPages.Standardsetcontroller fliterSetCon = new ApexPages.StandardSetController(Database.getQueryLocator(qry));        
        return fliterSetCon ;      
    }   
    
    /**
    * Begin of PAGINATION METHODS
    *
    */
    
    // indicates whether there are more records after the current page set.
    public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }
    
    // indicates whether there are more records before the current page set.
    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }
    
    // returns the page number of the current page set
    public Integer pageNumber {
        get {
            return setCon.getPageNumber();
        }
        set;
    }
    
    // returns the first page of records
    public void first() {
        setCon.first();
        products = (List<Price_List_Item__c>) setCon.getRecords();
    }
    
    // returns the last page of records
    public void last() {
        setCon.last();
        products = (List<Price_List_Item__c>) setCon.getRecords();
    }
    
    // returns the previous page of records
    public void previous() {
        setCon.previous();
        products = (List<Price_List_Item__c>) setCon.getRecords();
    }
    
    // returns the next page of records
    public void next() {
        setCon.next();
        products = (List<Price_List_Item__c>) setCon.getRecords();
    }
    
    // returns the PageReference of the original page, if known, or the home page.
    public void cancel() {
        setCon.cancel();
    }
    
    
    
    /** Inner class PriceItemWrapper.
    *  
    */
    public class PriceItemWrapper {
        public String ID {get;set;}
        public String Name {get;set;}
        public String prodType {get;set;}
        public String Qty {
            get{
                if(Qty!=null && Qty!=''){
                    Integer result =Qty.indexOf('.');
                    if(result != -1){
                        Qty= Qty.substring(0,result);
                    }
                }
                return Qty;
            }
            set;
        }
        public String itemID {get;set;}
        public ID oracleItemIDRef {get;set;}
        public Boolean isExisting {get;set;}
        public String error {get;set;}
        public Decimal bundleSize {get;set;}
        public Purchase_Order_Line__c pOrderLine {get;set;}
        public PriceItemWrapper() {
            pOrderLine = new Purchase_Order_Line__c();
            isExisting =false;
        }
        // new constructor having Qty and prodType.
        public PriceItemWrapper(String ID, String Name, String prodType, String Qty){                     
            this.pOrderLine = new Purchase_Order_Line__c();
            isExisting = false;
            this.ID = ID;   
            this.Name=Name;
            this.prodType = prodType;
            this.Qty = Qty;
        }
    }

}