objects/Item__c.object
<CustomObject>
    <description>Oracle Item Master View</description>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Item ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <fields>
        <fullName>Attention_To_Email__c</fullName>
        <inlineHelpText>Single email address that RMA emails will be sent to.</inlineHelpText>
        <label>Attention To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Attention_To__c</fullName>
        <inlineHelpText>Name of the person who will receive notifications about the RMA creation and shipment. Usually the Partner contact.</inlineHelpText>
        <label>Attention To Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>RMAs</relationshipLabel>
        <relationshipName>RMAs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{00000000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RMA_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipName>RMA_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Line Items</relationshipLabel>
        <relationshipName>RMA_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RMA Line Item</label>
    <nameField>
        <label>RMA Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RMALineItemTestData.cls
@isTest
public class RMALineItemTestData {
    public Item__c item_1, item_2;
    public RMA_Line_Item__c line_item_1;

    public void createTestData_setItem() {
        item_1 = getNewItem('item_1', 'item_1');
        item_2 = getNewItem('item_2', 'item_2');
        insert new List <Item__c>{item_1, item_2};
        
        Account account_1 = getNewAccount('account_1');
        insert new List <Account>{account_1};
         
        Case case_1 = getNewCase('test', account_1.Id);
        insert new List <Case>{case_1}; 
        
        RMA__c rma_1 = new RMA__c(Case__c = case_1.Id, Attention_To__c = 'xyz', Attention_To_Email__c = 'xyz@sptest.com');
        insert new List <RMA__c>{rma_1}; 
        
        line_item_1 = new RMA_Line_Item__c(RMA__c = rma_1.Id, Name = 'item_1');
        insert new List <RMA_Line_Item__c>{line_item_1};
    }
    
    private static Item__c getNewItem(String name, String itemId) {
        Item__c item = new Item__c();
        item.Name = name;
        item.Item_ID__c = itemId;    // required
        return item;
    }

    private static Account getNewAccount(String name) {
        Account a = new Account();
        a.Name = name; 
        a.BillingStreet = '100 XYZ Plaza';
        a.BillingCity = 'Sunnyvale';
        a.BillingState = 'CA';
        a.BillingCountry = 'United States'; 
        a.BillingPostalCode = '94086';     
        return a;    
    }
    
    private static Case getNewCase(String subject, String accountId) {
        Case c = new Case();
        c.Subject = subject;
        c.AccountId = accountId;
        return c;    
    }

}