objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <label>Campaign ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Locator_Selection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Selection</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Dealer Locator Selection)</relationshipLabel>
        <relationshipName>Leads3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsAutoConvert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAutoConvert</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestBatch_ConvertLead.cls
@IsTest (SeeAllData=true)
public with sharing class TestBatch_ConvertLead {

    static testMethod void testBatchConvertLead()
    {
        /*Lead l = TestALRCommon.CreateRawLead('Test', 'Web', '', '');
        l.IsAutoConvert__c = true;
        l.Status = 'Awaiting Duplicate Review';
        insert l;

        Batch_ConvertLead b = new Batch_ConvertLead();

        Test.startTest();
        String query = 'SELECT Id, Status, FirstName, Lastname, Company, street, city, state, postalCode, country, Email, isConverted, OwnerId, Campaign_ID__c, IsAutoConvert__c , Dealer_Locator_Selection__c FROM Lead where isConverted = false limit 1';
        List<Lead> listLeads = Database.query(query);

        Id batchProcessId = Database.executeBatch(b,1);
        b.execute(null, listLeads); //Strange but I needed this line to actually get coverage

        Test.stopTest();*/

    }

}