objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Manufacturer__c</fullName>
        <label>Lead Manufacturer</label>
        <picklist>
            <picklistValues>
                <fullName>SunPower</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Light Commercial Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI Home Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Owner (Dealer Lead)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility - Investor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility - Land Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI SPNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility - Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSE - RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ipp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM Integrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Seller</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Application</label>
        <referenceTo>Partner_Application__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <businessProcess>SunPower Residential Leads Process</businessProcess>
        <description>Residential Leads</description>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Partner_Application__c.object
<CustomObject>
    <description>Used to create PA related to Lead.</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Partner Applications</relationshipLabel>
        <relationshipName>Partner_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Application</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Partner Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPartnerAppsRejection.cls
public class TestPartnerAppsRejection
{ 
    @isTest
    public static void test_method()
    {
       Lead lead = New Lead();
       lead.Company = 'LeadCompany';
       lead.Lead_Type__c ='Residential';
       lead.Status = 'Open';
       lead.Lead_Manufacturer__c='SunPower';
       lead.LeadSource ='Web';
       lead.LastName = 'TestLead';
       lead.Email = 'testlead@gmail.com';
       insert lead;
       
       Partner_Application__c partnerApps = new Partner_Application__c();
       partnerApps.Company_Name__c = 'TestCompany';
       partnerApps.Lead__c =lead.Id;
       Insert partnerApps;
             
       String strFieldType = ApexPages.CurrentPage().getParameters().put('Id',partnerApps.Id); 
       ApexPages.StandardController sController = new ApexPages.StandardController(partnerApps); 
       PartnerAppsRejection controller = new PartnerAppsRejection(sController);
       List<SelectOption> emailTemplates = new List<SelectOption>();
       emailTemplates = Controller.getTamplate();             
    
       if(emailTemplates != null && emailTemplates.size() >0)
       {         
          controller.selectedTamplate = emailTemplates.get(1).getValue();
       }       
       controller.Save();      
       }
}