objects/Lease_2_1_PO_Creation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to used in Quote Trigger: CreatePurchaseOrderandPurchaseOrderLine, to be used to get the PriceList</description>
    <label>Lease 2.1 PO Creation</label>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Quote_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent summary for this quote.  Summary contains 3 quotes.</inlineHelpText>
        <label>Quote Summary</label>
        <referenceTo>Quote_Summary__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Summary__c.object
<CustomObject>
    <label>Quote Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AdhocLDAUtility_Test.cls
/**
 * Created by cdevarapalli on 8/2/17.
 */
@isTest
public class AdhocLDAUtility_Test {

    @testSetup
    static void dataSetup(){
        Lease_2_1_PO_Creation__c lease21PoC = TestFactory_Custom_Settings.createLease21POCreation();
        insert lease21PoC;
    }

    static testMethod void adhocCreateLDA(){

        Quote testQuote = TestFactory_StandardObjects.createProposalQuote(null);
        insert testQuote;

        Quote_Summary__c testQuoteSummary = TestFactory_Sales_Residential.createQuoteSummary(testQuote);
        insert testQuoteSummary;

        echosign_dev1__SIGN_Agreement__c testAgreement = TestFactory_Ordering.createAgreement(testQuote);
        insert testAgreement;

        test.startTest();
        String alertString = AdhocLDAUtility.adhocCreateLDA(testAgreement.Id);
        test.stopTest();

    }
}