objects/LeasePayment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>This Was made Master Detail as the LEase Payment was made private to avoid any visibility issues.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lease_old__c</fullName>
        <externalId>true</externalId>
        <label>Lease # old</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation with RMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased HO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separation of Lesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disposed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Payment</label>
    <nameField>
        <label>Financial Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Lease_Number__c</fullName>
        <label>Original Lease Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CaseLeasePaymentTestData.cls
@isTest
public class CaseLeasePaymentTestData {
    public Account account_1, account_2;
    public LeasePayment__c leasePayment_1, leasePayment_2;
    public Quote quote_1;
    public List <Account> accountList;
    public List <LeasePayment__c> leasePaymentList;
    public List <Quote> quoteList;
    
    public void createTestData_LeaseOld_NotBlank() {
        // account
        account_1 = getNewAccount('account_1');   
        insert new List <Account>{account_1};
        // lease payment
        leasePayment_1 = getNewLeasePayment('leasePayment_1', account_1.Id);
        leasePayment_1.Lease_old__c = '12345';   
        insert new List <LeasePayment__c>{leasePayment_1};
    }

    public void createTestData_Lease_Active() {
        // account
        account_1 = getNewAccount('account_1');   
        insert new List <Account>{account_1};
        // lease payment
        leasePayment_1 = getNewLeasePayment('leasePayment_1', account_1.Id);
        leasePayment_1.Lease_old__c = '12345';
        leasePayment_1.Status__c = 'Terminated';   
        leasePayment_2 = getNewLeasePayment('leasePayment_2', account_1.Id);
        leasePayment_2.Lease_old__c = '67890';   
        leasePayment_2.Status__c = 'Active';   
        insert new List <LeasePayment__c>{leasePayment_1, leasePayment_2};
    }

    public void createTestData_AccountChange() {
        // account
        account_1 = getNewAccount('account_1');   
        account_2 = getNewAccount('account_2');   
        insert new List <Account>{account_1, account_2};
        // lease payment
        leasePayment_1 = getNewLeasePayment('leasePayment_1', account_1.Id);
        leasePayment_1.Lease_old__c = '12345';   
        leasePayment_2 = getNewLeasePayment('leasePayment_2', account_2.Id);
        leasePayment_2.Lease_old__c = '67890';   
        insert new List <LeasePayment__c>{leasePayment_1, leasePayment_2};
    }

    public void createTestData_AccountChange_NoLease() {
        // account
        account_1 = getNewAccount('account_1');   
        account_2 = getNewAccount('account_2');   
        insert new List <Account>{account_1, account_2};
        // lease payment
        leasePayment_1 = getNewLeasePayment('leasePayment_1', account_1.Id);
        leasePayment_1.Lease_old__c = '12345';   
        insert new List <LeasePayment__c>{leasePayment_1};
    }

    public void createTestData_LeasePaymentChange() {
        // account
        account_1 = getNewAccount('account_1');   
        insert new List <Account>{account_1};
        // lease payment
        leasePayment_1 = getNewLeasePayment('leasePayment_1', account_1.Id);
        leasePayment_1.Lease_old__c = '12345';   
        leasePayment_2 = getNewLeasePayment('leasePayment_2', account_1.Id);
        leasePayment_2.Lease_old__c = '67890';   
        insert new List <LeasePayment__c>{leasePayment_1, leasePayment_2};
    }

    public void createTestData_OriginalLeaseNumber_NotBlank() {
        // account
        account_1 = getNewAccount('account_1');   
        insert new List <Account>{account_1};
        // opportunity
        Opportunity oppty_1 = getNewOpportunity('oppty_1', account_1.Id);
        insert new List <Opportunity>{oppty_1};
        // quote
        quote_1 = getNewQuote('quote_1', oppty_1.Id);
        quote_1.Original_Lease_Number__c = '12345';
        insert new List <Quote>{quote_1};
        // lease payment
        leasePayment_1 = getNewLeasePayment('leasePayment_1', account_1.Id);
        leasePayment_1.Quote__c = quote_1.Id;
        insert new List <LeasePayment__c>{leasePayment_1};
    }

    public void createTestData_SPVT() {
        // account
        account_1 = getNewAccount('account_1');   
        insert new List <Account>{account_1};
        // lease payment
        leasePayment_1 = getNewLeasePayment('leasePayment_1', account_1.Id);
        leasePayment_1.Lease_old__c = '12345';   
        insert new List <LeasePayment__c>{leasePayment_1};
    }

    public void createTestData_LeaseOld_Batch(Integer batchSize) {
        // account
        accountList = new List <Account>();
        for (Integer i=0; i<batchSize; i++) {
            Account a = getNewAccount('account_' + i);
            accountList.add(a); 
        }  
        insert accountList;
        // lease payment
        leasePaymentList = new List <LeasePayment__c>();
        for (Integer i=0; i<batchSize; i++) {
            LeasePayment__c lp = getNewLeasePayment('leasePayment_' + i, accountList[i].Id);
            lp.Lease_old__c = String.valueOf(i); 
            leasePaymentList.add(lp);  
        }
        insert leasePaymentList;
    }

    public void createTestData_OriginalLeaseNumber_Batch(Integer batchSize) {
        // account
        accountList = new List <Account>();
        for (Integer i=0; i<batchSize; i++) {
            Account a = getNewAccount('account_' + i);
            accountList.add(a); 
        }  
        insert accountList;
        // opportunity
        List <Opportunity> opptyList = new List <Opportunity>();
        for (Integer i=0; i<batchSize; i++) {
            Opportunity oppty = getNewOpportunity('oppty_' + i, accountList[i].Id);
            opptyList.add(oppty);
        }
        insert opptyList;
        // quote
        quoteList = new List <Quote>();
        for (Integer i=0; i<batchSize; i++) {
            Quote q = getNewQuote('quote_' + i, opptyList[i].Id);
            q.Original_Lease_Number__c = String.valueOf(i);
            quoteList.add(q);
        }
        insert quoteList;
        // lease payment
        leasePaymentList = new List <LeasePayment__c>();
        for (Integer i=0; i<batchSize; i++) {
            LeasePayment__c lp = getNewLeasePayment('leasePayment_' + i, accountList[i].Id);
            lp.Quote__c = quoteList[i].Id; 
            leasePaymentList.add(lp);  
        }
        insert leasePaymentList;
    }
    
    private static Account getNewAccount(String name) {
        Account a = new Account();
        a.Name = name; 
        a.BillingStreet = '100 XYZ Plaza';
        a.BillingCity = 'Sunnyvale';
        a.BillingState = 'CA';
        a.BillingCountry = 'United States'; 
        a.BillingPostalCode = '94086';     
        return a;    
    }
    
    private static LeasePayment__c getNewLeasePayment(String name, String accountId) {
        LeasePayment__c lp = new LeasePayment__c();
        lp.Name = name;
        lp.Account__c = accountId; 
        return lp;
    }
    
    private static Opportunity getNewOpportunity(String name, String accountId) {
        Opportunity oppty = new Opportunity();
        oppty.Name = name;
        oppty.AccountId = accountId;
        oppty.StageName = '20% - Opportunity Contacted';    // avoid null pointer exception
        oppty.CloseDate = System.today();    // required
        return oppty;    
    
    }

    private static Quote getNewQuote(String name, String opportunityId) {
        Quote q = new Quote();
        q.Name = name;
        q.OpportunityId = opportunityId;
        return q;    
    
    }
    
    
}