objects/LeasePayment__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation with RMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased HO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separation of Lesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed Buyout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disposed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Payment</label>
    <nameField>
        <label>Financial Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LeasePaymentBeforeInsertHandler.cls
public class LeasePaymentBeforeInsertHandler extends TriggerHandlerBase {
	// -------- Constants --------

	// -------- Constructor --------
	public LeasePaymentBeforeInsertHandler() {}

	// -------- Variables --------
	Map<Id, LeasePayment__c> quoteIdLP;
	List<LeasePayment__c> iiList; // ***** THIS CAN BE REMOVED AFTER INVOICE OPTIMIZATION CUT OVER *****

	// -------- Properties --------

	// -------- Methods --------
	// Cast and determine qualified records
	public override void qualifyStartingRecords(List<sObject> newList, List<sObject> oldList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap){
		Diagnostics.push('LeasePaymentBeforeInsertHandler qualifyStartingRecords');

		List<LeasePayment__c> newRecords = (List<LeasePayment__c>)newList;

		quoteIdLP = new Map<Id, LeasePayment__c>();
		iiList = new List<LeasePayment__c>(); // ***** THIS CAN BE REMOVED AFTER INVOICE OPTIMIZATION CUT OVER *****

		for(LeasePayment__c lp : newRecords) {
			if(String.isNotBlank(lp.Quote__c)) {
				quoteIdLP.put(lp.Quote__c, lp);

				// START ***** THIS CAN BE REMOVED AFTER INVOICE OPTIMIZATION CUT OVER *****
				// run the install/interconnect logic
				if(lp.Status__c == 'Active') iiList.add(lp);
				// END ***** THIS CAN BE REMOVED AFTER INVOICE OPTIMIZATION CUT OVER *****
			}
		}
		Diagnostics.pop();
	}

	public override void start() {
		Diagnostics.push('LeasePaymentBeforeInsertHandler start');

		Diagnostics.pop();
	}

	public override void finish(Boolean fromStart) {
		Diagnostics.push('LeasePaymentBeforeInsertHandler finish');

		if(fromStart) {
			if(!quoteIdLP.isEmpty()) {
				LeasePaymentService.connectFPOtoRP(quoteIdLP);

				LeasePaymentService.setLPemailAddresses(quoteIdLP);
			}
			if(!iiList.isEmpty()) LeasePaymentService.populateInstallAndInterconnect(iiList); // ***** THIS CAN BE REMOVED AFTER INVOICE OPTIMIZATION CUT OVER *****
		}
		Diagnostics.pop();
	}
}