objects/Lease_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <description>Every lease progress should look-up to a quote.</description>
        <inlineHelpText>Record to track payment terms / performance ranges of a quoted system.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Lease Schedules</relationshipLabel>
        <relationshipName>Lease_Progress</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lease Schedule</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Lease Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lease_Schedule_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Lease Schedule Summaries</relationshipLabel>
        <relationshipName>Lease_Schedule_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lease Schedule Summary</label>
    <nameField>
        <displayFormat>LSS-{0000}</displayFormat>
        <label>Lease  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Schedule Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LeasePayment__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Lease_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Payment</label>
    <nameField>
        <label>Financial Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestLeaseCalculationsController.cls
@isTest(SeeAllData=true)
private class TestLeaseCalculationsController {
//Unit tests for the button
	static Account newAccount;
    static Contact newContact;
    static Opportunity newOpportunity;
    static Quote newQuote;
    
    static void setup()
    {
        newAccount = TestUtils.createAccount('CPR TEST ACCOUNT 1', TestUtils.getResidentialRecordTypeId() , true );
        newContact = TestUtils.createContact('CPR TEST CONTACT 1', newAccount.Id, true );
        newOpportunity = TestUtils.createOpportunities( 1 , newAccount.Id, newContact.Id, true)[0];
    }
    
	static testMethod void testLeaseCalculationsConstructor() 
	{
		setup();
		
		newQuote = TestUtils.createQuotes( 1, 'Sample Quote Name', newOpportunity.Id, true )[0];
		
		
		LeasePayment__c leasePayment = TestUtils.createLeasePayment( 'Lease Payment', newAccount.Id, newQuote.Id, true );
				
		Test.startTest();
		
			ApexPages.Standardcontroller stdc = new ApexPages.Standardcontroller(leasePayment);
			LeaseCalculationsController leaseCalculationsController = new LeaseCalculationsController(stdc);
		
		Test.stopTest();
		
		System.assertNotEquals( null, leaseCalculationsController.leasePayment, 'The leasePayment should be set.' );
		System.assertEquals( leasePayment.Id, leaseCalculationsController.leasePayment.Id, 'The leasePayment should be set to the leasePayment created.' );
	}
	
	static testMethod void testRunCalculations()
	{
		setup();
		
		newQuote = TestUtils.createQuotes( 1, 'Sample Quote Name', newOpportunity.Id, true )[0];

		List<Lease_Schedule__c> leaseSchedules = TestUtils.createLeaseSchedules( newQuote.Id, true );
		
		LeasePayment__c leasePayment = TestUtils.createLeasePayment( 'Lease Payment', newAccount.Id, newQuote.Id, true );
				
		ApexPages.Standardcontroller stdc = new ApexPages.Standardcontroller(leasePayment);
		LeaseCalculationsController leaseCalculationsController = new LeaseCalculationsController(stdc);

		Test.startTest();
		
			PageReference actualPageRef = leaseCalculationsController.runCalculations();
		
		Test.stopTest();
		
		List<Lease_Schedule_Summary__c> actualLeaseSummaries = [SELECT Id FROM Lease_Schedule_Summary__c WHERE Quote__c = :leasePayment.Quote__c];
		
		System.assertEquals(1,actualLeaseSummaries.size(),'There should be one lease schedule summary created');
		
		String actualUrl = actualPageRef.getUrl();
				
		System.assert(actualUrl.contains(actualLeaseSummaries[0].Id),'The page ref should redirect to the newly calculated summary');	
	}
	
}