objects/Location__c.object
<CustomObject>
    <description>Hold information about location coordinates.</description>
    <fields>
        <fullName>Latitude__c</fullName>
        <description>Latitude of this location.</description>
        <label>Latitude</label>
        <precision>13</precision>
        <required>true</required>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <description>Longitude of this location.</description>
        <label>Longitude</label>
        <precision>13</precision>
        <required>true</required>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DealerLocatorControllerTests.cls
@isTest
private class DealerLocatorControllerTests {
    private static Account customer;
    private static Location__c baseLocation;
    
    testMethod static void testOnSearch() {
        setUp();
        
        DealerLocatorController target = new DealerLocatorController();
        target.radius = 5;
        target.baseLocation = '94306';
        target.accType = 'Home';
        target.onSearch();
    }
    
    private static void setUp() {
        customer = new Account(Name='DealerLocatorTest',ShippingPostalCode='94306');
        customer.BillingCountry='Test1';
        customer.BillingState='Test2';
        customer.BillingCity='Test3';
        customer.BillingStreet='Test4';
        customer.BillingPostalCode='1234';
        customer.ShippingCountry='Test1';
        customer.ShippingState='Test2';
        customer.ShippingCity='Test3';
        customer.ShippingStreet='Test4';
        customer.ShippingPostalCode='1234';
        insert customer;
        
        baseLocation = new Location__c(Name='94306101',Latitude__c=37.418009,Longitude__c=-122.127375);
        insert baseLocation;
    }
}