objects/Partner_Application__c.object
<CustomObject>
    <description>Used to create PA related to Lead.</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Industry__c</fullName>
        <inlineHelpText>What industry is the candidate currently operating (Construction, HVAC, Windows/Doors, Solar, etc.)</inlineHelpText>
        <label>Current Industry</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Existing_Pending_Litigation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Does the candidate have any lawsuits or legal issues against themselves, their company?</inlineHelpText>
        <label>Existing/Pending Litigation?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_1__c</fullName>
        <inlineHelpText>Candidate headquarter location (City and State)</inlineHelpText>
        <label>Location #1 (City, State)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Level_Employees__c</fullName>
        <formula>Manager_Design_Employees__c +  Manager_Finance_Employees__c +  
Manager_Installation_Employees__c +  Manager_Marketing_Employees__c +  
Manager_Operations_Employees__c +  Manager_Other_Employees__c +  
Manager_Sales_Employees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>How many Design managers does the candidate&apos;s organization currently employ?</inlineHelpText>
        <label>Manager-Level Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_to_Solar__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this candidate new to solar?</inlineHelpText>
        <label>New to Solar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PV_Watts_Sold_Q1__c</fullName>
        <description>Changes Paer Case# 00249138
(https://na29.salesforce.com/5008000000QWG9y)
PV Watts Sold (Q1) --&gt; Renamed to --&gt; PV KW Sold (Q1)</description>
        <inlineHelpText>Value in KW</inlineHelpText>
        <label>PV KW Sold (Q1)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PV_Watts_Sold_Q2__c</fullName>
        <description>Changes Paer Case# 00249138 
(https://na29.salesforce.com/5008000000QWG9y) 
PV Watts Sold (Q2) --&gt; Renamed to --&gt; PV KW Sold (Q2)</description>
        <inlineHelpText>Value in KW</inlineHelpText>
        <label>PV KW Sold (Q2)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PV_Watts_Sold_Q3__c</fullName>
        <description>Changes Paer Case# 00249138 
(https://na29.salesforce.com/5008000000QWG9y) 
PV Watts Sold (Q3) --&gt; Renamed to --&gt; PV KW Sold (Q3)</description>
        <inlineHelpText>Value in KW</inlineHelpText>
        <label>PV KW Sold (Q3)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PV_Watts_Sold_Q4__c</fullName>
        <description>Changes Paer Case# 00249138 
(https://na29.salesforce.com/5008000000QWG9y) 
PV Watts Sold (Q4) --&gt; Renamed to --&gt; PV KW Sold (Q4)</description>
        <inlineHelpText>Value in KW</inlineHelpText>
        <label>PV KW Sold (Q4)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Employees__c</fullName>
        <formula>Manager_Sales_Employees__c +
 Field_Level_Sales_Employees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solar_License_Certification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Solar License/Certification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Employee_Base__c</fullName>
        <formula>Field_Level_Employees__c + Manager_Level_Employees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Employee Base</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <inlineHelpText>address (URL) of the candidate&apos;s company website</inlineHelpText>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <inlineHelpText>How many years has the candidate&apos;s current company been in business</inlineHelpText>
        <label>Years in Business</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Bill to Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Partner Application</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Partner Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestNewPartnerScorecardController.cls
/**************************************************
** PR- 01923
**Created By- Harsh Mathur
**Created On- June 10 2009 
**Last Modified- Kapil G.
**Last Modified On-  July 13 2009 
**Desciption- Test class for controller NewPartnerScorecardController
*****************************************************/
	@isTest
private class TestNewPartnerScorecardController{
	@isTest
  public static void checkNewPartnerScorecardController(){
  	String id = '';
    Partner_Application__c partnerAppObj = new Partner_Application__c();
    partnerAppObj.Solar_License_Certification__c = true;
    //partnerAppObj.Total_Employee_Base__c = 7;
    partnerAppObj.Existing_Pending_Litigation__c = false;
    partnerAppObj.Location_1__c = 'test location';
    partnerAppObj.Current_Industry__c = 'PV or Solar';
    //partnerAppObj.Manager_Level_Employees__c = 2;
    //partnerAppObj.Sales_Employees__c = 2;
    partnerAppObj.Website__c = 'www.testing.com';
    partnerAppObj.New_to_Solar__c = true;
    partnerAppObj.Years_in_Business__c = 4;
    partnerAppObj.Company_Name__c = 'Test Company'+string.valueOf(DateTime.now());
    partnerAppObj.Zip__c = '123456';
    insert partnerAppObj;    
    id = partnerAppObj.Id;
    
    ApexPages.currentPage().getParameters().put('id', partnerAppObj.Id);
    ApexPages.StandardController controller = new ApexPages.StandardController(partnerAppObj);
    NewPartnerScorecardController testObj = new NewPartnerScorecardController(controller);
    testObj.partnerObj.Years_in_Business__c = 4;
    testObj.partnerObj.Current_Industry__c='PV or Solar';
    testObj.calculate();
    
    testObj.partnerObj.Years_in_Business__c = 2;
    testObj.partnerObj.Current_Industry__c='PV or Solar';
    testObj.calculate();
    
    testObj.partnerObj.Years_in_Business__c = 2;
    testObj.partnerObj.Current_Industry__c=null;
    testObj.calculate();
 
    
    testObj.autoComplete = false;
    //testObj.quickSavePartnerApp();
    testObj.savePartnerApp();
    //partnerAppObj = [Select Id from Partner_Application__c where Id =: id];
    //testObj.calculateFieldValues_CVAR();
    
    testObj.calculateFieldValues();
       
    //testObj.quickSavePartnerApp_CVAR();
    
    testObj.quickSavePartnerApp_EU();
    //partnerAppObj = [Select Id from Partner_Application__c where Id =: id];
    //testObj = new NewPartnerScorecardController(controller);
    testObj.quickSavePartnerApp_FR();
    //partnerAppObj = [Select Id from Partner_Application__c where Id =: id];
    //testObj = new NewPartnerScorecardController(controller);
    testObj.quickSavePartnerApp_IT();
    //partnerAppObj = [Select Id from Partner_Application__c where Id =: id];
    //testObj = new NewPartnerScorecardController(controller);
    testObj.quickSavePartnerApp_GE();    
    
    //TestPartnerApplicationManagement.Test_PartnerApplicationManagement();
    
    testObj.quickSavePartnerApp();
    testObj.quickSavePartnerApp();
    testObj.calculateFieldValues();
    testObj.calculateFieldValues_GE();
    testObj.calculateFieldValues_EU();
    testObj.calculateFieldValues_IT();
    testObj.calculateFieldValues_ES();
    testObj.calculateFieldValues_FR();
  }
  @isTest
   public static void checkNewPartnerScorecardControllerEU(){
  	String id = '';
    Partner_Application__c partnerAppObj = new Partner_Application__c();
    partnerAppObj.Solar_License_Certification__c = true;
    //partnerAppObj.Total_Employee_Base__c = 7;
    partnerAppObj.Existing_Pending_Litigation__c = false;
    partnerAppObj.Location_1__c = 'test location';
    partnerAppObj.Current_Industry__c = 'PV or Solar';
    //partnerAppObj.Manager_Level_Employees__c = 2;
    //partnerAppObj.Sales_Employees__c = 2;
    partnerAppObj.Website__c = 'www.testing.com';
    partnerAppObj.New_to_Solar__c = true;
    partnerAppObj.Years_in_Business__c = 4;
    partnerAppObj.Company_Name__c = 'Test Company'+string.valueOf(DateTime.now());
    partnerAppObj.Zip__c = '123456';
    partnerAppObj.PV_Watts_Sold_Q4__c = 30;
    partnerAppObj.PV_Watts_Sold_Q1__c = 15;
    partnerAppObj.PV_Watts_Sold_Q2__c = 20;
    partnerAppObj.PV_Watts_Sold_Q3__c = 25;
    insert partnerAppObj;    
    id = partnerAppObj.Id;
    Test.startTest();
    ApexPages.currentPage().getParameters().put('id', partnerAppObj.Id);
     ApexPages.currentPage().getParameters().put('Type','BGSM');     
     ApexPages.StandardController controller = new ApexPages.StandardController(partnerAppObj);
    NewPartnerScorecardController testObj = new NewPartnerScorecardController(controller);  
    testObj.quickSavePartnerApp_au();
     testObj.savePartnerApp_au();    
     testObj.quickSavePartnerApp_au();
   
    
    Test.stopTest();
  }
  
}