objects/PartnerPerformance__c.object
<CustomObject>
    <description>Business process require a validation process that kicks off when the user tries to submit a performance scorecard.</description>
    <fields>
        <fullName>Brand_Guidelines__c</fullName>
        <inlineHelpText>No violations.</inlineHelpText>
        <label>Brand Guidelines - 5 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Design_Training_Score__c</fullName>
        <inlineHelpText>All designers/engineers at Associate level within 6 months of hire date and Advanced within 12 months.</inlineHelpText>
        <label>Design Training - 5 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Home_Inspection_Score__c</fullName>
        <inlineHelpText>Pass 2 inspections in a row on first try.</inlineHelpText>
        <label>Home Inspection - 10 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Training_Score__c</fullName>
        <inlineHelpText>All installers at Associate level within 6 months of hire date and Advanced within 12 months.</inlineHelpText>
        <label>Install Training - 5 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Logo_Gear__c</fullName>
        <inlineHelpText>Ordered $2 worth of logo gear from Smart Store for every kW of sales.</inlineHelpText>
        <label>Logo Gear - 10 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDTF_Funds_Used__c</fullName>
        <inlineHelpText>90% of MDTF funds used before expiration.</inlineHelpText>
        <label>MDTF Funds Used - 5 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Marketing_Material__c</fullName>
        <inlineHelpText>One brochure ordered for each kW of sales.</inlineHelpText>
        <label>Marketing Material - 10 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Office_Display__c</fullName>
        <inlineHelpText>Office display in showroom; Premier Dealer logo in front of building.</inlineHelpText>
        <label>Office Display - 5 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Time_Sales_Forecast_Score__c</fullName>
        <inlineHelpText>Complete and by due date.</inlineHelpText>
        <label>On Time Sales Forecast - 10 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Contact__c</fullName>
        <inlineHelpText>Contacted within an average of 2 business days.</inlineHelpText>
        <label>Opportunity Contact - 10 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Training_Score__c</fullName>
        <inlineHelpText>All sales people at Associate level within 9 months of hire date.</inlineHelpText>
        <label>Sales Training - 5 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submit_Status__c</fullName>
        <label>Submit Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Validation_Status__c</fullName>
        <label>Validation Status</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Vehicle_Signage__c</fullName>
        <inlineHelpText>100% of company vehicles using Premier Dealer logo.</inlineHelpText>
        <label>Vehicle Signage - 5 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Warranty_Card_Return_Score__c</fullName>
        <inlineHelpText>1 warranty card received for every 10 kW of PV shipped.</inlineHelpText>
        <label>Warranty Card Return - 5 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website_Logo__c</fullName>
        <inlineHelpText>Premier Dealer logo on dealer homepage and all primary pages.</inlineHelpText>
        <label>Website Logo - 10 pts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>HRS Partner Performance</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Partner Performance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HRS Partner Performances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PartnerPerformanceManagement.cls
/***************************************
***PR-01926
***Created By- Kapil Goutam
***On - June 10 2009
***Last Modified- 
***Last Modified On - 
***Description- Class which update "Submit Status" & "Validation Status" according to specified validation
***Class method will be called from before insert & before update trigger of partner performance object  
****************************************/
public class PartnerPerformanceManagement {
	
	public static void beforePartnerPerformanceInsert (List<PartnerPerformance__c> partnerPerformanceList){
		Boolean isComplete = true;
 		for(PartnerPerformance__c pp:partnerPerformanceList){
 			 
 			if(pp.Brand_Guidelines__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Logo_Gear__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.MDTF_Funds_Used__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Marketing_Material__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Office_Display__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Vehicle_Signage__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Website_Logo__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Sales_Training_Score__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Install_Training_Score__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Design_Training_Score__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Opportunity_Contact__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Home_Inspection_Score__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.On_Time_Sales_Forecast_Score__c == null){
 				isComplete = false;
 			}
 			if(isComplete && pp.Warranty_Card_Return_Score__c == null){
 				isComplete = false;
 			}
 	
 			//to set status
 			if(isComplete == false){
 				//pp.Submit_Status__c = 'Incomplete';
 				pp.Validation_Status__c = 'Missing Data';
 			}
 			else{
 				//pp.Submit_Status__c = 'Complete';
 				pp.Validation_Status__c = 'Data Entry Complete';
 			}
 		}
    }        

    public static void beforePartnerPerformanceUpdate (List<PartnerPerformance__c> partnerPerformanceList, 
        List<PartnerPerformance__c> oldPartnerPerformanceList){
        	beforePartnerPerformanceInsert(partnerPerformanceList);
       
    }

}