objects/Partner_Application__c.object
<CustomObject>
    <description>Used to create PA related to Lead.</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Application</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Partner Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Country_Domain__c</fullName>
        <description>Used by external design applications to show country-specific content in the Partner Portal and in the external design applications.  Used for both SunPower and Partner Users.  For Partner users this value should default to the Account.Country_Domain.</description>
        <label>Country Domain</label>
        <picklist>
            <picklistValues>
                <fullName>rvar-us</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-be</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-au</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-rl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>rvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cvar-jp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>combo-jp</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestPartnerApplicationTopMsgController.cls
@isTest
private class TestPartnerApplicationTopMsgController {
    @isTest
    public static void testController() {
        List<RecordType> recordTypeList = [SELECT Id, Name FROM RecordType
                WHERE SObjectType = 'Partner_Application__c'
                AND Name IN ('EU Partner Application', 'NA Partner Application') ORDER BY Name];
        
        List<Partner_Application__c> partnerApplicationList = new List<Partner_Application__c>();
        
        Integer count = 0;
        for (RecordType recordType : recordTypeList) {
            count++;
            Partner_Application__c partnerApplication = new Partner_Application__c();
            partnerApplication.Company_Name__c = 'Company_Name__c' + count;
            partnerApplication.RecordTypeId = recordType.Id;
            partnerApplicationList.add(partnerApplication);
        }
        
        insert partnerApplicationList;
        
        count = 0;
        for (Partner_Application__c partnerApp : partnerApplicationList) {
            count++;
            String msg = '';
            PartnerApplicationTopMsgController controller =
                    new PartnerApplicationTopMsgController(new ApexPages.StandardController(partnerApp));
            if (count == 1 && recordTypeList.size() == 2) {
                // 'EU Partner Application'
                /*String countryDomain = [SELECT Country_Domain__c FROM User
                        WHERE Id = :UserInfo.getUserId()].Country_Domain__c;
                if (countryDomain != null && countryDomain.contains('-it')) {
                    msg = 'RSM, Area Sales Manager and Director of Sales';
                } else {*/
                    msg = 'RSM and Area Sales Manager';
                //}
            } else {
                // 'NA Partner Application'
                msg = 'Area Sales Manager';
            }
            //RSM and Area Sales Manager
            //System.assertEquals(controller.msg, msg + ' must be filled before submitting for approval.');
        }
    }
}