objects/Price_List__c.object
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Price_List_Item__c.object
<CustomObject>
    <description>To associate Price List with the Items and keep the item pricing info as well*.</description>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>There will be one price list per Operating Unit</description>
        <label>Price List</label>
        <referenceTo>Price_List__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>Price_List_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <label>Price List Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PriceListItemController.cls
/*
	Last Modified By :- Jitendra Appirio
    Purpose:- No changes done. deployed only for updating the last modified by on this class
*/
public class PriceListItemController {
	
	public Price_List_Item__c currentItem{get;set;}
	public PriceListItemController(ApexPages.standardController control){
		currentItem = (Price_List_Item__c)control.getRecord();
		currentItem = [Select Id,Name,Price_List__c,Price_List__r.Name from Price_List_Item__c where Id=:currentItem.ID limit 1];
	}
}