objects/Project_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Residential_Project__c</fullName>
        <label>Residential Project</label>
        <referenceTo>Residential_Project__c</referenceTo>
        <relationshipLabel>Project Team Members</relationshipLabel>
        <relationshipName>Project_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM{0000000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Residential_Project__c.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Justification__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This is a pick list field manually populated by any system user cancelling a project. This field is mandatory when a project&apos;s status to cancelled.
The pick list values represent the standard, allowable business justifications for cancelling a project.</description>
        <label>Cancellation Justification</label>
        <picklist>
            <picklistValues>
                <fullName>Financial Situation Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homeowner Death</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpermitted Structure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled within 7 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Sale Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Changed Mind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Service Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Death</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health &amp; Personal Reason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Install - 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunPower Service Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to External IP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Installation_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Name: Residential Installation Management 
Requester: Priti Rastogi 
Populated manually or programmatically based on zip code rules.</description>
        <label>Installation Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Residential Projects (Installation Partner)</relationshipLabel>
        <relationshipName>Residential_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Project Name: Residential Installation Management
Requester: Priti Rastogi
This pick list value is automatically populated at record creation with a default value of &quot;Active.&quot; This is a pick list field that can be manually updated by a project team member at any point during the installation project lifecycle in order to communicate project status to the whole team and to track project status data.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Residential Project</label>
    <nameField>
        <label>Residential Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ResidentialProjectNotification_Test.cls
@isTest
public class ResidentialProjectNotification_Test {
	
    static testMethod void testCancelChatterNotification(){

        Account partner = TestFactory_StandardObjects.createPartnerAccount();
        insert partner;

        Residential_Project__c project = TestFactory_ResidentialProjMgmt.createSPDProject(NULL,NULL,NULL);
        project.Installation_Partner__c = partner.Id;
        insert project; 

        Project_Team_Member__c ptm = TestFactory_ResidentialProjMgmt.getTeamMember(project.Id, 'Project Manager');

        Test.startTest();
        project.Status__c = 'Cancelled';
        project.Cancellation_Justification__c = 'Change of Dealer';
        update project;

        Test.stopTest();
    }
    
}