objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Partner PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Order_Line__c.object
<CustomObject>
    <description>This custom object holds the order line information to be passed to Oracle after Online Ordering Process.</description>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLine-{0000000000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PurchaseOrderDeltaControllerTest.cls
@isTest(SeeAllData = true)
private class PurchaseOrderDeltaControllerTest {

	@isTest static void init() {
		Quote quoteA = TestFactory_StandardObjects.getProposalQuote();

		Purchase_Order__c po1 = TestFactory_Ordering.createPurchaseOrder();
		po1.Quote__c = quoteA.Id;
		po1.Order_Status__c = 'Processed';
		insert po1;

		Purchase_Order_Line__c po1line = TestFactory_Ordering.createPurchaseOrderLine();
		po1line.Purchase_Order__c = po1.Id;
		insert po1line;

		Purchase_Order__c po2 = TestFactory_Ordering.createPurchaseOrder();
		insert po2;

		Purchase_Order_Line__c po12ine = TestFactory_Ordering.createPurchaseOrderLine();
		po12ine.Purchase_Order__c = po2.Id;
		insert po12ine;

		Test.startTest();
			Test.setCurrentPage(Page.PurchaseOrderDelta);
			ApexPages.currentPage().getParameters().put('newPOId', po2.Id);
            ApexPages.currentPage().getParameters().put('oldPOId', po1.Id);
            PurchaseOrderDeltaController controller = new PurchaseOrderDeltaController();
            String s = PurchaseOrderUtility.getPODeltaURL(po2.Id, quoteA.Id);
		Test.stopTest();
	}
}