objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Quote_ID__c</fullName>
        <label>Quote ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent summary for this quote.  Summary contains 3 quotes.</inlineHelpText>
        <label>Quote Summary</label>
        <referenceTo>Quote_Summary__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Locked_Scenario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Locked Scenario1</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Quote.Is_Locked__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Summaries</relationshipLabel>
        <relationshipName>Quote_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Roof_Details__c.object
<CustomObject>
    <fields>
        <fullName>Quote_Id__c</fullName>
        <label>Quote Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Roof Details</label>
    <nameField>
        <label>Roof Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roof Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestFactory_Sales_Residential.cls
/**
 * Created by cdevarapalli on 4/6/17.
 * Test Factory for Sales Residential
 */
@isTest
public class TestFactory_Sales_Residential {

    //Create Roof Detail
    public static Roof_Details__c createRoofDetail(Id quoteId){
        if(quoteId == NULL) quoteId = TestFactory_StandardObjects.getProposalQuote().Id;
        Roof_Details__c rDet = new Roof_Details__c();
        rDet.Quote_Id__c = quoteId;
        return rDet;
    }

    //Create Quote Summary
    public static Quote_Summary__c createQuoteSummary(Quote q){
        if(q == NULL) q = TestFactory_StandardObjects.getProposalQuote();
        Quote_Summary__c qs = new Quote_Summary__c();
        qs.Locked_Scenario__c = q.Id;
        return qs;
    }
}