objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Create_Amendment_Doc__c</fullName>
        <formula>IF( AND(Is_Locked__c = TRUE, Lease_Doc_Signed__c = TRUE) , HYPERLINK(&quot;https://composer.congamerge.com?sessionId=&quot;&amp;$Api.Session_ID&amp;&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_290&amp;&quot;&amp;ReportId= [SystemProd]00O80000005dse0&quot;&amp;&quot;&amp;id=&quot;&amp;Id&amp;&quot;&amp;QueryId=a2U80000000TN98&amp;TemplateId=&quot;&amp;IF( AmmendmentType_AmdQuote__c = &apos;Product&apos;, IF( ((Temp_Contact_1__c &lt;&gt; NULL || Temp_Contact_1__c &lt;&gt; &apos;&apos;) &amp;&amp; (Temp_Contact_2__c &lt;&gt; NULL || Temp_Contact_2__c &lt;&gt; &apos;&apos;)), &quot;a2N80000000PB2m&quot;, IF( ((Temp_Contact_1__c &lt;&gt; NULL || Temp_Contact_1__c &lt;&gt; &apos;&apos;) &amp;&amp; (Temp_Contact_2__c = NULL || Temp_Contact_2__c = &apos;&apos;)), &quot;a2N80000000PB2h&quot;, &apos;&apos;) ), IF( AmmendmentType_AmdQuote__c = &apos;Lessee&apos;, IF( ((Temp_Contact_1__c &lt;&gt; NULL || Temp_Contact_1__c &lt;&gt; &apos;&apos;) &amp;&amp; (Temp_Contact_2__c &lt;&gt; NULL || Temp_Contact_2__c &lt;&gt; &apos;&apos;)), &quot;a2N80000000PB2w&quot;, IF( ((Temp_Contact_1__c &lt;&gt; NULL || Temp_Contact_1__c &lt;&gt; &apos;&apos;) &amp;&amp; (Temp_Contact_2__c = NULL || Temp_Contact_2__c = &apos;&apos;)), &quot;a2N80000000PB2r&quot;, &apos;&apos;) ), IF( AmmendmentType_AmdQuote__c = &apos;Production&apos;, IF( ((Temp_Contact_1__c &lt;&gt; NULL || Temp_Contact_1__c &lt;&gt; &apos;&apos;) &amp;&amp; (Temp_Contact_2__c &lt;&gt; NULL || Temp_Contact_2__c &lt;&gt; &apos;&apos;)), &quot;a2N80000000PB36&quot;, IF( ((Temp_Contact_1__c &lt;&gt; NULL || Temp_Contact_1__c &lt;&gt; &apos;&apos;) &amp;&amp; (Temp_Contact_2__c = NULL || Temp_Contact_2__c = &apos;&apos;)), &quot;a2N80000000PB31&quot;, &apos;&apos;) ), &apos;&apos; ) ) )&amp;&quot;&amp;DS7=4&amp;ESSignaturetype=2&amp;ESCustomField1=Quote__c&amp;ESCustomFieldValue1=&quot;&amp;Id&amp;&quot;&amp;ESCustomField2=Account__c&amp;ESCustomFieldValue2=&quot;&amp;Related_Account__c&amp;&quot;&amp;ESCustomField3=OwnerId&amp;ESCustomFieldValue3=&quot;&amp;Account__r.OwnerId&amp;&quot;&amp;ESCustomField4=Created_By_Partner_Poratl_User__c&amp;ESCustomFieldValue4=Y&quot;&amp;&quot;&amp;ESCustomField5=Agreement_Name__c&amp;ESCustomFieldValue5=&quot;&amp;Account__r.Partner_Account__r.Account_Name__c&amp;&quot;-&quot;&amp;Account__r.Account_Name__c&amp;&quot;- Amendment&quot;&amp;&quot;&amp;DS7Preview=1&amp;FP0=1&amp;OFN=&quot;&amp;Account__r.Partner_Account__r.Account_Name__c&amp;&quot;-&quot;&amp;Account__r.Account_Name__c&amp;&quot;- Amendment&quot;&amp;&quot;-&quot;&amp;Final_Lease_Number__c&amp;&quot;&amp;DefaultPDF=1&amp;AttachmentParentId=&quot;&amp;Account__r.Id&amp;&quot;&amp;ESAgreementName=&quot;&amp;Account__r.Partner_Account__r.Account_Name__c&amp;&quot;-&quot;&amp;Account__r.Account_Name__c&amp;&quot;- Amendment&quot;,image(&quot;/servlet/servlet.FileDownload?file=01580000001Mehl&quot;,&quot;_blank&quot;) ), &apos;&apos;)</formula>
        <label>Create Amendment Doc</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Lease_Docs__c</fullName>
        <description>Project: GPP
Description: Create Lease Contract for Locked Quote.</description>
        <formula>IF(AND(Is_Locked__c,Code_Expiration_Date__c &gt;= TODAY(),Contractors_License__c = &apos;Y&apos;), 
IF(ISPICKVAL(QuoteType__c,&quot;Lease&quot;), 
IF(AND($User.Lease_doc_creation_allowed__c,Account__r.Partner_Account__r.Lease2_0_Program_Partner__c,INCLUDES($User.Business_Function__c,&quot;Create Lease Quote&quot;),NOT(Doc_out_for_signature__c)),IF(OR(Credit_Check_Application__r.Status__c=&apos;Approved&apos;,Credit_Check_Application__r.Status__c = &apos;Pending - Credit Review&apos;),HYPERLINK(&apos;apex/CreateLeaseDocsVF?Id=&apos;&amp;Id&amp; &quot;&amp;show=true&quot;,image(&quot;/servlet/servlet.FileDownload?file=01580000001MmlS&quot;,&quot;_blank&quot;)),HYPERLINK(&apos;apex/CreateLeaseDocsVF?Id=&apos;&amp;Id&amp; &quot;&amp;show=false&quot;,image(&quot;/servlet/servlet.FileDownload?file=01580000001MmlX&quot;,&quot;_blank&quot;))),IF(Doc_out_for_signature__c,image(&quot;/servlet/servlet.FileDownload?file=01580000001MDoh&quot;,&quot;_blank&quot;),&quot;You do not have authority to create Lease Contract&quot;) 
),IF(ISPICKVAL(QuoteType__c,&quot;Loan&quot;),IF(AND(Account__r.Partner_Account__r.Loan_Partner__c,INCLUDES($User.Business_Function__c,&quot;Create Loan Quote&quot;)),IF(ISPICKVAL(Loan_Contract_Status__c,&quot;Lending Agreement Created&quot;),HYPERLINK(&apos;apex/CreateLeaseDocsVF?Id=&apos;&amp;Id&amp; &quot;&amp;show=true&quot;,image(&quot;/servlet/servlet.FileDownload?file=01534000001tYhE&quot;,&quot;_blank&quot;)),IF(ISPICKVAL(Loan_Contract_Status__c,&quot;HIC Created&quot;),image(&quot;/servlet/servlet.FileDownload?file=01534000001tYh9&quot;,&quot;_blank&quot;),IF(ISPICKVAL(Loan_Contract_Status__c,&apos;&apos;),IF(Opportunity.Contract_Status__c != &apos;Lending Agreement Created&apos;,HYPERLINK(&apos;apex/SendLendingAgreementConfirmation?Id=&apos;&amp;Id+&apos;&amp;accId=&apos;&amp;Account__c,image(&quot;/servlet/servlet.FileDownload?file= 015340000025L2J&quot;,&quot;_blank&quot;),&apos;_self&apos;),&quot;Lending Agreement already exists for this Customer from another Quote&quot;),&quot;NOT NULL&quot;))),&quot;You do not have authority to create Loan Contract&quot;),IF(ISPICKVAL(QuoteType__c,&quot;Cash&quot;),IF(Sector__c = &apos;Residential&apos;,IF(OR(ISPICKVAL(Account__r.Partner_Account__r.Channel__c, &quot;Direct&quot;),ISPICKVAL(Account__r.Partner_Account__r.Channel__c, &quot;TPS&quot;)),HYPERLINK(&apos;apex/CreateLeaseDocsVF?Id=&apos;&amp;Id&amp; &quot;&amp;show=true&quot;,image(&quot;/servlet/servlet.FileDownload?file=015340000028Led&quot;,&quot;_blank&quot;)),&quot;Cannot Create Contracts for Cash Quotes&quot;),NULL),&quot;Cannot Create Contracts for Cash Quotes&quot;)) 
),IF(NOT(CONTAINS(Opportunity.Owner.CountryDomainText__c,&apos;au&apos;)),&quot;Quote must be locked&quot; ,&quot;Quote must be locked&quot;) 
)</formula>
        <inlineHelpText>Quote must be locked and w/in the Expiration Date. No Lease systems &gt;30 KW</inlineHelpText>
        <label>Create Contracts</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Termination_Doc__c</fullName>
        <formula>IF(OR($Profile.Name  = &apos;SunPower Lease Payment Access&apos;, $Profile.Name  = &apos;System Administrator&apos;,$Profile.Name  = &apos;Sunpower Admin(No Deployment)&apos; ),
IF(Lease_Doc_Created__c,
HYPERLINK(&quot;https://composer.congamerge.com?sessionId=&quot;&amp;$Api.Session_ID&amp;&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_290&amp;&quot;&amp;id=&quot;&amp;Id&amp;&quot;&amp;ReportId=00OV0000000OEB9&amp;TemplateId=&quot;&amp;IF(((Temp_Contact_1__c &lt;&gt; NULL || Temp_Contact_1__c &lt;&gt; &apos;&apos;)&amp;&amp; (Temp_Contact_2__c &lt;&gt; NULL || Temp_Contact_2__c &lt;&gt; &apos;&apos;)),&quot;a2N80000000PB0L&quot;,IF(((Temp_Contact_1__c &lt;&gt; NULL || Temp_Contact_1__c &lt;&gt; &apos;&apos;) &amp;&amp; (Temp_Contact_2__c = NULL || Temp_Contact_2__c = &apos;&apos;)), &quot;a2N80000000PB0Q&quot;, &apos;&apos;))&amp;&quot;&amp;DS7=4&amp;ESSignaturetype=2&amp;ESCustomField1=Quote__c&amp;ESCustomFieldValue1=&quot;&amp;Id&amp;&quot;&amp;ESCustomField2=Account__c&amp;ESCustomFieldValue2=&quot;&amp;Related_Account__c&amp;&quot;&amp;ESCustomField3=OwnerId&amp;ESCustomFieldValue3=&quot;&amp;Account__r.OwnerId&amp;&quot;&amp;ESCustomField4=Created_By_Partner_Poratl_User__c&amp;ESCustomFieldValue4=Y&quot;&amp;&quot;&amp;ESCustomField5=Agreement_Name__c&amp;ESCustomFieldValue5=&quot;&amp;Account__r.Partner_Account__r.Account_Name__c&amp;&quot;-&quot;&amp;Account__r.Account_Name__c&amp;&quot;-Termination Doc&quot;&amp;&quot;&amp;DS7Preview=1&amp;FP0=1&amp;OFN=&quot;&amp;Account__r.Partner_Account__r.Account_Name__c&amp;&quot;-&quot;&amp;Account__r.Account_Name__c&amp;&quot;-Termination Doc&quot;&amp;&quot;&amp;DefaultPDF=1&amp;AttachmentParentId=&quot;&amp;Account__r.Id&amp;&quot;&amp;ESAgreementName=&quot;&amp;Account__r.Partner_Account__r.Account_Name__c&amp;&quot;-&quot;&amp;Account__r.Account_Name__c&amp;&quot;-Termination Doc&quot;,image(&quot;/servlet/servlet.FileDownload?file=01580000001M9fq&quot;,&quot;_blank&quot;)
), &quot;&quot;
),&quot;Termination Not Allowed&quot;)</formula>
        <label>Create Termination Doc</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Installer__c</fullName>
        <label>Dealer/Installer</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <defaultValue>&quot;New Quote&quot;</defaultValue>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Edit_Quote_in_CPR__c</fullName>
        <description>HYPERLINK(&quot;/apex/Quickquote? &amp;id=&quot; &amp; Id , &quot;Edit Quote Details&quot;, &quot;_blank&quot; )</description>
        <formula>IF(OR(ISPICKVAL($User.Country_Domain__c, &apos;rvar-fr&apos;),ISPICKVAL($User.Country_Domain__c, &apos;combo-fr&apos;)),
(IF(TRUE,HYPERLINK(&quot;/apex/TPO_RoofDetailstab?mode=edit&amp;qid=&quot;+Id+&quot;&amp;aid=&quot;+Account__r.Id,&quot;Editer la proposition détaillée&quot;, &quot;_blank&quot;),&quot;Your customer is in a location that is not available for roof rental.&quot;)),
(IF($User.Quote_Creation_Allowed__c, HYPERLINK(&quot;/apex/GPPInstallerSelection?Id=&quot;+ Id +&quot;&amp;acc=&quot;+ Account__r.Id +&quot;&amp;act=e&quot;, &quot;Edit Quote Details&quot;, &quot;_blank&quot;),&quot;QUOTE EDIT NOT ALLOWED&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Edit Quote Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Date__c</fullName>
        <label>Install Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_Doc_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent summary for this quote.  Summary contains 3 quotes.</inlineHelpText>
        <label>Quote Summary</label>
        <referenceTo>Quote_Summary__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quote_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPR_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>CPR Company ID</label>
        <length>42</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPR_License_ID__c</fullName>
        <externalId>true</externalId>
        <label>CPR License ID</label>
        <length>42</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPR_QuoteID__c</fullName>
        <externalId>true</externalId>
        <label>CPR QuoteID</label>
        <length>42</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Reason for Amendment/Revision</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Create_Amendment_Doc__c</fullName>
        <formula>IF(  AND( ISPICKVAL( Ammendment__c , &apos;&apos; ) ,  Locked_Scenario__r.Lease_Doc_Signed__c = TRUE ,  Locked_Scenario__r.AmmendmentType_AmdQuote__c  &lt;&gt; &apos;&apos; ) ,  Locked_Scenario__r.Create_Amendment_Doc__c , &apos;&apos;  )</formula>
        <label>Create Amendment Doc</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Lease_Docs__c</fullName>
        <formula>IF(ISPICKVAL( Ammendment__c , &apos;&apos; ), Locked_Scenario__r.Create_Lease_Docs__c , &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Create Contracts</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Termination_Doc__c</fullName>
        <formula>Locked_Scenario__r.Create_Termination_Doc__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Create Termination Doc</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <formula>Account_Name__r.Partner_Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Installer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer/Installer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quote_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <formula>Dealer_Installer__r.FirstName &amp; &apos; &apos;&amp; Dealer_Installer__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Edit_Quote_in_CPR__c</fullName>
        <description>HYPERLINK(&quot;/apex/Quickquote? &amp;id=&quot; &amp; Id , &quot;Edit Quote Details&quot;, &quot;_blank&quot; )</description>
        <formula>IF(Locked_Scenario__r.Contractors_License__c=&apos;Y&apos;,IF( ISBLANK(TEXT(Locked_Scenario__r.Quote_Wizard__c)),HYPERLINK(&quot;/apex/QuoteReadOnly?id=&quot;+Locked_Scenario__r.Id, &quot;Edit Quote Details&quot;, &quot;_blank&quot;),HYPERLINK(&quot;/apex/DynamicProposal?quoteId=&quot;+ CASESAFEID(Locked_Scenario__c) +&quot;&amp;action=edit&amp;quoteWizard=&quot;+ TEXT(Locked_Scenario__r.Quote_Wizard__c), &quot;Edit Quote Details&quot;, &quot;_self&quot;)), &quot;QUOTE EDIT NOT ALLOWED&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Edit Quote Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Date__c</fullName>
        <inlineHelpText>Date of system installation</inlineHelpText>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Islocked__c</fullName>
        <formula>IF( Locked_Scenario__r.Is_Locked__c , &quot;Checked&quot;, &quot;Unchecked&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Islocked</label>
        <type>Text</type>
    </fields>
    <label>Quote Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchMarked3LockSceFirstQSTest.cls
/*********************************************************************
    Test Class For Class "BatchMarked3LockSceFirstQS".
*********************************************************************/
@isTest(seealldata = true) 
private class BatchMarked3LockSceFirstQSTest{
    
    static testMethod void BatchMarked3LockSceFirstQSTest() { 

        List<Quote_Summary__c> lstQ = new List<Quote_Summary__c>();
        Database.BatchableContext BC;
        BatchMarked3LockSceFirstQS batMarkQ = new BatchMarked3LockSceFirstQS();
            
            batMarkQ.Query='Select Id,Account_Name__c,Comments__c,CPR_Company_ID__c,CPR_License_ID__c,CPR_QuoteID__c,Create_Amendment_Doc__c,Create_Lease_Docs__c,Create_Termination_Doc__c,CurrencyIsoCode,Dealer_Account__c,Dealer_Installer__c,Dealer__c,Description__c,Edit_Quote_in_CPR__c,Install_Date__c,IsDeleted,Islocked__c,Lease_Doc_Signed__c,Lease_Doc_Terminated__c,Lease_Number__c,Lease_to_be_Amended__c,Lessee__c,Locked_Scenario_Formula__c,Locked_Scenario__c,Name,Old_Lease_Number__c,Old_Quote__c,Opportunity__c,Override_30KW_Limit__c,Override__c,OwnerId,Primary_PSR__c,Quote_Number__c,Quote_View__c,View_Quote__c,(Select Id,Quote_Summary__c From Quotes__r   ORDER BY  Lease_Number__c limit 1) FROM Quote_Summary__c WHERE DMDone__c = 6030330 OR DMDone__c = 6030320 order by createddate asc limit 10';
            
            Database.executeBatch(batMarkQ, 200);         

            Test.startTest();
            batMarkQ.execute(BC, lstQ);
            //batMarkQ.finish(BC); 
            Test.stopTest();
                       

    }
}