objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsSendApprovaltoSalesAnalyst__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsSendApprovaltoSalesAnalyst</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_Doc_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LineItemsFromOpp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LineItemsFromOpp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_s_Manager__c</fullName>
        <description>Opportunity Owner&apos;s Manager</description>
        <label>Opportunity Owner&apos;s Manager</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Override_30KW_Limit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked through the trigger ShowTerminationDocButton on Quote_Summary__c (After Update) when the Override_30KW_Limit__c field is checked by the internal user. Then we are using the value in this field in the Create Lease Doc Quote formula to display the button</description>
        <label>Override 30KW Limit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Steps__c</fullName>
        <label>Quote Type</label>
        <picklist>
            <picklistValues>
                <fullName>0. Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1. PSR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. PSR In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. PSR Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Proposal Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Approved - Sent to Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Proposal Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgetary Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Binding Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Management Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting PV Availability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quote_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent summary for this quote.  Summary contains 3 quotes.</inlineHelpText>
        <label>Quote Summary</label>
        <referenceTo>Quote_Summary__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>QuoteLineItem.Total_Cost_new__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Ammendment__c</fullName>
        <label>Amendment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Reason for Amendment/Revision</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lease_Doc_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_to_be_Amended__c</fullName>
        <label>Lease  # to be Amended</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locked_Scenario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Locked Scenario1</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Quote.Is_Locked__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Summaries</relationshipLabel>
        <relationshipName>Quote_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override_30KW_Limit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override 30KW Limit</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Systems Opps: Enter Cost in Dollar or Euro per Watt for Mounting System and PV line items. All others, enter total cost of line item.

Components Opps: Enter Cost per unit.</inlineHelpText>
        <label>Cost</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>CASE(PricebookEntry.Product2.Family, &quot;Total Price&quot;,&quot;Total Price&quot;,
&quot;PV Module&quot;,&quot;PV Module&quot;,
&quot;PV Cell&quot;,&quot;PV Cell&quot;,
&quot;O&amp;M&quot;,&quot;O&amp;M&quot;,
&quot;Development&quot;,&quot;Development&quot;,
&quot;Services&quot;,&quot;Services&quot;,
&quot;Mounting Systems - Roof&quot;,&quot;Mounting Systems - Roof&quot;,
&quot;Mounting Systems - Ground&quot;,&quot;Mounting Systems - Ground&quot;,
&quot;Mounting Systems - Parking&quot;,&quot;Mounting Systems - Parking&quot;,
&quot;Balance of Plant&quot;,&quot;Balance of Plant&quot;,
&quot;Contingency&quot;,&quot;Contingency&quot;,
&quot;Sales Tax&quot;,&quot;Sales Tax&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>CASE(  PricebookEntry.Product2.Product_Type__c,&quot;Mounting System&quot;,&quot;Mounting System&quot;,&quot;BOS&quot;,&quot;BOS&quot;,&quot;Development&quot;,&quot;Development&quot;,&quot;Balance of System&quot;,&quot;Balance of System&quot;,&quot;Total Price&quot;,&quot;Total Price&quot;,&quot;PV Module&quot;,&quot;PV Module&quot;,&quot;Services&quot;,&quot;Services&quot;,&quot;O&amp;M&quot;,&quot;O&amp;M&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site_Information_Form__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>IF( Contains( Quote.Opportunity.Pricebook2.Name , &quot;System&quot;), Cost__c * Quantity * Multiplier__c, Cost__c * PricebookEntry.Product2.Wattage_Out__c * Quantity )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_new__c</fullName>
        <label>Total Cost new</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestQuoteManagement.cls
// Test class for Class QuoteManagement 
// Test class for Trigger QuoteSummaryIsLocked
@isTest
public class TestQuoteManagement {
    static testMethod void testQuoteTrigger1() {
    
        QuoteManagement qm = new QuoteManagement ();
        
        Opportunity oppty = new Opportunity();
        oppty.Name = 'TestOpp'; // 'Test class oppty for quote';
        oppty.StageName= 'Binding Offer';
        oppty.Closedate = System.today();
        oppty.Sales_Analyst__c = UserInfo.getUserId();
        insert oppty;

            
        // START Modified Reetan on 15 Sept
        
        // Create Quote Summary
        Quote_Summary__c QS = new Quote_Summary__c();
        //QS.Locked_Scenario__c = q1.Id;
        QS.Ammendment__c = 'Product';
        QS.Lease_to_be_Amended__c = 'Hello';
        QS.Override_30KW_Limit__c = FALSE;
        QS.Comments__c = 'Comment';//JAJA SEPT2815
        insert QS;
            
        // END Modified Reetan on 15 Sept            
            
        //Opportunity insertedoppty = [select id,name from opportunity where name = 'TestOpp'];
        Quote quote1 = new Quote();
            quote1.Name = 'Test - quote';
            quote1.Quote_Steps__c= 'TEst Array Layout';
            quote1.ShippingCity ='.';
            quote1.ShippingCountry ='.';
            quote1.Override_30KW_Limit__c = FALSE;
            quote1.opportunityid = oppty.id;
            quote1.Lease_Doc_Signed__c = false;
            
            quote1.Quote_Summary__c = QS.Id;
            quote1.Is_Locked__c = TRUE;
       
                 
            Test.startTest();
            
            delete [Select id, Email from Contact where Id=:UserInfo.getUserId() or Email = 'davide.pasi@sunpowercorp.com'];
            insert quote1;       
            
            Test.stopTest();                 
      }    
      
      static testMethod void testQuoteTrigger2() {
      
      // Create Quote Summary
        Quote_Summary__c QS = new Quote_Summary__c();
        //QS.Locked_Scenario__c = q1.Id;
        QS.Ammendment__c = 'Product';
        QS.Lease_to_be_Amended__c = 'Hello';
        QS.Override_30KW_Limit__c = FALSE;
        QS.Comments__c = 'Comment';//JAJA SEPT2815
        insert QS;
        
        Test.startTest();
        
            Quote quote2 = [Select q.Id, q.Opportunity.Id, q.Opportunity.Sales_Analyst__c, q.Lease_Doc_Signed__c, Opportunity_Owner_s_Manager__c, //crystal added one field 11/3/2015
                            q.ShippingCity, q.sales_analyst__c From Quote q 
                            where q.Opportunity.Sales_Analyst__c != null limit 1];                                                                               
      
            if (quote2 != null) {          
                Quote quote3 = quote2.clone(true);
                quote3.Name ='Test quote3';
                quote3.ShippingCity ='.';
                quote3.ShippingCountry ='.';
                quote3.IsSendApprovaltoSalesAnalyst__c = true;
                quote3.Lease_Doc_Signed__c = TRUE; 

                QS.Override_30KW_Limit__c = TRUE;
                QS.Locked_Scenario__c = quote3.Id;
                update QS;     

                update quote3;       
               }
           Test.stopTest();

       }
       
       static testMethod void testQuoteTrigger3() {
           Test.startTest();
                List <Quote> list1= new List<Quote>([Select q.Id, q.Opportunity.Id, q.Opportunity.Sales_Analyst__c, Opportunity_Owner_s_Manager__c, //crystal added one field 11/3/2015
                                                    q.ShippingCity, q.sales_analyst__c From Quote q 
                                                    where q.Opportunity.Sales_Analyst__c != null limit 1]);
                                            
                QuoteManagement.beforeQuoteInsert(list1);             
          
                List<QuoteLineItem> list100= new List<QuoteLineItem>([Select LineNumber, CurrencyIsoCode, QuoteId, 
                                                                    PricebookEntryId, Quantity, UnitPrice, Discount, 
                                                                    ListPrice, Subtotal, TotalPrice, Product_Name__c,
                                                                    Product__c, Cost__c, Product_Type__c, Unit__c,
                                                                    Product_Family__c, Total_Cost__c, Site__c,
                                                                    Total_Cost_new__c FROM QuoteLineItem limit 1]); 
                
                QuoteManagement.beforeQuoteLineItesInsertMethod(list100);
                
                //Added by Venkat Ramesh
                List<Quote> quoteList = [select id from Quote where OpportunityId !=null and IsSyncing = true and 
                                         LineItemsFromOpp__c = true limit 1];                                                              
                
                if(quoteList.size()>0) {
                    List<QuoteLineItem> quoteLineItemsList = [select id, QuoteId, PricebookEntryId, UnitPrice, 
                                                              Site__c, ServiceDate, Quantity, Cost__c from 
                                                              QuoteLineItem where QuoteId =:quoteList[0].Id];
                                                              
                    QuoteManagement.beforeQuoteLineItesInsertMethod(quoteLineItemsList);        
                }
        //End Venkat Ramesh
       /* QuoteLineItem qli= [Select LineNumber, CurrencyIsoCode, QuoteId, PricebookEntryId, Quantity, UnitPrice,
                            Discount, ListPrice, Subtotal, TotalPrice, Product_Name__c, Product__c, Site__c, Cost__c,
                            Product_Type__c, Product_Family__c, Total_Cost__c, Total_Cost_new__c, Unit__c 
                            FROM QuoteLineItem limit 1];       */
         //if (qli==null) return;
        //QuoteLineItem qli2=qli.clone(true);
       //update qli2;
   
        Test.stopTest();                 
    }   
}