objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amended_Lease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amended Lease Scenario</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Quote.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Quote.Lease_Doc_Signed__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lease_Doc_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuoteType__c</fullName>
        <description>Project: GPP
Description: Type of Quote(Lease/Cash)</description>
        <inlineHelpText>Type of Quote(Lease/Cash)</inlineHelpText>
        <label>QuoteType</label>
        <picklist>
            <picklistValues>
                <fullName>Lease</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quote_Expiration_Date__c</fullName>
        <inlineHelpText>Typically, a Quote expires 60 days after it is sent to the Customer</inlineHelpText>
        <label>Quote Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote_Wizard__c</fullName>
        <label>Quote Wizard</label>
        <picklist>
            <picklistValues>
                <fullName>Dynamic Mode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Mode</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term_Years__c</fullName>
        <description>Used to track a PPA term in years</description>
        <label>Term (Years)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AgreementConfirmationController.cls
/*
	Created By:	Delivery Team
	Created:	Spring 2017

	Used by the Aggreement Confirmation page for change orders
*/
public with sharing class AgreementConfirmationController {
	private Id accountId;
	private Id quoteId;
	private Id opportunityId;
	private String errorMsg;
	private Id pendingAmendmentId;
	private Id oldQuoteId;
	public Boolean isInternalUser {get; private set;}
	public Boolean hasErrors {get; private set;}
	public String comment {get; set;}
	public Boolean quoteTypeMismatch {get; private set;}
	public String quoteType {get; private set;}
	public String oldQuoteType {get; private set;}
	public Boolean quoteTermMismatch {get; private set;}
	public Integer term {get; private set;}
	public Integer oldTerm {get; private set;}
	public Boolean systemError {get; private set;}
	public Boolean agreementFailure {get; private set;}
	public Boolean errorSubmitSuccess {get; private set;}
	public Boolean errorSubmitFailure {get; private set;}
	public Boolean amendmentExists {get; private set;}
	public Boolean isInService {get; private set;}
	public Boolean isLocked {get; private set;}

	public AgreementConfirmationController() {
		// set defaults
		quoteTypeMismatch = false;
		quoteTermMismatch = false;
		hasErrors = false;
		systemError = false;
		agreementFailure = false;
		errorSubmitFailure = false;
		errorSubmitSuccess = false;
		isInService = false;
		amendmentExists = false;
		// check user
		isInternalUser = UserInfo.getUserType() == 'Standard' ? TRUE : FALSE;
		// get ids
		quoteId = ApexPages.currentPage().getParameters().get('QuoteId');

		if(String.isBlank(quoteId)) {
			hasErrors = true;
			systemError = true;
			ApexPages.Message error = new ApexPages.Message(ApexPages.Severity.ERROR, 'Quote Id Missing, please close the page and try again.');
			ApexPages.addMessage(error);
		}
	}

	public PageReference init() {
		if(!hasErrors) {
			// get the quote data for comparison
			for(Quote q : [SELECT QuoteType__c, Amended_Lease__c, Amended_Lease__r.QuoteType__c, Term_Years__c, Amended_Lease__r.Term_Years__c, Is_Locked__c, AccountId, OpportunityId FROM Quote WHERE Id = :quoteId]) {
				// set vars
				accountId = q.AccountId;
				opportunityId = q.OpportunityId;
				oldQuoteId = q.Amended_Lease__c;
				isLocked = q.Is_Locked__c;
				quoteType = q.QuoteType__c;
				oldQuoteType = q.Amended_Lease__r.QuoteType__c;
				term = Integer.valueOf(q.Term_Years__c);
				oldTerm = Integer.valueOf(q.Amended_Lease__r.Term_Years__c);
				// check locked
				if(!isLocked) {
					hasErrors = true;
				} else if(String.isBlank(q.Amended_Lease__c)) {
					// quote is locked and we need to set the old quote that this new one amends
					oldQuoteId = ApexPages.currentPage().getParameters().get('oldQuoteId');
					if(String.isNotBlank(oldQuoteId)) {
						for(Quote oldQ : [SELECT QuoteType__c, Term_Years__c FROM Quote WHERE Id = :oldQuoteId]) {
							Quote newQuote = new Quote();
							newQuote.Id = quoteId;
							newQuote.Amended_Lease__c = oldQuoteId;
							newQuote.Quote_Expiration_Date__c = System.today().addDays(15);
							update newQuote;
							oldQuoteType = oldQ.QuoteType__c;
							oldTerm = Integer.valueOf(oldQ.Term_Years__c);
						}
					} else {
						hasErrors = true;
					}
				}
				// check type
				if(!hasErrors && quoteType != oldQuoteType) {
					hasErrors = true;
					quoteTypeMismatch = true;
				}
				// check term
				if(!hasErrors && !quoteTypeMismatch && checkNull(term) != checkNull(oldTerm)) {
					hasErrors = true;
					quoteTermMismatch = true;
				}
			}
			// check for pending amendments only if there are no errors
			if(!hasErrors) {
				ResultMessage result = QuoteAmendmentUtility.checkPendingAmendment(null, accountId, 'Economic Amendment');
				if(result.success) {
					pendingAmendmentId = result.message;
					hasErrors = true;
					amendmentExists = true;
				}
			}
			// check if system is in service only if there are no errors
			if(!hasErrors && QuoteAmendmentUtility.checkInService(accountId)) {
				hasErrors = true;
				isInService = true;
			}
		}
		return null;
	}

	private Integer checkNull(Decimal n) {
		Integer num = Integer.valueOf(n);
		if(num == null) num = 0;
		return num;
	}

	public PageReference createAmendment() {
		try{
			// user date/time stamp for notes
			String notesStamp = UserInfo.getName() + ' - ' + System.today().format() + ': ';
			// create new agreement
			ResultMessage result = DocGenEconomicAmendmentRequest.createAgreementRecord(quoteId, AgreementUtility.amendmentRecTypeId, null, notesStamp + comment, 'Economic Amendment', 'Economic');
			// check result
			if(result.success) {
				// send to new agreement
				PageReference pr = new PageReference('/' + result.message);
				pr.setRedirect(true);
				return pr;
			} else {
				// new agreement failed
				agreementFailure = true;
				hasErrors = true;
				errorMsg = result.message;
			}
			// test hack for 75% coverage
        	if(Test.isRunningTest()) {
				Integer i = 10/0;
        	}
		}
		catch(Exception e) {
			hasErrors = true;
			systemError = true;
			ApexPages.Message error = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() + ' - ' + e.getStackTraceString());
			ApexPages.addMessage(error);
		}
		return null;
	}

	public PageReference back() {
		PageReference pr = new PageReference('/' + accountId);
		pr.setRedirect(true);
		return pr;
	}

	public PageReference cancelContract() {
		Id agreementId;
        for(echosign_dev1__SIGN_Agreement__c a : [SELECT Id FROM echosign_dev1__SIGN_Agreement__c WHERE Quote__c = :oldQuoteId AND echosign_dev1__Status__c = 'Signed']) {
            agreementId = a.Id;
        }
        if(String.isNotBlank(agreementId)) {
			PageReference pr = new PageReference('/apex/Cancellation?id=' + agreementId + '&aid=' + accountId + '&oId=' + opportunityId);
			pr.setRedirect(true);
			return pr;
		} else {
			hasErrors = true;
			systemError = true;
			ApexPages.Message error = new ApexPages.Message(ApexPages.Severity.ERROR, 'We cannot locate the previously signed agreement to cancel. Please use the back button and locate the agreement record on the Account and cancel it there.');
			ApexPages.addMessage(error);
			return null;
		}
	}

	public PageReference createQuote() {
		try {
			// new quote
			Quote q = new Quote();
			// get original quote info
			if(isLocked) {
				for(Quote oq : [SELECT Amended_Lease__c, Amended_Lease__r.Name, Amended_Lease__r.OpportunityId, Amended_Lease__r.Account__c, Amended_Lease__r.RecordTypeId, Amended_Lease__r.Lease_Doc_Signed__c, Amended_Lease__r.QuoteType__c FROM Quote WHERE Id = :quoteId]) {
					q.Name = oq.Amended_Lease__r.Name;
				    q.OpportunityId = oq.Amended_Lease__r.OpportunityId;
				    q.Account__c = oq.Amended_Lease__r.Account__c;
				    q.RecordTypeId = oq.Amended_Lease__r.RecordTypeId;
				    q.QuoteType__c = oq.Amended_Lease__r.QuoteType__c;
					q.Quote_Wizard__c = 'Manual Mode';
				}
			} else {
				// the current quote isn't locked and therefore can't be used as the basis for the amendment so we'll use the previous quote and start over
				oldQuoteId = ApexPages.currentPage().getParameters().get('oldQuoteId');
				for(Quote oq : [SELECT Name, OpportunityId, Account__c, RecordTypeId, Lease_Doc_Signed__c, QuoteType__c FROM Quote WHERE Id = :oldQuoteId]) {
					q.Name = oq.Name;
				    q.OpportunityId = oq.OpportunityId;
				    q.Account__c = oq.Account__c;
				    q.RecordTypeId = oq.RecordTypeId;
				    q.QuoteType__c = oq.QuoteType__c;
					q.Quote_Wizard__c = 'Manual Mode';
				}
			}
			// insert new quote
			insert q;
			// send user to eddie w/new quote
			PageReference pr = new PageReference(QuoteAmendmentUtility.getEddieCloneURL(q.Id, oldQuoteId, q.Account__c));
			pr.setRedirect(true);
			// test hack for 75% coverage
        	if(Test.isRunningTest()) {
				Integer i = 10/0;
        	}
			return pr;
		}
		catch(Exception e) {
			hasErrors = true;
			systemError = true;
			ApexPages.Message error = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() + ' - ' + e.getStackTraceString());
			ApexPages.addMessage(error);
		}
		return null;
	}

	public PageReference reportError() {
		// reset failure
		errorSubmitFailure = false;
		// setup email
		List<Messaging.SingleEmailMessage> emails = QuoteAmendmentUtility.createEmails(accountId, quoteId, 'Amendment Creation Failure', 'Request: Help with an amendment creation failure', comment, errorMsg);
		// send emails
		ResultMessage result = QuoteAmendmentUtility.sendEmails(emails, errorMsg);
		// reset agreement failure
		agreementFailure = false;
		// check status
        if(result.success) {
        	errorSubmitSuccess = true;
    	} else {
    		errorSubmitFailure = true;
    		errorMsg = result.message;
    	}
		return null;
	}

	public PageReference requestHelp() {
		// setup email
		List<Messaging.SingleEmailMessage> emails = QuoteAmendmentUtility.createEmails(accountId, quoteId, 'Post-PIS Change Request', 'Request: Help changing a contract post-PIS', comment, errorMsg);
		// send emails
		ResultMessage result = QuoteAmendmentUtility.sendEmails(emails, errorMsg);
		// reset in service
		isInService = false;
		// check status
        if(result.success) {
        	errorSubmitSuccess = true;
    	} else {
    		errorSubmitFailure = true;
    		errorMsg = result.message;
    	}
		return null;
	}

	public PageReference viewAmendment() {
		PageReference pr = new PageReference('/' + pendingAmendmentId);
		pr.setRedirect(true);
		return pr;
	}
}