objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amended_Lease__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amended Lease Scenario</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Quote.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Quote.Lease_Doc_Signed__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_Doc_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuoteType__c</fullName>
        <description>Project: GPP
Description: Type of Quote(Lease/Cash)</description>
        <inlineHelpText>Type of Quote(Lease/Cash)</inlineHelpText>
        <label>QuoteType</label>
        <picklist>
            <picklistValues>
                <fullName>Lease</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteAmendmentDeltaControllerTest.cls
@isTest(SeeAllData = true)
private class QuoteAmendmentDeltaControllerTest {
    @isTest static void init() {
        // create amended quote
        Quote quoteA = TestFactory_StandardObjects.getProposalQuote();
        // update account
        for(Opportunity o : [SELECT AccountId FROM Opportunity WHERE Id = :quoteA.OpportunityId]) {
            quoteA.Account__c = o.AccountId;
        }
        quoteA.QuoteType__c = 'Lease';
        quoteA.Lease_Doc_Signed__c = true;
        update quoteA;
        // create quote
        Quote quoteT = new Quote();
        quoteT.Name = 'Test ' + System.now();
        quoteT.OpportunityId = quoteA.OpportunityId;
        quoteT.Account__c = quoteA.Account__c;
        quoteT.Amended_Lease__c = quoteA.Id;
        quoteT.QuoteType__c = 'Lease';
        quoteT.RecordTypeId = quoteA.RecordTypeId;
        insert quoteT;

        Test.startTest();
            Test.setCurrentPage(Page.QuoteAmendmentDelta);
            ApexPages.currentPage().getParameters().put('NewQuoteId', quoteT.Id);
            ApexPages.currentPage().getParameters().put('OldQuoteId', quoteA.Id);
            QuoteAmendmentDeltaController controller = new QuoteAmendmentDeltaController();
        Test.stopTest();
    }
}