objects/RMA__c.object
<CustomObject>
    <fields>
        <fullName>Attention_To_Email__c</fullName>
        <inlineHelpText>Single email address that RMA emails will be sent to.</inlineHelpText>
        <label>Attention To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>RMAs</relationshipLabel>
        <relationshipName>RMAs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{00000000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RMAAfterInsertTriggerTest.cls
//Test Class for code coverage of RMAAfterInsert Trigger
@isTest
private class RMAAfterInsertTriggerTest{

    static testmethod void testrmainsert1(){
    
            Account accAccount = new Account(Name = 'testrmainsert1TestClass',
            Phone = '4567865999',            
            BillingStreet = '77 Rio Roble', 
            BillingCity = 'San Jose',
            BillingState = 'CA', 
            BillingPostalCode = '95134', 
            BillingCountry = 'United States', 
            Type = 'Elite-Partner-Residential', 
            Theater__c = 'North America',
            Status__c = 'Active');
        insert accAccount;
        
        
        Case case1 = new Case(
            AccountId=accAccount.Id
        );
        insert case1;
        
        
        RMA__c rma1 = new RMA__c(
            Case__c=case1.Id, Attention_To_Email__c = 'testxyz@testspwr.com'  
        );
        insert rma1;
    }
    
}