objects/RMA__c.object
<CustomObject>
    <fields>
        <fullName>RMA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RMA Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RMAs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{00000000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RMA_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Return_Quantity__c</fullName>
        <label>Expected Return Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OEM__c</fullName>
        <label>OEM</label>
        <picklist>
            <picklistValues>
                <fullName>Fronius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KACO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PowerOne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Powered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quantum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SatCon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serengeti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarbridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunPower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenesol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xantrex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multitech Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solaredge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZyXel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPMX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPDV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPTT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jabil Poland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jabil Mexico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flextronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenesol - Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Santerno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPTXS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPMX 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunEnergy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Line Items</relationshipLabel>
        <relationshipName>RMA_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Line Item</label>
    <nameField>
        <label>RMA Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RMACaseTeamTest.cls
@isTest
public class RMACaseTeamTest {
    private static testMethod void test_caseTeam() {
        RMACaseTeamTestData td = new RMACaseTeamTestData();
        td.createTestData_caseTeam();
        
        // verify if rma owner is added to case team
        List <CaseTeamMember> ctmList = [SELECT Id, MemberId, TeamRole.Name FROM CaseTeamMember WHERE ParentId = :td.case_1.Id];
        system.assertEquals(1, ctmList.size());
        system.assertEquals(UserInfo.getUserId(), ctmList[0].MemberId);
        system.assertEquals('RMA Owner', ctmList[0].TeamRole.Name);
        //Creating RMA line item for RMA to honor RMA Line Item Validation Rule 
        RMA_Line_Item__c rmaLineItem=new RMA_Line_Item__c();
        rmaLineItem.RMA__c=td.rma_1.Id;
        rmaLineItem.Name='Test';
        rmaLineItem.OEM__c='Fronius';
        rmaLineItem.Type__c='Return';
        rmaLineItem.Expected_Return_Quantity__c=1;
        insert rmaLineItem;
        // change owner
        td.rma_1.RMA_Owner__c = td.user_2.Id; 
        update td.rma_1;
        ctmList = [SELECT Id, MemberId, TeamRole.Name FROM CaseTeamMember WHERE ParentId = :td.case_1.Id];
        system.assertEquals(2, ctmList.size());
        Set <String> memberIdSet = new Set <String>();
        for (CaseTeamMember ctm : ctmList) {
            system.assertEquals('RMA Owner', ctm.TeamRole.Name);
            memberIdSet.add(ctm.MemberId);
        }
        system.assert(true, memberIdSet.contains(td.user_1.Id));
        system.assert(true, memberIdSet.contains(td.user_2.Id));
        
    }
    
}