objects/Service_Console_Links_Section__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This contains Sections of the Quick Links.
Roles are assigned to control the view accessibility.</description>
    <fields>
        <fullName>Role__c</fullName>
        <description>Role ID that can access the Section.</description>
        <inlineHelpText>Role ID that can access the Section.</inlineHelpText>
        <label>Role</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Name__c</fullName>
        <description>Name of the sections in Quick Link. This should be used in InfoLeaseURL in grouping the URLs.</description>
        <inlineHelpText>Name of the sections in Quick Link. This should be used in InfoLeaseURL in grouping the URLs.</inlineHelpText>
        <label>Section Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Service Console Links Section</label>
</CustomObject>

objects/Service_Console_Links_URL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>contains URLs for Quick Links</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>Text shown on the list.</description>
        <inlineHelpText>Text shown on the list.</inlineHelpText>
        <label>Label</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Name__c</fullName>
        <description>Section Name. The value for this field must be existing in InfoLeaseSection Custom Setting.</description>
        <inlineHelpText>Section Name. The value for this field must be existing in InfoLeaseSection Custom Setting.</inlineHelpText>
        <label>Section Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Tab title shown in opened URL.</description>
        <inlineHelpText>Tab title shown in opened URL.</inlineHelpText>
        <label>Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>URL of the link.</description>
        <inlineHelpText>URL of the link.</inlineHelpText>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Service Console Links URL</label>
</CustomObject>

classes/TestUpdateConsoleLog.cls
@isTest
private class TestUpdateConsoleLog {
    static testMethod void unitTest1() {
    
    UserRole role = [SELECT Id FROM UserRole WHERE Name='Customer Services Representative'];
    Profile profile = [SELECT Id FROM Profile WHERE Name='xxx SunPower Service User'];
    User u2 = new User(
        Alias = 'newUser1', 
        Email='newuser001@testorg.com', 
        EmailEncodingKey='UTF-8', 
        LastName='Testing', 
        LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', 
        ProfileId = profile.Id,
        UserRoleId = role.Id,
        TimeZoneSidKey='America/Los_Angeles', 
        UserName='newuser001@testorg.com'
    );
    
        System.runAs(u2) {
            
            Service_Console_Links_Section__c consoleSection = new Service_Console_Links_Section__c();
            consoleSection.Name = 'CSR_1';
            consoleSection.Role__c = '00E800000010ZVw';
            consoleSection.Section_Name__c = 'CSR Links';
            insert consoleSection;
            
            Service_Console_Links_URL__c consoleUrl = new Service_Console_Links_URL__c();
            consoleUrl.Name = 'CSR_101_GoToInfoLease';
            consoleUrl.Label__c = 'Go To Info Lease';
            consoleUrl.Section_Name__c = 'CSR Links';
            consoleUrl.Title__c = 'Go To Info Lease';
            consoleUrl.URL__c = 'https://sunpowerbillpaycsr.osgview.com/';
            insert consoleUrl;
        
            PageReference updateInfoLeasePage = Page.InfoLease;
            Test.setCurrentPage(updateInfoLeasePage);
              
            UpdateConsoleLog uconsole=new UpdateConsoleLog();
            
            uconsole.InsertIntoConsoleLog();
            uconsole.UpdateTimeInAppTracker();
        }
    }
  
}