objects/Ship_to_Site__c.object
<CustomObject>
    <description>Ship to site from Oracle ERP</description>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <description>Cash flow redesign- Sangita changed the sharing to read only. This way all partner users who can read their account can create a shipping site.</description>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipping Sites (Dealer Account)</relationshipLabel>
        <relationshipName>Ship_to_Site</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Oracle_Operating_Unit__c</fullName>
        <description>Cash Flow- Existing oracle operating unit field maps the partner account number instead of operating unit. We need the actual operating unit (SPNA OU, SPEB OU) to query and find one ship to site to send to Oracle via OrderIntegrationService. SOA Integraion will populate this field for all primary addresses every 1 hour. OrderAppController class will read this value to populate ship to address on the PO.</description>
        <label>Oracle Operating Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteID__c</fullName>
        <externalId>true</externalId>
        <label>SiteID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shipping Site</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Ship to Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShippingSiteComponentControllerTest.cls
@isTest(SeeAllData=true)
private class ShippingSiteComponentControllerTest {

    @isTest static void test_method_one() {
        Account testPartner = TestClassFactory.CreateDealer('dealerName', 'North America');
        //Get record types to be tested
        Id dwRecordTypeId =  Schema.SObjectType.Ship_to_Site__c.getRecordTypeInfosByName().get('Dealer Warehouse').getRecordTypeId();
        Id isRecordTypeId =  Schema.SObjectType.Ship_to_Site__c.getRecordTypeInfosByName().get('Installation Site').getRecordTypeId();
        //Instantiate object
        ShippingSiteComponentController sscc = new ShippingSiteComponentController();
        sscc.getCountryCodes();
        sscc.compControllerTest2();
        //Create new records
        Ship_to_Site__c sts = new Ship_to_Site__c();
        sts.Address1__c = '1st Ave S';
        sts.City__c = 'Richmond';
        sts.State__c = 'GA';
        sts.Country__c = 'USA';
        sts.Zip__c = '30901';
        sts.SiteID__c = '01010102';
        sts.RecordTypeId = dwRecordTypeId;
        sts.Status__c = 'Active';
        sts.Oracle_Operating_Unit__c = 'SPNA OU';
        sts.Dealer_Account__c = testPartner.Id;
        //Test Dealer Warehouse
        String recordString = JSON.serialize(sts);
        ShippingSiteComponentController.saveShippingSite(recordString,'Dealer Warehouse');
        //Test Installation Site
        sts.RecordtypeId = isRecordTypeId;
        recordString = JSON.serialize(sts);
        ShippingSiteComponentController.saveShippingSite(recordString,'Installation Site');
        //Test single vertex data
        sts.Address1__c = '1st Ave S';
        sts.City__c = 'Fredonia (Biscoe)';
        sts.State__c = 'AR';
        sts.Country__c = 'USA';
        sts.Zip__c = '72017';
        sts.SiteID__c = '01010103';
        ResultMessage rm = ShippingSiteComponentController.saveShippingSite(recordString,'Installation Site');
    }
}