objects/Single_Line__c.object
<CustomObject>
    <description>Object used to capture high level electrical and single line information for a project.</description>
    <fields>
        <fullName>Refresh_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Refresh Count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Single_Line_Completed__c</fullName>
        <label>Electrical Support Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Single_Line_Tracking__c</fullName>
        <label>Electrical Support Tracking</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Single Line</label>
    <nameField>
        <displayFormat>ES-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Single Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_Refresh_SingleLine_Extension.cls
Public Class Test_Refresh_SingleLine_Extension 
{
@isTest
public static void testSingle()
 {
 Test.startTest();
 
 ApexPages.StandardController con6 = new ApexPages.StandardController(new Single_Line__c());
 Refresh_SingleLine_Extension singleLine = new Refresh_SingleLine_Extension(con6);
 
 Refresh_SingleLine_Extension design3 = new Refresh_SingleLine_Extension(con6);
 
 Single_Line__c single = new Single_Line__c();
 single.Status__c = 'Active';
 single.Refresh_Count__c = 2;
 single.Single_Line_Tracking__c = System.Today();
 single.Single_Line_Completed__c = System.Today();
 insert single;

 
 singleLine.SingleLineid = single.id;
 singleLine.Refresh();
 
 ApexPages.currentPage().getParameters().put('id', single.id);
 
 
  //estimate.Refresh();
    
 Test.stopTest();
 
 }
 
}