objects/Territory_Definition__c.object
<CustomObject>
    <description>Territory and zip mapping.</description>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory Definition</label>
    <nameField>
        <displayFormat>TD-{000000}</displayFormat>
        <label>Territory Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestBeforeTerritoryDefinitionUpdate.cls
/**************************************************
** PR- 01923
**Created By- Harsh Mathur
**Created On- June 12 2009
**Last Modified- Harsh Mathur
**Last Modified On-  June 17 2009 
**Desciption- Test class 
*****************************************************/

public class TestBeforeTerritoryDefinitionUpdate
{
	@isTest
  public static void checkBeforeTerritoryDefinitionUpdate()
  {
    List<Territory_Definition__c> lstTest = new List<Territory_Definition__c>();
    Territory_Definition__c terrObj = new Territory_Definition__c();
    terrObj.Territory__c = 'North America';
    lstTest.add(terrObj);
    insert lstTest;    
    
    update lstTest;

  }
}