objects/Warranty_Registration__c.object
<CustomObject>
    <description>Warranty Registration Object represent warranty.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Warranty Registration</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranty Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_FDS_Product__c.object
<CustomObject>
    <description>This being used in online warranty registration and is replica of FDS products.</description>
    <fields>
        <fullName>Alternate_Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Alternate PL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Converted_To_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted To Asset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Packing Slip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <externalId>true</externalId>
        <label>Serial Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <formula>Text(WR_ORACLE_SalesOrder__r.Partner_Account__r.Theater__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theater</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WR_ORACLE_SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_ORACLE_SalesOrder</label>
        <referenceTo>WR_ORACLE_SalesOrder__c</referenceTo>
        <relationshipLabel>WR_FDS_Products</relationshipLabel>
        <relationshipName>WR_FDS_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WR_FDS_Product</label>
    <nameField>
        <displayFormat>Product - {0000}</displayFormat>
        <label>WR_FDS_Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_FDS_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_Line_Item__c.object
<CustomObject>
    <description>Junction Object with Warranty_Registration and WR_FDS_Product .</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>WR_FDS_Product__r.Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>WR_FDS_Product__r.Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>WR_FDS_Product__r.Serial_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WR_FDS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_FDS_Product</label>
        <referenceTo>WR_FDS_Product__c</referenceTo>
        <relationshipName>WR_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty_Registration__c</fullName>
        <label>Warranty_Registration</label>
        <referenceTo>Warranty_Registration__c</referenceTo>
        <relationshipName>WR_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WR Line Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>WR Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WR_ORACLE_SalesOrder__c.object
<CustomObject>
    <description>Oracle Salesorder Replicate. - Packing slip information for warranty registration - populated by Middleware from Oracle (John Taylor 7/14/2014)</description>
    <fields>
        <fullName>Oracle_Account_Number__c</fullName>
        <label>Oracle Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Packing Slip</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>So_Created__c</fullName>
        <label>So Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>WR_ORACLE_SalesOrder</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SFDC_NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_ORACLE_SalesOrder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Warranty_SearchFDSAdminClass_Test.cls
/* Test functionality of Warranty_SearchFDSAdminClass

  @Author         Anjali Khandelwal
  CreatedDate     03/09/2011
*/

@isTest
private class Warranty_SearchFDSAdminClass_Test{

    public static WR_FDS_Product__c salesOrderLnItem1;
    
    private static void createTestData()
    {
               
        List<WR_ORACLE_SalesOrder__c> lstSalesOrder = new List<WR_ORACLE_SalesOrder__c>();
        List<WR_FDS_Product__c> lstProduct = new List<WR_FDS_Product__c>();
       
        //Create SaleOrder
        WR_ORACLE_SalesOrder__c salesOrder1 = new WR_ORACLE_SalesOrder__c(Sales_Order__c='test_salesorder1',CurrencyIsoCode='USD', Oracle_Account_Number__c='test_oracle',Packing_Slip__c='testPackingSlip1',So_Created__c = System.today(),Theater__c = 'testTheater1');
        lstSalesOrder.add(salesOrder1);
        WR_ORACLE_SalesOrder__c salesOrder2 = new WR_ORACLE_SalesOrder__c(Sales_Order__c='test_salesorder2',CurrencyIsoCode='USD',Oracle_Account_Number__c='test_oracle',Packing_Slip__c='testPackingSlip2',So_Created__c = System.today(),Theater__c = 'testTheater2');
        lstSalesOrder.add(salesOrder2);
        insert lstSalesOrder;
        
        //Create instances of WR_FDS_Product__c        
        salesOrderLnItem1 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Packing_Slip__c='testPackingSlip1',WR_ORACLE_SalesOrder__c = salesOrder1.Id, Converted_to_asset__c = false,Product_Type__c='MODULE');
        lstProduct.add(salesOrderLnItem1);
        WR_FDS_Product__c salesOrderLnItem2 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Packing_Slip__c='testPackingSlip1',Serial_Number__c = 'test_serialnum1',WR_ORACLE_SalesOrder__c = salesOrder1.Id, Converted_To_Asset__c = true);
        lstProduct.add(salesOrderLnItem2);
        WR_FDS_Product__c salesOrderLnItem3 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Alternate_Packing_Slip__c='testPackingSlip2',Serial_Number__c = 'test_serialnum2',WR_ORACLE_SalesOrder__c = salesOrder2.Id);
        lstProduct.add(salesOrderLnItem3);
        WR_FDS_Product__c salesOrderLnItem4 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Packing_Slip__c='testPackingSlip2',Serial_Number__c = 'test_serialnum3',WR_ORACLE_SalesOrder__c = salesOrder2.Id);
        lstProduct.add(salesOrderLnItem4);
        //start for case #00063392
        WR_FDS_Product__c salesOrderLnItem5 = new WR_FDS_Product__c(CurrencyIsoCode='USD',Packing_Slip__c='testPackingSlip5',Serial_Number__c = 'test_serialnum5',WR_ORACLE_SalesOrder__c = salesOrder1.Id, Product_Name__c = 'Test_Product');
        lstProduct.add(salesOrderLnItem5);
        //end for case #00063392
        insert lstProduct;           
        
        //start for case #00063392
        Warranty_Registration__c wr = new Warranty_Registration__c(Status__c='Draft');
        insert wr;
        WR_Line_Item__c wrline = new WR_Line_Item__c(Warranty_Registration__c = wr.Id, WR_FDS_Product__c = lstProduct.get(1).Id);
        insert wrline;
        //end for case #00063392
    }
    
    private static testMethod void testSearchRecords(){
        
        createTestData();
        
        ApexPages.StandardSetController setCon; 
        ApexPages.StandardController Con = new ApexPages.StandardController(salesOrderLnItem1);       
       
        Warranty_SearchFDSAdminClass wr_Search = new Warranty_SearchFDSAdminClass(Con );
        //When no value in standardSetController
        wr_Search.getFdsRecords();
        
        wr_Search.searchKey = 'w.Serial_Number__c';
        wr_Search.searchValue = 'test_serialnum1';
        
        //Call to searchRecords() with search value -> 'test_serialnum1' and searchKey > 'Serial_Number__c'
        PageReference pg = wr_Search.searchRecords();
        wr_Search.searchValue = 'test_serialnum1 test_serialnum2';
        //Call to searchRecords() with search value(space delimited multiple search ) -> 'test_serialnum1 test_serialnum2' and searchKey > 'Serial_Number__c'        
        pg = wr_Search.searchRecords();
        
        //When there is value in standardSetController
        wr_Search.getFdsRecords();
        
        wr_Search.exportCSV();
        
        wr_Search.getFdsRecords();
        //start for case #00063392
        wr_Search.getProdWarrantyWrapperLst();
        wr_Search.exportCSV();
        //end for case #00063392
        wr_Search.searchKey = 'w.Packing_Slip__c';
        wr_Search.searchValue = 'testPackingSlip2';
        pg = wr_Search.searchRecords();
    }
}