objects/WR_FDS_Product__c.object
<CustomObject>
    <description>This being used in online warranty registration and is replica of FDS products.</description>
    <fields>
        <fullName>Alternate_Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Alternate PL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <label>Dealer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Packing Slip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <externalId>true</externalId>
        <label>Serial Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WR_ORACLE_SalesOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WR_ORACLE_SalesOrder</label>
        <referenceTo>WR_ORACLE_SalesOrder__c</referenceTo>
        <relationshipLabel>WR_FDS_Products</relationshipLabel>
        <relationshipName>WR_FDS_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WR_FDS_Product</label>
    <nameField>
        <displayFormat>Product - {0000}</displayFormat>
        <label>WR_FDS_Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_FDS_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WR_ORACLE_SalesOrder__c.object
<CustomObject>
    <description>Oracle Salesorder Replicate. - Packing slip information for warranty registration - populated by Middleware from Oracle (John Taylor 7/14/2014)</description>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <label>Dealer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Account_Number__c</fullName>
        <label>Oracle Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_Slip__c</fullName>
        <externalId>true</externalId>
        <label>Packing Slip</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>WR_ORACLE_SalesOrder</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>SFDC_NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WR_ORACLE_SalesOrder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PopulateSalesOrderInRelatedProducts_Test.cls
/**
 * This class contains unit tests for validating the behavior of PopulateSalesOrderInRelatedProducts trigger
 * @Author Shailendra Singh (Appiro offshore)
 */
@isTest
private class PopulateSalesOrderInRelatedProducts_Test {

    static testMethod void testPopulateSalesOrderInRelatedProducts() {
        
        // create WR_FDS_Product
        
       	List<WR_FDS_Product__c> products = new List<WR_FDS_Product__c>();
       	WR_FDS_Product__c product1 = new WR_FDS_Product__c();
       	product1.Serial_Number__c = 'G20J01297002-test';
       	product1.Dealer_Name__c = 'test dealer name';
       	product1.Packing_Slip__c = 'TEST-5901180';
       	product1.Alternate_Packing_Slip__c = 'TEST-59011801';
       	
       	products.add(product1);
       	
       	WR_FDS_Product__c product2 = new WR_FDS_Product__c();
       	product2.Serial_Number__c = 'G20J01297003-test';
       	product2.Dealer_Name__c = 'test dealer name';
       	product2.Packing_Slip__c = 'TEST-59011801';
       	products.add(product2);
       	
       	insert products; 
       	
       	// create WR_Oracle_SalesOrder
       	
       	WR_ORACLE_SalesOrder__c salesOrder = new WR_ORACLE_SalesOrder__c();
       	salesOrder.Packing_Slip__c = 'TEST-59011801';
       	salesOrder.Dealer_Name__c = 'test dealer name';
       	salesOrder.Oracle_Account_Number__c = '121090_Test';
        insert salesOrder;
        // asset to check if WR_ORACLE_SalesOrder__c is populated and not populated condition 
        System.assertEquals([Select WR_ORACLE_SalesOrder__c from WR_FDS_Product__c where id =:product2.id ].WR_ORACLE_SalesOrder__c,salesOrder.id);
        // Alternat packslip case
        System.assertEquals([Select WR_ORACLE_SalesOrder__c from WR_FDS_Product__c where id =:product1.id ].WR_ORACLE_SalesOrder__c,salesOrder.id);
        System.assertEquals([Select Packing_Slip__c from WR_FDS_Product__c where id =:product1.id ].Packing_Slip__c,salesOrder.Packing_Slip__c);
    }
}